app/controllers/api-keys/post-create.controller.js
app/controllers/api-keys/post-revoke.controller.js
app/controllers/api-keys/post-update.controller.js
app/paths.js
app/routes.js
app/utils/nav-builder.js
app/views/api-keys/_key.njk
app/views/api-keys/_keys.njk
app/views/api-keys/create.njk
app/views/api-keys/update.njk
test/ui/navigation.ui.test.js
test/unit/controller/api-keys/get-index.controller.ft.test.js
test/unit/controller/api-keys/get-revoked.controller.ft.test.js
test/unit/controller/api-keys/post-create.controller.ft.test.js
test/unit/controller/api-keys/post-revoke.controller.ft.test.js
test/unit/controller/api-keys/post-update.controller.ft.test.js

with @sandorarpa
- paths.js
- Move API paths to `account` section.
- routes.js
- Add all API Key paths to the `account router`
- Update all API key views and controllers
- Update all references to API key pages to use the new URL structure
- i.e. /account/<gateway-account>/api-keys/*
- Update functional tests to use mock calls for the new account middleware
- Updated nav-builder to use new account URLs for the API Keys
- Updated template test for the navigation

PP-7583 URL Restructure - API Keys

---

app/utils/gateway-account-urls.js
app/utils/gateway-account-urls.js.test.js

Some browsers force navigating to remembered routes when visiting a particular
resource, the account url parsing should be resilient to trailing `/` to
correctly match when this is the case.

PP-7445 Normalise gateway account urls when upgrading

---

app/controllers/login/post-login.controller.js
app/controllers/stripe-setup/stripe-setup-link/stripe-setup-dashboard-redirect.controller.js

As we transition URL structure for accounts only new middleware routes
and the service switcher will be setting the external id required to
redirect to the correct URLs.
Ensure the external ID is set when the user logs in, this should then be
correct until the ID is changed by a known redirect controller.

PP-7445 Set account external ID on login

---

app/routes.js

Add the new routes which contain the account external ID for routes we
are going to switch over but haven't yet.
This is so that these routes will exist before we come to redirecting to
them from other pages.
Without doing this first, users may have issues while we are deploying
the app, where some instances of selfservice have the new route
available but others don't. This could cause users to see 404s on
redirects.

PP-7583 Add new account routes for routes we will move

---

.secrets.baseline
app/controllers/email-notifications/email-notifications.controller.js
app/paths.js
app/routes.js
app/utils/display-converter.js
app/utils/nav-builder.js
app/views/billing-address/index.njk
app/views/digital-wallet/apple-pay.njk
app/views/digital-wallet/google-pay.njk
app/views/email-notifications/collection-email-mode.njk
app/views/email-notifications/confirmation-email-toggle.njk
app/views/email-notifications/refund-email-toggle.njk
app/views/toggle-3ds/index.njk
app/views/toggle-moto-mask-card-number/index.njk
app/views/toggle-moto-mask-security-code/index.njk
test/cypress/integration/settings/3ds.cy.test.js
test/cypress/integration/settings/allow-apple-pay.cy.test.js
test/cypress/integration/settings/allow-google-pay.cy.test.js
test/cypress/integration/settings/email-notifications.cy.test.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/integration/settings/your-psp.cy.test.js
test/test-helpers/html-assertions.js
test/ui/toggle-collect-billing-address.ui.test.js

Un-reverts a previously reverted commit to update the settings route to use the new account URL structure.
It was previously reverted due to the potential for the user to see 404s while we were deploying because the new route would not exist on the old instances during deploy, but new instances would redirect to the new route. The new route now already exists so that won't be an issue.

PP-7583 Move settings route

---

.secrets.baseline
app/controllers/credentials.controller.js
app/controllers/your-psp/post-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/paths.js
app/routes.js
app/utils/nav-builder.js
app/views/credentials/worldpay.njk
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/flex.njk
test/cypress/integration/settings/your-psp.cy.test.js
test/integration/credentials.ft.test.js

This reverts commit f86dee8341b20553280abea18df1c99beac6fbc9.
Reverting as it breaks end to end tests due to the credentials not being available on the new get account by external ID connector endpoint.

Revert "PP-7583 Move your psp routes"

---

app/controllers/make-a-demo-payment/edit.controller.js
app/controllers/make-a-demo-payment/go-to-payment.controller.js
app/controllers/make-a-demo-payment/index.controller.js
app/controllers/make-a-demo-payment/mock-card-details.controller.js
app/controllers/test-with-your-users/disable.controller.js
app/controllers/test-with-your-users/links.controller.js
app/controllers/test-with-your-users/submit.controller.js
app/paths.js
app/routes.js
app/views/dashboard/_links.njk
app/views/dashboard/demo-payment/edit-amount.njk
app/views/dashboard/demo-payment/edit-description.njk
app/views/dashboard/demo-payment/index.njk
app/views/dashboard/demo-payment/mock-card-details.njk
app/views/dashboard/demo-service/confirm.njk
app/views/dashboard/demo-service/create.njk
app/views/dashboard/demo-service/index.njk
test/unit/controller/make-a-demo-payment-controller/edit.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/go-to-payment.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/index.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/mock-card-details.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/create.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/disable.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/links.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/submit.controller.ft.test.js

with @SandorArpa 
- Update all 'make a demo payment' and  'prototype' link references to use the new
URL structure
- Update the 'paths.js' and 'routes.js' to use the new URL structure and middleware.
- Use new `/account/<an-external-id>` format.
- Update all references in template 'njk' files
- Update all controllers
- Update functional tests.

PP-7583 URL Re-structure > Demo payments

---

.secrets.baseline
app/services/clients/connector.client.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/gateway-account.fixtures.js
test/integration/credentials.ft.test.js
test/integration/payment-types/payment-types.it.test.js
test/unit/clients/connector-client/connector-get-gateway-account-by-external-id.pact.test.js
test/unit/controller/api-keys/get-index.controller.ft.test.js
test/unit/controller/api-keys/get-revoked.controller.ft.test.js
test/unit/controller/api-keys/post-create.controller.ft.test.js
test/unit/controller/api-keys/post-revoke.controller.ft.test.js
test/unit/controller/api-keys/post-update.controller.ft.test.js
test/unit/controller/billing-address-controller/toggle-billing-address.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/edit.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/go-to-payment.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/index.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/mock-card-details.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/create.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/disable.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/links.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/submit.controller.ft.test.js

Use the `v1/frontend` version of the get gateway account by external id endpoint, which returns the gateway credentials. The `v1/api` version of the endpoint will be removed.
Add pact tests to get gateway accounts for each of the payment providers that have credentials set by the user: Worldpay, Smartpay and ePDQ to ensure connector is returning these in the format we're expecting.
Reviewing with whitespace diffs hidden is recommended as there is some indentation changes.

PP-7656 Use /v1/frontend/accounts/external-id endpoint

---

.secrets.baseline
app/controllers/credentials.controller.js
app/controllers/your-psp/post-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/paths.js
app/routes.js
app/utils/nav-builder.js
app/views/credentials/worldpay.njk
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/flex.njk
test/cypress/integration/settings/your-psp.cy.test.js
test/integration/credentials.ft.test.js

Un-does a revert to update your psp routes to use the new account URL
structure.
This was previously reverted because the connector endpoint to get a
gateway account by external id was not returning the gateway credentials
and this was only picked up by the end-to-end tests.
This has now been fixed and there are adequate pact tests to catch this.

PP-7583 Move your psp routes

---

app/controllers/stripe-setup/add-psp-account-details/get.controller.js
app/controllers/stripe-setup/add-psp-account-details/get.controller.test.js
app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js
app/controllers/stripe-setup/company-number/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js
app/controllers/stripe-setup/vat-number/post.controller.js
app/paths.js
app/routes.js
app/views/dashboard/_stripe-account-setup-banner.njk
app/views/stripe-setup/bank-details/index.njk
app/views/stripe-setup/company-number/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/stripe-setup/vat-number/index.njk
test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
test/cypress/integration/stripe-setup/bank-details.cy.test.js
test/cypress/integration/stripe-setup/company-number.cy.test.js
test/cypress/integration/stripe-setup/responsible-person.cy.test.js
test/cypress/integration/stripe-setup/vat-number.cy.test.js
test/cypress/stubs/user-stubs.js
test/integration/add-psp-details.ft.test.js

Update both the controllers for the pages and the redirect utility that
pieces all of the stripe setup steps together.
Move the live dashboard redirect that is given to services when they've
gone live (by support) out of the nested account paths as it belongs to
the service. Once the account URL structure is in place, this can likely
be removed and replaced with a simple link to the new live account that's
been created.

PP-7583 Stripe setup account url structure

---

app/routes.js

Add back in the api-keys path to the authenticated routes array so that
we redirect to the login page when someone tries to access the old
`/api-keys` URL directly without having a gateway account cookie set.
This is to temporarily fix ZAP tests, we will find a better solution to
this.

PP-7583 Fix zap tests

---

app/routes.js
test/integration/routes.it.test.js

If the user is not logged in but have directly visited a legacy account
specific URL we may not have all the information we need to direct
them to the correct account.
In this case previously middleware on those URLs would have redirected
the user to login.
Update the URL upgrader to factor in this scenario.
Prove this by removing the API keys route from the legacy middleware
auth stack, this page is currently accessed by ZAP tests before having ever
logged in.

PP-7629 Account URL upgrader redirect to login without session

---

app/views/transactions/index.njk

- All live service transactions download link doesnot appear for users as we check for transaction.read permission,
but this route is not tied to specific service and we can show the link directly (other checks about number of transactions before transactions download link appears is still in place).
All live services transactions controllers (get, download) has checks in place to render error page if user doesn't have access to live services.

BAU: Fix all service transactions download

---

.secrets.baseline
app/paths.js
app/routes.js

Add new route for the account dashboard. Adding this before merging changes to redirect to this route so that there is no risk of getting 404s on redirects when we deploy changes to redirect to the new route.

PP-7677 Add account dashboard route

---

app/views/transactions/list.njk
test/ui/transaction-list.ui.test.js

Currently we show fields (amount, email, card_brand) based on granular permissions
(`transactions_email_read, transactions_amount_read, transactions_card_type_read`) for user service role.
But granular permissions are not applied 
- for searches
- when users download CSV 
-  and currently there is no permission model for pages like all live services transactions (which shows transactions data for multiple live accounts).
Initial use case (PP-1469) when introducing permissions was a `super-admin` may not need to view `email, amount, description, card brand` fields. But super-admin role is currently not used. All other roles are service specific and permissions (transactions_email_read, transactions_amount_read, transactions_card_type_read) are available for all roles. So we can safely …

PP-7680 Remove granular permissions checks for transaction search

---

app/views/dashboard/_activity.njk

Fix a minor regression in the dashboard activity page. The test coverage
for this feature ([at the time of this PR](https://github.com/alphagov/pay-selfservice/blob/master/test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js)) navigates directly to the page however the template
currently relies on the page being redirected from the root index `/`.
Directly submit form requests to the dashboard page for now to line up
with the test coverage. How this should be covered should be considered
following up.

PP-7667 Remove redirect from dashboard activity tool

---

app/routes.js

- When submitting feedback, users are shown account specific menu (Dashboard , transactions ...) which is currently broken as we don't get account (in the middleware) anymore and also account info is also passed to zendesk.
- Adding getAccount middleware back to feedback routes to fix broken links while we decide on moving feedback to service level or  keeping it at account level (in which case we need to update feedback pages to new account URL structures)

PP-7641 Add getAccount middleware to feedback routes

---

app/controllers/transactions/transaction-detail-redirect.controller.js
app/controllers/transactions/transaction-detail.controller.js
app/controllers/transactions/transaction-list.controller.js
app/controllers/transactions/transaction-refund.controller.js
app/middleware/get-service-and-gateway-account.middleware.js
app/paths.js
app/routes.js
app/services/transaction.service.js
app/utils/nav-builder.js
app/utils/transaction-view.js
app/views/dashboard/_activity.njk
app/views/transaction-detail/_refund.njk
app/views/transaction-detail/index.njk
test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js
test/cypress/integration/transactions/transaction-details.cy.test.js
test/cypress/integration/transactions/transaction-list-pagination.cy.test.js
test/cypress/integration/transactions/transaction-search.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/stubs/transaction-stubs.js
test/cypress/stubs/user-stubs.js
test/fixtures/ledger-transaction.fixtures.js
test/integration/add-psp-details.ft.test.js
test/integration/pagination.ft.test.js
test/integration/router.test.js
test/integration/transaction-details.it.test.js
test/integration/transaction-list.ft.test.js
test/integration/transaction-redirect-details.ft.test.js
test/ui/transaction-details.ui.test.js
test/unit/controller/transaction-refund.controller.it.test.js

With @SandorArpa
- Update to use the new '/account/<external-id>' format for transaction pages.
- Update controllers.
- Update templates.
- Update functional tests.
- Update UI template tests
- Update Refund redirect controller
- Add connector call to get `gateway > external_id`
- Update transaction detail redirect
- Now redircet to the new URL format: `/account/an-external-id/transactions/<charge-id>`
- Update transaction.service.js
- Do not make a call to get user external ids for refunds - if there are no refunds.
- Add new Cypress test for `All Service Transactions`
- Should load Transaction list
- Show Transaction detail
- Update Cypress test for `transaction detail`
- Remove stub to get user details for refund events when - not needed when there have been no refunds.

PP-7668 URL Restructure - Transactions

---

app/routes.js
app/utils/display-converter.js
app/views/request-to-go-live/agreement.njk
app/views/request-to-go-live/choose-how-to-process-payments.njk
app/views/request-to-go-live/index.njk
app/views/request-to-go-live/layout.njk
app/views/request-to-go-live/organisation-address.njk
app/views/request-to-go-live/organisation-name.njk
test/cypress/integration/request-to-go-live/agreement.cy.test.js
test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
test/cypress/integration/request-to-go-live/index.cy.test.js
test/cypress/integration/request-to-go-live/organisation-address.cy.test.js
test/cypress/integration/request-to-go-live/organisation-name.cy.test.js

The URLs for these pages were at the service level, but they were displayed with the account navigation.
As we are going to remove the cookie for determining the current gateway account, these pages will no longer know which account the user has come from.
Remove the `getAccount` middleware from these routes and stop showing the account navigation. Continue displaying the service name header and include a "My services" back link in the top left corner.  Remove some top padding on the index page as this space is now filled by the back link.
Replace the link on the confirmation page with a "Go to My services" link.

PP-7694 Move request to go live pages to service level

---

app/views/your-psp/_worldpay-flex.njk

Now that credentials are verified before being saved in the backend
there is no need to warn users about this implication up front.
Also @stevenjmesser told me to.

BAU Remove 3DS flex warning

---

app/controllers/all-service-transactions/download-transactions.controller.js
app/controllers/all-service-transactions/get.controller.js
app/controllers/payouts/payout-list.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js
app/errors.js
app/middleware/error-handler.js

Don't call res.render directly for error pages, as we want to run them through the display converter so we can display the logged in header if the user is logged in.
For places where we did this, call `next` with an error and let the `error-handler` render an appropriate error page using the function in `response.js`.
Recommended to view with whitespace changes hidden due to indentation changes.

PP-7561 Render errors using response function

---

app/controllers/feedback/post-index.controller.js
app/services/clients/zendesk.client.js

- Refactor the Zendesk call to create a ticket.
- Use Aysnc/await when calling the 'zendesk.client.js' util.
- Refactor 'zendesk.client.js'
- Remove promise wrapper and just 'return' the output of the
'zendeskClient.tickets.create'

PP-7445 Feedback form - refactor Zendesk call

---

.gitignore
app/views/self-create-service/register.njk
test/ui/self-create-service.ui.test.js

- when a user is on the sign up page, and enters a valid email address, but it is not on the approved list, they are shown the link to contact support
- replaced 'govukInput' with custom code. govukInput.errorMessage.text does not render html markups

PP-7592 add onward journey link to email error

---

app/models/Service.class.js
app/models/ServiceUpdateRequest.class.js
app/models/psp-test-account-stage.js
test/fixtures/service.fixtures.js
test/unit/clients/adminusers-client/service/update-service.pact.test.js

- add new field `current_psp_test_account_stage` to Serivce class
- add new field `current_psp_test_account_stage` to ServiceUpdateRequest class
- create enum type `current_psp_test_account_stage`
- update relevant pact test

PP-7765 add psp test account stage to pact test

---

app/controllers/service-roles-update.controller.js
app/models/Service.class.js
app/utils/roles.js
app/views/team-members/team-member-permissions.njk
test/ui/service-role-update.ui.test.js

Allow admin users of a service to change an existing user’s role to `view-and-initiate-moto` or `view-refund-and-initiate-moto`.
For now, these two new roles are only shown if the service has the `agent_initiated_moto_enabled` flag set, which we’re using to limit which services have the agent-initiated MOTO payments feature.
If the flag is false, a determined admin could still assign one of the new roles to a user. However, on its own that will not allow
the user to to do anything more, so it’s not really worth trying to prevent this.

PP-7708 Allow assigning existing users to telephone payments roles

---

app/controllers/user/phone-number/get.controller.js
app/controllers/user/phone-number/post.controller.js

We now decide whether to show the logged in or logged out header in the display converter, so that we can show the logged in header for errors (PP-7561).
In this case, we were rendering the view directly using `res.render` rather than using the `response` function to render after calling the display converter.
This was the only case for a logged in route where we were rendering in this way.

BAU Fix logged out error shown for phone number page

---

app/controllers/invite-user.controller.js
app/views/team-members/team-member-invite.njk
test/integration/invite-users.controller.ft.test.js
test/ui/invite-user.ui.test.js
test/ui/service-role-update.ui.test.js

Allow admin users of a service to invite a user granting them the `view-and-initiate-moto` or `view-refund-and-initiate-moto` role.
For now, these two new roles are only shown if the service has the `agent_initiated_moto_enabled` flag set, which we’re using to limit which services have the agent-initiated MOTO payments feature.
If the flag is false, a determined admin could still invite a user and grant them one of the new roles. However, on its own that will not allow the user to to do anything more, so it’s not really worth trying to prevent this.

PP-7708 Allow inviting new users to telephone payments roles

---

app/controllers/register-user.controller.js
app/controllers/service-users.controller.js

There is the following error on register user and service users controller testing.
```
UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
This change adds missing `return` to resolve the error in both controllers.

BAU: Fix err http headers sent on register user and service users controllers

---

app/controllers/payment-links/get-manage.controller.js
app/controllers/test-with-your-users/links.controller.js
app/services/clients/products.client.js
test/cypress/integration/payment-links/create-payment-link.cy.test.js
test/cypress/integration/payment-links/delete-payment-links.cy.test.js
test/cypress/integration/payment-links/edit-payment-link.cy.test.js
test/cypress/integration/payment-links/manage-payment-links.cy.test.js
test/cypress/stubs/products-stubs.js
test/unit/clients/products-client/product/get-by-gateway-account-id-and-type-with-metadata.pact.test.js
test/unit/clients/products-client/product/get-by-gateway-account-id-and-type.pact.test.js
test/unit/controller/test-with-your-users-controller/links.controller.ft.test.js

When we need all the payment links for a gateway account or all the prototype links for a gateway account, use the new endpoint on the products microservice that filters by type.
This is more efficient than retrieving every live product for a gateway account from the database, dragging them all across the network and then filtering out the ones we do not want.

PP-7709 Filter products by type in products not selfservice

---

app/controllers/dashboard/dashboard-activity.controller.js
app/views/dashboard/_links.njk
test/fixtures/service.fixtures.js
test/fixtures/user.fixtures.js
test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js

Show a ‘Take a telephone payment’ link on the dashboard if all of the following are true:
- The service has the `agent_initiated_moto_enabled` flag set to true
- There is at least one `AGENT_INITIATED_MOTO` product for the gateway account
- The user has the `agent-initiated-moto:create` permission
The link links directly to the initial page of the payment journey for the `AGENT_INITIATED_MOTO` product (if there is more than one, only the first one is used — this is fine for now while we control the creation of `AGENT_INITIATED_MOTO` products).

PP-7709 Show telephone payment link on dashboard if appropriate

---

app/controllers/dashboard/dashboard-activity.controller.js
test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
test/unit/controller/dashboard/dashboard-activity.controller.test.js

- Update the Dashboard activity controller
- If a Stripe test account > Do not try to retrieve Stripe account details.
- This prevents showing the Stripe setup banner.
- Add a Unit test for the dashboard activity controller
- There are existing funcitonal tests but these do not make it easy to test if
the controller has tried to call Connector function or use the Stripe API.
- Therefore, add a unit test just to cover this use case.

PP-7739 Stripe Test Account > Do not show any Stripe Set-up banners

---

app/services/clients/products.client.js

- Removed metadata specific client methods as these are no longer used and the metadata is now passed as part of payload to create/update product.

PP-7611 Remove unused product client methods

---

app/controllers/my-services/get-index.controller.js
app/controllers/payouts/payout-list.controller.js
app/paths.js
app/routes.js
app/utils/permissions.js
app/views/payouts/list.njk
app/views/services/index.njk
test/cypress/integration/my-services/my-services-links.cy.test.js
test/unit/utils/permissions.test.js

Depends on https://github.com/alphagov/pay-selfservice/pull/2584
Allow the payments to your bank account page to filter live or test
accounts based on the updated cross account permissions utility.
Add a tag to show what environment is being displayed following the
ticket design.
Update the download link for live and test environments.
Add a link to switch between live and test environments with the
following logic:
* viewing test data and has live accounts - show switch to live
* viewing test data with no live accounts - nothing
* viewing live data - show switch to test

PP-7786 Payments to your bank account status filter

---

app/assets/sass/components/navigation.scss
app/utils/display-converter.js
app/views/feedback/index.njk
app/views/includes/header.njk
app/views/includes/phase-banner-old.njk
app/views/includes/phase-banner.njk
app/views/layout.njk
app/views/macro/breadcrumbs.njk
app/views/merchant-details/edit-merchant-details.njk
app/views/merchant-details/merchant-details.njk
app/views/payouts/list.njk
app/views/request-psp-test-account/index.njk
app/views/request-to-go-live/layout.njk
app/views/services/index.njk
app/views/team-members/team-members.njk
app/views/transactions/index.njk
test/cypress/integration/feedback/feedback.cy.test.js
test/cypress/integration/request-to-go-live/agreement.cy.test.js
test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
test/cypress/integration/request-to-go-live/index.cy.test.js
test/cypress/integration/request-to-go-live/organisation-address.cy.test.js
test/cypress/integration/request-to-go-live/organisation-name.cy.test.js

Update the service/ account navigation "phase_banner" using the new
breadcrumb according to the ticket specification.
Move the account specific navigation down to the line below.
Update pages that currently have a manual link back to the my services
page as they can now rely on the breadcrumb for that functionality.
All changes are behind the future method feature flag.
Beginning to formalising page types
* All services page
* Service page
* Account page 
* Top level
Removes the "My services" link from the navigation header in favour of the breadcrumbs, behind the future feature flag.
**All services page header**
**Account page header**
**Service page header**
**Top level**

PP-7789 Breadcrumbs navigation header

---

app/views/payouts/list.njk

Add tag to display whether the payments to your bank account page is
showing test payments or live payments.

PP-7759 Add test/live tag to payouts breadcrumb

---

app/views/transaction-detail/index.njk

When visiting the transaction detail page from the all services transactions page, include the breadcrumb "Transactions for all services" in the phase banner.
Put this behind the feature flag.
Alter the text of the back link to say "Back to...".

PP-7759 Add breadcrumb on transaction detail page

---

app/controllers/credentials.controller.js
app/controllers/credentials.controller.test.js

When users have copied and pasted credentials from their payment service
providers they will sometimes come with hidden whitespace. This should
be removed before sending it to the backend as it can lead to invalid
credentials.

PP-4339 Trim gateway credentials before sending to Connector

---

test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/stubs/transaction-stubs.js
test/cypress/stubs/user-stubs.js
test/fixtures/ledger-transaction.fixtures.js

Add Cypress assertions for the all services transactions page to check:
- the correct breadcrumb navigation is shown
- clicking "Switch to test accounts" shows accounts for test transactions

PP-7835 Add Cypress assertions for transactions page

---

test/cypress/integration/payouts/payouts-list.cy.test.js
test/cypress/stubs/user-stubs.js

Add some simple Cypress assertions to check:
- the breadcrumb is correct for the payouts page
- the link to show test payouts works and content is displayed correctly
for test payouts.

PP-7835 Add Cypress assertions for payouts page

---

test/cypress/integration/errors/errors.cy.test.js

Add assertions to check:
- "My services" breadcrumb is shown when user is logged in
- Breadcrumb is not shown when user is logged out

PP-7835 Add Cypress assertions for error pages

---

app/assets/sass/components/flex-grid.scss
app/assets/sass/components/my-services.scss
app/views/services/_service-section.njk
app/views/services/index.njk
test/cypress/integration/index/index.cy.test.js
test/ui/service-switcher.ui.test.js

- Change page h1 to "Overview"
- Add h2 "Reports" above links to reports
- Add horizontal divide
- Add h2 "Services" above service list
- Remove ", 'My services'" from notification banner text as this does not relate to the h1 of the page.
- Make service names h3 and smaller.

PP-7632 Update My services content

---

app/assets/sass/components/my-services.scss

Use border-bottom rather than border-top to avoid a double line.
Use $govuk-border-colour for colour

PP-7632 Fix styling of divider on "My services"

---

app/utils/filters.js
test/unit/utils/filters.test.js

Any filter that isn't a predefined choice (states, card brands) should
have leading and trailing whitespace removed. Whitespace can often be
included when copying and pasting. As whitespace at the beginning and
end of values is never stored, searches with these accidental characters
will fail.
Trim the direct input filters before passing them to the backend.

BAU Trim filters on the search transaction page

---

app/utils/get-query-string-for-params.js
app/views/transactions/filter.njk
test/unit/clients/ledger-client/ledger-search-transaction.pact.test.js

- Pass metadataValue search param & value to Ledger
- Rename query `metadata` to `metadataValue` as per the story and naming is inline with other query params
- Added pact to search transactions by metadata value

PP-7859 Pass metadata_value to Ledger for transaction search

---

app/controllers/all-service-transactions/get.controller.js
app/utils/transaction-view.js
app/views/transactions/filter.njk
test/cypress/integration/transactions/transaction-search.cy.test.js

- Add the 'Advanced filters' to 'All transactions' view.
- Keep the 'Advanced filters' toggle open if a user has already submitted
a metadata filter search.
- Update the controller, to pass the metadata filter values to the base client.
- Update the `download transactions` link to include query param for metadata filter.
- Update Cypress test for `transaction search` to include testing by metadata.

Pp 7859 metadata filter controller updates

---

app/utils/display-converter.js

There was an additional `govuk-phase-banner` element below the banner
containing the "My services" link on the edit phone number and change
second factor method pages under "My profile".
Add these views to the list of views that don't display the account
navigation so this doesn't happen.
This is what we were seeing:

BAU Fix double line below My services breadcrumb

---

app/views/api-keys/_keys.njk
app/views/api-keys/index.njk
app/views/api-keys/revoked-keys.njk

The id on the header is used by end to end tests to check which page it's on. It's not a nice way of doing it but add it back in to avoid the hassle of editing the end to end tests.

PP-7893 Add back id used by endtoend tests

---

.secrets.baseline
app/routes.js
app/services/auth.service.js
test/integration/auth.ft.test.js
test/integration/login.controller.test.js
test/integration/service-users.ft.test.js
test/unit/routes.test.js
test/unit/services/auth.service.test.js

Remove the getAccount, hasServices and resolveService middleware on all
routes that no longer require it.
Replace usages of the `enforceUserAuthenticated` middleware with the new
`is-user-authorised` middleware which does all the same checks.
Change tests that expect a redirect to `/otp-login` if the user has not
completed second factor authentication. This was never actually the
behaviour, as there was always a check on the session version first
which is updated after second factor authentication was completed, and
if the session version didn't match we redirected to `/login`. The
new `is-user-authorised` middleware now just always directs to `/login`
so this ambiguity is removed without changing actual behaviour.

PP-7733 Remove unnecessary middleware

---

app/controllers/all-service-transactions/get.controller.js
app/controllers/transactions/transaction-detail-redirect.controller.js
app/controllers/transactions/transaction-detail.controller.js
app/controllers/transactions/transaction-refund.controller.js
app/views/transaction-detail/_refund.njk
app/views/transaction-detail/index.njk
test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js

Fix the redirect after making a refund if the user has come from the
"Transactions for all services" page, rather than the transactions list
for a particular account.
Do this by adding a hidden input to the refund form to indicate that we
have come from the all services transactions page which is passed along
with the redirect.
Store the filters for the all services transaction search on the session
as we do for the account transaction search so we can construct the back
link from these, even after redirecting following a refund. Also include
the status filter (live/test) to ensure we get back to the correct
search.

PP-7715 Fix redirect after refund

---

test/cypress/integration/dashboard/dashboard-statistics.cy.test.js

Cypress tests didn't take into account daylight savings, fix this

BAU Fix Cypress tests

---

app/views/request-to-go-live/agreement.njk

- Removed `aria-describedby` as it refers to non-existent ID and not required on the fieldset

PP-7545 Remove broken aria-describedby

---

app/paths.js
app/routes.js
app/views/merchant-details/edit-merchant-details.njk
app/views/services/_service-section.njk
test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
test/cypress/integration/manage-team-members/manage-team-members.cy.test.js
test/integration/service-users.ft.test.js

Add new URLs for the organisation details page that use the pattern
`/service/:externalServiceId` so that we can use a Router for all
service routes.
Also change the URL for view/edit team members to be
`/service/:externalServiceId/team-members` rather than
`/service/:externalServiceId/` as this isn't really a root URL for a
service.
Keep routes for the old URLs which will be removed after this change
has been deployed. This is to avoid breaking user journeys during
deployment.

PP-7735 Make service URLs uniform

---

app/routes.js
test/unit/routes.test.js

Remove the array of `authenticatedPaths` to apply this middleware to and inline the middleware per route. This should make it clearer what middleware is being called on the routes and should make it harder to make mistakes when adding a new route.
The unit test for `routes.test.js` ensures that all routes using the main Express router call this middleware unless they are specifically excluded which adds protection against coding mistakes.

PP-7735 Inline userIsAuthorised middleware

---

app/routes.js
test/integration/routes.it.test.js
test/test-helpers/mock-session.js

If a user visits an old account URL not containing the account external ID, if they don't have a `gateway_account` cookie set, redirect them to "My services".
This will allow us to stop setting the `gateway_account` cookie when users first log in and retain sensible behaviour.

PP-7734 Redirect to my services for old URLs if no cookie

---

app/views/transaction-detail/_refund.njk
app/views/transaction-detail/index.njk
test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js

- Update refund button as per design recommentation
- Add/change heading to 'Refund'
- Make refund button secondary on the page
- Change 'Refund button' to 'Confirm refund' when submitting for refund
1. On visiting transaction page
2. On clicking 'Refund payment'
3. On confirming refund

PP-7235 Update refund section UI

---

app/middleware/get-service-and-gateway-account.middleware.js
app/services/auth.service.js
app/utils/log-context.js
app/utils/logger.js
server.js
test/integration/log-context.it.test.js

Add middleware to open an AsyncLocalStorage store on a request. Add the correlation ID when the store is initialised.
Add a format function to the logger that pulls fields that have been added to the store and adds them to the log line.
Add middleware to add user info to the log context when it is available. Add account and service info to the log context in the middleware that resolves them.
Re-order the server middleware so that the auth middleware is run after the global middleware that initialises logging amongst other things.

PP-7570 Use AsyncLocalStorage to provide shared logging context

---

app/controllers/request-to-go-live/organisation-name/post.controller.js

Prevent having duplicate organisations in our reports due to trailing whitespaces by trimming the name when it is entered.

BAU Trim whitespace from organisation name

---

server.js

There is an issue when body-parser middleware is added after an AsyncLocalStorage store is opened, where the async context is lost.
This is identified here https://stackoverflow.com/questions/64330910/nodejs-asynclocalstorage-getstore-return-undefined, although no cause is identified.
This ordering was also required in Toolbox when using a different library using async_hooks.
Change middleware ordering to fix this.

PP-7570 Fix logging context for POST requests

---

app/assets/csv/sample_reporting_payout.csv
app/views/dashboard/_links.njk
app/views/payouts/list.njk
app/views/request-psp-test-account/index.njk
test/cypress/integration/payouts/payouts-list.cy.test.js

Description:
- Display 'No payments to your bank acount found on or after...' only for live accounts with no payouts
- Display sample report and inset text explaining test reports only for test accounts with no payouts
- Added a cypress test to verify if sample report is displayed on test account if there are no payouts
- Added a cypress test to verify if text is shown indicating no payouts on a live account if there are no payouts

PP-8003 - Release Stripe content changes

---

app/utils/display-converter.js

Policy document pages were being shown as account pages before the
refactored URL based account routing. This behaviour is not desired as
the it would have been the previous account the user had selected, which
will never be directly relevant to the policy document selected.
Include the template path in the non-service/ account pages until the
template inheritance method is reviewed.
**Current behaviour**

BAU Include policy pages in non-service/account templates

---

app/views/includes/cookie-message.njk

- This will make the banner easier to navigate for screen readers.

PP-8015 Cookie banner - replace "aria-describedby" with "aria-label=cookie banner"

---

app/services/clients/ledger.client.js
test/mocha.opts
test/unit/clients/ledger-client/ledger-get-transaction-details.pact.test.js
test/unit/clients/ledger-client/ledger-get-transaction-events.pact.test.js
test/unit/clients/ledger-client/ledger-get-transaction-summary.pact.test.js
test/unit/clients/ledger-client/ledger-pact-test-provider.js
test/unit/clients/ledger-client/ledger-search-payout.pact.test.js
test/unit/clients/ledger-client/ledger-search-transaction.pact.test.js

Pact tests have begun failing locally as they are taking longer than the 5 second timeout. It's unclear why, but increasing the timeout allows for them to pass.
Also, we were using a hardcoded port defined in the test.env file when running ledger pact tests. Instead default to using a free port assigned by the pact provider and pass this to the client when making request to ledger, as we do for all other pact tests.
This means that there isn't possible conflict with another process using the same port.

BAU Fix pact tests failing locally

---

app/controllers/register-service.controller.js
app/controllers/register-user.controller.js
app/errors.js
app/middleware/error-handler.js
test/integration/register-user.controller.ft.test.js
test/integration/self-registration/self-registration-otp-resend.ft.test.js
test/integration/self-registration/self-registration-otp-verify.ft.test.js
test/unit/controller/register-service-controller/register-service.controller.test.js

Add a new error type to handle in the error handler which is thrown when the registration data isn't found in the session cookie. This allows us to handle these errors uniformly. Use a 400 error code for this as it makes more sense than 404.
Handle unexpected errors by passing an error to next to show the standard 500 error page.

PP-8032 Handle errors uniformly for registration

---

app/utils/response.js

All unexpected errors are now handled by the error handler middleware which sends the error to Sentry before rendering the internal error page.
There are many other times we render the error view, when there are errors for things such as cookies missing or invites having expired which are "business as usual" and do not need to be investigated by a developer. This will stop events being sent to Sentry for these type of errors.

PP-8032 Don't log at error level every time we show error

---

.secrets.baseline
package-lock.json
package.json

- Noticed in `npm audit --production` that a lot of transitive vulnerable dependencies are related to pact module and also pact is only for testing. So moving pact module to dev dependencies

PP-7905 Move pact module to dev dependencies

---

.github/workflows/run-tests.yml

We might want this as a separate job we can run in parallel, particularly if we can share the build artefacts so they only need to be built once for the workflow. For now add as another step to the same job.

PP-8048 Add step to workflow job to run Cypress tests

---

.github/workflows/run-tests.yml

- First job runs install and compile, and caches the output directories
- Second job restores cache of build directories and runs unit tests
- Third job restores cache of build directories and runs Cypress tests
Unit and Cypress test jobs run in parallel. The build dependencies are cached using the commit SHA and the HEAD reference in the key, so they will be unique to the commit and the branch it's on, so should only be cached for a single workflow run or repeated workflow runs for the same commit.

PP-8048 Run unit and Cypress tests in parallel

---

app/controllers/credentials.controller.js
app/controllers/credentials.controller.test.js
app/controllers/your-psp/get-flex.controller.js
app/controllers/your-psp/get.controller.js
app/controllers/your-psp/post-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/paths.js
app/utils/nav-builder.js
app/views/credentials/epdq.njk
app/views/credentials/index.njk
app/views/credentials/smartpay.njk
app/views/credentials/worldpay.njk
app/views/your-psp/_epdq.njk
app/views/your-psp/_smartpay.njk
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/_worldpay.njk
app/views/your-psp/flex.njk
app/views/your-psp/index.njk
test/cypress/integration/settings/your-psp.cy.test.js

Link specficially to payment provider versions of PSP and credential
configuration pages.
This willl support individual accounts to link to multiple credential
configurations.
It will also allow supported PSP credential specific pages, Worldpay
with Worldpay credential validation.
- The "Your PSP" and "Credentials" pages should work exactly as they do now, no user facing changes

PP-8131 Namespace PSP and credential pages by provider

---

app/views/credentials/worldpay.njk
test/cypress/integration/settings/your-psp.cy.test.js

E2E select by ID https://github.com/alphagov/pay-endtoend/blob/8b3165297ec56f1a6d774bfac61d17be07d56abd/src/test/java/uk/gov/pay/endtoend/pages/selfservice/GatewayAccountEditCredentialsPage.java#L12
Even though this is inconsistent, remove the discrepancy

PP-8131 Fix lining up worldpay creds page with end to end selectors

---

app/controllers/credentials/credentials-form.js
app/controllers/credentials/credentials-form.test.js
app/controllers/credentials/worldpay.controller.js
app/views/credentials/worldpay.njk

Allow environments to suppress PSP credential validation checks.
Set `SKIP_PSP_CREDENTIAL_CHECKS` to "true" in an environment to skip
checking the PSP credentials against the PSP before submitting them to
Connector.
This should allow the end to end environment to use fake credentials and
support to respond to issue in the case of network issues or a Worldpay
failure response incident
* Add logging for audit trail around error and validation on credentials
* Content updated to use instructions

PP-8131 Allow environments to skip PSP credential validation

---

test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/worldpay-credentials.fixtures.js

Now that fixtures exist that are checked against consumer pacts, use those in the Worldpay credentials validation Cypress tests.

PP-8131 Use pact fixtures in Worldpay credentials validation tests

---

app/assets/sass/application.scss
app/assets/sass/components/task-list.scss
app/controllers/switch-psp/switch-psp.controller.js
app/middleware/error-handler.js
app/middleware/restrict-to-switching-account.js
app/middleware/restrict-to-switching-account.test.js
app/paths.js
app/routes.js
app/utils/credentials.js
app/utils/credentials.test.js
app/utils/nav-builder.js
app/views/switch-psp/switch-psp.njk
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/gateway-account.fixtures.js

Add controllers, template and base test structure for the switching PSP page.
Future pull requests will add individual tasks and completion in conjunction with the backend specs becoming available.
* if an account is not configured to switch, navigating to the page `404`s 
* if an ambiguous switching configuration is found (too many or too few credentials to fill in) an invalid configuration error is raised and handled
* page descriptions and requirements templated in based on the provider being switched to
* cover new middleware and controllers
**Base page that can be integrated with individual future steps**

PP-8213 Switching PSP base page

---

test/unit/clients/connector-client/connector-post-worldpay-check-3ds-flex-config.pact.test.js
test/unit/clients/connector-client/connector-post-worldpay-check-credentials.pact.test.js

I'm not familiar with the chai `should` syntax but this unit test seems
to fail every so often for no reason.
Use async/ await syntax to make it clearer what's going on and review
behaviour to make sure it will only return once the request and
assertion have completed.
- test should pass 
- test should always pass, independent of CPU cycles, temperature, day of the week, alignment of the stars

BAU Fix setup for flakey worldpay flex pact

---

app/controllers/credentials.controller.js
app/controllers/credentials.controller.test.js
app/controllers/credentials/worldpay.controller.js
app/controllers/credentials/worldpay.controller.test.js
app/controllers/switch-psp/switch-psp.controller.js
app/controllers/switch-psp/switch-tasks.service.js
app/controllers/switch-psp/switch-tasks.service.test.js
app/paths.js
app/routes.js
app/services/clients/connector.client.js
app/utils/credentials.js
app/utils/credentials.test.js
app/utils/nav-builder.js
app/views/credentials/worldpay.njk
app/views/switch-psp/switch-psp.njk
app/views/your-psp/_worldpay.njk

As this is the first task added to the switching PSP process, propose a
basic interface for task lists:
- service to index required tasks indexed by payment provider
- callable methods assigned to tasks to determine if they are enabled
or complete
- template drives look of task items (link, status tag, aria, ids) --
this can be optimised with macros when there are more task list items
for more providers
Update the new worldpay credentials controller to be aware of switch account linking context.
- add branch to worldpay credential to use new connector route if
switching psp -- cover this well with unit assertions
- add context aware back link

PP-8216 Switch PSP - linking Worldpay credentials

---

app/controllers/credentials/worldpay.controller.js
app/controllers/credentials/worldpay.controller.test.js
app/controllers/switch-psp/switch-tasks.service.test.js
app/services/clients/connector.client.js
test/fixtures/gateway-account.fixtures.js
test/unit/clients/connector-client/connector-patch-gateway-account-credentials.pact.test.js

- Fix the request body sent to the new PATCH gateway account credentials endpoint to match the format expected, and also update the last_updated_by_user_external_id.
- Add pact test.

PP-8216 Fix patch and add pact test

---

app/controllers/credentials/worldpay.controller.js
app/controllers/switch-psp/switch-psp.controller.js
app/controllers/switch-psp/switch-tasks.service.js
app/controllers/switch-psp/switch-tasks.service.test.js
app/controllers/switch-psp/verify-psp-integration.controller.js
app/controllers/switch-psp/verify-psp-integration.controller.test.js
app/paths.js
app/routes.js
app/services/clients/connector.client.js
app/utils/verify-psp-integration.js
app/utils/verify-psp-integration.test.js
app/views/switch-psp/switch-psp.njk
app/views/switch-psp/verify-psp-integration-payment.njk
test/fixtures/connector-charge.fixtures.js

Adds pages
* verify PSP integration page, routes to start and receive test payment journey hooks
Extends connector helpers
* add helper methods to interact with Connector charges (creating and
checking in-flight status)
* fixtures for charge interaction (POST and GET return the same shape of
data)
Updates switching PSP tasks
* refactored to use a new `taskListItem` macro that will keep formatting consistent for all future tasks
* added task for verifying PSP integration
Proposed to add in a follow up PR
* pacts with Connector for new endpoints
* Cypress happy path for this task list item
Recommend stepping through commits as each piece was done in a logical order, happy to split into multiple PRs if more appropriate for reviewing.
Journey step page
Successful task item completion 
Failed …

PP-8215 Switching payment validator tool

---

app/controllers/switch-psp/verify-psp-integration.controller.js
app/paths.js
app/routes.js
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/stubs/connector-charge-stubs.js

Depends on https://github.com/alphagov/pay-selfservice/pull/2793
Add Cypress coverage for task lisk item to verify PSP integration.
Asserts that high level success and non-success payment routes are
appropriately handled.

PP-8215 Cypress coverage for payment validator task 

---

test/cypress/integration/settings/switch-psp.cy.test.js

Jenkins sets a different URL for end to end tests that other
envrionments. Use a relative URL for the `next_url` on switch PSP tests
so that it doesn't matter what environment it is run in.

PP-8215 Fix using absolute path for cypress environment

---

app/controllers/switch-psp/switch-psp.controller.js
app/controllers/switch-psp/switch-psp.controller.test.js
app/routes.js
app/services/clients/connector.client.js
app/views/switch-psp/switch-psp.njk
app/views/your-psp/index.njk
test/cypress/integration/settings/switch-psp.cy.test.js

Add button and POST endpoint to switch account payment service provider.
Button is only available if all of the required tasks are complete.
Add connector client helper to call new `switch-psp` endpoint.
Add coverage for POST switch controller and assertions on button state
for different end to end scenarios.
**Button blocked before task list is complete**
**Button available when task list is complete**
**Navigates to your PSP on completion**

PP-8217 Add button to switch provider

---

app/controllers/credentials.controller.js
app/controllers/credentials.controller.test.js
app/controllers/credentials/worldpay.controller.js
app/controllers/credentials/worldpay.controller.test.js
app/controllers/digital-wallet/post-google-pay.controller.js
app/services/clients/connector.client.js
test/cypress/integration/settings/allow-google-pay.cy.test.js

To interleave with backend releases, define a future strategy that will be used only when multiple credentials are available on an account -- this will make sure code that doesn't replace the top level `credentials` will only be run when a service opts-in to the new switching code. 
Once the backend is fully released in production the branching logic can be removed (PP-8723) and the future strategy will be default. 
Do this for credentials and patching google pay details.

PP-8190 Update credentials by ID future strategy

---

app/controllers/dashboard/dashboard-activity.controller.js
app/controllers/your-psp/get.controller.js
app/views/dashboard/_switching-psp-banner.njk
app/views/dashboard/index.njk
app/views/includes/phase-banner.njk
app/views/your-psp/index.njk
test/cypress/integration/settings/switch-psp.cy.test.js

* notification banner on dashboard if switching
* account header for all account pages status label updated to factor in
switching progress
* end of switch status text added to your psp page
* cypress coverage for visual elements

PP-8214 Switching PSP banners and labels

---

app/utils/credentials.js
app/utils/credentials.test.js

When moving from a psp that doesn't support credential pages (currently
sandbox and stripe) the current algorithm returns a pending credential
as it assumes it is the only one on the account.
Guard against this by checking against the complete number of
credentials rather than one already filtered by provider.

PP-8190 Fix listing non-terminal credential pages

---

app/controllers/credentials.controller.js
app/controllers/credentials.controller.test.js
app/controllers/credentials/worldpay.controller.js
app/controllers/credentials/worldpay.controller.test.js
app/controllers/digital-wallet/post-google-pay.controller.js
app/services/clients/connector.client.js
test/unit/clients/connector-client/connector-patch-gateway-account-merchant-id.pact.test.js

We were using the old endpoints previously if not switching supplier, as connector was still reading credentials from the credentials column on the gateway account. Now we're no longer using that column we can just use the new endpoints to only update the `gateway_account_credentials` table.

PP-8273 Always use new PATCH credentials endpoint

---

app/controllers/switch-psp/switch-psp.controller.js
app/controllers/switch-psp/switch-psp.controller.test.js
app/controllers/switch-psp/verify-psp-integration.controller.js
app/controllers/switch-psp/verify-psp-integration.controller.test.js
app/utils/credentials.test.js
app/utils/verify-psp-integration.js
app/views/switch-psp/switch-psp.njk
app/views/switch-psp/verify-psp-integration-payment.njk
test/cypress/integration/settings/switch-psp.cy.test.js

Previously, we were redirecting to the "Switch PSP" page if the test payment failed. Instead redirect to the "Test connection" page.
Use `req.flash` to display the error/success messages and remove some of the boiler plate as it makes less sense now they're displayed on different pages.

PP-8272 Redirect to test connection page on payment failure

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/company-number/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/vat-number/post.controller.js

Log when Stripe account details provided by admin tool. These details
are provided in initial onboarding and when services are switching PSP
to Stripe.

PP-8218 Log on completion of Stripe on-boarding tasks

---

test/unit/clients/connector-client/connector-post-create-charge.pact.test.js

Description:
- Previously no payment_provider was provided which didn't allow us to test the happy path
- PR adds the payment_provider field allowing us to test the happy path to Connector

PP-8210 - Update post-create-charge pact test to include payment_provider

---

README.md
app/routes.js
test/unit/routes.test.js

Make `/.well-known/security.txt` and `/security.txt` redirect to https://vdp.cabinetoffice.gov.uk/.well-known/security.txt.
Update `README.md` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.

PP-8095 Add security.txt file

---

app/controllers/switch-psp/switch-tasks.service.js
app/utils/nav-builder.js
app/views/payment-links/manage.njk
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/integration/stripe-setup/company-number.cy.test.js
test/cypress/integration/stripe-setup/responsible-person.cy.test.js

- Show the "Payment links" option in the account navigation for view-only users and make it link to the "View payment links" page.
- Hide the left hand nav for view-only users as they are not able to create payment links.
- Hide the text about adding metadata for view-only users.
- Move the warning text for view only users below the h1.

PP-8296 Improve view payment links page for view-only users

---

app/services/clients/adminusers.client.js
app/services/clients/connector.client.js
app/services/service-registration.service.js
app/services/service.service.js
test/cypress/integration/my-services/add-new-service.cy.test.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/stubs/service-stubs.js
test/fixtures/gateway-account.fixtures.js
test/fixtures/invite.fixtures.js
test/fixtures/service.fixtures.js
test/integration/self-registration/self-registration-otp-verify.ft.test.js
test/integration/service-registration.service.it.test.js
test/unit/clients/adminusers-client/invite/complete-service-invite.pact.test.js
test/unit/clients/adminusers-client/service/create-service.pact.test.js

Test card gateway accounts are created by default when a new service is
created, this happens:
- when an existing user adds a new service
- when a new user signs up for Pay, either themselves or following an
invite link
We are now associating connector integrations with services rather than
storing the internal IDs of card connector gateway accounts in the
service object.
- send `service_id` through with all calls to create card gateway
account
- remove `gateway_account_ids` attribute from calls to create service
(backend resources set this as optional, nothing provided will still
result in a created service)
- change order of operations so that a service is created first,
followed by the test card gateway account
- pass the service id correctly to the call to create a default card …

PP-8438 Associate service ID when creating default test card account

---

app/controllers/billing-address/toggle-billing-address.controller.js
app/controllers/digital-wallet/post-apple-pay.controller.js
app/controllers/digital-wallet/post-google-pay.controller.js
app/controllers/email-notifications/email-notifications.controller.js
app/controllers/settings/get.settings.controller.js
app/controllers/toggle-3ds/3ds.post.controller.js
app/controllers/toggle-moto-mask-card-number/toggleMotoMaskCardNumber.post.controller.js
app/controllers/toggle-moto-mask-security-code/maskSecurityCode.post.controller.js
app/paths.js
app/routes.js
app/utils/humanise-email-mode.js
test/cypress/integration/settings/3ds.cy.test.js
test/cypress/integration/settings/allow-apple-pay.cy.test.js
test/cypress/integration/settings/allow-google-pay.cy.test.js
test/cypress/integration/settings/email-notifications.cy.test.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/unit/controller/billing-address-controller/toggle-billing-address.controller.ft.test.js

Previously, some settings pages would stay on the same page and display an error message when submitted, and others would redirect back to the main settings page.
Make this consistent so that:
- We always redirect to the main settings page when setting is saved
- We always display a success message
Additionally, have refactored email-notifications.controller.js to adhere to our style guide.

PP-8445 Make settings redirects consistent

---

app/controllers/settings/default-billing-address-country.controller.js
app/controllers/settings/get.settings.controller.js
app/models/Service.class.js
app/paths.js
app/routes.js
app/services/clients/adminusers.client.js
app/utils/nav-builder.js
app/views/default-billing-address-country/index.njk
app/views/settings/index.njk
test/cypress/integration/settings/default-billing-address-country.cy.test.js
test/cypress/integration/settings/email-notifications.cy.test.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/stubs/service-stubs.js
test/cypress/stubs/user-stubs.js
test/fixtures/service.fixtures.js
test/unit/clients/adminusers-client/service/update-default-billing-address-country.pact.test.js
test/unit/controller/settings/default-billing-address-country.controller.test.js

Add settings page to update the default billing address country for a service.
Currently, the 2 options are to set the pre-filled country either to 'United Kingdom' or to be blank.

PP-8445 Add settings page for default country

---

app/services/clients/stripe/stripe.client.js

- Pass httpAgent to Stripe constructor instead of using deprecated `setHttpAgent` method
- Also sets `timeout` to retrieve account details to 1 second which was originally intended rather than 10 seconds

PP-8555 Pass httpAgent to Stripe constructor

---

app/utils/transaction-view.js
test/cypress/integration/transactions/transaction-search.cy.test.js
test/fixtures/ledger-transaction.fixtures.js

For stripe accounts we display net amount. Due to switching work, there are now accounts where net amount is displayed for payments not taken with stripe. These will sometimes have total amount set.
The bug was that in these cases, total amount would be displayed in net column (correct) but incorrectly formatted - see https://govuk.zendesk.com/agent/tickets/4708679
This PR adds test that recreates bug and fix - always format `total_amount` if set.
It also fixes small bug in tests, where total amount was not being passed through in ledger fixtures.

BAU Fix net amount display

---

app/assets/sass/application.scss
app/assets/sass/components/contract.scss
app/views/policy/policy-html.njk

- When printing - it displays the URL of the dowload link which is really long.
- This PR hides this section when printing as it is not required in the printed
version.

PP-8571 Contract pages - hide download link section when printing

---

app/views/two-factor-auth/index.njk

Update the authenticator app links (shown to a user on the page that lets them choose their sign-in method) to be more helpful.
The Duo homepage is very enterprisey, so link instead to the specific page for the Duo Mobile app, which still is not aimed at end users but a least has links to download the app.
Update the Microsoft Authenticator link (the old link redirects to the new one).

PP-8715 Update authenticator app links

---

.github/dependabot.yml

- Due to recent update to `@sentry/node` version (https://github.com/alphagov/pay-selfservice/pull/2934), all requests to stripe started to fail.
- This could be due to the way sentry is set up in selfservice middleware.
- Ignoring new versions until this is looked into closely

BAU - Ignore @sentry/node versions

---

app/views/your-psp/_stripe.njk

- Changes `<ol>` to `<div>` tag to remove left padding for KYC tasks

PP-8801 Fix KYC tasks spacing

---

app/browsered/analytics.js
test/unit/browsered/analytics.test.js

- Fix bug so that when the Google Analytic cookies are created -
we explicitly set a domain.
- Update the `ga('create'...)` to use the cookieFunctions.getDomainCookie
method.

PP-8519 Google Analytics - set cookie domain.

---

app/controllers/email-notifications/email-notifications.controller.js

Client side validation was refined and improved in
https://github.com/alphagov/pay-selfservice/pull/2966.
It looks like the maximum paragraph length for custom emails was set in
error, revert it to its previous value.

BAU Fix custom email paragraph validation length

---

app/services/clients/stripe/StripeDirector.class.js
app/services/clients/stripe/StripeDirector.class.test.js
app/services/clients/stripe/stripe.client.js

- Added new class for StripeDirector which will be used when adding new director for stripe accounts.
- Separate class instead of using StripePerson to keep classes simple. 
- Other options could be i) to use StripePerson for both responsible person and director ii) define base class and inherit as needed.
- Added new stripe client method to create and update director.

PP-8804 Add StripeDirector class

---

app/controllers/stripe-setup/vat-number/post.controller.js
app/controllers/stripe-setup/vat-number/post.controller.test.js
app/controllers/stripe-setup/vat-number/vat-number-validations.js
app/controllers/stripe-setup/vat-number/vat-number-validations.test.js
app/views/stripe-setup/vat-number/index.njk
test/cypress/integration/stripe-setup/vat-number.cy.test.js

- At present, VAT number is mandatory for services onboarding with Stripe. Services will have enter a valid VAT number and if they don’t have one, we need to override tasks (manual update to DB). VAT is not a mandatory field as per Stripe. Thus make it optional in onboarding journey.
- update cypress tests

PP-8832 make vat number optional

---

app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/stripe-setup.util.test.js

- Added a new Stripe setup utility which has common functions used across stripe setup controllers (responsible person, director, bank details and so on).
Some could possibly (like `getFormFields`) be used in all selfservice controllers.

PP-8804 Add Stripe setup utility

---

app/controllers/stripe-setup/bank-details/get.controller.js
app/controllers/stripe-setup/bank-details/get.controller.test.js
app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js
app/controllers/stripe-setup/company-number/get.controller.js
app/controllers/stripe-setup/company-number/get.controller.test.js
app/controllers/stripe-setup/company-number/post.controller.js
app/controllers/stripe-setup/company-number/post.controller.test.js
app/controllers/stripe-setup/director/get.controller.js
app/controllers/stripe-setup/director/get.controller.test.js
app/controllers/stripe-setup/director/post.controller.js
app/controllers/stripe-setup/director/post.controller.test.js
app/controllers/stripe-setup/responsible-person/get.controller.js
app/controllers/stripe-setup/responsible-person/get.controller.test.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js
app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/vat-number/get.controller.js
app/controllers/stripe-setup/vat-number/get.controller.test.js
app/controllers/stripe-setup/vat-number/post.controller.js
app/controllers/stripe-setup/vat-number/post.controller.test.js
test/cypress/integration/stripe-setup/bank-details.cy.test.js
test/cypress/integration/stripe-setup/company-number.cy.test.js
test/cypress/integration/stripe-setup/director.cy.test.js
test/cypress/integration/stripe-setup/responsible-person.cy.test.js
test/cypress/integration/stripe-setup/vat-number.cy.test.js

Previously, we were redirecting to the dashboard and displaying an
error message in an error summary banner. However, the banner was
appearing inside the blue banner asking to submit details.
Instead, render an error page displaying the error with a link to go to
the dashboard.
Before:
After:

PP-8913 Render error page for Stripe details already submitted

---

app/views/email-notifications/email-refund-body.njk

We discovered a copy issue with the header text in the Self-Service UI email example template. This should correct the example to match what we send in production.
This was discovered by a user and reported via our Helpdesk.

[ZD-4775772] Fix heading in refund email example

---

app/controllers/switch-psp/switch-tasks.service.js
app/views/switch-psp/switch-psp.njk
test/cypress/integration/settings/switch-psp.cy.test.js

Add the task to add director information to the switch PSP task list
when switching to Stripe.
Displaying the page with the back link and navigating back to the task
list after completion has already been implemented.

PP-8834 Add director task to switch PSP

---

app/controllers/stripe-setup/responsible-person/get.controller.js
app/paths.js
app/routes.js
app/views/stripe-setup/responsible-person/index.njk
app/views/stripe-setup/responsible-person/kyc-additional-information.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
test/cypress/integration/stripe-setup/responsible-person.cy.test.js
test/cypress/stubs/stripe-psp-stubs.js
test/fixtures/stripe-psp.fixtures.js

Add a new view to add the additional fields for the responsible person,
showing the name of the existing responsible person with the option to
change it.
This commit only implements loading the page, not submission or loading
the form to change the responsible person.
Hiding whitespace changes will make this a lot easier to review, as the indentation in the cypress tests has changed.

PP-8803 Add page to add additional responsible person details

---

app/controllers/stripe-setup/responsible-person/get.controller.js
app/views/stripe-setup/responsible-person/index.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js

When the "Change" button is clicked next to the name of the existing responsible person on the KYC additional information page, reload the responsible person page with all fields present.

PP-8803 Show all responsible person fields when change is clicked

---

app/controllers/webhooks/webhooks.controller.js
app/controllers/webhooks/webhooks.service.js
app/controllers/webhooks/webhooks.service.test.js
app/paths.js
app/routes.js
app/services/clients/webhooks.client.js
app/utils/display-converter.js
app/views/webhooks/edit.njk
app/views/webhooks/list.njk
test/cypress/integration/webhooks/webhooks.cy.test.js
test/cypress/stubs/webhooks-stubs.js
test/fixtures/webhooks.fixtures.js
test/unit/clients/webhooks-client/webhooks.pact.test.js

Controller, paths and routes to connect the create and update routes.
Use the same template with an `isEditing` flag to reduce boilerplate. Explicit controllers for creating and updating call separate backend endpoints.
- bump pay js commons dependency to bring in new Webhooks constants definitions
- add simple service method to normalise frontend checkbox form
formatting to always send an array of subscriptions to the backend
This pull request doesn't do any validation on the create/ update inputs. If this should be done as a one off (following a similar example to other admin tool pages) or used as the first instance of a shared forms validation library should be discussed.

PP-8498 Create/ update Webhook page

---

app/views/kyc/organisation-url.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js

- Update the `organisation-url.njk` template
- Use the `error-summary.njk` macro so the summary is consistent
with Design System guidelines.
- Update Cypress test

PP-8802 Org URL - Update error messages to be consistent with Design System

---

app/views/stripe-setup/vat-number/index.njk
test/cypress/integration/stripe-setup/vat-number.cy.test.js

For radio buttons, there is no ID for the containing fieldset, so error summary messages need to link to the first radio button item. Fix the ID for the error on the VAT number page so it links to the first radio button item, which has a custom ID.

PP-8928 Fix link in error summary

---

app/controllers/your-psp/get.controller.js
app/controllers/your-psp/kyc-tasks.service.js
app/models/StripeAccountSetup.class.js
app/utils/credentials.js
app/views/your-psp/_stripe.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
test/cypress/stubs/stripe-account-setup-stub.js
test/unit/clients/connector-client/connector-get-stripe-account-setup.pact.test.js

Show the completed task list with a different paragraph above it when all KYC tasks have been completed.
Also continue to show the "Your PSP - Stripe" link in the settings navigation after tasks have been completed.
We disable the `requires_additional_kyc_data` flag after all tasks have been completed, but we set the `additional_kyc_data` Stripe setup task on the gateway account, so look at this to determine whether to show the navigation link.

PP-8861 Show KYC task list after all tasks complete

---

app/views/your-psp/_stripe.njk

We were showing the KYC task list after switching PSP to Stripe was
complete, as we were loading the Your PSP page.
Only show the task list when the service is providing KYC data or after
they have completed providing KYC data to make sure this doesn't happen.
Most of the affected lines are just indentation changes, hiding whitespace changes might help
This is what was happening:

PP-8861 Don't show KYC task list after Stripe switch complete

---

Dockerfile

switched `npm install` to `npm ci`, as reported by @heathd, which creates reproducible builds.
`docker build .` observe how `package-lock.json is unmodified`
On my machine, both take 84s to build, so there appears to be no change in build time.

PP-8901 `npm install` -> `npm ci`

---

app/controllers/stripe-setup/government-entity-document/index.js
app/controllers/stripe-setup/government-entity-document/post.controller.js
app/controllers/stripe-setup/government-entity-document/post.controller.test.js
app/routes.js
server.js
test/cypress/integration/stripe-setup/government-entity-document.cy.test.js

- Added post controller for new Stripe onboarding task (Proof of Government Entity document)
- Starts using csrfToken available on query param as for multipart form we will be specifying csrfToken as the query param
- Use multer middleware to handle multipart/form-data and configured to use in-memory storage by default.
Can't add Cypress tests for full post journey as stripe hardcodes hostname (files.stripe.com) for file upload and cannot be overridden. Unit tests asserts that correct payload is passed to stripe client methods.

PP-8962 Add post controller for government entity document task

---

app/controllers/stripe-setup/company-number/post.controller.js
app/controllers/stripe-setup/company-number/post.controller.test.js

- We are creating new stripe accounts with capabilities -card_payments, transfers. Companies house registration number is no longer mandatory for accounts with these capabilities. It was mandatory for legacy_payments capabilities and we had to set something to enable stripe accounts.

PP-8983 Stop setting default value for company number

---

app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/stripe-setup.util.test.js
app/services/clients/stripe/StripePersonAdditionalKYCDetails.class.js
app/services/clients/stripe/StripePersonAdditionalKYCDetails.class.test.js
app/services/clients/stripe/stripe.client.js

- Set responsible person as executive when updating only phone number and email address.
- For stripe accounts switched to new capabilities (card_payments) company phone number is mandatory. We provided organisation phone number at the time of creating stripe account (accounts with legacy_payments capabilities) but this appears in a different place (business_profile.support_phone_number) for accounts switched to new capabilities.
- Also remove legacy_payments capability (if exists on account) once new capabilities (card_payments, transfers) are enabled - stripe api https://stripe.com/docs/api/capabilities/update?lang=node to update capability

PP-8860 Stripe KYC: Set additional required fields and remove legacy capabilities

---

app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/stripe-setup.util.test.js

- Use snake case `telephone_number` as it is not converted to camelcase when transforming service response from adminusers

PP-8860 Fix getting telephone number from merchant details

---

app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/stripe-setup.util.test.js
app/services/clients/stripe/stripe.client.js

- As stripe accounts are being restricted (both payments & payouts), stop moving accounts to new capabilities while stripe addresses the issue of providing grace period for services to provide missing info.
- mcc is currently set when switching stripe accounts to new capabilities. But mcc cannot be updated if it is already set on account (some live accounts on Stripe has mcc set). So set mcc only when it is not available on stripe account.

PP-8929 Stripe KYC: stop moving stripe accounts to new capabilities

---

app/middleware/multer-middleware.js
app/routes.js

- We are using multer for document upload and noticed request context (gateway_account_id, service id,...) added as part of middleware are missing from the logs. This works sometimes and not sure yet why.
- There is an open issue multer where content is lost #/multer/issues/814 and the work around is to wrap upload in a Promise.
with @stephencdaly, @sandorarpa, @nlsteers, @nimalank7

PP-8929 Wrap multer upload with a Promise

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/paths.js
app/routes.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js

- Added a new route `organisation-details` (for stripe kyc and switch PSP) which uses existing organisation details controller and .njk template.
with @stephencdaly, @sandorarpa, @nlsteers, @nimalank7

PP-8995 Stripe KYC - Add get controller for organisation details

---

app/controllers/stripe-setup/stripe-setup.util.js
app/controllers/stripe-setup/stripe-setup.util.test.js
app/services/clients/stripe/stripe.client.js

- Enable new capabilities for stripe accounts when services submits all info (but does not remove legacy payments capabilities). legacy_payments capability will be removed (manually and in batch) after verifying that the stripe accounts do not have any information due.

PP-8929 Stripe KYC: enable new capabilities

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/paths.js
app/routes.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js

Reverts alphagov/pay-selfservice#3130 as we are going to review organisation details separately for new users flow and for existing stripe accounts, we will address any issues with verification manually. There won't be issues with accounts as legacy_payments capabilities won't be removed until accounts are fully verified for new capabilities.

Revert "PP-8995 Stripe KYC - Add get controller for organisation details"

---

app/controllers/edit-service-name.controller.js
app/controllers/register-service.controller.js
app/views/services/add-service.njk
app/views/services/edit-service-name.njk
test/cypress/integration/my-services/add-new-service.cy.test.js
test/cypress/integration/my-services/update-service-name.cy.test.js

If there were validation errors when adding a Welsh service name, these were not being passed correctly through to the view, and not displayed inline correctly.
This affects adding new services and editing service names.
Remove validation for Welsh service names from the controller for naming a service when registering an account, as the page shown for this does not have an option to add a Welsh name.
Also fix the page for adding a new service so that the checkbox for adding a Welsh name is checked if a Welsh name has been entered but  there are errors.

BAU Fix Welsh service name validation

---

app/controllers/webhooks/webhooks.controller.js
app/routes.js
app/utils/nav-builder.js
app/views/webhooks/detail.njk
app/views/webhooks/edit.njk
test/cypress/integration/webhooks/webhooks.cy.test.js

* adds template and controller for webhooks detail page
* conditionally display data that may not be supported by the backend, show a degraded message if not available
* updates existing create/ update flow to work with the detail page
Depends on https://github.com/alphagov/pay-selfservice/pull/3012

PP-8499 Webhook detail page

---

app/assets/sass/components/colour.scss
app/controllers/webhooks/webhooks.controller.js
app/controllers/webhooks/webhooks.service.js
app/controllers/webhooks/webhooks.service.test.js
app/paths.js
app/routes.js
app/services/clients/webhooks.client.js
app/views/webhooks/detail.njk
app/views/webhooks/signing_secret.njk
app/views/webhooks/toggle_active.njk
test/cypress/integration/webhooks/webhooks.cy.test.js
test/cypress/stubs/webhooks-stubs.js
test/fixtures/webhooks.fixtures.js

Adds pages to manage an individual webhooks, supporting
* accessing a given webhooks signing secret
* deactivating and activating a given webhook
Adds helper methods for accessing singing secret endpoint and service wrapper to toggle status.
Happy path Cypress coverage.
**Signing secret page**
**Toggle status page**
**Detail page (following toggle status action**

PP-8499 Manage Webhook pages

---

app/controllers/webhooks/webhooks.controller.js
app/controllers/webhooks/webhooks.service.js
app/controllers/webhooks/webhooks.service.test.js
app/paths.js
app/services/clients/webhooks.client.js
app/views/webhooks/_paginator.njk
app/views/webhooks/detail.njk
test/cypress/integration/webhooks/webhooks.cy.test.js
test/cypress/stubs/webhooks-stubs.js
test/fixtures/webhooks.fixtures.js

Implement webhook messages table on the details page.
Status tags to represent proposed message states, dates passed through commons formatting.
Support
* status filter propagated through to backend calls
* page query propagated through to backend calls
* pagination utility

PP-8499 Webhook messages table

---

app/controllers/policy/policy.controller.js
app/controllers/policy/supported-policy-documents.js
app/utils/display-converter.js
app/views/policy/document/v2/contract-for-non-crown-bodies.njk
app/views/policy/document/v2/memorandum-of-understanding-for-crown-bodies.njk
app/views/policy/document/v2/policy-no-html.njk
app/views/policy/document/v2/stripe-connected-account-agreement.njk

Added accessible pages for the 2022 contracts, these are PDF download only for now with a view adding HTML at a later date.
Paired with @stephencdaly

PP-9080 add pages for 2022 contracts

---

app/controllers/all-service-transactions/download-transactions.controller.js
app/controllers/transactions/transaction-download.controller.js
app/utils/get-query-string-for-params.js

- Requests CSV for fee breakdown fields if
- for test accounts, flag `ENABLE_FEE_BREAKDOWN_IN_CSV_FOR_STRIPE_TEST_ACCOUNTS` is set
- or current date is on or after the env variable INCLUDE_FEE_BREAKDOWN_HEADERS_IN_CSV_DATE (timestamp). Defaults to 1642982460 (24-Jan-22).

PP-9038 Request CSV with fee breakdown headers if enabled

---

package-lock.json
package.json

Bring in the latest supported webhook event types.
Lines admin tool up with https://github.com/alphagov/pay-webhooks/pull/55

PP-9077 Bump commons for webhook event type update

---

app/views/webhooks/detail.njk
test/cypress/integration/webhooks/webhooks.cy.test.js

Webhooks typo, events sort order, add webhook description back onto the details page.

BAU  Fix webhooks typo and events sort order

---

.secrets.baseline
app/controllers/my-services/get-index.controller.js
app/controllers/register-service.controller.js
app/services/service.service.js
app/utils/constants.js
test/unit/controller/register-service-controller/register-service.controller.test.js

Ensure that the service we are setting the name for as the last step of a user signing up for a user account is the test service created for them during the sign-up process.
There was an issue where if the user started registering for an account and then accepted an invite to join a service before completing it, they could end up changing the name of the service they were invited to by mistake, as our code was only expecting them to have one service at this point.
To avoid this, check for a service with the default name, which is always "System Generated", and rename that service. If the user does not have a service with the default name, show an error page.
If the user tries to access the page for setting the service name when they do not have a service with the default name, redirect to …

PP-9052 Fix name service during account creation bug

---

.github/workflows/run-tests.yml

In our workflow for running tests on PRs, we cache Cypress so that it doesn't need to be downloaded and installed for each test run, as this takes a number of minutes. This cache is persisted between action runs.
We were caching with the key `Linux-cypress` not taking into account versioning. This means that if we tried to update our Cypress version, we would probably end up with multiple Cypress versions in the same cache due to restoring the existing version from the cache and then installing the new version when we run `npm install`.
To ensure that we only cache and restore the required version, retrieve the Cypress version number from the package.json file and append this to the cache key.

PP-9148 Cache Cypress with version in key

---

app/assets/sass/components/transaction-list.scss
app/views/transactions/list.njk

- Set the background colour of the table to white so that in smaller
screens, you do not get the grey overlap.
- Tables with an overflow do not style well on small screens.
So cannot add a right margin.  So have just left it to go
to the edge of the screen.

PP-9161 Transaction Table - update styling in the mobile view

---

Jenkinsfile
package-lock.json
package.json
test/cypress/integration/cookie-banner/cookie-banner.cy.test.js
test/cypress/integration/errors/errors.cy.test.js
test/cypress/integration/transactions/transaction-search.cy.test.js
test/cypress/plugins/cookie-monster.js

Upgrades:
- Upgrade Cypress to minimum safe version 5
Additions:
- Jenkinsfile now specifies the Cypress version used for integration tests on master builds, see https://github.com/alphagov/pay-jenkins-library/pull/142

PP-9148 prevent unsafe transitive dependencies being resolved by old Cypress version

---

app/controllers/switch-psp/verify-psp-integration.controller.js
app/views/switch-psp/verify-psp-integration-payment.njk
test/cypress/integration/settings/verify-psp-integration.cy.test.js

- Do not allow services switching to Stripe to make a test payment until they are verified. Once Stripe verified and enabled their account, they can make a test payment.

PP-9155 disable making a live payment

---

app/views/switch-psp/verify-psp-integration-payment.njk

When a service verifies their PSP credentials on a live account
(during switching), the error message refers to a specific PSP (Worldpay).
Only mention Worldpay credentials if the target PSP is Worldpay,
otherwise use the same but generic message.

BAU Fix PSP specific verification error message

---

app/controllers/dashboard/dashboard-activity.controller.js
app/views/dashboard/_stripe-account-setup-banner.njk
test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js

- Currently we ask for a `Government entity document` as part of stripe onboarding flow and it is not mandatory for all stripe accounts (accounts with `legacy_payments` capabilities). So we don't check if the `Government entity document` task is completed when displaying stripe-account-setup-banner.
- When the user doesn't complete the `Government entity document` immediately after the `company number` task, then the banner disappears if user logs in again i.e., stripe-account-setup-banner is not displayed if the `Government entity document` task is the only task due.
- so display the banner if ‘Government entity document’ is not completed for stripe accounts without `legacy_payments` capability.
- All accounts (with new capabilities) that are fully verified on stripe has …

BAU - Display stripe account setup banner when entity document task is not completed

---

app/controllers/policy/policy.controller.js
app/controllers/policy/policy.controller.test.js
app/controllers/policy/supported-policy-documents.js
app/controllers/stripe-setup/company-number/post.controller.test.js
app/views/includes/footer-categories.njk

- Revert change with Footer links point to the new 2022 URL.
- Make them link to the original URL.
- Update the orignal contract URLs to use the new V2 policy template files.
- policy.controller
- Remove call to get HTML from S3.
- We will add this back later once we have HTML versions of the contracts.

PP-9264 Update Footer links to new versions of contracts.

---

app/controllers/my-services/get-index.controller.js

- Update the code to increase the time the banner  is displayed until:
- Increase the display time of the banner until 21st Mar 2022.
- Use the Unix date: 1647820800
- Not using the SHOW_NEW_CONTRACTS_BANNER_UNTIL_DATE env variable
- as we currently do not set this in Terraform.
- As easier to just update the code.
- This code will also be removed soon anyway.

PP-9264 New Contract banner on My Services - update how long to show.

---

.github/workflows/post-merge.yml
.github/workflows/run-tests.yml

1. Cache consumer pact files from unit tests to use in post-merge
2. Add post-merge pact tests
Prior to removing the post-merge PR test this run completed succesfully with a `starling-test` pact tag: https://github.com/alphagov/pay-selfservice/actions/runs/1986521835

PP-9239: Run pact tests post-merge

---

app/controllers/all-service-transactions/download-transactions.controller.js
app/controllers/transactions/transaction-download.controller.js
app/utils/get-query-string-for-params.js

- Stripe contract fee V2 is now applicable to all services which use Stripe as PSP, thus we no longer need `includeFeeBreakdownHeaders`. All Stripe csv download will contain the fee break down. Remove fee break down flag.

PP-8608 remove deprecated stripe contract fee handling

---

app/controllers/agreements/agreements.controller.js
app/routes.js
app/views/agreements/detail.njk
test/cypress/integration/agreements/agreements.cy.test.js
test/cypress/stubs/agreement-stubs.js

Adds page to show agreement details and their payment instrument (if it
exists).
Agreement detail pages follows roughly the same pattern as transaction list -> transaction detail.
Caches the filters from the list page in the session to appropriately
return the user to their context.
Uses macros from the agreement list page for consistency.
---
**Agreement that needs payment instrument**
---
**Active agreement**

PP-9542 Add agreements detail page

---

.stylelintrc.json
app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.service.js
app/controllers/agreements/agreements.service.test.js
app/services/clients/ledger.client.js
package-lock.json
package.json
test/cypress/integration/agreements/agreements.cy.test.js
test/cypress/stubs/agreement-stubs.js
test/fixtures/agreement.fixtures.js

Update package.json
- Use the GDS Stylelint NPM module.
- Add Stylelint dependencies.
- Add Stylelint config - to extend GDS Stylelint config.
- Stylelint issues will be fixed in a seperate ticket that will be prioritised in the future.
- Want to remove `sass-lint` so that we can remove the `minimist` override in the future.
- Update Mocha - so it does not use the vulnerable version of Minimist.
- Remove the `minimist` override

PP-9357 Remove 'sass-lint' and add 'stylelint'

---

app/views/two-factor-auth/index.njk

In our list of suggested authenticator apps, remove LastPass Authenticator because the page we link to —
https://lastpass.com/auth/ — now redirects to https://www.lastpass.com/solutions/authentication and extols the virtues of ‘Customizable authentication methods with admin oversight’ and tries to persuade me to sign up for LastPass Business. There is no link to download LastPass Authenticator any more (the app does still seem to be available in the iOS App Store and Google Play but the only page on the LastPass site with download links seems to be a support page at https://support.lastpass.com/help/enroll-the-lastpass-authenticator-app where the download links are buried in the middle of a bunch of steps for enabling 2FA on a LastPass vault, which is not user-friendly).
Replace it with a …

BAU — Remove LastPass Authenticator link and add FreeOTP link

---

app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js
app/services/clients/stripe/StripeOrganisationDetails.class.js
app/services/clients/stripe/StripeOrganisationDetails.class.test.js
app/services/clients/stripe/stripe.client.js

- Update `StripeOrganisationDetails` model
- Makes it so that Org name, tel and URL are optional.
- So that it can be used for all user journey's used by the `Org address` controller.
- Update Stripe client
- Add new method to update Organisation details.
- Stripe setup > Org address > POST Controller
- Add code for a successful submission.
- Update `Stripe` account with new Org details that match the government entity document.
- Update the `Connector > Stripe setup flag` - set this to `organisation_details`
- Update unit tests.

PP-9004 - Stripe Setup > Add Org details - Update Stripe and Setup flag

---

app/models/StripeAccountSetup.class.js
app/services/clients/stripe/StripeOrganisationDetails.class.js
app/views/macro/error-summary.njk
app/views/stripe-setup/check-org-details/index.njk
test/cypress/integration/stripe-setup/check-org-details.cy.test.js
test/cypress/stubs/stripe-account-setup-stub.js
test/fixtures/stripe-account-setup.fixtures.js
test/fixtures/user.fixtures.js

- `check-org-details.test.cy.js`
-  Add new Cypress test file.
- Update Nunjuks files to use the `data-cy` attribute
- This is recommended good practise from Cypress.
- Added this to the `error-summary`, `check-org-details/index.njk` file.
- Also makes it's easier to write test.
- Update `StripeAccountSetup` model
- Add the `organisation_details` field.
- Update Cypress user stubs
- Add new permission - 'stripe-organisation-details:update'
- Required to access the page
- Update `stripe account setup` stub
- Add new `organisation_details` response

Pp 9004 org details page 6 cypress tests

---

app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/stripe-setup/update-org-details.cy.test.js

- New Cypress test file -  `update-org-details.cy.test.js`
- Check validation, user has correct permissions and is using a LIVE Stripe account.
- Hide the telephone and URL fields.
- Update `organisation address > post controller`
- When validation fails, make sure to corrretly pass down the `isRequestToGoLive` and
`isStripeUpdateOrgDetails` flags correctly.
- Rename functions so that the match up to our Node style guide.
- Update unit test
- When validation fails, test the `isRequestToGoLive` and
`isStripeUpdateOrgDetails` flags correctly.

PP-9004 Stripe setup > Update Org details - add Cypress test

---

app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js

- When updating Org details.
- If the user does not submit `address-line2`, then it was sending an empty string
to the Stripe client as `address-line2`.
- Updated code, if the `address-line2` is empty - then do not pass it to the Stripe
client when updating the organisation details.
- Only had to update `update org address` post controller.

PP-9004 Check org details - fix bug with address line 2

---

app/utils/states.js
test/unit/utils/states.test.js

- Added disputes statuses to states.js which are only returned if `includeDisputeStatuses` method param (allDisplayStateSelectorObjects) is `true`

PP-9673 Update states for dispute statuses

---

app/controllers/all-service-transactions/get.controller.js
app/controllers/all-service-transactions/get.controller.test.js
app/utils/permissions.js
test/unit/utils/permissions.test.js

- Displays dispute statuses on all services transactions page if service has stripe account and if relevant (live/test) environment is set to display dispute statuses

PP-9673 Update all-service-transactions to display dispute statuses

---

app/controllers/transactions/transaction-list.controller.js
app/controllers/transactions/transaction-list.controller.test.js

- Displays dispute statuses on account transactions page (status dropdown) if payment provider is stripe and relevant (live/test) environment variable is enabled to display dispute statuses

PP-9763 Display dispute statues on transaction search page

---

app/models/DisputeTransaction.class.js
app/models/DisputeTransaction.class.test.js
app/models/TransactionEvent.class.js
app/services/clients/ledger.client.js
app/services/transaction.service.js
app/utils/transaction-view.js
app/views/transaction-detail/_details.njk
app/views/transaction-detail/_dispute.njk
app/views/transaction-detail/index.njk
test/cypress/integration/transactions/transaction-details.cy.test.js
test/cypress/stubs/transaction-stubs.js
test/fixtures/ledger-transaction.fixtures.js
test/unit/utils/transaction-view.test.js

- If payment is disputed, get and display dispute info on the transaction detail page
- Set payment status to the latest dispute status
_Dispute details_
_Transaction events_
_Payment status_

PP-9662 Display dispute info on transaction details page

---

app/views/agreements/detail.njk
app/views/agreements/list.njk
app/views/agreements/macro/status.njk
test/fixtures/agreement.fixtures.js

The transactions page adds some custom styling to reduce text size.
Update the agreements page to make the styling more consistent and put
statuses into columns to avoid table flow issues.
Add missing properties from agreement detail page.
**Before**
**After**

PP-9846 Bring agreements list styling into line with transactions

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/controllers/request-to-go-live/organisation-address/get.controller.test.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js
app/views/includes/phase-banner.njk
app/views/stripe-setup/update-org-details/index.njk
test/cypress/integration/request-to-go-live/organisation-address.cy.test.js
test/cypress/integration/stripe-setup/check-org-details.cy.test.js
test/cypress/integration/stripe-setup/update-org-details.cy.test.js

- Bug - Stripe setup > Update Org details - was not showing `account sub nav`.
- This is because it uses the same controller and Nunjuks file as `request to go live` >
`organisation address` - and that Nunjuks file is configured in the display converter
to hide the `account sub nav`.
- Create a new template which extends the existing `organisation address` page.
- New template - `update-org-details`
- Use this template when in the `Stripe setup` journey.
- This template will not be configured to hide the `service nav`.
- Update unit tests
- Update Cypress tests
- `phase-banner.njk` - This is the `account sub nav`.  Add a Cypress
data attribute to this - so it is easier to select in a Cypress test.
- Update `Stripe setup` > `check-org-details` & `update-org-details` test to check that …

PP-9004 Stripe setup > update org details - fix template bug

---

package-lock.json
package.json

This fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24434.

 PP-9900: Bump multer to 1.4.5

---

app/controllers/webhooks/webhooks-form.js
app/controllers/webhooks/webhooks-forms.test.js
app/controllers/webhooks/webhooks.controller.js
app/views/webhooks/edit.njk
server.js
test/cypress/integration/webhooks/webhooks.cy.test.js
test/cypress/stubs/webhooks-stubs.js

This is directly copied from the Worldpay credentials from utility.
The change was delayed to allow form utilities to be moved to a
re-usable, well tested form library. As this hasn't happened yet this
directly copies an existing from and repurposes it for webhooks.
Responsibility of the frontend:
- required data to act on resource exists
- required data meets simple rules for create/ update request
Responsibility of the backend:
- data meets business rule constraints (valid URLs)

PP-9016 Validate webhooks form

---

app/views/webhooks/_message_status.njk
app/views/webhooks/_webhook_status.njk
app/views/webhooks/detail.njk
app/views/webhooks/list.njk
app/views/webhooks/message.njk
test/cypress/integration/webhooks/webhooks.cy.test.js

Following the pattern set by agreements for recurring card payments.
Move webhook and webhook message status tags to macros that can be
shared between templates. Add entries for new statuses.
**Webhook status**
**Message status**

PP-9016 Refine webhooks status tags

---

app/controllers/stripe-setup/add-psp-account-details/get.controller.js
app/controllers/stripe-setup/add-psp-account-details/get.controller.test.js
app/views/dashboard/_stripe-account-setup-banner.njk
app/views/stripe-setup/check-org-details/index.njk
test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
test/integration/add-psp-details.ft.test.js

- Update the `Stripe setup > add-psp-account-details` controller
- Make the `check org details` page appear before the `gov entity doc upload process`
- Update the `check org details` to have content about what a gov entity doc is.`
- As we believe it's the doc upload which triggers the Stripe verification process - we want the user to confirm / update 
org details before that.
- Dashboard `Nunjuks file > Stripe setup banner`:
- show new content about the new step for `confirm org details`.
- Clean up CSS classes - change `govuk-body-m` to `govuk-body`.
- Update Cypress tests
- Increase test coverage of the Stripe setup banner.
- Update unit tests.

PP-9207 Stripe setup - add `check org details` to flow

---

app/controllers/webhooks/webhooks-forms.test.js
package-lock.json
package.json
test/cypress/integration/webhooks/webhooks.cy.test.js

Bump js commons to bring in the newly supported webhook subscriptions.
Remove fixture references to `card_payment_started` which isn't planned
to be included in the first round of events.

PP-9274 Update webhook subscriptions

---

app/controllers/agreements/agreements.controller.js
app/utils/get-query-string-for-params.js
app/utils/transaction-view.js
app/views/agreements/detail.njk
app/views/transactions/filter.njk
test/cypress/integration/agreements/agreements.cy.test.js
test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js
test/cypress/integration/transactions/transaction-search.cy.test.js

Show the 5 most recent transactions on the agreement details page.
Transactions can be filtered by their agreement identifier, if
they've been taken on behalf of a recurring card payment agreement.
This adds an additional filter to the "Advanced filter" element, this
has the benefit of not confusing users which this filter has no
relevance for however where and how this filter fits in the with the
larger transactions page should be considered in future design.

PP-9846 show transactions related to agreement

---

app/controllers/all-service-transactions/get.controller.js
app/controllers/transactions/transaction-list.controller.js
app/utils/permissions.js
app/views/transactions/filter.njk
test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js
test/cypress/integration/transactions/transaction-search.cy.test.js
test/unit/utils/permissions.test.js

For the time being the admin tool only shows the agreement tab to
services with the `recurring_enabled` flag set to true (as managed by
Toolbox). Reflect this with the transactions filter until a decision is
made on if this should be shown to all users.
Update test scenarios that cover the agreement id filter to include the 
appropriate property on the stubbed account.
Update the content to read "Search by agreement" followed by the hint to
"Enter agreement identifier".

PP-9846 Only show recurring filters to appropriate accounts

---

app/utils/display-converter.js
app/utils/nav-builder.js

This generic flag will give us control to turn the administration of
webhooks on for specific services in a given environment (where the
feature flag for the entire env is off).

BAU Add webhooks permissions to experimental feature flag

---

app/controllers/payment-links/get-start.controller.js
app/views/payment-links/_pre-filled-payment-moto-content.njk
app/views/payment-links/index.njk
test/cypress/integration/payment-links/create-payment-link.cy.test.js
test/unit/controller/payment-links/get-start.controller.test.js

Add a warning to the create payment link page imploring the user to not create a payment link if and only if the gateway account has current credentials for Worldpay using a merchant code that ends in ‘MOTO’ (which is how Worldpay identify MOTO merchant codes).
The existing warning on the create payment link page, which informs users about the existence of telephone payment links (agent-initiated MOTO payments) is changed to inset text so we do not end up with two warnings on single page.

PP-9882 Create payment link page: warn if Worldpay MOTO service

---

app/controllers/stripe-setup/check-org-details/get.controller.js
app/controllers/stripe-setup/check-org-details/get.controller.test.js

- Stripe onboarding - check organisation details page currently displays string 'null' for the part of organisation details (name or address lines) empty. Display an empty string instead

PP-9207 Check organisation details - display empty string instead of 'null'

---

app/assets/sass/application.scss
app/assets/sass/components/transaction-details.scss
app/assets/sass/components/transaction-list.scss

Make extremely long payment references with no spaces not overflow on both the transactions list page and the transaction details page.
This has been a problem since forever but it’s more pressing now that we allow payment link references (which may be entered by paying users without oversight from the partner service that’s going to see them in the admin tool) to be up to 255 characters in length (up from 50).
We use `table-layout: fixed` and `overflow-wrap: break-word` to force jumbo references to wrap. For compatibility with browsers that do not support `overflow-wrap` (mostly IE11), we also use the legacy `word-wrap` property.
On the transaction details page, this will also stop extremely long email addresses and cardholder names from causing mischief.

PP-6213 Make extremely long payment references not overflow

---

app/controllers/register-service.controller.js
app/services/clients/adminusers.client.js
app/services/service-registration.service.js
test/fixtures/invite.fixtures.js
test/integration/service-registration.service.it.test.js
test/unit/clients/adminusers-client/invite/complete-service-invite.pact.test.js

* Include an otp code in the request body when calling `${inviteResource}/${inviteCode}/complete` on adminusers.
* Except for when the invite is for an existing user - the otp code is not required in that case.
* adminusers will not yet actually use this code, but we are soon going to make changes that mean it will.
* This PR also includes some cleanup relating to https://github.com/alphagov/pay-selfservice/pull/2890 - the pact tests were still passing gatewayAccountIds in the request body, but that has not been necessary or useful for quite a while now.

PP-10041: Send OtpCode to 'complete' endpoint

---

app/controllers/register-service.controller.js
app/services/clients/adminusers.client.js
app/services/service-registration.service.js
test/fixtures/invite.fixtures.js
test/integration/service-registration.service.it.test.js
test/unit/clients/adminusers-client/invite/complete-service-invite.pact.test.js

Reverts alphagov/pay-selfservice#3506
We realised that unifying OTP validation and invite completion isn't a good idea (it makes it too difficult to define suitable test coverage).  So, #3506 is no longer helpful and should be reverted.  See https://payments-platform.atlassian.net/browse/PP-10041?focusedCommentId=48911

Revert "PP-10041: Send OtpCode to 'complete' endpoint"

---

app/controllers/stripe-setup/check-org-details/get.controller.js
app/controllers/stripe-setup/check-org-details/get.controller.test.js
app/controllers/stripe-setup/check-org-details/post.controller.js
app/controllers/stripe-setup/check-org-details/post.controller.test.js
app/paths.js

PP-9984 Switch PSP > Check org details - update controllers
Update the Check org details > Get controller:
- Add boolean - to let people know it is a switch psp url.
- Will use boolean to decide to show setting layout.
Update the Check org details > Post controller:
- On successful post, do the following:
- When switch PSP - redirect to Switch PSP index page
- When Stripe onboarding - redirect to the Stripe onboarding index
controller.
- Add unit tests

PP-9984 Switch PSP > Check org details - update controllers

---

app/controllers/invite-validation.controller.js
test/integration/invite-validation.controller.ft.test.js

We have added several new InviteType enum values in pay-adminusers.  Like the old ones (which are currently still in use), these get serialised into self-service requests as lower-cased strings.  Self-service needs to be ready to handle these strings as potential values for the `type` field of invites.
Please check the test coverage and let me know what you think.  I've made duplicates of the tests in `invite-validation.controller.ft.test.js`, but there are a few other test classes (`service-registration.service.it.test.js`, `self-reigstration-otp-verify.ft.test.js`, `complete-service-invite.pact.test.js` and `complete-user-invite.pact.test.js`) which reference the old enum values in a more incidental way (I think?), and it's not clear to me whether it's worth making duplicates of these …

PP-10041: Prepare for switching to new InviteType strings

---

app/views/team-members/team-member-profile.njk
test/cypress/integration/user/my-profile.cy.test.js

It will be possible for a User to not have a telephone number set if they have registered using an Authenticator App as their second factor method.
If a phone number isn't set, don't display the phone number row on the "My profile" screen. In future, we will amend the user journey to change the second factor method SMS to ask for a phone number if the user does not have one set.

PP-10048 Don't display phone number when not present

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/controllers/request-to-go-live/organisation-address/get.controller.test.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js
app/routes.js
app/views/request-to-go-live/organisation-address.njk

Get controller
- Update how we check to see if it the `Stripe onboarding` or `Switch PSP > Stripe`
- Display form when it is in the `switch PSP` user journey.
- Set the `isSwitchingCredentials` flag
- Update unit test.
Post controller
- Display form when it is `switch PSP` user journey.
- Set the right validation rules.
- Update unit test.
Routes.js
- Update routes - add Get & Post routes for:
- Switch PSP > confirm org details
- Switch PSP > update org details

PP-9984 Switch PSP > Update org - get controller updates & update routes

---

app/services/clients/adminusers.client.js
app/services/service-registration.service.js
test/integration/self-registration/self-registration-otp-verify.ft.test.js
test/unit/clients/adminusers-client/invite/verify-service-otp-code.pact.test.js

In `adminusers.client`, stop calling `/v1/api/invites/otp/validate/service` and instead call `/v2/api/invites/otp/validate`.

PP-10041: Switch to using new /otp/validate endpoint

---

app/controllers/login/otp-login.controller.js
app/controllers/login/send-again-post.controller.js
app/controllers/service-users.controller.js
app/controllers/user/two-factor-auth/get-configure.controller.js
app/controllers/user/two-factor-auth/get-index.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.js
app/controllers/user/two-factor-auth/post-index.controller.js
app/models/second-factor-method.js
app/views/login/otp-login.njk
app/views/team-members/team-member-profile.njk
app/views/two-factor-auth/configure.njk
app/views/two-factor-auth/index.njk
test/fixtures/user.fixtures.js
test/ui/team-member-details.ui.test.js
test/unit/controller/user/two-factor-auth/get-configure.controller.ft.test.js
test/unit/controller/user/two-factor-auth/get-index.controller.ft.test.js
test/unit/controller/user/two-factor-auth/post-index.controller.ft.test.js

Rather than hardcoding the strings "SMS" or "APP" for the second factor method in many places in the code, define constants that are used in all places.

PP-10047 Use constants for second factor method

---

app/controllers/forgotten-password.controller.js
app/controllers/login/logout.controller.js
app/controllers/login/otp-login.controller.js
app/controllers/login/send-again-post.controller.js
app/controllers/payment-links/get-start.controller.js
app/controllers/request-to-go-live/organisation-address/get.controller.js
app/controllers/request-to-go-live/organisation-address/get.controller.test.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/stripe-setup/check-org-details/post.controller.js
app/controllers/stripe-setup/check-org-details/post.controller.test.js
app/controllers/switch-psp/switch-tasks.service.js
app/controllers/user/two-factor-auth/post-index.controller.js
app/controllers/user/two-factor-auth/post-resend.controller.js
app/paths.js
app/services/user.service.js
test/cypress/integration/payment-links/create-payment-link.cy.test.js
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/integration/stripe-setup/update-org-details.cy.test.js
test/cypress/integration/user/my-profile.cy.test.js
test/cypress/stubs/stripe-account-setup-stub.js
test/integration/add-psp-details.ft.test.js
test/unit/controller/payment-links/get-start.controller.test.js

Refactor methods in user.service to accept a user external ID rather than an entire user object. This will make testing controllers that call this service easier.
There are 2 commits in this PR, the second is to run the linter on the whole of selfservice.

PP-10047 Refactor user service

---

app/controllers/register-service.controller.js
app/services/clients/adminusers.client.js
app/services/clients/base-client/wrapper.js
app/services/clients/connector.client.js
test/unit/clients/adminusers-client/authenticate/authenticate.pact.test.js
test/unit/clients/adminusers-client/forgotten-password/create-forgotten-password.pact.test.js
test/unit/clients/adminusers-client/invite/generate-invite-otp-code-user.pact.test.js
test/unit/clients/adminusers-client/invite/invite-user.pact.test.js
test/unit/clients/adminusers-client/invite/resend-otp-code.pact.test.js
test/unit/clients/adminusers-client/invite/submit-service-registration.pact.test.js
test/unit/clients/adminusers-client/invite/verify-otp-code.pact.test.js
test/unit/clients/adminusers-client/invite/verify-service-otp-code.pact.test.js
test/unit/clients/adminusers-client/service/add-gateway-accounts-to-services.pact.test.js
test/unit/clients/adminusers-client/user/authenticate.pact.test.js
test/unit/clients/connector-client/connector-client-create-gateway-account.pact.test.js

There is currently the concept of an "old" and a "new" error handler.
The "old" error handler puts the entire response body in the message
field of the "error" object returned by the client.
There was only one place in the code where fields in the response body
was accessed - when attempting to complete a registration. Here we were
using the backend error message to display on the error page. We
shouldn't do this, so instead just display a generic error page.
Remove the "old" error handler so that the clients return an error
with a uniform signature when a request returns a non-success response.
This error contains the error message string extracted from the HTTP
response body.

PP-10240 Remove the "old" client error handler

---

app/controllers/invite-validation.controller.js
test/integration/invite-validation.controller.ft.test.js

Reverts alphagov/pay-selfservice#3546
We have realised that it is not going to be viable to use the new InviteType enum values in pay-adminusers, so they have been removed; we no longer need to support them in selfservice.

Revert "PP-10041: Prepare for switching to new InviteType strings"

---

app/errors.js
app/middleware/error-handler.js
app/services/clients/base-client/wrapper.js
test/unit/clients/base-client/wrapper.test.js

Introduce a new type which extends Error for representing errors thrown by the REST client. This makes the API of these errors clearer and makes it possible to handle these in a specific way.
Handle uncaught RESTClientErrors in the error handler middleware in order to log more detail about the error.
Rewrite `wrapper.test.js` to be easier to understand.

PP-10240 Introduce RESTClientError type

---

app/controllers/user/two-factor-auth/get-phone-number.controller.js
app/controllers/user/two-factor-auth/index.js
app/controllers/user/two-factor-auth/post-index.controller.js
app/controllers/user/two-factor-auth/post-index.controller.test.js
app/controllers/user/two-factor-auth/post-phone-number.controller.js
app/controllers/user/two-factor-auth/post-phone-number.controller.test.js
app/paths.js
app/routes.js
app/utils/display-converter.js
app/views/two-factor-auth/phone-number.njk
test/cypress/integration/user/change-sign-in-method.cy.test.js
test/cypress/integration/user/edit-phone-number.cy.test.js
test/cypress/integration/user/my-profile.cy.test.js
test/cypress/stubs/user-stubs.js

When a user has registered their account using an authenticator app to get security codes, which is currently being implemented, they won't be asked for a phone number.
If they then go to change their sign-in method to "Text message" from their profile settings, add a page that asks for their phone number. This page is shown after selecting the new sign-in method, if "Text message" is selected and the user does not have a phone number set.
Upon submitting the new phone number, make a PATCH request to adminusers to update the phone number on the user, then make requests to provision a new provisional OTP key and to send a text message with a security code.

PP-10047 Add page to provide phone number

---

app/controllers/user/two-factor-auth/post-configure.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.test.js
app/controllers/user/two-factor-auth/post-index.controller.js
app/controllers/user/two-factor-auth/post-index.controller.test.js

Previously, if there were unexpected errors returned by adminusers in
the controllers for updating the second factor method, we redirected the
user back to the "My profile" page and showed an error notification box
at the top of the page.
This is not a pattern we use elsewhere anymore, instead we render an
error page. Make these controllers consistent with behaviour elsewhere
and render an error page.

PP-10047 Render error page for errors updating 2FA method

---

app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/stripe-setup/update-org-details.cy.test.js

Change ‘you’ to ‘your’ and ‘identity’ to ‘entity’.
Before:
After:

PP-10269 Fix typos in Stripe onboarding update org details header

---

app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js

- Update `post controller`
- Pass `isSwitchingCredentials` flag correctly when getting the Stripe account id.
- Add unit tests to check this.
- General clean up of the unit test.

PP-9984 Switch PSP > Update org details - bug creating Sentry error

---

app/controllers/credentials/worldpay.controller.js
app/controllers/your-psp/get.controller.js
app/views/your-psp/index.njk
test/cypress/integration/settings/your-psp.cy.test.js

- Added validation to allow merchant IDs ending with MOTO only for moto enabled accounts, and allow non-MOTO IDs for non-moto accounts

PP-10198 Validate merchant account code for MOTO and non-MOTO accounts

---

app/browsered/analytics.js
test/unit/browsered/analytics.test.js

The current method for stripping PII from the domain passed through to Google Analytics was to strip the email query string, if it existed.
These pages have been excluded from Google Analytics as users sometime mistakenly enter PII (email addresses) into other freely editable search fields like `reference`.
In addition, partial email addresses were allowed thorugh as the regex has a specific name @ domain . suffix group.
In order to allow these pages to go back through Google Analytics:
- Instead of removing values, replace them redacted text, this will give an idea of the frequency these fields are used
- Redact any fields that the user can freely input text for as users may put PII in these in error
- Don't just replace the email field, include other fields that could contain PII

PP-10037 GA redact any freely editable transaction search predicate

---

app/browsered/analytics.js
test/unit/browsered/analytics.test.js

We were previously setting the 'path' attribute on Google Analytics, this is submitted with a `dp=` attribute and had appropriately redacted values, however the full location is also sent through `dl=` which didn't included the full url.
These fields are documented
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location.
The "Document Path" which we were previously setting seems to be set up for "specify virtual page paths.", as we have no dynamic or client side managed navigation, "Document Location" feels like the appropriate place to redact and send this information.
Set the 'location' attribute instead to ensure everything that is sent to GA is appropriately redacted.
Any pages which may be impacted have been filtered out of GA until this …

PP-10037 Fix google analytics set path

---

app/controllers/stripe-setup/check-org-details/post.controller.js
app/controllers/stripe-setup/check-org-details/post.controller.test.js

- Post controller
- Correctly pass the `isSwitchingCredentials` flag when getting the Stripe account ID.
- Add a check in the unit test to check for this.

PP-9984 - Switch PSP Stripe > Check org details - click 'yes' bug

---

app/browsered/analytics.js
test/unit/browsered/analytics.test.js

Set the redacted 'location' property for all analytics ids.
Fix setting the `anonymizeIp` property on the linker plugin rather than than the tracking profile.

PP-10037 Run all analytics ids through PII method

---

app/services/clients/adminusers.client.js
test/fixtures/invite.fixtures.js

* Send `second_factor` parameter in body of requests the `/v1/api/invites/${inviteCode}/complete` adminusers endpoint
* Currently this will always be set to 'SMS'; this will be changed later.

PP-10038: Include 2FA method in invite complete requests

---

app/controllers/register-user.controller.js
test/unit/controller/register-user.controller.test.js

We have some validation to check that when a user clicks a link to invite an existing user from the invite email, that the invite is for them before accepting it. Without this, it was possible for a logged in user to accept an invite on behalf of a different user if they knew what the invite code was.
This validation was doing a case sensitive check that the email on the invite was the same as the user's email. However, emails should be case insensitive, and this was causing invites not to work for users when the email entered for the invite had a different case to the email on their account.
Make this check case insensitive.

BAU Fix validation that invited user is logged in user

---

app/controllers/my-services/get-index.controller.js
app/views/services/index.njk
test/cypress/integration/my-services/my-services.cy.test.js
test/cypress/stubs/user-stubs.js

A user can be a member of no services if they have been removed from all services they were a member of. Currently the controller for showing the "My services" page throws an error if the user is a member of no services and an error page is rendered.
Fix this so that the controller does not throw an error, and the page is rendered. The rendered page does not include the "Reports" section and has an additional paragraph instructing the user on what to do next.
Add some additional Cypress tests to check we're displaying the "My services" page correctly in different scenarios.
Hiding whitespace changes in the diff should make it easier to see what's changed in the template.

PP-10244 Render "My services" page for no services

---

.secrets.baseline
app/controllers/register-service.controller.js
app/routes.js
app/services/service-registration.service.js
test/fixtures/invite.fixtures.js
test/integration/service-registration.service.it.test.js
test/unit/controller/register-service-controller/register-service.controller.test.js

We are going to remove creating a service as part of a self-signup registration.
The service is currently created by adminusers when a request is made to the `/v1/api/invites/{code}/complete` endpoint, which also creates the user account. Selfservice then redirects the user to a page to name the created service.
We are going to stop creating a test service in adminusers when `/v1/api/invites/{code}/complete` is called. When we are no longer creating a service, the response from this endpoint will no longer include a `service_external_id` field.
Prepare for a service no longer being created by handling the case where `/v1/api/invites/{code}/complete` does not include a `service_external_id`. In this case, do not attempt to create a gateway account in connector. And instead of redirecting …

PP-10244 Handle service not created during registration

---

app/controllers/webhooks/webhooks-forms.test.js
test/cypress/integration/webhooks/webhooks.cy.test.js
test/fixtures/webhooks.fixtures.js
test/unit/clients/webhooks-client/webhooks.pact.test.js

Any callback URL fixtures built for tests should use test-y domain TLDs.

BAU Use `.test` domain for webhook fixtures

---

.secrets.baseline
test/fixtures/invite.fixtures.js
test/integration/service-users.ft.test.js
test/unit/clients/adminusers-client/invite/get-invite.pact.test.js

Amend get-invite.pact.test.js which previously wouldn't be verified against adminusers as it had consumer `selfservice-to-be` so that it will successfully run against adminusers.
Remove pact tests that check error responses, as we handle these in a standard way.
Fix the invite fixture so that it will not insert properties that are not defined in the fixture  - using `lodash.defaults` was using any fields passed in in the `opts` object even if they were not defined in the fixture. Remove the fields from the fixture that selfservice does not consume.

PP-10055 Add pact test for GET invite

---

app/controllers/registration/registration.controller.js
app/paths.js
app/routes.js
app/views/registration/authenticator-app.njk
app/views/registration/get-security-codes.njk
app/views/registration/password.njk
app/views/registration/phone-number.njk
app/views/registration/resend-code.njk
app/views/registration/sms-code.njk
app/views/registration/success.njk
test/unit/routes.test.js

Add the GET routes and the basic templates for the new registration journey that includes the ability to select an authenticator app to get 2FA codes.
Currently when the routes are visited, the templates are just rendered with dummy data and no other logic is performed.

PP-10055 Add routes and templates for new registration journey

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js

When a GET request is made to /register/password:
- If the register_invite cookie is not present, show an error page
- Get the invite from adminusers. If the invite has `password_set` set to true, redirect the user to the next page in the journey
- Otherwise, render the page to enter a password.

PP-10055 Add validation to show password page

---

.secrets.baseline
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/routes.js
app/views/registration/password.njk

Add a POST `/register/password` route that is POSTed to when the password page is submitted. This does validation of the "Enter a password" and "Re-type your password" fields.
If the password is valid, a PATCH request is made to adminusers to update the password and we redirect to the next page in the journey.

PP-10055 Add route to submit password page

---

app/controllers/register-service.controller.js
app/controllers/register-user.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.test.js
app/utils/validation/field-validation-checks.js

To ensure that we are using the same error message in all places that validate OTP codes, move the validation messages we display when adminusers returns a 401 response when verifying the code to shared constants.
Also, display an improved error message if the OTP method is to use an authenticator app. This message is taken from the GOV.UK Sign-in login/registration pages.

PP-10052 Use constants for invalid OTP error messages

---

app/controllers/register-service.controller.js
app/controllers/register-user.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.js
app/controllers/user/two-factor-auth/post-configure.controller.test.js
app/services/auth.service.js
app/utils/security-code-utils.js
app/utils/security-code-utils.test.js
test/unit/controller/register-service-controller/register-service.controller.test.js
test/unit/controller/register-user.controller.test.js
test/unit/services/auth.service.test.js

In the design system page for the pattern to enter OTP codes, it says to
"Let the user enter the code in whatever format is familiar to them. Allow additional spaces, hyphens and dashes."
The reasoning for this is that speech-to-text programs may cause spaces to be entered in the code, or authenticator apps might provide the code in a different format using spaces or dashes.
For all places where we ask the user to enter an OTP code, remove spaces and dashes before validating and submitting the code.

PP-10052 Strip spaces and dashes from OTP codes

---

.secrets.baseline
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/views/registration/authenticator-app.njk
test/cypress/integration/registration/register.cy.test.js
test/fixtures/invite.fixtures.js

A route already existed for GET `/register/authenticator-app` which just displayed dummy data. Update the controller for this to retrieve the invite from adminusers and then render the page, displaying the OTP secret key from the invite and the QR code generated from this.

PP-10052 Add logic for route to display authenticator app page

---

app/controllers/your-psp/post-flex.controller.js
app/controllers/your-psp/post-flex.controller.test.js

- Update post-flex controller
- Auto toggle the 3DS setting when a LIVE Account
- Add unit test.

PP-10274 Worldpay 3DS Flex - auto toggle 3DS setting when LIVE account

---

app/controllers/request-to-go-live/agreement/post.controller.js

- Currently, zendesk emails for go-live requests include the last stage service is in (which is usually CHOOSEN_PSP..) rather than the new stage (TERMS_AGREED_..) that will be set when the terms are agreed.
- Updated so that the email will include TERMS_AGREED.. stage which will match with Toolbox.

PP-10199 Set latest go live stage in the Zendesk email

---

app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/views/your-psp/_worldpay-flex.njk
test/cypress/integration/settings/your-psp.cy.test.js

- Toggle 3DS post controller
- Throw error if trying to toggle 3DS flex toggle for live account.
- Live accounts have 3DS flex automatically enabled when they enter their flex credentials.
- Update `your psp > worldpay > 3DS flex` Nunjuks file
- Hide the following then it is a live account
- Info inset text.
- Text in the description about enabling the 3DS flex settings.
- Toggle 3DS flex button

Pp 10274 - worldpay flex show toggle for test account

---

app/views/registration/authenticator-app.njk
app/views/registration/get-security-codes.njk
app/views/two-factor-auth/_authenticator-app-details.njk
app/views/two-factor-auth/_authenticator-app-instructions.njk
app/views/two-factor-auth/configure.njk
app/views/two-factor-auth/index.njk
test/cypress/integration/user/change-sign-in-method.cy.test.js

- Update the details hint text that explains what an authenticator app is on all pages it's displayed
- Update the page accessed from "My profile" to change sign-in method to use the same content as the new page in the registration journey.
- Use Nunjucks sub-templates to share content used in multiple templates

PP-10052 Update authenticator app content

---

.secrets.baseline
app/controllers/invite-validation.controller.js
app/controllers/login/setup-direct-login-after-register.controller.js
app/controllers/register-service.controller.js
app/controllers/register-user.controller.js
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/middleware/invite-cookie-is-present.js
app/middleware/invite-cookie-is-present.test.js
app/routes.js
app/services/auth.service.js
app/utils/constants.js

To avoid checking in every controller for the registration pages whether the session cookie for registration is present, add middleware to check it is present, else call next with an error so that an appropriate error page is displayed to the user.
Add a constant for the session cookie name to avoid hardcoding it in lots of places.

PP-10057 Add middleware to check registration cookie is present

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
test/cypress/integration/registration/register.cy.test.js

This controller and template for this page already existed, but it was rendered with dummy data.
Render the page, displaying a redacted phone number that the OTP code was sent to

PP-10057 Add logic to controller to show check your phone page

---

.secrets.baseline
app/controllers/register-user.controller.js
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/services/clients/adminusers.client.js
app/services/service-registration.service.js
test/fixtures/invite.fixtures.js
test/pact/adminusers-client/invite/complete-invite.pact.test.js

After successfully verifying the OTP code on the page to configure an authenticator app, we make a request to
/v1/api/invites/${inviteCode}/complete on adminusers to complete the invite and create the user. Make it so that we send "second_factor": "APP" in the request body so that the user is created with "APP" set as their second factor method for logging in.
Add an additional Pact test to ensure that it's possible to provide no request body when completing an invite for an existing user. As in this case, we wouldn't need to set a second factor method.

PP-10052 Send second factor method when completing invite

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/routes.js
app/services/clients/adminusers.client.js
app/views/registration/sms-code.njk
test/cypress/integration/registration/register.cy.test.js

When the page is submitted:
- Validate that the OTP code has a valid format
- Call adminusers to verify the OTP code
- Call adminusers to complete the invite, with a body containing `"second_factor": "SMS"`
If there are validation errors, or the code fails verification, redirect to the GET route with errors in the session that are displayed on the page.

PP-10057 Add route to submit the SMS security code page

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/views/registration/resend-code.njk

The GET route and template for the page to resend the security code already exists. Make it so that the page will pre-fill the phone number field with the phone number the user has already entered for the invite.
Will check the phone number is pre-filled in the Cypress test for registration when the POST route is added.

PP-10056 Display existing phone number on resend page

---

app/controllers/register-user.controller.js
app/controllers/register-user.controller.test.js
app/services/user-registration.service.js

Now that second factor method will only be included in the invite complete request if it is passed into the client method, all consuming code should set the value.
Propagate the value through the client method but also set a default to SMS which is currently used for all invites.

PP-10052: Fix: pass second factor method through for invite client

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/routes.js
app/views/registration/resend-code.njk
test/cypress/integration/registration/register.cy.test.js

Add a POST route for resending the OTP code. The page asks for the user to confirm their phone number before resending the code. When the submit button is clicked:
- Validate the phone number
- Make a PATCH request to adminusers to update the phone number on the invite
- Make a POST request to adminusers to send an OTP code to the entered phone number
- Redirect to the page for the user to enter their security code.

PP-10056 Add POST route for resend code page

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
test/cypress/integration/registration/register.cy.test.js
test/cypress/stubs/invite-stubs.js

* Call the POST `/v1/api/invites/{code}/reprovision-otp` when the `/register/phone-number` page is submitted, before calling the endpoint to send the SMS with the OTP code.
* Call the POST `/v1/api/invites/{code}/reprovision-otp` when the GET `/register/authenticator-app` route is called, before rendering the page. Use the new otp_key in the invite the endpoint returns to display the code when rendering the page.

PP-10367: Re-provision OTP key

---

app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/routes.js
test/cypress/integration/registration/register.cy.test.js

After submitting a valid OTP code on either the page to configure SMS as the second factor method or Authenticator app as the second factor method, redirect to the success page. This page informs the user that registration was successful and has a button to continue to the "My services" page.
When the `/register/success` route is visited, call the middleware that will log the user in using the `userExternalId` from the `register_invite` cookie. Previously this was done as part of the redirect to `/proceed-to-login` which logged the user in then called the controller to render the "My services" page.

PP-10395 Show success page when registration is complete

---

.secrets.baseline
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js
app/paths.js
app/routes.js
app/services/clients/adminusers.client.js
app/utils/validation/field-validation-checks.js
test/cypress/integration/registration/complete-registration.cy.test.js
test/cypress/integration/registration/start-self-signup-registration.cy.test.js
test/cypress/stubs/invite-stubs.js

* Validate email address
* Handle 403 or 409 from call to `/v1/api/invites/service` on adminusers
* On success or 409 from adminusers, set `email` on session cookie and redirect to 'check email' page

PP-10402: POST route for enter email page

---

app/controllers/registration/registration.controller.js
app/routes.js
app/routes.test.js
app/views/includes/phase-banner.njk
app/views/macro/breadcrumbs.njk
app/views/registration/success.njk
test/cypress/integration/registration/complete-registration.cy.test.js

When the user is shown the registration success page, at this point they have been logged in. Make it so that the navigation bar reflects this by displaying the links for a logged in user.
Ensure that the  phase banner containing the service navigation and breadcrumbs is not shown for this page.

PP-10395 Show logged in nav on success page

---

app/middleware/invite-cookie-is-present.js

For the new registration journey, add an invite_code field to the log context that is added in the middleware that checks the registration cookie is present. This will cause the invite_code to be logged for all lines logged for requests made to the registration routes.

BAU Log invite code where it is present

---

app/controllers/your-psp/get-flex.controller.js
app/controllers/your-psp/get-flex.controller.test.js
app/controllers/your-psp/post-flex.controller.js
app/controllers/your-psp/post-flex.controller.test.js
app/paths.js
app/routes.js
app/views/your-psp/flex.njk

- Add new path and routes for `switch psp > flex` journney.
- Update Flex credentials GET controller
- Pass a flag to the Nunjuks file - which states if the user is on the `switch psp` journey.
- Update Flex credentials POST controller
- When on the `switch psp` route, after a successful POST, redirect to the `switch psp` index page
- Update Nunjuks file
- Add back link when on the `switch psp` route

PP-10313 - Switch PSP > Flex - update the Flex controller and page

---

test/cypress/integration/invite/complete-invite-for-existing-user.cy.test.js
test/cypress/integration/registration/complete-registration.cy.test.js
test/cypress/stubs/invite-stubs.js

Cypress test checks that an invite for an existing user is successfully completed and a success banner is displayed on the My services page.

PP-10063 Add Cypress test for completing existing user invite

---

app/controllers/subscribe-service.controller.js
app/controllers/subscribe-service.controller.test.js
app/routes.js

* Use middleware instead of checking session cookie in controller
* Change handling of 410 responses (pass an error to `next` instead of directly rendering an error page from the controller)

PP-10063: Refactor subscribe-service.controller

---

.secrets.baseline
app/controllers/switch-psp/switch-psp.controller.test.js
app/controllers/switch-psp/switch-tasks.service.js
app/controllers/switch-psp/switch-tasks.service.test.js
app/views/switch-psp/switch-psp.njk
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/stubs/gateway-account-stubs.js

- `Switch PSP` page - add new task when switching to Worldpay
- Users must provide 3dS flex credentials.
- This task links to the existing `3DS flex page`.
- Add Cypress tests to check this functionality.
- Make sure it displays the tasks in the right state.
- Should only enable the `verify with live payment` when all
the right tasks have been completed.
- Test it correctly goes to the 3DS flex page from the task.
- Update the `Cypress > gateway account stubs > post 3DS flex settings stub`
- Clean up code.
- Make it more flexible by passing down the options parameter to calling functions.
- Update the `your psp` Cypress test - to work with the latest updates to this method.

Pp 10313 switch psp flex tasklist

---

app/utils/validation/server-side-form-validations.js
app/utils/validation/server-side-form-validations.test.js
package-lock.json
package.json

Our current method of URL validation has allowed a number of invalid URLs to pass. This results in the URL being passed to downstream services which can reject it in an unpredictable way where the error isn't well handled.
The two outliers:
- spaces in the URL allowing multiple URLs to be enterered (neither expected nor wanted)
- incomplete URLs without a TLD specified
The `validatorjs/validator` library includes some fairly gnarly and well tested regex to ensure that TLD can be required and are well formed. This library is also actively maintained, quite popular and has no dependencies.
Include the validator library and use this to catch the exceptional cases provided above.

PP-10099 Extend URL validation used for organisation website address

---

app/controllers/request-to-go-live/organisation-address/post.controller.js

We've had report(s) of users confused when entering website addresses as part of the organisation detail requirements.
Now that we've updated the validation to try and catch more edge cases in https://github.com/alphagov/pay-selfservice/pull/3704, add some structured logging to measure how often we are blocking urls as well as what some common mistakes or misunderstandings might be.

PP-10099 Add logging tracking to org url validation

---

app/controllers/invite-validation.controller.js
app/controllers/invite-validation.controller.test.js
app/controllers/your-psp/get.controller.js
app/controllers/your-psp/get.controller.test.js
test/cypress/integration/invite/complete-invite-for-existing-user.cy.test.js
test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js
test/fixtures/invite.fixtures.js
test/pact/adminusers-client/invite/get-invite.pact.test.js

The `type` field in invites returned from adminusers is going to be removed; use the `invite_to_join_service`
flag instead.
N.b. The field is `isInviteToJoinService` in adminusers, but is getting serialised without the 'is' because it's a boolean.  I think this looks a bit confusing at the selfservice end - would it be worth me changing it in adminusers?  I presume I would be able to override the renaming there.

PP-10338: Remove references to invite type

---

.secrets.baseline
app/controllers/registration/registration.controller.js
app/controllers/registration/registration.controller.test.js

We want to avoid the situation where the OTP key is re-provisioned when the page to configure an authenticator APP is reloaded - particularly if it is reloaded due to the security code entered being invalid. If the OTP key is re-provisioned, the user would have to set up a new account in their app with the new OTP, which they are likely to miss - meaning their invite will be disabled.
Store the last selected second factor method in the registration cookie, and only re-provision the OTP key if the method currently being configured does not match the method last time we re-provisioned the OTP key. This means we will only re-provision if the user goes back and selects a different method.

PP-10465 Only reprovision OTP key if method has changed

---

app/assets/sass/application.scss
app/assets/sass/components/sub-navigation.scss
app/views/privacy/privacy.njk
test/cypress/integration/privacy/privacy.cy.test.js

- Add the sub navigation to the privacy page
- Copy the sub navigation SCSS from the product page into Self service.
- Create a new style to make the sub navigation sticky as you scroll down.
- This matches up to the functionality on the product pages.
- Add ID's to each H2 so that it can be linked from the sub navigation.
- Update Cypress tests.

PP-10242 Privacy page - sub navigation

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js

- Updated bank details's post controller so when  ENABLE_STRIPE_ONBOARDING_TASK_LIST is set to true it redirects to task-list page
- Added unit test to check this

PP-10355 redirect user when bank details complete

---

app/controllers/privacy/privacy.controller.js
app/controllers/privacy/privacy.controller.test.js
test/cypress/integration/privacy/privacy.cy.test.js

- Update Privacy page show that it appears correctly whether a user is logged in or out
- Header - show the sign in / sign out link correctly.
- Only display the phase banner if the user is signed in.
- Update Cypress tests.

PP-10242 Privacy page - logged in status

---

app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.controller.test.js

Trim spaces from the value entered into the reference field on the agreements search filter before performing the search.

PP-10486 Trim reference for agreements filters

---

.secrets.baseline
test/cypress/integration/registration/complete-registration.cy.test.js
test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.test.js
test/cypress/integration/request-to-go-live/agreement.cy.test.js
test/cypress/integration/settings/default-billing-address-country.cy.test.js
test/cypress/stubs/go-live-request-stubs.js
test/cypress/stubs/invite-stubs.js
test/cypress/stubs/service-stubs.js
test/fixtures/gateway-account.fixtures.js
test/pact/connector-client/connector-patch-email-collection-mode.pact.test.js
test/pact/connector-client/connector-patch-email-confirmation-toggle.pact.test.js
test/pact/connector-client/connector-patch-email-refund-toggle.pact.test.js

We are intending to change the default response when Mountebank does not match on a stub for a request from returning a 200 to returning a 404.
In order to do this, we need to setup some missing stubs for Cypress tests where we currently rely on the default behaviour of getting a 200 when there is no stub, as these tests would fail when the default is 404.
This PR adds missing stubs to several more Cypress tests and fixes some stubs which existed but weren't being successfully matched on.

PP-10397 Add missing stubs to more Cypress tests

---

.secrets.baseline
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/integration/settings/payment-types.cy.test.js
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/integration/stripe-setup/director.cy.test.js
test/cypress/integration/stripe-setup/update-org-details.cy.test.js
test/cypress/integration/stripe-setup/vat-number.cy.test.js
test/cypress/integration/transactions/transaction-details.cy.test.js
test/cypress/integration/webhooks/webhooks.cy.test.js
test/cypress/stubs/connector-charge-stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/stubs/stripe-account-setup-stub.js
test/cypress/stubs/transaction-stubs.js
test/cypress/stubs/webhooks-stubs.js
test/fixtures/gateway-account.fixtures.js
test/fixtures/worldpay-3ds-flex-credentials.fixtures.js

We are intending to change the default response when Mountebank does not match on a stub for a request from returning a 200 to returning a 404.
In order to do this, we need to setup some missing stubs for Cypress tests where we currently rely on the default behaviour of getting a 200 when there is no stub, as these tests would fail when the default is 404.
This PR adds missing stubs to several more Cypress tests and fixes some stubs which existed but weren't being successfully matched on.

PP-10397 Add missing stubs to more Cypress test

---

.secrets.baseline
test/cypress/integration/settings/allow-apple-pay.cy.test.js
test/cypress/integration/settings/allow-google-pay.cy.test.js
test/cypress/integration/settings/switch-psp.cy.test.js
test/cypress/plugins/index.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/gateway-account.fixtures.js
test/fixtures/worldpay-3ds-flex-credentials.fixtures.js

Return a 404 when no stub matches a predicate, rather than a 200.
This means that all requests to external services will need to be stubbed when previously we didn't have to when we just expected a success response and didn't rely on the response having a non-empty body.
Add missing stubs to the final tests where we were previously relying on the 200 default response from Mountebank where stubs weren't set up.

PP-10397 Change mountebank imposter default response

---

app/controllers/switch-psp/switch-tasks.service.js
app/controllers/switch-psp/switch-tasks.service.test.js

Update switch tasks service:
- When switching a MOTO gateway account to Worldpay, do not require the `link flex credentials`

PP-10313 Switch PSP for Moto accounts - update Switch tasks service

---

app/controllers/switch-psp/switch-tasks.service.test.js
app/views/switch-psp/switch-psp.njk
test/cypress/integration/settings/switch-psp.cy.test.js

- MOTO accounts do not not need 3DS.
- Update the `switch PSP` journey
- When switching a MOTO account to Worldpay, do not show the `add 3DS flex settings` step.

PP-10313 Switch PSP > Worldpay MOTO account - do not show the 3DS flex step.

---

test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js

- Updated Cypress test to check page is redirected to task-list page valid company number is submitted
- Refactored the Bank and VAT cypress test so each test is not relying on the previous

PP-10356 redirect user when company reg complete cypress test

---

app/controllers/stripe-setup/director/post.controller.js
app/controllers/stripe-setup/director/post.controller.test.js

- Updated post controller so that when ENABLE_STRIPE_ONBOARDING_TASK_LIST flag is on and service director task is  completed correctly it redirects to the task list page
- Updated unit tests accordingly

PP-10353 return user when service director task complete

---

app/controllers/stripe-setup/government-entity-document/post.controller.js
app/controllers/stripe-setup/government-entity-document/post.controller.test.js

- Updated government entity document's post controller so when ENABLE_STRIPE_ONBOARDING_TASK_LIST is set to true it redirects to task-list page
- Added unit test accordingly

PP-10351 return user when government entity document is submitted

---

app/views/request-to-go-live/organisation-address.njk

- When a service goes live using Stripe, we send the service’s organisation address to Stripe. It turns out this has to be a physical address and cannot be a PO box.

PP-8020 make clear to the service not to use a po box address

---

app/views/request-to-go-live/organisation-address.njk

Correct spelling to PO Box, as per Style Guide (Do not use full stops in abbreviations: BBC, not B.B.C.)

PP-8020 correct spelling of p.o. box

---

app/routes.js
app/utils/gateway-account-urls.js
app/utils/gateway-account-urls.js.test.js

Since we no longer use gateway account cookie we don't reformat legacy urls. Instead we redirect the user to the `My services` page.
- removing reformatting, leaving redirect only.

PP-10413 remove legacy url reformatting

---

app/controllers/stripe-setup/government-entity-document/post.controller.js
cypress.config.js
test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js

PP-10351 Check Government entity task page is correctly displayed after completing all other tasks
- Context: Originally we were meant to test that the user  is redirected to the task-list page after uploading correct document. However, this has become difficult as we need to stub out the stripe api to upload a file. This requires a lot of work and is currently complex to do. We do have a unit test that does redirect when correct document is passed. There will be a ticket created in the epic for later to test this part in the integration test.
- Update cypress test for Government entity task to be displayed correctly when all other tasks are completed.

Pp 10351 return user when government entity document complete cypress test

---

.github/workflows/run-tests.yml

Fixes the caching steps for the Cypress tests.
Thanks @stephencdaly for spotting this.

PP-10697: Use GITHUB_OUTPUT to store env var rather than GITHUB_STATE

---

test/cypress/integration/stripe-setup/bank-details.cy.js
test/cypress/integration/stripe-setup/check-org-details.cy.js
test/cypress/integration/stripe-setup/company-number.cy.js
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js

- Updated Cypress test for all seven tasks to test for a bank-link that redirects to task-list when ENABLE_STRIPE_ONBOARDING_TASK_LIST is true

 PP-10342 add back link for all tasks to redirect to task list page cypress test

---

app/utils/credentials.js
app/utils/credentials.test.js
app/utils/nav-builder.js
app/utils/nav-builder.test.js
test/cypress/integration/settings/your-psp-stripe-kyc.cy.js

- For Stripe settings page:
- When Stripe task-list flag is enabled, show 'Information for Stripe' in the side navigation.
- Otherwise leave it 'Your PSP - Stripe'
- Update the existing `Stripe KYC tests` - to check for the new name side navigation name - `Information for Stripe`.

 PP-10331 add side navigation for stripe task list

---

app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.controller.test.js
app/controllers/agreements/agreements.service.js
app/controllers/agreements/agreements.service.test.js
app/services/clients/ledger.client.js
test/cypress/integration/agreements/agreements.cy.js
test/cypress/stubs/agreement-stubs.js

The original intention when agreements were added was to move away from identifying resources by the gateway account ID, but instead by the service ID and whether they are live/test.
However, a migration plan hasn't currently been made to move to a world where there is only one live/test gateway account per service. So for now, we want to send the account ID when searching for agreements so we can be sure we're only getting agreements for the current account.
This should be revisited when we can be sure there will only be one live/test account per service.

PP-10805 Send account id when getting agreements

---

app/views/stripe-setup/bank-details/index.njk
app/views/stripe-setup/check-org-details/index.njk
app/views/stripe-setup/company-number/index.njk
app/views/stripe-setup/director/index.njk
app/views/stripe-setup/government-entity-document/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/stripe-setup/vat-number/index.njk
test/cypress/integration/stripe-setup/bank-details.cy.js
test/cypress/integration/stripe-setup/check-org-details.cy.js
test/cypress/integration/stripe-setup/company-number.cy.js
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js

- Context: For stripe onboarding tasks: when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled:
- Updated logic to display side navigation when on each task
- Updated existing cypress tests to check for the navigation bar
- Further context
- There will be a separate PR covering update organisation details.

PP-10348 display side navigation in each task

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/controllers/request-to-go-live/organisation-address/get.controller.test.js
app/utils/nav-builder.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/stripe-setup/bank-details.cy.js
test/cypress/integration/stripe-setup/check-org-details.cy.js
test/cypress/integration/stripe-setup/company-number.cy.js
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js
test/cypress/integration/stripe-setup/update-org-details.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js

- For Stripe onboarding task:  Update-org-details, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled:
- display back link that redirects to check your organisation’s details page
- updated cypress test to check this

PP-10348 display back link for update organisation details page

---

app/views/your-psp/_stripe.njk
test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js

- For Stripe onboarding task list, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled:
- Added H2 title: 'Add your organisation’s details' for the task list
- The H2 is added using the design systems task list heading styling

 PP-10812 Add Your Organisation's details heading

---

test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js

- For stripe onboarding tasks, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled:
- grouped some of the cypress tests for the task-list page to follow cypress documentation recommendation

PP-10346 grouping cypress tests for task list page

---

.secrets.baseline
app/views/dashboard/_stripe-account-setup-banner_tasklist.njk
app/views/dashboard/index.njk
test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.js
test/cypress/stubs/stripe-psp-stubs.js
test/fixtures/stripe-psp.fixtures.js

- For stripe onboarding tasks, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled, display Stripe notification banner:
- Added new nunjucks page for the new Stripe banners
- Added Cypress tests to check banner is shown depending on Stripe account credentials and a tasks complete

PP-10358 Show new Stripe dashboard banner when tasks incomplete

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js
app/controllers/stripe-setup/check-org-details/post.controller.js
app/controllers/stripe-setup/check-org-details/post.controller.test.js

- Updated post controllers for bank-details and check-org-details to check for ENABLE_STRIPE_ONBOARDING_TASK_LIST and pass variable to the error page
- added the necessary unit tests

Pp 10840 fixing side nav disappearing when error on task page

---

app/controllers/stripe-setup/vat-number/post.controller.js
app/controllers/stripe-setup/vat-number/post.controller.test.js

- fixed this bug for the VAT task

PP-10840 fix side nav disappearing when error for VAT

---

app/controllers/stripe-setup/government-entity-document/post.controller.js
app/controllers/stripe-setup/government-entity-document/post.controller.test.js

- fixed this bug for the government entity document task

PP-10840 fix side nav disappearing when error for government entity doc

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js

- fixed this bug for the responsible person task

PP-10840 fix side nav disappearing when error for government responsible person

---

test/cypress/integration/stripe-setup/bank-details.cy.js
test/cypress/integration/stripe-setup/check-org-details.cy.js
test/cypress/integration/stripe-setup/company-number.cy.js
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js
test/cypress/integration/stripe-setup/update-org-details.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js

- Updated cypress to check nav bar and back links is shown on the error pages for all Stripe onboarding tasks

PP-10840 fix side nav disappearing when error for tasks cypress test

---

app/views/dashboard/_stripe-account-setup-banner_tasklist.njk
test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.js

- Before a service could take £2000 of payments before their account was restricted if they hadn’t filled in all the Stripe information.
- Now the account gets restricted striaght away.
- This means that currently the service would always see the 'Stripe has restricted your account. You need to submit additional information to Stripe to take payments.' if they haven’t completed the tasks.
- They will never see 'You need to submit additional information to Stripe to be able to take payments.'
- Therefore removing the restricted scenario when setting up a new Stripe account so that they see the standard Stripe task list banner.
- Also removing the new Stripe account > deadline scenario as in reality this will not occur anymore when the service hasn’t completed the task list.
- However, we …

 PP-10358 updating stripe banners

---

test/cypress/integration/agreements/agreements.cy.js

PP-10862 Combine agreements Cypress tests

---

.secrets.baseline
test/cypress/integration/all-service-transactions/all-service-transactions.cy.js

Remove tests for checking dispute filters. We already have a Cypress test checking these for the standard list transactions page, and the functionality being tested is shared.
Hiding whitespace changes should help with reviewing

PP-10862 Combine all services transactions Cypress tests

---

test/cypress/integration/dashboard/dashboard-statistics.cy.js

PP-10862 Combine dashboard statistics Cypress tests

---

test/cypress/integration/demo-payment/demo-payment.cy.js

PP-10862 Combine demo payment Cypress tests

---

test/cypress/integration/feedback/feedback.cy.js

PP-10862 Combine feedback Cypress tests

---

test/cypress/integration/manage-team-members/edit-permissions.cy.js

PP-10862 Combine edit permissions Cypress tests

---

test/cypress/integration/my-services/add-new-service.cy.js
test/cypress/integration/my-services/my-services.cy.js

PP-10862 Combine add service Cypress tests

---

test/cypress/integration/my-services/organisation-details.cy.js

Remove the `.within(() => {})` blocks from the tests as they made it difficult to read once the tests were combined.
Add in `{ delay: 0 }` to the options when calling `.type()` on an element to speed up text input to make runtime less.
Hiding whitespace changes from the diff will make this a lot easier to review

PP-10862 Combine organisation details Cypress tests

---

test/cypress/integration/payouts/payouts-list.cy.js

PP-10862 Make payouts Cypress tests standalone

---

test/cypress/integration/settings/default-billing-address-country.cy.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.js
test/cypress/integration/settings/payment-types.cy.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/card.fixtures.js

Simplify payment-types.cy.js to not attempt to check what the new selected card types are after updating. This was only checking that the page has the enabled card types returned by connector selected and not any selfservice logic. Instead, just check that the page is successfully reloaded with a success message.
Hiding whitespace changes will make this slightly easier to review

PP-10862 Make settings Cypress tests standalone

---

test/cypress/integration/settings/switch-psp.cy.js

Restructured the tests slightly so that the tests for the individual pages for submitting the switch details are separate from tests for the task list logic. I Did this because the task list logic relies purely on what is returned from connector rather than any client session saved after a step is completed. This means we don't need to set up new stubs part way through a test to simulate the task list being updated after a step is completed.
Hiding whitespace changes from the diff will make this easier to review

PP-10862 Make switch PSP tests standalone

---

test/cypress/integration/settings/verify-psp-integration.cy.js
test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
test/cypress/integration/settings/your-psp.cy.js

PP-10862 Make your PSP tests standalone

---

test/cypress/integration/webhooks/webhooks.cy.js

PP-10862 Make webhooks Cypress tests standalone

---

test/cypress/integration/switch-psp/organisation-url.cy.js

PP-10862 Make organisation URL tests standalone

---

test/cypress/integration/demo-payment/demo-payment.cy.js
test/cypress/integration/my-services/update-service-name.cy.js

PP-10862 Make update service name Cypress tests standalone

---

test/cypress/integration/stripe-setup/update-org-details.cy.js

Hiding whitespace from the diff will make this easier to review

PP-10862 Make stripe setup tests standalone

---

app/views/registration/phone-number.njk
app/views/registration/resend-code.njk
app/views/request-to-go-live/organisation-address.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/team-members/edit-phone-number.njk
app/views/two-factor-auth/phone-number.njk
app/views/two-factor-auth/resend-sms-code.njk
test/cypress/integration/stripe-setup/responsible-person.cy.js

Use better mark-up for telephone number fields to help browsers display an appropriate on-screen keyboard for entering phone numbers and autofill appropriate phone numbers.
Specifically, when the input expects a user’s phone number for receiving text messages, use `type="tel"` and `autocomplete="mobile tel"`.
When the input expects a responsible person’s phone number, use `type="text"` and `autocomplete="work tel"`. We use `type="text"` as opposed to `type="text"` because a responsible person’s work phone number may have an extension and an on-screen keyboard triggered by `type="tel"` may not offer a way to enter this (though it’s unclear if Stripe accept extensions in phone numbers).
When the input expects an organisation’s phone number, use `type="tel"` and `autocomplete="work tel"`.

PP-10863 Better mark-up for telephone number inputs

---

app/views/forgotten-password/index.njk
app/views/login/login.njk
app/views/registration/email.njk
app/views/stripe-setup/director/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/team-members/team-member-invite.njk
app/views/transactions/filter.njk
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js

For all inputs where we expect a full email address, use `type="email"` and `spellcheck="false"` (the latter is recommended by the GOV.UK Design System for email addresses).
For all other inputs where we expect the user to enter the email address of themselves or a colleague, use `autocomplete="work email"`, except for on the sign in and forgotten password pages, where we use `autocomplete="username"` because we really want the username component of the user’s sign-in details to be filled in.
(An argument could be made that we could use `autocomplete="username"` on the page where the user enters their email address when registering. However, it would be more straightforward to include their email address in a hidden form field on the page where the user chooses their password to strongly …

PP-10863 Use appropriate attributes for email inputs

---

app/views/forgotten-password/index.njk
app/views/login/login.njk
app/views/stripe-setup/director/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/team-members/team-member-invite.njk
app/views/transactions/filter.njk

The `govukInput` Nunjucks macro’s `spellcheck` option (which we presently only ever set to false) takes a boolean, not a string.
If quotation marks are used, the option is ignored and no `spellcheck` attribute is added to the generated HTML.
So change all instances of:
```javascript
spellcheck: "false"
```
…or:
```javascript
spellcheck: 'false'
```
… to:
```javascript
spellcheck: false
```
Slightly confusingly, within the `attributes` option, `"false"` does work, so leave those alone.

PP-10863 For govukInput, value of spellcheck is false not "false"

---

app/views/stripe-setup/director/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/transactions/filter.njk

Add `spellcheck="false"` to inputs where we expect to get a person’s name, as [recommended by the GOV.UK Design System](https://design-system.service.gov.uk/patterns/names/).

PP-10863 Add spellcheck="false" to person name inputs

---

app/views/request-to-go-live/organisation-address.njk
app/views/switch-psp/organisation-url.njk

Where we expect the user to enter the URL of their own organisation, consistently use `type="url"`, `autocomplete="url"` and `spellcheck="false"`.

PP-10863 Appropriate attributes for organisation URL inputs

---

app/views/services/edit-service-name.njk

Add `spellcheck="true"` to service name inputs because the words in service names should generally be spell-checkable.
On the input for a Welsh service name, the `lang="cy"` attribute should ensure that a Welsh spell-checking dictionary is used if available.

PP-10863 Add spellcheck="true" to service name inputs

---

app/views/request-to-go-live/organisation-name.njk

Add `autocomplete="organization"` to organisation name input, which might cause the right thing to be suggested.
There is the possibility it might autofill an inappropriate name but let’s hope the user reads the guidance and edits it as necessary.

PP-10863 Add autocomplete="organization" to organisation name input

---

app/views/payment-links/amount.njk
app/views/payment-links/edit-information.njk
app/views/payment-links/edit-reference.njk
app/views/payment-links/information.njk
app/views/payment-links/reference.njk
app/views/payment-links/web-address.njk

- Do not use `inputmode="decimal"` for the amount because the GOV.UK Design System recommends against it
- Add `spellcheck="true"` to everywhere we expect users to enter normal prose (titles, descriptions etc.)
- Where we expect the user to enter a path of a web address, use `autocapitalize="none"` and `spellcheck="false"` (but not `type="url"` or `inputmode="url"` because it’s not a full URL)

PP-10863 Improve attributes for payment link config inputs

---

package-lock.json
package.json
test/cypress/integration/agreements/agreements.cy.js
test/cypress/integration/dashboard/dashboard-worldpay-setup-banner.cy.js
test/cypress/integration/settings/switch-psp.cy.js
test/cypress/integration/transactions/transaction-list-pagination.cy.js
test/cypress/integration/transactions/transaction-search.cy.js
test/cypress/integration/user/edit-phone-number.cy.js

Make changes to make tests pass:
- Cannot call assertions on multiple elements - so when `cy.get` finds multiple matches need to call `first()` or `eq()` before doing assertions
- A blank page is now loaded at the start of each `it`, rather then the previous behaviour of starting on the page the last test loaded. Needed to make sure all tests call `cy.visit`. Combined some tests to deal with this.

PP-10862 Upgrade to Cypress 12

---

app/views/dashboard/demo-service/create.njk

On the create prototype link page, remove `autofocus` from all three inputs (it makes no sense to have it on more than one), use `type="url"` for the confirmation page URL input and add `spellcheck` attributes:
- `spellcheck="true"` for the payment description input
- `spellcheck="false"` for the amount input (recommended by the GOV.UK Design System for decimal numbers)
- `spellcheck="false"` for the confirmation page URL input

PP-10863 Better attributes for create prototype link inputs

---

app/views/webhooks/edit.njk

Make the webhook callback URL input have `type="url"` and `spellcheck="false"`.
Make the webhook description have `spellcheck="true"` because the description will probably have mostly spell-checkable words.

BAU — Appropriate attributes for inputs on edit webhooks page

---

app/controllers/webhooks/webhooks.service.js
app/controllers/webhooks/webhooks.service.test.js
app/utils/paginator.js
app/utils/paginator.test.js
app/views/webhooks/_paginator.njk
test/cypress/integration/webhooks/webhooks.cy.js
test/fixtures/webhooks.fixtures.js

The webhooks details page currently shows a nubered centered range with a next/ previous button on either side for pagination. Replace this with just next/ pervious to
- bring it in line with the transactions pagination component
- remove the need for the total count performed by the backend
- represent that this is ephemeral data that is useful for debugging your webhook integrations but not a permanent management tool
Bring the pagination component in-line with the transactions page and update any expectations for the backend pagination response.
Uses the [same logic as backend resources](https://github.com/alphagov/pay-ledger/blob/d7793355168004d9ec99b0c280e63807715afbb1/src/main/java/uk/gov/pay/ledger/util/pagination/PaginationBuilder.java#L95-L97) to determine if there might be …

PP-10834 Replace webhooks numbered centered range with previous/ next pagination

---

app/views/dashboard/demo-payment/edit-amount.njk

Do not use `inputmode="numeric"` for the input that asks for the demo payment amount because this will usually bring up an on-screen keyboard that does not have a decimal separator, preventing users from entering amounts that are not whole pounds.
Add `spellcheck="false"` to the input to bring it in to line with what the GOV.UK Design System recommends for decimal number inputs (`type="text"` and `spellcheck="false"`), which is what we already use where we ask for amounts elsewhere in the application (payment link amounts and prototype link amounts).

BAU — Do not use inputmode="numeric" for demo payment amount

---

app/controllers/switch-psp/verify-psp-integration.controller.js
test/fixtures/charge.fixtures.js
test/pact/connector-client/connector-post-create-charge.pact.test.js

- Connector now supports credential_id on create charge request https://github.com/alphagov/pay-connector/pull/4493
- Pass the credential_id when creating a charge to verify payment during PSP switching. Can remove `payment_provider` as credential_id will uniquely identify the gateway_credentials to use in connector.
- depends on https://github.com/alphagov/pay-connector/pull/4497

PP-10958 Use credential_id when creating a charge

---

app/controllers/switch-psp/verify-psp-integration.controller.js
app/controllers/switch-psp/verify-psp-integration.controller.test.js

- Passes credential `external_id` when creating a charge instead of internal ID

PP-10958 Fix creating charge

---

package-lock.json
package.json

Cypress has its own fork of request as a dependency - we don't use this in our tests so it should be safe to override.
~TODO: figure out why the npm has mangled the package-lock version for `qs` in one place (`"version": "https://registry.npmjs.org/qs/-/qs-6.5.3.tgz",`). [See equivalent in products-ui](https://github.com/alphagov/pay-products-ui/pull/2417/files).~ Fixed by refreshing the package-lock.json.

PP-10951: Update qs to 6.11.1 and @cypress/request to 2.88.11

---

app/views/agreements/list.njk
app/views/agreements/macro/status.njk

We don’t have any process/code that sets the payment_instrument/agreement status to expired.
Also, we don’t have any plans to set payment instruments to expired status.
- remove `EXPIRED` from agreements.status
- replace `EXPIRED` with `INACTIVE` (it was forgotten in PP-10949)

PP-10977 remove expired status from agreement

---

app/controllers/webhooks/webhooks.controller.js
app/controllers/webhooks/webhooks.service.js
app/controllers/webhooks/webhooks.service.test.js
app/services/clients/webhooks.client.js
test/cypress/integration/webhooks/webhooks.cy.js
test/cypress/stubs/webhooks-stubs.js
test/pact/webhooks-client/webhooks.pact.test.js

- We now require the gateway account ID when calling webhook functions.
- This PR is to update calls to webhooks.
- The backend changes will be done once this is merged in.

PP-11020 Update webhook calls to pass `gateway account id`

---

app/controllers/webhooks/webhooks.controller.js
test/cypress/integration/webhooks/webhooks.cy.js

- Update calls to Webhook API to use `req.account.gateway_account_id` instead of `req.account.exeternal_id`

PP-11020 Update webhook to include gateway account id correctly

---

app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.controller.test.js

- Add cancel agreement method to the agreement controller.
- This calls the `agreement service > cancel agreement` function
- Then calls the `agreement details` function.
- As we want to to show agreement details page after someone has cancelled an agreement.
- Also pass a `isCancel` flag to the `agreement details` function that will be used to show a notification that the agreement was cancelled.

PP-10601 Cancel agreement - add cancel functionality to agreeement controller

---

app/controllers/agreements/agreements.service.js
app/controllers/agreements/agreements.service.test.js

Update agreement service:
- Fix the call to `ConnectorClienti > postCancelAgreement`.
- Update the test to use gateway account id instead of a gateway external id.

PP-10601 Cancel agreement - fix agreement service bug

---

app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.controller.test.js

- Update agreement controller
- Set flag to only show cancel functionality when agreement is active and user has `agreements:update` functionality
- Rename existing `isCancel` flag to `isCancelAgreementSuccess` so it is more descriptive.

PP-10601 Cancel agreement - showing cancel functionality

---

app/controllers/agreements/agreements.controller.js
app/controllers/agreements/agreements.controller.test.js

- Refactor when cancelling an agreement
- So that it redirects to the agreement detail page rather than calling the agreement detail page directly.
- Use the req.flash method to set the `cancel success` notification

PP-10601 Cancel agreement - update agreement controller

---

package-lock.json
package.json

Resolves a long running issue with `ejs` (see https://github.com/alphagov/pay-selfservice/security/dependabot/34). Solving this should reduce noise in our dependency alerts.
See the equivalent PR in products-ui: https://github.com/alphagov/pay-products-ui/pull/2471
Check if the cypress tests pass on this PR!

BAU: Resolve ejs/mountebank-formatters conflict

---

test/cypress/plugins/index.js
test/integration/proxy.it.test.js

- Replaced request library usage in tests with Axios. This is to eventually remove the request library dependency which is not maintained anymore

PP-10875 Remove request library usage from tests

---

test/cypress/integration/agreements/agreement.cy.js
test/cypress/stubs/agreement-stubs.js

- Add tests for:
- If the user does not have correct permissions.
- If the cancel agreement call to connector fails.
- Some minor code cleanup

PP-10601 Cancel agreement - add more Cypress test coverage

---

app/assets/sass/components/target-to-show.scss
app/views/agreements/detail.njk
app/views/api-keys/_key.njk
app/views/payment-links/_product.njk
app/views/team-members/team-member-details.njk
app/views/transaction-detail/_refund.njk

- Refactor the CSS that is used by the code to make functionality work without JS. This is the `target-to-show` CSS.
- Clean up to make it simpler.
- Make it consistent with the design system.  So that the cancel button is aligned to the left.
- See this link from the Design system: https://design-system.service.gov.uk/components/button/ - Go to grouping buttons section.
- Update the code in the following places so that the `cancel` button is aligned correctly.
- Cancel agreement
- Refund transaction
- Remove team member
- Update API key
- Revoke API key
- Delete payment link
Updated the following pages with cancel buttons as per below:

PP-11119 - Grouping buttons - refactor and alignment issuses.

---

app/controllers/service-switch.controller.it.test.js
app/services/clients/connector.client.js
test/cypress/stubs/gateway-account-stubs.js
test/integration/make-a-demo-payment/go-to-transactions.controller.ft.test.js
test/integration/transaction-redirect-details.ft.test.js
test/pact/connector-client/connector-get-gateway-account.pact.test.js
test/pact/connector-client/connector-get-multiple-gateway-accounts.pact.test.js

Use the GET `/v1/api/accounts` and GET `/v1/api/accounts/{accountId}` endpoints rather than the `/v1/frontend/` variants.
The behaviour of the `/v1/api/` and `/v1/frontend/` endpoints is now identical and we intend to remove the `/v1/frontend` variants.

PP-11244 use /api/ endpoint for getting gateway accounts

---

app/views/agreements/detail.njk
app/views/agreements/list.njk
app/views/agreements/paginator.njk
test/cypress/integration/agreements/agreement.cy.js
test/cypress/integration/agreements/agreements.cy.js

- add a new test that checks the rendering of the agreement details page in specifics

PP-10627 add agreement details page cy test

---

app/views/email-notifications/confirmation-email-toggle.njk
app/views/email-notifications/refund-email-toggle.njk
app/views/includes/cookie-message.njk
app/views/includes/footer-categories.njk
app/views/includes/footer.njk
app/views/payment-links/amount.njk
app/views/payment-links/web-address.njk
app/views/request-to-go-live/organisation-address.njk
app/views/request-to-go-live/organisation-name.njk
app/views/services/add-service.njk
app/views/services/edit-service-name.njk
package-lock.json
package.json
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js

Went through the release notes for version 4 and made the necessary updates:
https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0
- Most changes are minor changes.
- Main bit of work was updating the footer - as CSS width classes must now be used.
- All changes have been checked using the Percy > Cypress integrations.
- This is both the mobile and desktop view.
- Once this is merged, will pin the release and do a bit more testing in the test env.
- More details about the changes are below:
The main changes are listed below
Hint text uses a `<div>` instead of a `<span>`
Hint text uses a `<div>` instead of a `<span>`
Add the `data-nosnippet` attribute to the banner.
Have to add the width classes to the individual columns.
Also add `aria-hidden=true` for the OGL logo.
Error message …

PP-10845 Upgrade to `govuk-frontend 4.7.0` (Design system v4)

---

app/controllers/your-psp/get-flex.controller.js
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/_worldpay.njk
app/views/your-psp/flex.njk

- Update the page to use the new `Summary list card` styling from design system v4.
- Update the `account credentials` and `3DS flex` sections.
- No longer have a seperate change link for each entry in the `summary list`. Just one change link in the heading.
- Remove the `?change=**` query parameter from the change link.  As this is no longer required as we only have 1 change link per section.
- Update the `3DS flex` credentials nunjucks file to longer use the `change` query       parameter.
- Update the 3DS flex controller - Remove references to the `change` query parameter as  this is no longer used.

PP-11251 Update `Your PSP > Worldpay` with new styling

---

app/controllers/credentials/worldpay.controller.js

The configure Worldpay credentials page was not loading when no Worldpay credentials are set. The code was expecting the `one_off_customer_initiated` key to not exist in the credentials JSON from connector.
We should change connector so that it doesn't return fields with null values, but making this change makes the handling of the JSON from connector a bit more robust.

PP-11152 Fix loading credentials page

---

test/pact/adminusers-client/authenticate/authenticate.pact.test.js
test/pact/adminusers-client/user/authenticate.pact.test.js

Temporarily disable some pact test where the username is not an email address. We are re-factoring adminusers and username must be the email address.
- disable tests

PP-11283 temporarily disbale some adminusers pact test

---

test/fixtures/gateway-account.fixtures.js
test/pact/connector-client/connector-patch-gateway-account-credential-state.pact.test.js
test/pact/connector-client/connector-patch-gateway-account-credentials.pact.test.js
test/pact/connector-client/connector-patch-gateway-account-merchant-id.pact.test.js

We now consume one-off Worldpay credentials from the nested `credentials.one_off_customer_initiated` field in responses from Connector. Update pact tests so connector can stop returning the legacy credentials fields.
We do not need to check the one-off credentials in responses to update other fields on the gateway credentials, so remove these from pact tests where they are unnecessary.

PP-11152 Update pact tests to use new credentials structure

---

test/pact/adminusers-client/forgotten-password/create-forgotten-password.pact.test.js

Temporarily disable some pact test where the username is not an email address. We are re-factoring adminusers and username must be the email address.
- disable tests

PP-11283 temporarily disable some adminusers pact test 2

---

app/views/your-psp/_worldpay-flex.njk
test/cypress/integration/settings/your-psp.cy.js

- Update the 3DS section for test Worldpay accounts.
- Move the `toggle 3DS` button higher.
- General clean up of code.

PP-11251 Your PSP > Worldpay creds for test accounts - update design

---

.secrets.baseline
app/services/clients/adminusers.client.js
test/fixtures/user.fixtures.js
test/pact/adminusers-client/authenticate/authenticate.pact.test.js
test/pact/adminusers-client/user/authenticate.pact.test.js

We are removing username from `adminusers` API and all consumers. We are going to use email instead. In the first iteration we send the email with all authentication requests.
- add email to authentication requests

PP-11327 add email to authentication

---

app/services/clients/adminusers.client.js
app/services/user.service.js
test/cypress/integration/user/login.cy.js
test/cypress/stubs/user-stubs.js
test/fixtures/user.fixtures.js
test/pact/adminusers-client/authenticate/authenticate.pact.test.js
test/pact/adminusers-client/user/authenticate.pact.test.js

Authenticating against adminusers now requires email, not username
- remove username from authentication requests
- refactor tests accordingly

PP-11327 remove username from authentication

---

.secrets.baseline
app/views/your-psp/_worldpay-flex.njk
test/cypress/integration/settings/your-psp.cy.js

Your PSP > Worldpay Test account
- When 3DS flex crendentials already exist in a Worldpay test account, hide the content that tells the user to enter 3DS flex crendentials in order to enable 3DS flex.
- As it is not relevant if 3DS flex settings are already configured.

PP-11251 Your PSP > Worldpay test accounts - Toggle 3DS flex content

---

.secrets.baseline
test/fixtures/gateway-account.fixtures.js
test/pact/connector-client/connector-get-gateway-account-by-external-id.pact.test.js
test/pact/connector-client/connector-patch-gateway-account-credentials-customer-initiated.pact.test.js
test/pact/connector-client/connector-patch-gateway-account-credentials-merchant-initiated.pact.test.js
test/pact/connector-client/connector-patch-gateway-account-credentials-one-off.pact.test.js

- Update existing PACT test for patching Worldpay credentials
- Make it more specific for `one off` payments.
- Add 2 new PACT tests
- 1 for patching `recurring customer initiated` credentials.
- 1 for patching `recurring merchant initiated` credentials.
- Update existing PACT for `get gateway account by external id`
- Test that `recurring customer initiated` and `recurring merchant initiated` transactions
are returned.
- This test requires that the connector PACT state `is gateway account 333 with Worldpay 3DS Flex credentials exists` is updated.

PP-11251 Worldpay credentials PACT tests

---

.secrets.baseline
app/utils/is-a-potential-pan.js
app/utils/is-a-potential-pan.test.js
package-lock.json
package.json

- Add util methods to check if value is a potential PAN.
- These methods were taken from an older version of `products-ui` which use to check if a reference was a PAN using these methods.
- These methods will be used in a future PR to check if the user is searching for transactions with a potential PAN.

PP-10823 Check for PAN in reference field - add util methods

---

app/views/transactions/filter.njk

- Need to update the layout HTML:
- So that in a future PR when we add an error message to the reference field, then it does not break the layout.
- Need to wrap the filters in `gov-grid-row` with correct padding.
- Visually, everything looks the same.

PP-10823 Transactions - Update HTML

---

app/views/digital-wallet/google-pay.njk
test/cypress/integration/settings/allow-google-pay.cy.js

Hide the copy that says "You’ll need a Google Pay merchant ID" on the Google Pay settings page for Stripe accounts.

PP-11318 Hide merchant ID copy for Stripe account

---

app/middleware/error-handler.js

We use axios to make requests to the zendesk API. Update `error-handler.js` to log available data from errors returned by axios.

BAU Log details for AxiosError

---

app/controllers/dashboard/dashboard-activity.controller.js
app/controllers/request-psp-test-account/post.controller.js
app/controllers/request-to-go-live/agreement/post.controller.js
app/controllers/user/two-factor-auth/get-configure.controller.js
test/pact/adminusers-client/user/get-multiple-users.pact.test.js
test/pact/adminusers-client/user/get-user.pact.test.js

When creating a Zendesk ticket, we need to send the name of the requester. We were getting this from the `username` field on a User, but this field has been removed. Zendesk was returning a 422 when the name was empty in some cases.
Instead, get the name from the `email` field, which was the same as the `username` anyway when the username existed.
Remove/replace other places where we were still trying to access the `username` on the User.

BAU Fix creating zendesk ticket

---

test/pact/connector-client/connector-get-charge.pact.test.js

The `before` wasn't waiting for a Promise to resolve. Return the Promise so it is awaited before the test is run.

BAU Fix flaky test

---

.github/dependabot.yml

- Set Dependabot config for Github Actions and npm dependencies to receive security updates only.
- Keep the existing 'ignores' for `change-case`, `joi` and `@sentry/node` as we can't currently update these

PP-11138: Set npm and Github Actions dependencies to security updates only

---

app/utils/display-converter.js
app/utils/display-converter.test.js

Enable digital wallet toggles for Stripe test gateways

PP-11602 enable wallet config for stripe test gateways

---

app/utils/transaction-view.js
app/utils/transaction-view.test.js
app/views/transaction-detail/_events.njk
app/views/transaction-detail/index.njk
test/cypress/integration/transactions/transaction-details.cy.js

- For the transaction fields redacted for personally identifiable information (PII), display the text as `Data unavailable' on the transaction details page
- Hides the transaction events section when there are no events (deleted when PII is redacted) for the transaction.

PP-11598 Display appropriate text for redacted fields

---

.secrets.baseline
app/views/dashboard/demo-payment/mock-card-details.njk
test/cypress/integration/demo-payment/mock-cards-stripe.cy.js
test/cypress/integration/demo-payment/mock-cards.cy.js

Change test card number in Stripe test accounts to UK issued test card
https://payments-platform.atlassian.net/browse/PP-9916
Update ‘Mock card numbers’ template to test for ‘stripe’ account and display UK issued test card.

PP-9916 Change test card number in Stripe test accounts

---

app/utils/display-converter.js
app/utils/display-converter.test.js
test/cypress/integration/demo-payment/mock-cards-stripe.cy.js
test/pact/connector-client/connector-patch-apple-pay-toggle.pact.test.js
test/pact/connector-client/connector-patch-google-pay-toggle.pact.test.js

Allow enabling Apple Pay and Google Pay for Sandbox gateway accounts
[https://payments-platform.atlassian.net/browse/PP-11594](https://payments-platform.atlassian.net/browse/PP-11594)
This is a rework of original pull request [#4143](https://github.com/alphagov/pay-selfservice/pull/4143). Mainly to make clearer the commits relating to this change as previously, due to rebasing and merge commits,  they were spread amongst other unrelated changes.
Also, this PR addresses comments from that review.
- Extend existing ‘isDigitalWalletsSuported’ test for ‘Stripe’ and ‘Worldpay’ accounts to include ‘sandbox’ accounts
- Add feature flag ‘ALLOW_ENABLING_DIGITAL_WALLETS_FOR_SANDBOX_ACCOUNT’ as part of test condition
- Add unit tests for all sandbox feature flag states

PP-11594 - Allow enabling Apple Pay and Google Pay for Sandbox gateway accounts

---

package-lock.json
package.json

Apply overrides to ensure a minimum `ansi-regex` version of 3.0.1. 
`npm run compile && npm test` still passes, and `npm list --all shows no 2.x version of `ansi-regex`.

PP-11934-patch-ansi-regex

---

app/controllers/all-service-transactions/get.controller.js
app/controllers/all-service-transactions/get.controller.test.js
app/controllers/transactions/transaction-list.controller.it.test.js
app/controllers/transactions/transaction-list.controller.js
app/utils/filters.js
app/utils/filters.test.js
app/utils/transaction-view.js
app/views/transactions/index.njk
app/views/transactions/list.njk
test/cypress/integration/transactions/transaction-search.cy.js

When searching for transactions in SelfService between two dates, if the start date entered is later than the end date, no transactions are listed. 
We should be rendering an error here to show the user the input mistake and how to rectify it.
This fix is done on both the transactions and the all transactions search pages 
Test all existing filter combinations as well as the new date range validation

PP 11877 Validate date range entry on the transaction search page

---

app/views/includes/head.njk

We want stop our sign in page from appearing in search engine results, so that citizens are less likely to navigate to [GOV.UK](http://gov.uk/) Pay and contact support about their PIP accounts.
The following meta tag has been added to the head.njk template.
`<meta name="robots" content="noindex, nofollow">`

PP-12098 Add robots noindex and nofollow to meta tag

---

.secrets.baseline
app/assets/sass/components/transaction-filter.scss
app/views/transactions/filter.njk
app/views/transactions/index.njk
test/cypress/integration/transactions/transaction-search.cy.js

- Use design system guidelines for validation styling.
- When searching for transactions and the end date < start date:
- Display an error summary
- Display an error message around the `end date` field.
- Highlight the `end date` field.
- The code to carry out the validation was done previously.
- This PR is to only update the design / styling.

PP-12055 Update validation styling for transactions search filter

---

app/services/clients/stripe/StripeAccount.class.js
app/services/clients/stripe/StripeBankAccount.class.js
app/services/clients/stripe/StripeCompany.class.js
app/services/clients/stripe/StripeDirector.class.js
app/services/clients/stripe/StripeDirector.class.test.js
app/services/clients/stripe/StripeOrganisationDetails.class.js
app/services/clients/stripe/StripePerson.class.js
app/services/clients/stripe/StripePerson.class.test.js
package-lock.json
package.json

Context: Need to update joi version to one which does not use hoek versions before 8.5.1 because previous versions of hoek have a [vulnerability](https://github.com/alphagov/pay-selfservice/security/dependabot/71)
- update to current joi version 17.12.1
- update uses of joi as Joi.validate() function is no longer supported

PP-12167 Update joi to resolve hoek vulnerability

---

app/views/includes/header.njk
package-lock.json
package.json

- Bump govuk-frontend to 4.8 so we have access to
the crown logo.
- Enable setting to use the tutor cronw as per design
system instructions GOV.UK Design system:
https://github.com/alphagov/govuk-frontend/releases/tag/v4.8.0
- Do not merge this until we get approval from the
#govuk-logo-crown-change team.
- Which should be on Mon 19th Feb.

PP-12179 Add new crown logo and bump govuk-frontend

---

app/controllers/all-service-transactions/get.controller.js
app/controllers/all-service-transactions/get.controller.test.js
app/controllers/dashboard/dashboard-activity.controller.js
app/controllers/transactions/transaction-list.controller.it.test.js
app/controllers/transactions/transaction-list.controller.js
app/utils/filters.js
app/utils/transaction-view.js
test/cypress/integration/dashboard/dashboard-statistics.cy.js
test/integration/dashboard/dashboard-activity.controller.ft.test.js

As described in PP-10608 the number of days searched on the dashboard is currently out by one.  It was intentionally written (with comments describing it) but having looked deeper into it because of the use of midnight as the start of the period the extra day wasn't needed
On an account with transactions every day visit the dashboard and select "Previous 7 days" or "Previous 30 days", the query was previously showing a date range one day longer than requested for each of these categories.

PP-10608: Correcting the number of days in transaction queries.

---

app/services/clients/base/config.js
app/services/clients/base/config.test.js
app/services/clients/base/request-context.js
app/services/clients/base/request-logger.js
package-lock.json
package.json

- Initial set up for using `axios` as opposed to `request` library.
- Use latest version of `pay-js-commons` library containing `axios-base-client` code.
- Add `clients/base` files for use with axis-base-client calls.

PP-11681 Replace `request` library with `axios`.

---

app/controllers/stripeTermsAndConditions.controller.js
app/controllers/stripeTermsAndConditions.controller.test.js
app/paths.js
app/routes.js
app/utils/display-converter.js
app/views/policy/stripe-terms-and-conditions/stripe-terms-and-conditions.njk

- This page will contain the latest Stripe terms and conditons.
- This page will be on a brand new URL: /policy/stripe-terms-and-conditions
- Intend to put this live but hidden from real users.
- This will allow the team to review the content and request updates.
- We expect there to be some late edits as we are working with the legal team to finalise the content.
- This page is implemented differently from the other /policy/ pages:
- The other pages generate a 1 hour link to a policy PDF file and follow a specific page layout.
- This new page will look different and we need to release it quickly.
- Making this work with the existing code would have required too much effort.
- Therefore, this was implemented differently as a static page - which is quicker to implement without affecting …

PP-12295 Add new Stripe terms and conditions page

---

app/services/clients/products.client.js
test/pact/products-client/product/delete.pact.test.js
test/pact/products-client/product/disable.pact.test.js

- Change  ‘products.client’ methods to use ‘axios-base-client’ library.
- Refactor call parameters initialisation.
- Use ‘async/await’ syntax.

PP-11681 Replace ‘base-client’ with ‘axios-base-client’

---

app/controllers/payment-types/post-index.controller.js

Code QL flagged this as potential loop bound injection. Use ES6 functionality to replace use of lodash.

PP-12235 Fix loop bound injection

---

app/utils/validation/server-side-form-validations.js
app/utils/validation/server-side-form-validations.test.js

Code QL flagged that the `A-z` in the regex was a "Suspicious character range that is equivalent to [A-Z\[\\]^_`a-z]."

PP-12237 Fix permissive regex

---

app/services/clients/base/config.js
app/services/clients/base/config.test.js
test/pact/adminusers-client/invite/get-invite.pact.test.js

When configuring `axios-base-client` call, encode the url passed in.
- Amend `configureClient` function to encode url passed in from client code issuing axios call.
- Amend unit test to cover change.

PP-11681 Encode URL when making axios call

---

app/services/clients/ledger.client.js
app/services/clients/ledger.client.test.js

- Change ‘ledger.client’ methods to use ‘axios-base-client’.
- Refactor call parameters initialisation.
- Use ‘async/await’ syntax.

PP-11681 Replace 'base-client' with 'axios-base-client' in 'ledger.client'

---

app/services/clients/connector.client.js

- Change ‘connector.client’ methods to use ‘axios-base-client’.
- Refactor call parameters initialisation.
- Use ‘async/await’ syntax.

PP 11681 Replace 'base-client' with 'axios-base-client' in 'connector.client'

---

.secrets.baseline
app/controllers/dashboard/dashboard-activity.controller.js
test/cypress/integration/dashboard/dashboard-statistics.cy.js
test/integration/dashboard/dashboard-activity.controller.ft.test.js

- We don't specify a date format for `moment` which is returning dates in the format `2024-04-02T00:00:00+01:00` for transaction summary reporting causing Ledger to return an error. 
- Updated the date format to the one expected by the ledger transaction summary endpoint. The change will return date as `2024-04-02T00:00:00.000Z`

PP-12510 Specify format for transaction summary dates

---

.secrets.baseline
app/controllers/dashboard/dashboard-activity.controller.js
test/cypress/integration/dashboard/dashboard-statistics.cy.js
test/integration/dashboard/dashboard-activity.controller.ft.test.js

- When getting the date range for transaction summary search, `moment.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]')` returns datetime in the specified format but doesn't convert it to UTC.
-  As a result, the ledger API call for transaction summary is using incorrect date ranges (BST date ranges instead of UTC)
- in Nunjucks filters, `fromDateTime` and `toDateTime` are converted to BST (this is BST->BST instead of UTC->BST) which adds an hour to the BST date range. So date filters for the `successful payments` link on the dashboard and others are incorrect.
- Change gets date ranges in UTC and uses these fields
- to query Ledger for transaction summary
- in the dashboard explainer in the Nunjucks template. 
- to create a transaction period string (in BST) to search for successful payments - …

PP-12510 Fix gateway account dashboard date ranges

---

.secrets.baseline
app/controllers/all-service-transactions/all-service-transactions-no-autosearch.controller.js
app/controllers/all-service-transactions/all-service-transactions-no-autosearch.controller.test.js
app/controllers/all-service-transactions/get.controller.js
app/controllers/all-service-transactions/index.js
app/controllers/all-service-transactions/populateModel.js
app/controllers/all-service-transactions/populateModel.test.js
app/errors.js
app/middleware/error-handler.js
app/paths.js
app/routes.js
app/services/transaction.service.js
app/utils/response.js
app/views/error.njk
app/views/transactions/index.njk
app/views/transactions/list.njk
test/cypress/integration/all-service-transactions/all-service-transactions-no-autosearch.cy.js
test/cypress/integration/all-service-transactions/all-service-transactions.cy.js

- Add new error for a ledger timeout on all services transactions search
- Link from the error page to the all services transaction search page,  without the automatic search, to avoid a perpetual timeout
- Refactor to share the code that populates the model
- Update unit tests
- Update cypress tests
with @DomBelcher and @nataliecarey

PP-12100 Allow users to apply filters to their transaction search if it times out

---

.secrets.baseline
app/controllers/credentials/worldpay.controller.js
test/cypress/integration/settings/your-psp.cy.js

MOTO enabled services typically have merchant codes ending MOTO and this is validated in self-service.
Worldpay has started allocating codes that end MOTOGBP. This is preventing a service from onboarding ([Zendesk ticket 5817027](https://govuk.zendesk.com/agent/tickets/5817027))
- Allow MOTO-enabled services to enter merchant codes ending MOTOGBP

ZD5817027 Allow moto merchant code ending MOTOGBP

---

package-lock.json
package.json

- Pay-js-commons has been updated with the latest changes of Axios base client.
- The new changes do not affect this repository directly, but want update the version so that it is aligned with the other reporistories.

PP-12659 Bump pay-js-commons

---

app/middleware/error-handler.js
test/cypress/integration/all-service-transactions/all-service-transactions.cy.js

Context: When there is a database timeout from a transactions search across all services, the resulting error page sometimes has a malformed url, because it relies on a parameter stored in the session, which is not present when a user of live services clicks on the 'View transactions for all my services' link on the My Services page.
- update the formation of the url in the link to the all services transactions 'no-search' page so that if the `live|test` parameter is not stored in the session, `live` is added to the url.
- update Cypress tests to cover all permutations of the all-services-transactions url.

PP-12624 Fix bug in timeout error page

---

.secrets.baseline
app/views/transactions/index.njk

Updated jQuery libraries to latest version.
- jQuery -> 3.7.1
- jQuery Timepicker -> 1.14.1
- jQuery Datepair -> 0.4.17
- Bootstrap Datepicker -> 1.10.0
Updating CDN links in the nunjucks transactions/index file.

PP-12764 Update jquery libraries

---

app/views/webhooks/detail.njk

There was a mismatch between the time we display webhooks for and the time we claim to hold them for.  This corrects that mismatch.

PP-13022: Updated the content on the webhooks page to match the implementation.

---

app/services/clients/connector.client.js
test/pact/connector-client/connector-post-request-stripe-test-account.pact.test.js

Pact test to verify a call of `POST
/v1/service/{serviceId}/request-stripe-test-account` from selfservice to connector works.

PP-12413: Pact test for requesting a stripe test account

---

app/services/clients/connector.client.js

It makes for a very unpleasant developer experience to be unable to easily see what connector urls are being called. Rectify this by hardcoding URLs.

PP-12413: Hardcode connector urls

---

.secrets.baseline
test/fixtures/gateway-account.fixtures.js
test/pact/connector-client/connector-client-create-gateway-account.pact.test.js

Context: In a subsequent PR, serviceId will be made mandatory for create gateway account requests to connector. Selfservice already sends the serviceId but this isn't reflected in the PACT tests
- Enable PACT tests for create gateway account
- Update PACT tests for create gateway account to include serviceId
- Amend PACT test for failed create gateway account request to reflect that connector sends 422 for invalid parameter values

PP-12876-Enable PACT test for create gateway account

---

test/pact/connector-client/connector-post-request-stripe-test-account.pact.test.js

Temporarily disabling because the request stripe test account URL [has been changed](https://github.com/alphagov/pay-connector/pull/5505).

PP-12413: Temporarily disable request stripe test account pact test

---

app/views/dashboard/_stripe-account-setup-banner.njk
app/views/request-to-go-live/index.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/switch-psp/switch-psp.njk

Change all links to https://www.payments.service.gov.uk/what-being-a-responsible-person-means/ (which no longer exists) to instead link to https://www.payments.service.gov.uk/required-responsible-person-and-director-information/ (which does exist).

BAU — Fix responsible person links

---

app/assets/sass/application.scss
app/assets/sass/components/messages.scss
app/controllers/create-service/create-service.controller.js
app/controllers/create-service/get.controller.test.js
app/controllers/create-service/post.controller.test.js
app/controllers/create-service/select-organisation-type/select-organisation-type.controller.js
app/controllers/create-service/select-organisation-type/select-organisation-type.test.js
app/controllers/dashboard/dashboard-activity.controller.js
app/controllers/dashboard/dashboard-activity.controller.test.js
app/paths.js
app/routes.js
app/services/clients/connector.client.js
app/services/service.create-service.test.js
app/services/service.service.js
app/utils/display-converter.js
app/views/dashboard/index.njk
app/views/includes/systemMessages.njk
app/views/services/add-service.njk
app/views/services/index.njk
app/views/services/select-org-type.njk
app/views/team-members/team-member-profile.njk
test/cypress/integration/my-services/add-new-service.cy.js
test/ui/team-member-details.ui.test.js

- add new view and controller to enable user to select what type of organisation they work for when creating a new service
- create Stripe test account by default when selecting 'local' government, sandbox when selecting 'central'
- redirect user to new service on creation (was previously the 'My Services' overview)
- update psp test account stage when creating new stripe service
- introduce new 'SystemMessages' macro for displaying simple notifications to users
- show 'Service created successfully' message on successful creation of a new service
- layout bug fixes

PP-13091 select organisation type view/controller

---

app/views/services/add-service.njk
app/views/services/edit-service-name.njk
app/views/services/select-org-type.njk
test/cypress/integration/my-services/add-new-service.cy.js

- Some design changes to the Service Name page in the 'Add Service' flow
- Update page title
- Update page heading
- Move paragraph text to hint text on text input
- Replace text about Welsh translation documentation with link to documentation
- Remove 'cancel' link
- Fix padding on 'back' link to be 15px above and below
- Some of the design changes have already been addressed in #4256 & #4258
This is what the current Service Name page looks like:
This is the updated version (with these changes)

PP-13090 Service Name design changes

---

app/views/services/add-service.njk

- Update the text size in link to "Use Welsh on your payment pages" documentation in Add Service flow
New appearance:
See #4259 for previous appearance

PP-13090 Update size of link to Welsh language docs

---

README.md
server.js

Bind to 127.0.0.1 by default instead of 0.0.0.0 and allow override with BIND_HOST env var.
You can see this works, on master:
*  On master run `npm run start:dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp46      0      0  *.3000                                        *.*                                           LISTEN
```
* Switch to this branch, then `npm run start:dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp4       0      0  127.0.0.1.3000                                *.*                                           LISTEN
```
* Now `BIND_HOST=0.0.0.0 npm run start:dev`
* A final netstat to prove the override works
```
$ netstat -anl | grep 3000
tcp4       0      0  *.3000                                        *.*                                           LISTEN
``` …

PP-13145: Accept BIND_HOST env var and default to localhost

---

app/assets/js/components/add-service-spinner.js
app/assets/js/components/request-psp-test-account-spinner.js
app/assets/sass/application.scss
app/assets/sass/components/spinner.scss
app/controllers/create-service/create-service.controller.js
app/controllers/request-psp-test-account/post.controller.js
app/views/includes/spinner.njk
app/views/request-psp-test-account/index.njk
app/views/services/select-org-type.njk
test/cypress/integration/my-services/add-new-service.cy.js
test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.js

- Add a loading spinner which shows when creating a Stripe test account. This shows in two scenarios:
- When creating a new service for a local government organisation
- When requesting a Stripe test account on a service with a Sandbox test account
- The spinner does not show when creating a central government service, as this should not take long enough to warrant use of the spinner, and may cause issues for tools such as screen readers
- There are some Cypress tests for this, but they aren't comprehensive as it doesn't seem possible to check both that the spinner shows and the form submits in one test. 
- This can be tested locally by modifying a local instance of Connector to enforce a delay on the `/request-stripe-test-account` endpoint - see comment below for more info

PP-13111 Show spinner when creating a Stripe test account

---

app/assets/js/components/notification-banner.js
app/browsered/cookie-functions.js
app/utils/cookie.js
test/unit/browsered/cookie-banner.test.js
test/unit/browsered/cookie-functions.test.js

Implements `[RFC] SameSite attribute for cookies`
add SameSite=Lax to:
- session
- govuk_pay_cookie_policy
- govuk_pay_notifications
- register_invite

PP-13011 add SameSite Lax to cookies

---

app/controllers/dashboard/dashboard-activity.controller.js
test/cypress/integration/dashboard/dashboard-links.cy.js
test/cypress/stubs/user-stubs.js
test/fixtures/service.fixtures.js

Context: Changes to the onboarding flow on 29/08/2024 mean that local gov services are now automatically allocated a Stripe test account. Therefore the link to create a Stripe test account should not be displayed for services that onboarded since that date.
- add condition to only show the create Stripe test account link to services onboarding prior to 29/08/2024
- update Cypress tests accordingly

PP-13174 Do not show test stripe link for new services

---

app/controllers/dashboard/dashboard-activity.controller.js

- Updates the cutoff time added in #4284 to approximately the time when the change to create a Stripe test account as part of the onboarding flow was deployed.
- This is approx. `2024-08-29T10:08:00Z`, the time PR  #4256 was deployed (release tag `alpha_release-3056`, concourse build `698`)
- There was one service created on  2024-08-29 before the above change went live which currently would be unable to request a Stripe test account, this change should rectify that

PP-13174 Update cutoff time for removing link to request stripe test account

---

package-lock.json
package.json
test/cypress/integration/webhooks/webhooks.cy.js

Using the latest version of `run-amock` which uses case-sensitive query strings as we no longer have to maintain feature-compatibility with Mountebank.
This new version treats query strings as case-sensitive (as our production apps do) so one mock needed updating.

PP-13234: Using latest run-amock

---

app/controllers/simplified-account/settings/index.controller.js
app/controllers/simplified-account/settings/index.controller.test.js
app/controllers/simplified-account/settings/service-name/service-name.controller.js
app/controllers/simplified-account/settings/service-name/service-name.controller.test.js
app/paths.js
app/routes.js
app/services/service.service.js
app/utils/display-converter.js
app/utils/simplified-account/settings/SettingsBuilder.class.js
app/utils/simplified-account/settings/service-settings.js
app/views/simplified-account/settings/email-notifications/index.njk
app/views/simplified-account/settings/service-name/edit-service-name.njk
app/views/simplified-account/settings/service-name/index.njk
test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.js
test/cypress/integration/simplified-account/service-settings/service-name-test-helpers.js
test/cypress/integration/simplified-account/service-settings/service-name.cy.js
test/cypress/stubs/gateway-account-stubs.js

- add 'Remove Welsh service name' button when editing Welsh service name (if one is set)
- show a success message when clearing the Welsh service name via the new button
- add Cypress test for service name settings

PP-13133 simplified account settings cypress test service name

---

app/controllers/simplified-account/settings/team-members/remove-user/remove-user.controller.js
app/controllers/simplified-account/settings/team-members/remove-user/remove-user.controller.test.js
app/controllers/simplified-account/settings/team-members/team-members.controller.js
app/middleware/simplified-account/enforce-cannot-remove-self-from-service.middleware.js
app/middleware/simplified-account/enforce-cannot-remove-self-from-service.middleware.test.js
app/middleware/simplified-account/index.js
app/simplified-account-routes.js
app/views/simplified-account/settings/team-members/remove-user.njk

- Implement the functionality to Remove a user from a service
- Cypress test will be added in a subsequent PR
Screenshot from 12 Nov 2024 - Confirm page
---------
Screenshot from 12 Nov 2024 - Success message
---------
Screenshot from 12 Nov 2024 - Invalid form message
---------

PP-12398 Remove team member

---

app/services/clients/connector.client.js
app/services/email.service.js

Use singular `patchEmailNotificationByServiceIdAndAccountType` method on the connector client. This helps with keeping things DRY.

bau: Using singluar patch email method

---

app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.js
app/utils/roles.js
app/utils/roles.test.js
app/views/simplified-account/settings/team-members/change-permission.njk

- Add the explanatory content about each role to the roles file and add a method to get the relevant role information for a service. 
- Iterate over the roles in the change permission template to reduce repetition
- The above changes will also make the 'invite team member' page simpler.
- Also, make the radio button labels bold to match the design.
It should be possible to simplify the roles.js file further; I don't think that the `extId` property is actually necessary although it is referred to elsewhere, I will see if this can be refactored in a subsequent PR.
Still to do: Implement the functionality in the post controller for changing permission (and lots of tests)
Screenshot as of 15-11-2024
------

PP-13297 Add logic to roles and refactor template

---

app/controllers/request-to-go-live/choose-takes-payments-over-phone/post.controller.js
app/controllers/request-to-go-live/choose-takes-payments-over-phone/post.controller.test.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.test.js
app/controllers/request-to-go-live/organisation-name/post.controller.js
app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.js
app/controllers/simplified-account/settings/organisation-details/organisation-details.controller.js
app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-check-answers.controller.js
app/controllers/switch-psp/organisation-url/post.controller.js
app/controllers/switch-psp/organisation-url/post.controller.test.js
app/models/ServiceUpdateRequest.class.js
app/models/ServiceUpdateRequest.class.test.js
app/utils/format-address-as-paragraph.js
app/views/simplified-account/settings/organisation-details/index.njk
jsconfig.json
package.json
test/pact/adminusers-client/service/update-service.pact.test.js

- Implement POST functionality for organisation details settings form
- implement patch request to adminusers to save POSTed organisation details
- update ServiceUpdateRequest to be more robust by only allowing predefined paths to be used
- redirect from organisation details index view to organisation details form when no organisation details have been set
- abstract address formatter to util

PP-13255 Add post functionality for organisation details settings form

---

app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.js
app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.test.js
app/utils/roles.js
app/utils/roles.test.js
app/views/simplified-account/settings/team-members/change-permission.njk

- Refactor the display of roles in the change permissions form to ensure that the ordering of roles matches the design
- Correct spacing between radios and 'save changes' button.
Screenshot for service that doesn't have agent-initiated moto enabled:
-------
Screenshot for service that has agent-initiated moto enabled:
--------

PP-13297 change permission layout corrections

---

app/controllers/simplified-account/settings/team-members/invite/invite.controller.js
app/controllers/simplified-account/settings/team-members/invite/invite.controller.test.js
app/views/simplified-account/settings/team-members/invite.njk

- add the post controller to handle the invite user form, and a unit test for the happy path
To do in subsequent PRs:
- Error page for 412 response from admin for a user who is already a team member, and a corresponding unit test. I'm deferring this as it needs some UCD input.
- I've reverted from the ControllerTestBuilder back to the previous test setup but I will revisit this later to see if it's possible to use/adapt ControllerTestBuilder to use in this and other team-members controller tests.
Screenshots for validation errors:
----
Success notification:
-----

PP-13296 invite post controller

---

package-lock.json
package.json

We're currently blocked on upgrading `@sentry/node` and replacing the deprecated `csurf` package.
To resolve a vulnerability in the `cookie` subdependency of both these packages, I've added in an override. The overrided version 0.7.2 does not have any breaking changes [according to the changelog](https://github.com/jshttp/cookie/releases).

PP-13282: Add overrides for cookie subdependencies

---

app/controllers/simplified-account/settings/team-members/invite/invite.controller.js
app/controllers/simplified-account/settings/team-members/invite/invite.controller.test.js
app/views/simplified-account/settings/team-members/invite.njk

Context: If the invited user is already in the team or has been invited recently by a different user, an error message should be displayed. The content is taken from the existing error message but will be updated if necessary in a subsequent PR.
- if adminusers returns 412, display an error in the same pattern as validation errors.
- unit test for this scenario
For subsequent PRs
- error content update if necessary
Screenshot of error page:

PP-13296 handle user already in team error

---

app/assets/sass/application.scss
app/assets/sass/components/hint-and-body-width.scss
app/assets/sass/components/hint-text.scss
app/views/simplified-account/settings/email-notifications/collect-email-page.njk
app/views/simplified-account/settings/email-notifications/payment-confirmation-email-toggle.njk
app/views/simplified-account/settings/email-notifications/refund-email-toggle.njk

As per the designers [recommendation](https://payments-platform.atlassian.net/browse/PP-13135?focusedCommentId=58875), the hint text should be restricted to a width of 630px. 
Old view:
New view:

PP-13135: Restrict hint text length

---

app/views/payouts/list.njk
test/cypress/integration/payouts/payouts-list.cy.js

Payments into your bank accounts page only display the day & month (DD MON) of the payout date and we only support pagination to go back to previous months or years.
While adding some search boxes involves design and more work, we should at least display the year.
Changed dateformat to `D MMMM YYYY` to match other dateformat on page.

PP-13349 display year on payout pages

---

app/assets/sass/application.scss
app/assets/sass/components/fieldset-legend-width.scss
app/views/simplified-account/settings/team-members/change-permission.njk
app/views/simplified-account/settings/team-members/invite.njk
app/views/simplified-account/settings/team-members/remove-user.njk

Style changes to meet design requirements:
- Set maximum width for hint content for the radios for change permissions and invite user pages to 630px.
- Set heading max width for change permissions and remove user pages to 630px.
**Before**
______
______
**After**
_____

PP-13296 Set max width

---

app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.js
app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.test.js
app/simplified-account-routes.js
app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
app/views/simplified-account/settings/organisation-details/index.njk
test/cypress/integration/simplified-account/service-settings/organisation-details/organisation-details.cy.js
test/fixtures/roles.fixtures.js

- Add Cypress tests for organisation details simplified account settings
- Show back link on "edit organisation details" page when organisation details have already been set - since this requires navigating there from the index page
- Add role fixtures for use in Cypress tests - with full permissions for each role
View without organisation details set - no back link:
View with organisation details set - showing back link:

PP-13255 Organisation details Cypress tests

---

app/simplified-account-routes.js
app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
app/views/simplified-account/settings/organisation-details/index.njk

- Enforce only allowing viewing/editing organisation details in live environment when a service is live
- Add line width limit to content on organisation details pages

PP-13255 Enforce live account only for live services on org details, add line width limit

---

app/views/simplified-account/settings/email-notifications/templates.njk

As per the Figma design.
New view:

PP-13135: Move 'description' paragraph outside the tabs

---

app/assets/sass/components/multi-select.scss

- fix styling of the card brand and payment status drop down selectors

ZD-5983846 correctly align drop-down items

---

app/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
app/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.test.js
app/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.js
app/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
app/middleware/simplified-account/settings/default-view-decider.middleware.test.js
app/models/WorldpayTasks.class.js
app/paths.js
app/simplified-account-routes.js
app/views/simplified-account/settings/worldpay-details/credentials.njk
test/test-helpers/simplified-account/controllers/ControllerTestBuilder.class.js

Deal with validations. This PR does not deal with checking the creds against the Worldpay API and storing them in connector.
These should match the existing validations in the current [worldpay controller](https://github.com/alphagov/pay-selfservice/blob/master/app/controllers/credentials/worldpay.controller.js).

PP-13313: Validations for Worldpay credentials for a MOTO gateway account

---

app/utils/roles.js
app/utils/roles.test.js
app/views/simplified-account/settings/team-members/change-permission.njk
app/views/simplified-account/settings/team-members/invite.njk

- The following changes are made to the Change Permissions page and Invite user page:
- Fix a layout problem relating to hint text
- Make radio button labels clickable
- Add commas to role explanation text as indicated in design.
**Screenshot before fix, showing layout problem with the hint text for 'View only'**
-----
-----
**Screenshot for Change Permission (moto service)**
----
----
**Screenshot for Invite User (moto service)**
----
----
**Screenshot for Change Permission (non-moto service)**
----
----
**Screenshot for Invite User (non-moto service)**
----
----

PP-13297 clickable text, layout, and Oxford commas

---

app/browsered/multi-select.js
app/views/services/_service-switch.njk
test/cypress/integration/simplified-account/service-settings/stripe-details/company-number.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/director.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/vat-number.cy.js

- cypress tests for the following tasks:
- company number
- vat number
- service director
- small improvement to multi-select enhancement that refocuses the open button for the drop down when clicking the close button (maintains current position when navigating by keyboard)
- case typo in service switcher template (DSv5)
https://github.com/user-attachments/assets/0a509051-fccc-47db-a0a9-67f02c9e6378

PP-12444 simplified account stripe onboarding tasks cypress tests

---

app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
test/cypress/integration/simplified-account/service-settings/organisation-details/organisation-details.cy.js

- Add error summary to organisation details form
- update cypress tests to check for error summary

PP-13255 Add error summary to organisation details form

---

app/controllers/simplified-account/settings/card-types/card-types.controller.js
app/controllers/simplified-account/settings/card-types/card-types.controller.test.js
app/services/card-types.service.js
app/services/clients/connector.client.js
app/simplified-account-routes.js
app/utils/simplified-account/format/format-card-types.js
app/utils/simplified-account/format/format-card-types.test.js
app/views/simplified-account/settings/card-types/cardTypesCheckboxes.njk
app/views/simplified-account/settings/card-types/cardTypesList.njk
app/views/simplified-account/settings/card-types/index.njk
test/test-helpers/simplified-account/controllers/ControllerTestBuilder.class.js

- Get controller for simplified settings / card types
- As design stipulates that admin users should see checkboxes and non-admins should see a simple list, implement two methods for formatting the card types data and two child templates to slot into the parent card types page.
- Retain existing logic to disable checkbox for Maestro if the service doesn't have 3ds enabled.
- Update existing logic to provide hint to enable with Worldpay for American Express and UnionPay - this is only necessary if it's a Worldpay service.
For subsequent PRs:
- implement the post controller
**Screenshot for admin user**
**Screenshot for non-admin user**

PP-13312 Settings for card types get controller

---

package-lock.json
package.json

Changelog: https://github.com/expressjs/express/releases/tag/4.21.2
Addresses issue with `path-to-regexp` v0.1.10 (see https://github.com/advisories/GHSA-9wv6-86v2-598j). 
Dependabot cannot always automatically create updates where the security patch is for a subdependency. In this case [the update failed without giving a reason](https://github.com/alphagov/pay-selfservice/actions/runs/12281147991/job/34269296953).

PP-13422: Upgrade express to 4.21.2

---

app/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
app/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.test.js
app/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
app/middleware/simplified-account/simplified-account-strategy.middleware.js
app/models/GatewayAccount.class.js
app/models/WorldpayTasks.class.js
app/models/gateway-account-credential/Credential.class.js
app/models/gateway-account-credential/GatewayAccountCredential.class.js
app/models/gateway-account-credential/GatewayAccountCredentialUpdateRequest.class.js
app/models/gateway-account-credential/WorldpayCredential.class.js
app/paths.js
app/services/clients/connector.client.js
app/services/worldpay-details.service.js
app/simplified-account-routes.js

- Implement saving of credentials to Connector on form submission

PP-13313 Implement save credentials functionality in POST

---

app/assets/sass/components/api-keys.scss
app/controllers/simplified-account/settings/api-keys/api-keys.controller.js
app/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.js
app/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.test.js
app/paths.js
app/services/api-keys.service.js
app/simplified-account-routes.js
app/utils/simplified-account/settings/service-settings.js
app/views/simplified-account/settings/api-keys/api-key-name.njk
app/views/simplified-account/settings/api-keys/new-api-key-details.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js

Creating an API key consists of two pages: the "API key name" and "New API key" pages.
Validation of the name/description and cypress test will be done in the next PRs.
API key name page:
New API key page:

PP-12395: Create API key functionality

---

app/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.js
app/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.test.js
app/utils/simplified-account/settings/service-settings.js
app/views/simplified-account/settings/api-keys/api-key-name.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js

A description is not valid if it's empty or more than 50 chars. Given the text box has a maxLength of 50, the latter validation error can't occur in practice.

PP-12395: Validation when creating API key

---

app/controllers/simplified-account/settings/api-keys/api-keys.controller.js
app/controllers/simplified-account/settings/api-keys/api-keys.controller.test.js
app/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.js
app/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.test.js
app/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.test.js
app/controllers/simplified-account/settings/api-keys/validations.js
app/models/Token.class.js
app/paths.js
app/services/api-keys.service.js
app/simplified-account-routes.js
app/views/simplified-account/settings/api-keys/api-key-name.njk
app/views/simplified-account/settings/api-keys/index.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
test/cypress/stubs/api-keys-stubs.js

Changing the name uses the same view as the "API key name" view in https://github.com/alphagov/pay-selfservice/pull/4394

PP-12395: Change api key name

---

app/controllers/simplified-account/settings/api-keys/api-keys.controller.js
app/controllers/simplified-account/settings/api-keys/api-keys.controller.test.js
app/controllers/simplified-account/settings/api-keys/revoke/revoke.controller.js
app/controllers/simplified-account/settings/api-keys/revoke/revoke.controller.test.js
app/paths.js
app/services/api-keys.service.js
app/services/clients/public-auth.client.js
app/simplified-account-routes.js
app/views/simplified-account/settings/api-keys/index.njk
app/views/simplified-account/settings/api-keys/revoke.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js

The revoke key confirmation screen:
This PR does not include cypress tests, which will be in the next PR.

PP-12395: Revoke key functionality

---

src/views/simplified-account/settings/api-keys/revoke.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
test/cypress/stubs/api-keys-stubs.js

Cypress tests for https://github.com/alphagov/pay-selfservice/pull/4400

PP-12395: Cypress test for revoking api keys

---

src/controllers/simplified-account/settings/stripe-details/bank-details/bank-details.controller.js
src/controllers/simplified-account/settings/stripe-details/bank-details/bank-details.controller.test.js
src/controllers/simplified-account/settings/stripe-details/company-number/company-number.controller.js
src/controllers/simplified-account/settings/stripe-details/director/director.controller.js
src/controllers/simplified-account/settings/stripe-details/government-entity-document/government-entity-document.controller.js
src/controllers/simplified-account/settings/stripe-details/organisation-details/organisation-details-update.controller.js
src/controllers/simplified-account/settings/stripe-details/organisation-details/organisation-details.controller.js
src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-check-answers.controller.js
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.test.js
src/controllers/simplified-account/settings/stripe-details/vat-number/vat-number.controller.js
src/paths.js
src/services/stripe-details.service.js
src/simplified-account-routes.js
src/utils/simplified-account/settings/stripe-details/tasks.js
test/cypress/integration/simplified-account/service-settings/stripe-details/bank-details.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/director.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/responsible-person.cy.js
test/cypress/stubs/stripe-psp-stubs.js

- rename `/bank-account` path to `/bank-details` in stripe details settings
- prevent unhandled errors in stripe details controllers from being swallowed
- update cypress tests to account for additional stubbing

PP-12444 unswallow unhandled errors

---

README.md
dev-server.mjs
package.json

- add npm run command to start cypress server with inline source maps and hot reload enabled
- update `dev-server.mjs` to load cypress test .env
- update README with usage instructions

BAU add cypress dev server config

---

src/controllers/simplified-account/settings/api-keys/api-keys.controller.js
src/controllers/simplified-account/settings/api-keys/api-keys.controller.test.js
src/controllers/simplified-account/settings/api-keys/revoked-keys/revoked-keys.controller.js
src/controllers/simplified-account/settings/api-keys/revoked-keys/revoked-keys.controller.test.js
src/models/Token.class.js
src/paths.js
src/services/api-keys.service.js
src/simplified-account-routes.js
src/views/simplified-account/settings/api-keys/index.njk
src/views/simplified-account/settings/api-keys/revoked-keys.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js

If there revoked keys, show the "Show revoked API keys" button on the API keys landing page. If there no revoked keys, this button should not be shown.
Not covered in this PR:
* Cypress tests
* Returning a 404 if navigating directly to /simplified/service/{serviceId}/account/{type}/settings/api-keys/revoked when there are no revoked keys
If there no revoked keys, this "Show revoked API keys" button  should not be shown:
The "Revoked API keys" page:

PP-12395: Show revoked API keys page

---

.secrets.baseline
src/controllers/payment-types/get-index.controller.js
src/models/GatewayAccount.class.js
src/utils/simplified-account/format/format-card-types.js
src/utils/simplified-account/format/format-card-types.test.js
test/cypress/integration/settings/payment-types.cy.js

There's a discrepancy in the card types pages for old settings and simplified settings in relation to the Maestro cards. Maestro cards require a 3ds check so are only available for accounts where `requires3ds` is set to `true`. Maestro is not available on sandbox.
- fix old settings code - check if the `paymentProvider` is `sandbox` (rather than the account `type` which can only be `test` or `live`) to determine what message to display if Maestro is disabled. Correct Cypress tests accordingly.
- fix simplified settings code - add `requires3ds` to the `GatewayAccount` class so that it is available as `req.account.requires3ds` (previously this was `undefined`, causing the Maestro card type checkbox to be disabled incorrectly).
A Cypress test will be added in a separate PR to cover the …

PP-13312 Fix bugs in card types

---

src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.js
src/models/WorldpayTasks.class.js
src/paths.js
src/simplified-account-routes.js
src/views/simplified-account/settings/worldpay-details/flex-credentials.njk
src/views/simplified-account/settings/worldpay-details/index.njk

- Update one-off customer initiated credentials task to show for all Worldpay accounts
- add skeleton for 3ds flex credentials task for non-MOTO accounts
- currently has a basic task object, basic controller with GET endpoint, and nunjucks template for flex credentials form
Tasks for non-MOTO service:
3ds Flex Credentials form:

PP-12440 Worldpay Details Settings - one off card payments & 3ds flex credentials skeleton

---

src/controllers/simplified-account/settings/team-members/team-members.controller.test.js
src/controllers/simplified-account/settings/webhooks/create/create.controller.js
src/controllers/simplified-account/settings/webhooks/create/create.controller.test.js
src/controllers/simplified-account/settings/webhooks/webhooks.controller.test.js
src/simplified-account-routes.js
src/views/simplified-account/settings/webhooks/create.njk

- Update the create webhook page to match design
- Remove some duplicate lines that were spotted in other simplified settings tests.
- NB: This step is just to present the form as it appears on the design. Functionality to be implemented later. This page will also be used for updating existing webhooks, but this responsibility isn't implemented either.
For subsequent PRs:
- logic to handle form submission, including validation and saving the webhook.
- using this page for updating existing webhooks.

PP-13136 Create webhook page

---

src/controllers/payment-links/post-amount.controller.js
src/views/payment-links/amount.njk
test/cypress/integration/payment-links/create-payment-link.cy.js

Validation shown for when a payment is for less than 30p and the gateway account uses Stripe:

PP-13511: Validation for a fixed amount for a payment link

---

src/client-side/analytics.js

- `gtag` function was converted to arrow, losing access to arguments object. converted back to regular function

BAU fix GA setup bug

---

src/controllers/simplified-account/settings/webhooks/create/create.controller.js
src/controllers/simplified-account/settings/webhooks/create/create.controller.test.js
src/controllers/simplified-account/settings/webhooks/webhooks.controller.js
src/controllers/webhooks/webhooks.controller.js
src/services/clients/webhooks.client.js
src/utils/simplified-account/validation/webhook.schema.js
src/utils/simplified-account/validation/webhook.schema.test.js
src/views/simplified-account/settings/webhooks/create.njk

- Validation for create webhook
- Call pay-webhooks to create the webhook
- Handle validation errors from pay-webhooks (pay-webhooks validation includes a check against an allow list of domains).
NB Currently following webhook creation there is a redirect to the main webhooks page. Discussing with designers whether this is the right approach, could potentially direct to the webhook details page (which hasn't yet been added).
For subsequent PRs
- Cypress tests for main webhook page and create webhook page.
- Other webhook settings pages are subject of separate JIRA tickets.
**Screenshot 1. Callback url empty**
---
**Screenshot 2. Callback url non-https**
---
**Screenshot 3. Callback url has domain not in allow list (live accounts only)**
---
**Screenshot 4. Description empty**
--- …

PP-13136 Validate and create webhook

---

src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.test.js
src/paths.js
src/services/stripe-details.service.js
src/simplified-account-routes.js
src/views/simplified-account/settings/stripe-details/_task-list.njk
src/views/simplified-account/settings/stripe-details/index.njk
test/test-helpers/simplified-account/controllers/ControllerTestBuilder.class.js

- asynchronously retrieve stripe account data when clientside javascript is enabled, fall back to synchronous loading otherwise
_Screenshots if view has been modified:_
Notice the delay when clicking `Stripe details` and how long the page takes to load
https://github.com/user-attachments/assets/1c3b1351-575e-47c8-b01b-2d9020d4564e
Instant page load, additional data is loaded in when ready
https://github.com/user-attachments/assets/ec1fc4c8-99ef-4089-9419-3c1a56a1b3c1
Browser javascript disabled (page will auto refresh once spinner has loaded to request stripe data synchronously):
https://github.com/user-attachments/assets/45f72ef5-6e84-4d6e-8f97-ca0021276ff1
Error state when loading data async:
https://github.com/user-attachments/assets/c287beb2-a9f1-43f2-b048-3ff9ea7e77e1

BAU async stripe account data loading for simplified settings

---

src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.test.js
src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
src/models/GatewayAccount.class.js
src/models/WorldpayTasks.class.js
src/models/gateway-account-credential/Worldpay3dsFlexCredential.class.js
src/views/simplified-account/settings/worldpay-details/flex-credentials.njk
src/views/simplified-account/settings/worldpay-details/index.njk

- Display saved 3DS Flex credentials in completed task card & edit credentials form
- this omits the JWT Mac Key for security purposes
- updates Flex credentials task to show as "Cannot start yet" if Worldpay details are not set

PP-12440 Display saved 3DS flex credentials in settings

---

src/utils/simplified-account/settings/SettingsBuilder.class.js
src/utils/simplified-account/settings/service-settings.js

- tighten up validation on 'current' key in the SettingsBuilder
_Screenshots if view has been modified:_

BAU fix issue in settings navigation where two links could be 'active'

---

package-lock.json
package.json
test/cypress/stubs/api-keys-stubs.js

There was a breaking change to Run Amock which was intended to make this test work.  The desired behaviour for this test is "it should only match when no query string is present", that lead to a change where all query strings, headers and request bodies were treated in a stricter way than Mountebank (which Run Amock is based on) handles them.
As we're reverting that change this breaking change, this test needs to specify that it should only match when there is no query string, that's done by specifying `query: {}`.
Note - there was a bug in Run Amock which meant that this approach did not work, this is resolved in PR https://github.com/alphagov/pay-run-amock/pull/16
Related PRs:
The change in Run Amock: https://github.com/alphagov/pay-run-amock/pull/16
Updates to other projects: …

PP-13557: Specifying that it the stub should only match when there is no query string.

---

src/controllers/simplified-account/settings/webhooks/detail/detail.controller.js
src/controllers/simplified-account/settings/webhooks/webhooks.controller.js
src/paths.js
src/simplified-account-routes.js
src/views/simplified-account/settings/webhooks/detail.njk
src/views/simplified-account/settings/webhooks/index.njk

Set up initial outline for webhooks details view. This commit just sets up the basic view template and controller, and links them from the webhooks ndex page.
* Create detail controller
* Create detail view template
* Update paths
* Add route
* Update webhooks controller to link webhook summary to webhook detail.

PP-13521: Initial setup of webhooks detail view

---

src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.test.js
src/controllers/switch-psp/switch-tasks.service.js
src/controllers/switch-psp/verify-psp-integration.controller.js
src/middleware/error-handler.js
src/middleware/simplified-account/check-task-completion.middleware.js
src/middleware/simplified-account/index.js
src/middleware/simplified-account/settings/stripe-account-setup-strategy.middleware.js
src/middleware/simplified-account/settings/stripe-account-setup-strategy.middleware.test.js
src/middleware/simplified-account/simplified-account-strategy.middleware.js
src/middleware/simplified-account/simplified-account-strategy.middleware.test.js
src/models/GatewayAccount.class.js
src/models/GatewayAccount.class.test.js
src/models/StripeAccountSetup.class.js
src/models/credential-state.js
src/models/gateway-account-credential/GatewayAccountCredential.class.js
src/services/stripe-details.service.js
src/simplified-account-routes.js
src/utils/credentials.js
src/utils/nav-builder.js
src/utils/simplified-account/settings/stripe-details/tasks.js
src/utils/simplified-account/settings/stripe-details/tasks.test.js
test/cypress/integration/simplified-account/service-settings/stripe-details/bank-details.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/company-number.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/confirm-org-details.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/director.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/government-entity-document.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/responsible-person.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary.cy.js
test/cypress/integration/simplified-account/service-settings/stripe-details/vat-number.cy.js

- new 'enum' of credential states
- new connector stripe account setup strategy middleware
- remove call to connector from account strategy middleware for stripe account setup
- add stripe account strategy middleware to stripe details router
- stop mutating the gateway account model with stripe account setup progress
- move stripe account setup progress to a specific key on the request
- update gateway account model with class method for identifying a switching credential

PP-12427 switching credential logic

---

src/utils/simplified-account/validation/webhook.schema.js
src/utils/simplified-account/validation/webhook.schema.test.js
src/views/simplified-account/settings/webhooks/create.njk

Max length for webhook description was incorrectly set to 40 characters.
- Correct max webhook description length to 50 characters in template and schema.

PP-13136 Correct max webhook description length to 50 chars

---

src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
src/models/WorldpayTasks.class.js
src/models/gateway-account-credential/Credential.class.js
src/paths.js

This PR displays outstanding recurring payment credentials tasks on the Worldpay details page. The links don't link to anywhere valid yet.
Tasks shown where recurring payments are enabled:

PP-13261: Show recurring payment credentials tasks

---

src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
src/models/WorldpayTasks.class.js
test/cypress/integration/simplified-account/service-settings/worldpay-details/flex-credentials.cy.js
test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js

As per current functionality, the ability to configure 3ds flex creds isn't dependent on already configuring one off customer initiated creds.

PP-13261: Configure 3ds flex credentials

---

src/assets/sass/components/service-settings.scss
src/controllers/simplified-account/settings/webhooks/detail/detail.controller.js
src/controllers/simplified-account/settings/webhooks/detail/detail.controller.test.js
src/controllers/simplified-account/settings/webhooks/webhooks.controller.test.js
src/views/simplified-account/settings/webhooks/detail.njk
src/views/simplified-account/settings/webhooks/index.njk

- Webhook detail controller: Get the webhook and signing secret and pass to the template
- Webhook detail template: Display the webhook details and signing secret as per design
- Add some scss to position the status tag correctly next to the webhook detail heading
- Unit test the detail controller
To do in subsequent PRs:
- Add the 'Events' table which shows the events that have been sent as webhook messages. The design for this is being reviewed so this section will be implemented later, with corresponding updates to the unit tests.

Pp 13521 webhook details page

---

src/controllers/transactions/transaction-detail.controller.js
src/controllers/transactions/transaction-detail.controller.test.js
src/services/transaction.service.js
src/utils/transaction-view.js
src/utils/transaction-view.test.js
src/views/transaction-detail/_details.njk
test/cypress/integration/transactions/transaction-details.cy.js
test/fixtures/ledger-transaction.fixtures.js

- Updating the transaction details controller to append the following
- Add 3DS secure information about the transaction.
- Add information about corporate exemptions.
- If corporate exemptions are disabled on the gateway, then we only show information older transactions when a corporate exemption has been requested.
- If corporate exemptions are enabled, then it will show information at all times about the transaction.
- It will show `not requested`, if a corporate exemption was not not requested for the current transaction.
- This PR is only for updating the controllers.
- A future PR will add the fields to the Nunjucks file to display the fields correctly.

PP-13335 PP-13335 Transactions details page - display corporate exemptions data.

---

test/pact/ledger-client/ledger-get-transaction-details.pact.test.js

Add PACT tests between selfservice and ledger to test for 3D secure and corporate exemption data

PP-13428 add ledger pact tests

---

jsconfig.json
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/add-flex-credentials.controller.js
src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/add-worldpay-credentials.controller.js
src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/make-test-payment.controller.js
src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/switch-to-worldpay.controller.js
src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/switch-to-worldpay.controller.test.js
src/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
src/middleware/restrict-to-switching-account.js
src/middleware/simplified-account/settings/stripe-account-setup-strategy.middleware.js
src/models/ChargeRequest.class.js
src/models/GatewayAccount.class.js
src/models/GatewayAccount.class.test.js
src/models/Service.class.js
src/models/WorldpayTasks.class.js
src/models/gateway-account-credential/GatewayAccountCredentialUpdateRequest.class.js
src/models/gateway-account/GatewayAccountSwitchPaymentProviderRequest.class.js
src/paths.js
src/services/charge.service.js
src/services/clients/connector.client.js
src/services/gateway-accounts.service.js
src/services/worldpay-details.service.js
src/simplified-account-routes.js
src/utils/simplified-account/validation/worldpay/one-off-customer-initiated.schema.js
src/utils/verify-psp-integration.js
src/views/simplified-account/settings/switch-psp/switch-to-worldpay/add-worldpay-credentials.njk
src/views/simplified-account/settings/switch-psp/switch-to-worldpay/index.njk
src/views/simplified-account/settings/switch-psp/switch-to-worldpay/make-a-test-payment.njk
test/cypress/integration/simplified-account/service-settings/switch-psp/switch-to-worldpay/switch-to-worldpay.cy.js

- new views and controllers for handling switch to worldpay tasks for a moto service
- new `ChargeRequest` class
- new `GatewayAccountSwitchPaymentProviderRequest` class
- extend `WorldpayTasks`: add `makeALivePayment` (verify that worldpay credentials are working)
- update `GatewayAccountCredentialUpdateRequest`, enable credential state change
- extract one off customer initiated credentials validation into reusable schema
this PR requires a [corresponding change in connector](https://github.com/alphagov/pay-connector/pull/5722) in order to behave correctly
additionally, our stubbing mechanism for worldpay orders does not account for how we currently handle moto services. 
in production a gateway account will have a MOTO specific merchant code that worldpay will recognise and determine …

PP-12427 switch to worldpay (MOTO service) impl

---

test/cypress/integration/simplified-account/service-settings/card-payments/index.cy.js
test/cypress/integration/simplified-account/service-settings/card-payments/updates.cy.js

Add cypress tests to check:
* the navigation highlight is correct
* the change links go to the correct urls
* can navigate to detail page and return

PP-12416: Add more cypress tests to card-payments

---

src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.js
src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.test.js
src/models/WorldpayTasks.class.js
src/models/gateway-account-credential/Credential.class.js
src/views/simplified-account/settings/worldpay-details/index.njk

Enable the worldpay details page controller and view show the one-off and recurring credentials correctly.
Screenshot of notification banner when either CIT or MIT creds were the last task to complete:
Screenshot when re-visiting Worldpay details page:
I've also verified that one-off card payments creds still work as expected:

PP-13261: Recurring creds on the worldpay details page

---

src/views/simplified-account/settings/settings-layout.njk

- adjust the skiplink component to target the main content of each settings page
skiplink targets left side nav
https://github.com/user-attachments/assets/1b13720d-ee3d-4256-a21a-184e5c78a687
skiplink targets main settings content
https://github.com/user-attachments/assets/b1d53332-7cb8-420f-a822-d880fd3c2d74

PP-13613 move skip link target for settings pages

---

src/controllers/simplified-account/settings/webhooks/detail/detail.controller.js
src/controllers/simplified-account/settings/webhooks/detail/detail.controller.test.js
src/paths.js
src/views/simplified-account/settings/webhooks/_message_status.njk
src/views/simplified-account/settings/webhooks/detail.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-detail.cy.js

Update Webhook details page:
- Add Webhook summary card
- Add Webhook secret
- Add events to the webhooks details page.
The correct information is displayed, including links to the event details page, however the exact formation will require more work.
Pagination, filtering and test are not part of this PR.

Pp 13521: Update Webhooks details page

---

src/controllers/simplified-account/settings/webhooks/detail/detail.controller.js
src/views/simplified-account/settings/webhooks/detail.njk

Implement pagination control to the webhook detail view.
We have done this by building the pagination object in the controller and passing that the nunjucks view. 
Manipulating the page query parameters to invalid values is handled by redirecting to the default base url for the webhook detail view.

PP-13521: Implement pagination for webhook detail messages

---

package-lock.json
package.json
src/controllers/simplified-account/settings/webhooks/detail/detail.controller.js
src/controllers/simplified-account/settings/webhooks/detail/detail.controller.test.js
src/services/clients/webhooks.client.js
src/views/simplified-account/settings/webhooks/detail.njk

Worked on with @kerrr, now that the page is mostly complete we are submitting for peer review.
This PR contains these changes:
- Refactor webhook detail controller to improve readability
- Fix webhook event date formatting
- Update controller unit test
Still to do:
- The page does not perfectly match the design. The design indicates a different colour coding for the delivery status tags than what services are currently seeing in the old settings; the design also shows a wider table than will currently fit in the standardised simplified settings layout. These issues require some discussion then can be resolved in a subsequent PR.
- Cypress tests will be done in a subsequent PR
- The event detail page has not yet been created so the 'view details' links for each of the webhook events don't …

PP-13521 tidy up detail controller and template and update unit test

---

src/assets/sass/components/my-services.scss
src/controllers/simplified-account/services/my-services.controller.js
src/views/simplified-account/services/my-services/_service-section.njk

- in the case of a service with only test accounts without provider duplication, return one
- don't provide live gateway link formatting to test account links

PP-13525 return a test account if only test accounts exist

---

src/views/simplified-account/settings/card-payments/index.njk

Add a sub heading and paragraph for the billing address section of the card payments settings page to match design specification.

PP-12416: Add billing address sub heading

---

src/controllers/simplified-account/services/my-services.controller.test.js

- unit tests for the `my-services` controller. Given this controller is temporary, I've covered off all the important cases around filtering, prioritisation and flag setting

PP-13525 add unit tests for my-services.controller

---

src/views/simplified-account/settings/team-members/index.njk

Accessibility testing identified that we aren't providing sufficient context to screenreader users to indicate the function of the 'change' and 'remove' links on the team members settings pages.
- Add the email address of the relevant team member as visually hidden text to these links so it's clear which team member the link relates to

PP-13612 Add visually hidden text to links

---

src/views/simplified-account/settings/webhooks/toggle-status.njk
test/cypress/integration/simplified-account/service-settings/webhooks/toggle-webhook-status.cy.js

- update headings to show webhook description instead of callback url

PP-13522 Update headings on toggle webhook status pages

---

src/views/simplified-account/settings/team-members/index.njk

- correct role headings on team members page from h3 to h2 to avoid skipping heading levels which can cause confusion for some users.

PP-13612 Change h3 to h2

---

src/controllers/simplified-account/settings/webhooks/event/event.controller.js
src/controllers/simplified-account/settings/webhooks/webhooks.controller.js
src/simplified-account-routes.js
src/views/simplified-account/settings/webhooks/event.njk

Add the page showing detail for an individual webhook event. This is linked from the webhooks detail page showing all events.
Tests are not included in this PR.

PP-13521: Add webhook event page

---

src/controllers/simplified-account/settings/team-members/invite/invite.controller.js
src/views/simplified-account/settings/team-members/invite.njk

- remove ids from radio buttons for setting permission on the invite team member page so that the ids are generated automatically, which ensures that the validation error link points to the first radio button.
- fix order of validation error messages to match the order the elements appear in the form
https://github.com/user-attachments/assets/285f59c3-7731-49de-ba11-43aad9a3dcd9

PP-13629 Correct select permission error link

---

src/views/simplified-account/settings/card-payments/index.njk

On the ‘Card payments' screen heading level 2 (H2) is skipped. ‘Card payments’ is h1 and then ‘Digital wallets’ is h2.
- correct 'Digital wallets' heading to h2

PP-13625 Correct Digital Wallets heading to h2

---

src/controllers/simplified-account/settings/card-payments/card-payments.controller.test.js
src/controllers/simplified-account/settings/card-payments/google-pay.controller.js
src/controllers/simplified-account/settings/card-payments/google-pay.controller.test.js
src/controllers/simplified-account/settings/card-payments/moto-security/hide-card-number.controller.test.js
src/controllers/simplified-account/settings/card-payments/moto-security/hide-card-security-code.controller.test.js
src/views/simplified-account/services/my-services/_service-section.njk

- add unit tests for mask card number and security code settings controllers
- update google pay controller test to include worldpay specific google pay merchant id logic
- remove MOTO UI flag from my services view

PP-13354 unit test moto security controllers

---

src/controllers/simplified-account/settings/card-payments/card-payments.controller.js
src/controllers/simplified-account/settings/card-payments/card-payments.controller.test.js

- fixes a small issue where in some cases a non-worldpay service could not update the google pay setting without completing the onboarding steps
- ensure only worldpay services are restricted from modifying this setting prior to setting credentials

PP-13354 fix google pay access bug

---

src/controllers/simplified-account/settings/team-members/invite/invite.controller.test.js
src/controllers/simplified-account/settings/team-members/remove-user/remove-user.controller.test.js

- Refactor remove user controller test to use ControllerTestBuilder
- also: minor refactor to invite user controller test to avoid using multiple stubs for same method

PP-13356 Use ControllerTestBuilder in remove user test

---

src/assets/sass/components/navigation.scss
src/assets/sass/components/service-settings.scss
src/views/includes/phase-banner.njk
src/views/simplified-account/settings/card-payments/index.njk
src/views/simplified-account/settings/organisation-details/index.njk
test/cypress/integration/agreements/agreements.cy.js
test/cypress/integration/settings/allow-apple-pay.cy.js
test/cypress/integration/webhooks/webhooks.cy.js
test/ui/navigation.ui.test.js

- update the service navigation to use the design system `service navigation` component
- tidy up the service settings navigation menu to better align with the design system
- a11y: improve hover and focus states of links
- correct typos and link states
Screenshot of Simplified Account Settings:
- Simplified Account Settings is the active service navigation element
- Service name is the active service settings navigation element
- Organisation details is being `hovered` over
Screenshot of Simplified Account Settings:
- Simplified Account Settings is the active service navigation element
- Active text is now bold
- Active indicator is now blue
- Nav target sizes increased 
- Service name is the active service settings navigation element
- Active indicator is slightly thicker to match …

PP-13356 use design system service nav

---

src/views/simplified-account/settings/card-payments/index.njk

On the ‘Card payments' screen heading level 2 (H2) is skipped. ‘Card payments’ is h1 and then ‘Billing address’ is h3.
- change h3 to h2 for Billing address heading.

PP-13779 - Correct h3 to h2 on card payments page

---

src/views/simplified-account/settings/webhooks/event.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-event.cy.js

Update the webhook event detail page to show a json representation of the resource from the event, in a design system detail component. This is to match the UI  design.
Update the Cypress test for webhook events details page to check for the event body detail.
Update the table showing delivery attempts for webhook events, so that when there is no status code we do not leave a blank cell. This is to improve accessability.

PP-13521: Show webhook event resource

---

src/views/simplified-account/settings/webhooks/event.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-event.cy.js

Minor update to Webhook event page title to match design.
While most pages insert the same value as the H1 heading into the start of the standardized title, this page should be:
```
[Event name] event details - Settings - [Service name] - GOV.UK Pay
```

PP-13521: Update webhook event page title

---

src/controllers/simplified-account/settings/stripe-details/director/director.controller.js
src/controllers/simplified-account/settings/stripe-details/director/director.controller.test.js
src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.js
src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.test.js
src/utils/simplified-account/format/format-validation-errors.js
src/utils/simplified-account/validation/stripe-person.schema.js

- when a validation error is returned for the `dob` component where the error is not specific to an individual field within said component, ensure that the error summary links to the first field (`dobDay`)
- tidy up the `dob` custom validations on the stripe person schema
https://github.com/user-attachments/assets/cdaab9dc-3727-41dc-b58e-3fe32ad406d3

PP-13763 `dob` form validation cont

---

src/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.js
src/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.test.js
src/views/simplified-account/settings/api-keys/api-key-name.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js

The ‘API key name’ field is not populated with the previous saved name when the user selects ‘Change name' from the 'API keys’ page. 
- prepopulate the api key name field with the saved value
In the screenshots below the original value is 'my original name' and this is shown when the user clicks on 'Change name'.

PP-13624 Prepopulate api key name field

---

src/views/simplified-account/settings/organisation-details/_edit-organisation-details-address.njk
src/views/simplified-account/settings/organisation-details/_edit-organisation-details-name.njk
src/views/simplified-account/settings/stripe-details/partials/_stripe_person_dob.njk
src/views/simplified-account/settings/stripe-details/responsible-person/contact-details.njk
src/views/simplified-account/settings/stripe-details/responsible-person/home-address.njk
src/views/simplified-account/settings/stripe-details/responsible-person/index.njk

In some cases, particularly when we make use of partials to put together a complete form, we mix `autocomplete` attributes that do not have a `section-*` token with attributes that do have a `section-*` token. This places them in different autofill scopes, indicating they do not refer to the same subject, which may hinder browsers from filling in complete and consistent information.
Remove all the `section-*` tokens. They are only useful when there’s a form that asks for information about two different subjects (for example, two different people) and we do not seem to do that.
Also add a missing `autocomplete="organization"` attribute.

BAU — Remove section-* tokens from autocomplete attributes

---

src/views/simplified-account/settings/webhooks/event.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-event.cy.js

https://www.w3.org/WAI/WCAG22/Techniques/css/C7 states:
"The objective of this technique is to supplement the link text by adding additional text that describes the unique function of the link"
Therefore, add the hidden text "GOV.UK Payment ID" before the transaction id [link] for a screen reader to read.

PP-13817: Add visually hidden text to GOV.UK Payment ID link

---

src/utils/nav-builder.js

- there was a bug where the "agreements" tab in the nav bar would not show when viewing simplified settings
- this fixes the bug
before (link showing on agreements page):
before (link not showing on simplified settings):
after (link showing on simplified settings page):

PP-13856 Ensure link to agreements is shown when viewing simplified settings

---

src/views/simplified-account/settings/_settings-navigation.njk

Add aria labels for navigation:
* add aria-current page to the `<a>` tag for the active page.
* add aria-labelledby to the `<nav>` tag, linking to a new `<h2>` hidden navigation heading.
* demoted the previous `<h2>` section headings to `<h3>`

PP-13616: Add ARIA labels for settings navigation

---

src/views/simplified-account/settings/webhooks/event.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-event.cy.js

The screenreader won't read out the text within the span tag if it's outside the anchor tag.
See [jira comment](https://payments-platform.atlassian.net/browse/PP-13817?focusedCommentId=61862).

PP-13817: Place span tag within the anchor tag

---

src/assets/sass/components/service-settings.scss
src/views/simplified-account/settings/settings-layout.njk

Context: H1 'Change permission for [email address]' does not adjust to screen size so some of the characters cannot be seen without horizontal scrolling. The same applies to the remove user page. Additionally, the validation error summary (and form error message will also extend outside of the boundary of the error box when the screen is resized. This problem also applies to webhooks where a 50-character webhook description may be used in the heading.
- apply `word break: break-word;` across the simplified settings pane
**change permissions before**
-----
-----
**change permissions after**
-----
-----
**remove user after**
-----

PP-13760 Fix headers and error messages not wrapping when screen resized

---

src/assets/sass/components/service-settings.scss
src/views/simplified-account/settings/webhooks/event.njk

When showing the JSON dump of a webhook event the `<pre><code>` block can distort the usual layout because it is too wide.
This has been resolved by adding using css `overflow: scroll`

PP-13821: Fix wide pre/code display issues

---

src/utils/simplified-account/settings/service-settings.js

In the case of a service that has a live worldpay gateway and a test worldpay gateway and NO sandbox account (not a configuration we expect), worldpay details are not accessible for the test gateway. 
worldpay details should always be accessible, regardless of test or live mode.

BAU always show worldpay details

---

.secrets.baseline
src/middleware/simplified-account/simplified-settings-redirect.middleware.js
src/routes.js
src/services/gateway-accounts.service.js
test/cypress/integration/demo-payment/mock-cards-stripe.cy.js
test/cypress/integration/manage-team-members/edit-permissions.cy.js
test/cypress/integration/manage-team-members/manage-team-members.cy.js
test/cypress/integration/settings/allow-apple-pay.cy.js
test/cypress/integration/settings/allow-google-pay.cy.js
test/cypress/integration/settings/api-keys.cy.js
test/cypress/integration/settings/default-billing-address-country.cy.js
test/cypress/integration/settings/email-notifications.cy.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.js
test/cypress/integration/settings/payment-types.cy.js
test/cypress/integration/settings/switch-psp.cy.js
test/cypress/integration/settings/verify-psp-integration.cy.js
test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
test/cypress/integration/settings/your-psp.cy.js
test/cypress/integration/stripe-setup/bank-details.cy.js
test/cypress/integration/stripe-setup/check-org-details.cy.js
test/cypress/integration/stripe-setup/company-number.cy.js
test/cypress/integration/stripe-setup/director.cy.js
test/cypress/integration/stripe-setup/government-entity-document.cy.js
test/cypress/integration/stripe-setup/responsible-person.cy.js
test/cypress/integration/stripe-setup/update-org-details.cy.js
test/cypress/integration/stripe-setup/vat-number.cy.js
test/cypress/integration/switch-psp/organisation-url.cy.js
test/cypress/integration/webhooks/webhooks.cy.js

- if a degatewayed user attempts to access an old settings route (e.g. in case of having them bookmarked) this will redirect them to the settings index page
- attempts to redirect to the correct account type based on the accessed setting
- for service level settings, redirect to live if a live account exists, otherwise redirect to test
- logs redirects so we can easily determine if the old settings routes are still accessed

PP-13829 Redirect to simplified settings index page from old settings

---

src/assets/sass/components/service-settings.scss
src/views/simplified-account/settings/webhooks/detail.njk
src/views/simplified-account/settings/webhooks/index.njk
test/cypress/integration/simplified-account/service-settings/webhooks/webhook-detail.cy.js

- css override classes for handling summary cards with tags
_Screenshots if view has been modified:_

BAU webhooks card and heading layout tweaks

---

src/views/transaction-detail/index.njk
src/views/transactions/index.njk
src/views/transactions/timezone-banner.njk
test/cypress/integration/all-service-transactions/all-service-transactions.cy.js
test/cypress/integration/transactions/transaction-details.cy.js
test/cypress/integration/transactions/transaction-list-pagination.cy.js

- add timezone notification banner for timezone guidance to transactions list page, transactions for all services and transaction details page

PP-13825 Admin tool timezone notification banner

---

src/controllers/simplified-account/services/my-services.controller.js
src/controllers/simplified-account/services/my-services.controller.test.js
src/models/GatewayAccount.class.js

- this fixes a bug in the my services view where services can still be linked to disabled gateway accounts, however these will not be returned by Connector when querying by service external ID & account type, and so should not be viewable

PP-13525 Fix my services view to not show disabled gateway accounts

---

src/views/privacy/privacy.njk

In our privacy policy, update the link to Worldpay’s privacy policy from the current URL (which no longer exists) to the new [Worldpay Privacy Center](https://privacy.worldpay.com/policies/en).

PP-13619 Fix Worldpay privacy policy link

---

.github/PULL_REQUEST_TEMPLATE.md
cypress.config.js
package-lock.json
package.json
src/views/includes/degateway-banner.njk
src/views/macro/breadcrumbs.njk
src/views/macro/spinner.njk
test/cypress/integration/simplified-account/service-settings/service-name/service-name.cy.js
test/cypress/support/index.js

PP-13879
- add `cypress-axe`, `axe-core` and `wick-a11y` dev dependencies
- enable accessibility tasks in cypress configuration
- add cypress convenience command for running accessibility checks
- configures target wcag specs and by default excludes any issues re `.govuk-skip-link`
- update service name setting cypress test to demo functionality
- fix first pass accessibility issues re breadcrumb and degateway banner
_Steps to test or reproduce_
> [!IMPORTANT]
> Complete this checklist when adding/modifying nunjucks templates
<details>
<summary>checklist</summary>
</details>
> [!NOTE]
> Include mobile and desktop variants, **highlight**(`#ff0000`) changes to existing views to help reviewers

PP-13879 introduce accessibility checks to cypress tests

---

.secrets.baseline
src/utils/transaction-view.js
src/utils/transaction-view.test.js
test/cypress/integration/transactions/transaction-search.cy.js

With this change, we are fixing a bug for which disputed amounts are shown in the admin tool always as negative numbers.
The logic will now consider also the state of the dispute and present the value as positive when the dispute has been won by the service.
Further information in Jira.
https://payments-platform.atlassian.net/browse/PP-13622

PP-13622 Fix incorrect negation of value in the admin tool search when a dispute is won

---

src/models/TransactionEvent.class.js
src/models/TransactionEvent.class.test.js
test/cypress/integration/transactions/transaction-details.cy.js

With this change, we are fixing the display of the transaction details page
where won disputes were incorrectly displayed as negative amounts.

PP-13622 Fix sign for won dispute amount in details page

---

src/views/simplified-account/settings/_settings-navigation.njk
src/views/simplified-account/settings/api-keys/index.njk
src/views/simplified-account/settings/api-keys/partials/_api_key_name_form.njk
src/views/simplified-account/settings/api-keys/revoke/index.njk
test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
test/cypress/integration/simplified-account/service-settings/card-payments/index.cy.js
test/cypress/integration/simplified-account/service-settings/card-payments/updates.cy.js

PP-13989
- add classes & IDs to elements on the API keys settings so these can be used in end to end tests

PP-13989 Add classes & IDs for end to end test compatibility

---

package-lock.json
package.json

New version of pay-js-metrics, using Node 22. Bumping self-service so it doesn't get left behind.

PP-13985: Bump pay-js-metrics

---

src/controllers/feedback/get-index.controller.js
src/controllers/feedback/post-index.controller.js
src/views/feedback/index.njk

With this change, we are fixing a minor issue with an internal feedback form so that service admins cannot replace the email address when sending feedback.
Further information in Jira.
https://payments-platform.atlassian.net/browse/PP-14020

PP-14020 Fix feedback form so that email cannot be replaced

---

src/assets/sass/components/my-profile.scss
src/views/team-members/team-member-profile.njk
test/cypress/integration/user/my-profile.cy.js

PP-14067
- show link to add a mobile number in `/my-profile` if no mobile number is set
<details>
<summary>checklist</summary>
</details>
> [!NOTE]
> Include mobile and desktop variants, **highlight**(`#ff0000`) changes to existing views to help reviewers

PP-14067 Add link to set mobile number if no number is set

---

src/utils/simplified-account/validation/worldpay/validations.schema.js
src/utils/simplified-account/validation/worldpay/validations.schema.test.js

With this change, we are updating the merchant code validation 
in order to allow merchant codes ending with MOTONI.
https://govuk.zendesk.com/agent/tickets/6128034
Note that I have included changes introduced by `npx prettier` 
which are just style related changes and can be ignored. 
I have commented in the code the changes that matter for this PR.
Next time, I will split the change in two commits or two PRs.

ZD-6128034 Update merchant code validation

---

.secrets.baseline
cypress.config.js
package.json
test/cypress/integration/rebrand/rebrand-header-footer.cy.rebrand.js

- Updating the Cypress tests to handle rebranding.
- This approach is taken from `pay-frontend` where it is already working.
- We now need 2 Cypress test suites temporarily until the new branding is live
- Main test suite
- Rebranding flag ENABLE_REBRAND is undefined.
- Standard Cypress tests with the current branding.
- Custom branding tests.
- These are run with
- `npm run cypress:server`
- `npm run cypress:test`
- Rebranding test suite
- Rebranding flag ENABLE_REBRAND = true
- Want to run the test to check the rebranding
- I.e. Check that the header and footer has the new CSS styling.
- This is a new test that is only run when ENABLE_FLAG=true.
- Custom branding tests
- These tests should work whether the ENABLE_REBRAND is true or false/undefined.
- These are run with - `npm run …

PP-14158 - Updating the Cypress tests to test rebranding.

---

package.json
test/cypress/integration/errors/errors.cy.js
test/cypress/integration/rebrand/errors.cy.rebrand.js

PP-14265
- Create separate tests to check the branding for error pages depending on the ENABLE_REBRAND flag.
- Update the rebrand test suite to run the new branding test for error pages.

PP-14265 Add tests to error pages to check branding

---

src/views/simplified-account/services/dashboard/partials/_links.njk
src/views/simplified-account/services/demo-payment/edit/update-payment-details.njk
src/views/simplified-account/services/demo-payment/index.njk
src/views/simplified-account/services/demo-payment/mock-card-number.njk
test/cypress/integration/make-a-demo-payment/make-a-demo-payment.cy.js
test/cypress/integration/make-a-demo-payment/mock-card-numbers.cy.js

- replace references to 'demo' with 'test'
- update payment description hint text
- change order of content on mock card number view
PP-14191

PP-14191 implement design review comments

---

esbuild.config.mjs

- Update the favicon to show the new branding
- It was showing the old branding colours (black and white) and now it shows the new one(blue and white)
Before:
After:

PP-14264 Update favicon to show new brand colours

---

src/controllers/simplified-account/services/dashboard/dashboard.controller.ts
src/controllers/test-with-your-users/create.controller.js
src/controllers/test-with-your-users/disable.controller.js
src/controllers/test-with-your-users/index.controller.js
src/controllers/test-with-your-users/links.controller.js
src/controllers/test-with-your-users/submit.controller.js
src/paths.js
src/routes.js
src/simplified-account-routes.js
src/views/dashboard/demo-service/confirm.njk
src/views/dashboard/demo-service/create.njk
src/views/dashboard/demo-service/index.njk
test/cypress/integration/test-with-your-users/create-prototype-link.cy.js
test/cypress/integration/test-with-your-users/prototype-links.cy.js
test/cypress/integration/test-with-your-users/test-with-your-users.cy.js

PP-14193
- move `test-with-your-users` pages to service-level routes
- update associated controllers to use the service model
Controllers will be re-written in typescript in later PRs, this allows them to be re-written one by one on the new routes 
N/A - views should not have changed
Redo of #4630

PP-14193 Move prototypes to service routes

---

esbuild.config.mjs

- Changing the favicon has led to some flashing between navigating to different links and has broken the fonts
- This PR reverts the change made in https://github.com/alphagov/pay-selfservice/commit/8bda217b923661d0b0b1469eb85397cfa2b059f8

 PP-14264 revert favicon change

---

src/views/transactions/filter.njk

Remove superfluous and `legend`-less `fieldset` for card brand form controls on transactions page.
On the same page, WAVE complains that the ‘Card brand’ and ‘Payment status’ `label` elements are orphans because they reference `button` elements after the JavaScript enhances the select to a multi-select. However, the HTML standard says it is valid for a `label` element to reference a `button` element. Add Nunjucks comments clarifying this.

PP-14241 Remove superfluous fieldset on transactions page

---

src/controllers/simplified-account/services/test-with-your-users/index.controller.ts
src/controllers/simplified-account/services/test-with-your-users/links.controller.ts
src/views/simplified-account/services/service-layout.njk
src/views/simplified-account/services/test-with-your-users/index.njk
src/views/simplified-account/services/test-with-your-users/partials/_mock-card-numbers.njk
src/views/simplified-account/services/test-with-your-users/partials/_payment-links-list.njk

PP-14193
- migrate index + payment links pages in `test-with-your-users` journey to new service layout

PP-14193 Use service layout for test-with-your-users index and payment links pages

---

src/assets/sass/application.scss
src/assets/sass/components/url-preview.scss
src/client-side/input-confirm.js
src/views/simplified-account/services/payment-links/create/index.njk

[PP-14331](https://payments-platform.atlassian.net/browse/PP-14331)
- update web address preview as per new design, when creating payment links
- long text wraps to new line
- navigate to create a (test) payment link in new service navigation
><img width="661" height="332" alt="Screenshot 2025-08-13 at 11 37 30" src="https://github.com/user-attachments/assets/e7b78194-4a6d-4503-af28-970d0a060d2c" />
------------
><img width="667" height="191" alt="Screenshot 2025-08-13 at 11 37 59" src="https://github.com/user-attachments/assets/f09b88d4-8fdd-4ef8-8c93-fddc39676628" />
[PP-14331]: https://payments-platform.atlassian.net/browse/PP-14331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-14331 Restyle web address widget for new payment link

---

src/controllers/simplified-account/services/payment-links/create/payment-link-information.controller.test.ts
src/controllers/simplified-account/services/payment-links/create/payment-link-information.controller.ts

PP-**[14384]**
Bug fix for language selection during payment link creation journey.
If the user starts the creation of a payment link in Welsh, then going back to 
the information page should not drop that selection.
- Update the service in the settings so that there is a Welsh version for the service name (optional: see notes below)
- Create a payment link in Welsh
- note that the information page does not show a screenshot at the bottom of the page
- Enter a title for the payment link
- note that the web address widget is using a URL containing the Welsh version of the service name
- Continue to the reference page
- no need to add anything here
- Click Back (at the top left) to go back to the information page
- you are back on the information page
- the language setting is still right …

PP-14384 fix bug with language selection

---

src/views/simplified-account/services/payment-links/partials/forms/_payment-link-amount.njk
src/views/simplified-account/services/payment-links/partials/forms/_payment-link-reference.njk

[PP-**14352**](https://payments-platform.atlassian.net/browse/PP-14352)
With this change, we are changing a couple of components from govukCharacterCount to the simpler govukInput so that we stop showing the number of characters remaining when the user is typing the reference name or the hint for the payment amount.
Further information in Jira.
https://payments-platform.atlassian.net/browse/PP-14352
* start the payment link creation journey
* enter a title
* continue to the reference page
* check the radios items
<details>
<summary>checklist</summary>
- no changes
</details>

PP-14352 Improve UI for payment link creation journey - Remove character count

---

src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.test.ts
src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.ts

PP-**[14438](https://payments-platform.atlassian.net/browse/PP-14438)**
With this change, we are improving the success banner at payment link
creation, so that it displays an additional message with a link to test the
newly created payment link if the payment link has been created in a test
service or for a live service in sandbox mode.
No message aside from the banner title will be displayed if the service is
live and in normal mode.
Further information in Jira.
https://payments-platform.atlassian.net/browse/PP-14438
- start a payment link creation journey
- get to the review page
- confirm the creation of the payment link
- check that the success banner is appropriate for the type and mode of the account as follows
- for a test account: "You can test your payment link."
- for a live …

PP-14438 Improve payment link creation success banner

---

src/views/simplified-account/services/test-with-your-users/confirm.njk
src/views/simplified-account/services/test-with-your-users/create.njk
src/views/simplified-account/services/test-with-your-users/index.njk
src/views/simplified-account/services/test-with-your-users/links.njk

PP-14193
- fix layout for long payment link descriptions & URLs
- format nunjucks files with prettier

PP-14193 Fix text overflow for long descriptions & URLs

---

src/views/simplified-account/services/payment-links/partials/_index-admin.njk

- fix text overflow in payment link card titke
before:
after:

BAU Fix text overflow in payment link card title

---

src/views/simplified-account/home/my-services/_services.njk
src/views/simplified-account/home/my-services/_side-bar-links.njk

PP-**[14457](https://payments-platform.atlassian.net/browse/PP-14457)**
With this change, we are fixing the names of services listed in the new My services page as well as links to reach the page for All transactions so that they are set as headings, in line with the WCAG review performed by our designer.
- log on to Selfservice
- visit /my-services
- inspect the rendered HTML code for the service names and the links in the right hand side
- check that they are rendered as headings, H2 and H3, respectively

PP-14457 Fix headings for accessibility

---

src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.test.js
src/controllers/simplified-account/settings/stripe-details/stripe-details.controller.ts
src/services/stripe-details.service.ts
src/views/simplified-account/settings/stripe-details/index.njk
test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary.cy.js

- Displays `Stripe Account ID` on Stripe details page
_**current:**_
_**new:**_
##
**current:**
**new:**

PP-14458 Add Stripe account ID to stripe-details page
