alphagov/pay-selfservice

package.json

Remove bcrypt from SelfService
Removes a transient dependency on a package containing low vun i.e. ms - https://snyk.io/vuln/npm:ms:20170412

PP-2509 remove bcrypt from SelfService

---

app/views/3d_secure/index.html

We use “Mastercard” elsewhere in selfservice and the company themselves seem to have standardised on this over the former “MasterCard” (even though it’s easy to find stuff from them online that still uses the capital “C”).
_“When referencing the Mastercard® name in text, use an uppercase ‘M’ and lowercase ‘c’ with no space between ‘Master’ and ‘card’. The name should not appear with a capital ‘C’.”_
— from the ‘Using the Mastercard® name in text’ section of
https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html

On the 3D Secure settings page, change “MasterCard” to “Mastercard”

---

app/utils/transaction_view.js

- added filter to transaction detail events list that filters out events with `event.type !== 'REFUND'`

PP-2398 Backwards compatibility filter out REFUND events

---

Jenkinsfile

- revert the jenkins library branch to master (cleaning up backward compat fix from #468 )

PP-2497 Revert jenkins library branch to master

---

app/utils/json_to_csv.js
test/unit/utils/json_to_csv_tests.js

For refunds, the status needs to be prefixed with the word 'refund_' in the downloaded CSV
Download transactions containing a refund.
The refund status should be prefixed as expected.

PP-2478 New line item in csv file for full and partial refunds

---

.dockerignore
.gitignore
build-local.sh
package.json

- fixed build-local.sh so that it restores previously existing node_modules after it runs
- bug used to occur when a non-linux user ran `msl run` after having run `build-local.sh` as the latter would install platform dependent deps in the project for running in the mounted test image. These then naturally would not run locally on the users machine.

PP-2548 Fixed ./build-local.sh conflicting compiled npm deps

---

app/views/transaction_detail/_details.html

Add ids to the only to fields that don't have an id in the transaction details section to make it more more testable from an end-to-end tests perspective.

PP-2239 Include ids for 'date created' and 'provider' fields on transaction details

---

app/views/includes/propositional_navigation.html
app/views/includes/propositional_navigation_logged_out.html
app/views/layout_logged_out.html
app/views/login/login.html
app/views/login/otp-login.html
app/views/self_create_service/verify_otp.html
app/views/user_registration/verify_otp.html

OTP input was too wide so set to a quarter (instead of half)
Made logged out nav more like https://www.payments.service.gov.uk/

PP-2499 - Fixing otp width and nav links

---

app/assets/sass/application.scss
app/assets/sass/modules/_info_box.scss
app/utils/navBuilder.js
app/views/3d_secure/index.html
app/views/email_notifications/index.html
app/views/payment_types.html
app/views/payment_types_summary.html
app/views/settings_read_only.html
test/ui/navigation_ui_tests.js
test/ui/payment_types_summary_ui_tests.js
test/ui/toggle_3ds_ui_tests.js

Before know view-only users would and on settings and not
see a lot, know they can view the settings for 3D Secure,
Payment tyles and Email notifications but not edit them.
They cannot see API keys or Account credentials though
(as it was before).

PP-2584 - Allowing view-only users to _just_ view settings

---

app/views/email_notifications/edit.html

Upper-case “HTTPS”, “URL” and add apostrophes to “don’t”

Fix shocking lack of uppercase and apostrophes

---

app/views/transaction_detail/_events.html
test/ui/transaction_details_ui_tests.js

- moved `by <br>` out of `span.submitted-by` to make tests cleaner on transaction events template

PP-2575 updated `submitted by` markup yet again

---

app/assets/js/components/refund.js
app/assets/sass/helpers/_links.scss
app/assets/sass/modules/_flash.scss
app/assets/sass/modules/_transaction_detail.scss
app/assets/sass/modules/_transaction_refund.scss
app/controllers/transactions/transaction_refund_controller.js
app/views/includes/flash.html
app/views/layout.html
app/views/settings_read_only.html
app/views/transaction_detail/_refund.html
app/views/transaction_detail/index.html
test/integration/transaction_details_refunds_ft_tests.js
test/ui/transaction_details_ui_tests.js
test/unit/controller/refunds_controller_test.js

I’ve removed the refund modal as modals don't work
well on mobile and I have restyled to use GOV.UK
standards for radio buttons and currency inputs.
There was no messaging for a successfully submitted
refund so I have added one and I’ve also changed it
so that error messages show up using the flash
pattern we use around pay rather than redirect to an
error page which feels more helpful and less _dead-end_.

PP-2582 refund flow redesign

---

package.json

Snyk is reporting a vulnerability in fresh
included through serve-favicon
https://snyk.io/vuln/npm:fresh:20170908
Upgrading to 2.4.5 fixes this.

PP-2712 Upgrade serve-favicon

---

Jenkinsfile

This adds an extra step for deploying to the ECS cluster after deploying
to the normal cluster. We pass an extra boolean flag to both steps which
corresponds to `run_tests` boolean flag. This is so that we don’t smoke
test an environment after deploying to the first cluster, but haven’t
actually deployed anything yet to the ECS cluster.

PP-2728 Add DeployEcs step to deploy task

---

app/browsered.js
app/browsered/field-validation-checks.js
app/browsered/field-validation.js
app/views/includes/validation-errors.html

Usually we write validation into the controllers
which ends up meaning we have a lot of duplication
which is a shame and is loooong.
So this is a generic browserified validation engine.
To use it anywhere you need to do a couple of things
- add `data-validate="true"` to the form you want to validate
- add `data-validate` to each of the `input/select/textarea`'s you want validated
- by default it will check that the value is not blank but you can add a space separated list of validations e.g. `data-validate="required currency"`
Currently I have only written validators for `isCurrency`
and `isEmpty`. You can add new ones to `field-validation-checks.js`
The validator expects them to return a `string` with the error message or else `false`

PP-2655 - Reusable client side form validation

---

app/assets/sass/gov-uk-overrides/_icons.scss

The icon was missong from turn off email notifications screen
There was a load of CSS to replace it, that was no longer working, I don't know why so much was written when only the background-image: url() was causing the issue
There is a screenshot of the problem on Jira — https://payments-platform.atlassian.net/browse/PP-2800

PP-2800 - fixed missing icon

---

app/assets/sass/helpers/_headings.scss
app/assets/sass/helpers/_tables.scss
app/views/provider_credentials/epdq.html
app/views/provider_credentials/smartpay.html
app/views/provider_credentials/worldpay.html

The smartpay creds tables didnt line up vertically also the were close together which was consfusing and ugly.
Now it's all uniform across all provider creds tables

PP-2816 fix irregular spacing on smartpay creds page

---

app/assets/sass/modules/_service_switcher.scss
app/controllers/my_services_controller.js
app/views/services/_service_section.html

I thought this would be quite straight forward but the I don't data available to use in the template. I had a quick go a wrangling the controllers but there are a lot of async requests and I feel out of my depth and could do with pairing with someone to see how best to do it (without loads of duplication of functionality elsewhere)

PP-2683 - Rejigging type hierarchy

---

app/browsered/field-validation.js

We were using the spread operator [...] to convert a node list
into a standard array and as its ES6 it was converted on build.
in then used Array.from() which upset PhantomJS. We could update
PhantomJS but we're phasing it out so easier to not use the spread operator here.

PP-2655 - PhantomJS doesnt like fancy ES6 stuff

---

Jenkinsfile

This PR removes the requirement that end-to-end tests are run on
PR build. This change has been tried out already on connector and
has been successful. This removal is potentially  controversial - it makes
it possible to commit potentially broken (or incompatible) code to master.
However, I believe developer discipline and intuition should guide whether
running this before merge is necessary or not. For small changes (which
we should be encouraging) this seems way too much largely irrelevant
testing. And if you do break master, it would be much quicker to get out
a fix. If you feel need for Jenkins to run e2e against your branch before
merge, I have added a manually configurable option to be able to do that.

Streamline Jenkins pipeline

---

app/views/services/team_members.html

The copy was redundant for view-only users. So know they see a more relevant line
and only admins see the line about invites.

PP-2698 - Added logic to show conditional copy based on user permissions level

---

.snyk
package-lock.json

As specified in the ticket, after investigation we can tell that we have no exposure for the issue found for the dependency 'npm:timespan:20170907'.
We don't want to keep the alert to avoid that another person on support wastes time investigating the issue again. Considering that there's no fix for this issue yet, we decided to ignore the issue for a given period of time and the revisit to check if it applies.
In order to ignore the issue the snyk client has to be installed and the ignore the desired dependency by running:
```
snyk ignore --id=npm:timespan:20170907 --expiry='2018-01-20' --reason='No exposure. Transitive dependency pulled from forever dependency.'
```
That will modify the existing .snyk file in the repo to tell Snyk to ignore that issue.

PP-2687 Ignore snyk issue

---

app/models/Payment.class.js
app/models/Product.class.js
app/services/clients/products_client.js
test/fixtures/product_fixtures.js
test/unit/clients/product_client/payment/create_test.js
test/unit/clients/product_client/payment/get_by_payment_external_id_test.js
test/unit/clients/product_client/payment/get_by_product_external_id_test.js
test/unit/clients/product_client/product/create_test.js
test/unit/clients/product_client/product/disable_test.js
test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
test/unit/clients/product_client/product/get_by_product_external_id_test.js

Migration to pay-selfservice of changes to productsClient made in pay-products-ui
- Updated productsClient with changes from products_ui
- Moved from `.createProduct()` style to `.product.create()` style
- Product client now includes following methods:
- create payment
- get payment by payment external id
- get payments by product external id
- create product
- get product by product external id
- get product by gateway account id
- Also copied over corresponding Pact tests from products ui

PP-2655 Update productsClient

---

app/controllers/my_services_controller.js
app/views/services/_service_section.html

Services only have one live account so it's not
necessary to show the account type. So added a
property to the object to let the template know
whether it is live or not.

PP-2683 - Don't show gateway type if live

---

Jenkinsfile

Due to changes in ecs terraform the ecs deploy job is currently failing
To unblock rest of team removing this step for now.

Remove ecs deploy step

---

app/browsered/field-validation-checks.js
app/browsered/field-validation.js
app/controllers/forgotten_password_controller.js
app/controllers/invite_user_controller.js
app/services/user_service.js
app/utils/email_tools.js
app/utils/registration_validations.js
app/views/self_create_service/register.html
app/views/user_registration/register.html
test/integration/forgotten_password_ft_test.js
test/ui/self_create_service_ui_tests.js
test/unit/utils/registration_validations_test.js

Error messaging about whether a password was strong enough
wasnt very helpful and was inconsistent. I've made it
explicitly tell you whether your password is too simple or
too short.
Whilst doing this I have noticed that the email validation
was entirely a duplication. So I have stripped it back and
updated all applications of it.
I also added the new client side validation to the sign up
forms to give more immediate feedback to users.

PP-2517 - Improved account creation validation messaging

---

Jenkinsfile

Currently we don't tag selfservice after deployment.
We need to call deploy step with `tagAfterDeployment` set to `true` to tag selfservice properly.
see: https://github.com/alphagov/pay-jenkins-library/blob/1230893d0689f5f256ada585c79b6498ba872267/vars/deploy.groovy#L3

PP-2688 Fix deploy step

---

Dockerfile
docker/build_and_test.sh

- Use symlink rather than directory copy for node_modules caching layer in dockerfiles
- Speeds up the docker image build process both for the test image and the deploy image
- Makes the images smaller too

Use symlink in docker build

---

docker/build_and_test.sh

- a dead node_modules symlink remained in the workspace after a test run which prevented future builds
- this commit will remove this symlink once done

Delete node_modules symlink after test

---

Jenkinsfile

We disabled ecs deploys as they were broken.
They are now fixed, so re-enabling.

Reinstate ecs deploy

---

app/services/auth_service.js

For some reason the correlation ID stored using the `correlation-id` library is going missing in `/services/auth_service`.
In order to rectify this while we search for a cause, just including the `correlation-id` module in the `auth_service` file seems to solve it.

PP-2655 Temporary Fix for Missing Correlation ID in products client calls

---

app/views/3d_secure/index.html
app/views/services/team_member_permissions.html

`info` was a non standard implementation of thing that already existed. I removed it a few weeks back and broke this icon

PP-2878 - was using wrong class

---

app/middleware/restrict_to_sandbox.js
app/routes.js
test/unit/controller/test_with_your_users_controller/create_controller_test.js
test/unit/controller/test_with_your_users_controller/disable_controller_test.js
test/unit/controller/test_with_your_users_controller/links_controller_test.js
test/unit/controller/test_with_your_users_controller/submit_controller_test.js
test/unit/middleware/restrict_to_sandbox.js

- Restricted demo and prototype payments to sandbox accounts
- Created `restrict_to_sandbox` middleware
- Added tests for new middleware

PP-2655 Restrict demo and prototype payments to sandbox

---

app/browsered/field-validation.js
app/views/dashboard/demo-service/confirm.html
app/views/dashboard/demo-service/create.html
app/views/dashboard/demo-service/index.html

- Removed syntactic sugar that has been used in the field validation that is unfortunately only supported in the more recent version of browsers which causes problems during end to end testing with our version of PhantomJs. The following has been replaced with a more backward compatible alternative:
```
- Spread: `[... ]` replaced by equivalent `Array.prototype.slice.call()`
- let... of replaced by equivalent `forEach`
```
- Added `id` attributes to certain elements to facilitate E2E.

Pp 2755 Removed syntactic sugar that has been used in field validation

---

app/browsered/multi-select.js
app/views/includes/multi-select.html

I switched to using `.after()` which was foolish because it appended every change leading to a huge list of words which broke the layout, switched back to `.text()` but wrapped what we update in specific `<span>` so that we can keep the screen reader text all the time.

PP-2543 - text was not being cleared on subsequent update

---

app/controllers/make_a_demo_payment/confirm_controller.js
app/controllers/make_a_demo_payment/edit_controller.js
app/controllers/make_a_demo_payment/index_controller.js
app/controllers/test_with_your_users/links_controller.js
app/controllers/test_with_your_users/submit_controller.js
app/models/Product.class.js
app/routes.js
app/views/dashboard/demo-payment/confirm.html
app/views/dashboard/demo-payment/edit-amount.html
app/views/dashboard/demo-payment/edit-description.html
app/views/dashboard/demo-payment/index.html
app/views/dashboard/demo-service/index.html
test/unit/controller/make_a_demo_payment_controller/confirm_controller_test.js
test/unit/controller/make_a_demo_payment_controller/edit_controller_test.js
test/unit/controller/make_a_demo_payment_controller/index_controller_test.js
test/unit/controller/test_with_your_users_controller/links_controller_test.js
test/unit/middleware/get_gateway_account_test.js

- refactored confirm page so as to be a GET using session variables only
- added validation to index page on POST copying validation from prototype links pages
- added tests for index, confirm and edit pages

PP-2655 Added unit tests for make_demo_payment controllers

---

app/views/dashboard/demo-payment/confirm.html
app/views/dashboard/demo-service/index.html

The mock card number is a credit card number
Some services reject credit cards, so a debit card is more widely received

PP-2914 - some services dont accept credit cards so a mock debit is better

---

app/controllers/test_with_your_users/disable_controller.js
test/unit/controller/test_with_your_users_controller/disable_controller_test.js

- Now when you disable a prototype link it uses flash.generic not flash.genericError

PP-2671 Updated Disable prototype link to use generic

---

Gruntfile.js
app/browsered.js
package.json

We weren't polyfilling ES2015+ features for IE (and Opera, etc)
Added the config in to do so. Without this the multiselect
doesn't work in IE.

PP-2543 - Setting up Babel polyfill for IE

---

app/assets/sass/application.scss
app/assets/sass/modules/_dashboard-first-steps.scss
app/assets/sass/modules/_flex_grid.scss
app/utils/display_converter.js
app/views/dashboard/_first-steps.html

On IE, the dashboard layout was a total mess because of flexbox css, it was actually superfluous anyway, so taken it out. So that's fixed
Also the two payment prototype links should have been restricted to sandbox accounts only. So made that change too

PP-2966 IE flexbox and dashboard bugs 

---

app/controllers/make_a_demo_payment/go_to_payment_controller.js
app/controllers/make_a_demo_payment/index.js
app/controllers/make_a_demo_payment/mock_card_details_controller.js
app/paths.js
app/routes.js
app/views/dashboard/demo-payment/mock-card-details.html
test/unit/controller/make_a_demo_payment_controller/go_to_payment_controller_test.js
test/unit/controller/make_a_demo_payment_controller/mock_card_details_controller_test.js

- added `POST:/make-a-demo-payment/go-to-payment` and moved demo product creation logic to here
- updated mock card numbers page to point at new post endpoint
- updated tests accordingly

PP-2999 Moved Demo Product Creation to POST Endpoint

---

app/views/includes/head.njk

We recently added GA tracking to selfservice, but during a merge it got dropped when moving to Nunjucks, re-adding it

PP-2264 - This got dropped during the Nunjucks conversion

---

Dockerfile

bumped busybox from r6 to r7 as r6 no longer available on repo

bumped busybox from r6 to r7 as r6 no longer available on repo

---

Dockerfile
app/views/dashboard/_activity.njk

We used "refunded" when it should have been "refund-success" its causing an error for anyone with the refunds feature flag right now

PP-2877 - used the wrong refund state

---

Dockerfile

Bumped `musl`, `musl-dev` and `libc6-compat` from `r2` to `r3`

Bumped musl, musl-dev and libc6-compat from r2 to r3

---

app/views/includes/footer-categories.njk

Because other wise it said Support Support, so now support is last in the list

PP-3057 - sonia wanted to move the footer Support nav around

---

app/controllers/make_a_demo_payment/go_to_payment_controller.js
app/controllers/test_with_your_users/submit_controller.js
app/models/Product.class.js
app/services/clients/products_client.js
app/utils/product_types.js
test/fixtures/product_fixtures.js
test/unit/clients/product_client/product/create_test.js
test/unit/clients/product_client/product/get_by_product_external_id_test.js
test/unit/controller/make_a_demo_payment_controller/go_to_payment_controller_test.js
test/unit/controller/test_with_your_users_controller/submit_controller_test.js

Post the product `type`during product creation, which for now can be either `DEMO` or `PROTOTYPE`depending on whether we want to create demo payments or prototype links. Note that this field will be ignored until the accompanying backend piece is merged: 
https://github.com/alphagov/pay-products/pull/54

PP-3032 Specify the `type` during product creation

---

app/browsered.js
app/browsered/analytics.js
app/views/includes/propositional_navigation.njk
app/views/includes/propositional_navigation_logged_out.njk

We’d like to start tracking events across pay and in the wider GAAP team, this script will add event listeners to fire the google analytics tracking event when an element is clicked
It can be applied to a single link/input/button or can be applied to a parent element and will search for `a/input/button`’s within it and try to label them appropriately.
I've tagged up our header and propositional nav to show how the data-attributes work. 
I'll tag up the rest of selfservice in a separate PR

PP-3112 - Generic google analytics event tracking builder

---

app/views/dashboard/demo-service/index.njk

We’re updating our links (because we're moving from Paas back to our own AWS infrastructure) so we need to let users know this is happening.

PP-3078 - Added info message about links changed

---

Dockerfile
app/browsered/analytics.js
app/views/dashboard/demo-service/index.njk
package.json
server.js

But on test analytics is purposefully not set up and so `ga` doesn’t exist so the click events triggered an error in the console.
Also updated dependencies in `dockerfile` to fix breaking build

New analytics tracking function expected analytics functions to be present

---

Dockerfile
docker-startup.sh
docker/build_and_test.Dockerfile
docker/build_and_test.sh

Experimental. 
Rather than using the maintained Docker image for Node.js, we have instead derived an image from Alpine 3.7 (as opposed to 3.4), used the same pattern as Node.js for installing v6.12.2 and then upgraded c-ares to a version clear from CVEs that were being flagged up for older versions than those installed by default.
This enables us to reduce the number of updated packages we need to track, to keep ahead of CVEs, as well as reduce false positives in vulnerability scans through Docker hub.

PP-2967 Created custom Docker image, audited package version against CVEs and added manual upgrades where necessary

---

Jenkinsfile

ECS deployments are currently in a bit of a state,
so stopping until we've sorted this out

BAU pause ecs deployments

---

app/services/clients/connector_client.js
app/services/transaction_service.js
test/integration/transaction_download_ft_tests.js
test/integration/transaction_list_ft_tests.js
test/integration/transaction_search_ft_tests.js
test/unit/services/transaction_service_test.js

- removed `state` param from transactions search when downloading csv and when refund_states or payment_states filters have been selected
- because connector expects selfservice to make this call either with the old pattern ('state') or the new pattern ('refund_states', 'payment_states') and not both. This has been handled for the transactions list page but not the download page.
- on selfservice, with refund reporting enabled, filter by refund states and try to download a csv.

PP-3193 Fix transaction download bug

---

app/views/self_create_service/register.njk

We are starting a pilot with local authorities and so central government email is no longer required.
Remove 'central' from email hint copy
this replaces #621 as it fell behind and I can't rebase

BAU - removed central, as we want to encourage Local Gov to sign up too

---

package.json

Chamber is now in our base image, we should use that instead.
solo @tlwr

BAU: Use chamber in base image

---

app/controllers/transactions/transaction_download_controller.js
app/controllers/transactions/transaction_list_controller.js
app/services/clients/connector_client.js
app/services/transaction_service.js
app/utils/get_query_string_for_params.js
test/integration/pagination_ft_tests.js
test/integration/transaction_download_ft_tests.js
test/integration/transaction_list_ft_tests.js
test/integration/transaction_search_ft_tests.js
test/unit/services/transaction_service_test.js

This moves the use of 'state' vs 'refund_states' & 'payment_states' to being switched on the feature flag.
This should fix the broken _.csv_ download when the feature flag is enabled.

PP-3193 fix nasty refund transaction download bug

---

package.json
run-with-chamber.sh

All the other microservices that require secrets use run-with-chamber.sh
This service used npm start-with-chamber
Now it uses run-with-chamber.sh

pp-3167: use run-with-chamber.sh instead of npm

---

app/controllers/service_users_controller.js
app/services/clients/adminusers_client.js
app/services/user_service.js

We removed the deprecated way to send service internal ids in adminusers,
this commit contains some small refactoring of the service external id names.
https://github.com/alphagov/pay-adminusers/pull/154

PP-3063 Renamed internal id variables to external ids

---

app/assets/sass/helpers/_headings.scss
app/browsered/multi-select.js
app/controllers/transactions/transaction_list_controller.js
app/utils/filters.js
app/views/includes/multi-select.njk
app/views/transactions/filter.njk

Showing the multi-select for card brands if showing multi-select for
refunds, once everyone has refunds reporting will show both for
everyone.
Refactored the multi-select to work agnostically for different multi-selects
Added in logic so that filter can display a list of card brands and not
just one

PP-2705 - conditionally adding multi-select for card brands

---

app/services/clients/products_client.js

- removed payApiToken which is needed for publicauth. Placed it back

PP-3204 Fix bug (headers not set by base_client)

---

Jenkinsfile

This needs to wait till https://github.com/alphagov/pay-selfservice/pull/640 being merged.
As the way currently setup we are at a risk of releasing selfservice with broken products functionality given that the products e2e tests are not part of the selfseervice build.
This adds the products e2e tests as part of the `test` phase of selfservice.

PP-3250 Run products e2e test as part of selfservice build

---

app/controllers/credentials_controller.js
docker/build_and_test.sh
test/fixtures/product_fixtures.js
test/integration/credentials_ft_tests.js
test/unit/clients/product_client/product/create_test.js

* removed commands in `docker/build_and_test.sh` after test command because:
* they weren't needed as we ditch the image after tests run
* because they weren't strung on to the rest of the command with `&&\` they occurred even if the build failed
* linting fixes to get build green
* reverted changes in products tests that had removed pay_api_token

PP-3289 Make mocha fail builds on failed tests

---

app/controllers/test_with_your_users/links_controller.js
test/unit/controller/test_with_your_users_controller/links_controller_test.js

We don't want non-demo links showing up in the links page
for prototyping.
This PR filters it on the controller level and adds a test
to make sure this filtering is working.

PP-3120: Filter non-prototype links from links page

---

app/browsered/field-validation-checks.js
test/unit/browsered/field_validation_checks_test.js
test/unit/controller/make_a_demo_payment_controller/index_controller_test.js
test/unit/controller/test_with_your_users_controller/submit_controller_test.js

- At the point of payment creation the validator MAX_PRICE is set to pounds while
the incoming payload's `price` field is in pence.
with @kakumara

PP-3305 Fix validation mismatch for products creation

---

app/utils/registration_validations.js
test/unit/utils/registration_validations_test.js

- Add 50 characters max length validation for service name when registering a new user. This has been added for consistency across all the microservices.

PP-3295 Service name validation. Register user - add service name

---

server.js

Moves the initialisation of static asset handling higher up in the express configuration, which will remove them from the passport user serialisation middleware flow.
Results in a 12x reduction in calls to adminusers on common page requests and smoke tests.

Prevent static assets from being included in passport user deserialisation

---

Dockerfile
docker/build_and_test.Dockerfile
npm-shrinkwrap.json

Add the shrinkwrap from the last known healthy version of selfservice to master.
This should pin the dependencies to the versions as they were before we experienced problems.

BAU add last know healthy shrinkwrap

---

app/views/login/login.njk

- So it can be easily located by our end to end tests. Previous accepttests were navigating straight to the registration page rather than navigating users following page links (not convenient).

PP-3378 Add class to create new account link

---

app/views/self_create_service/verify_otp.njk

- So it can be easily located my our end to end tests. Current tests visiting the pages via URL which is not ideal.

PP-3378 Set css class to resend otp link view

---

app/browsered.js
app/views/self_create_service/set_name.njk
package.json

We want to be able to track signups as a goal to see if people are dropping off through the journey, but to do this we need a definitive end, so over on [GaaP Analytics](https://github.com/alphagov/gaap-analytics/pull/4) I added the ability to do so. This PR just updates our version of the npm module and inserts the markup

PP-3191 - adding virtual pageview so we can track signups

---

app/views/3d_secure/index.njk

Change link from https://govukpay-docs.cloudapps.digital/switching-to-production#worldpay-setup-for-3d-secure to https://govukpay-docs.cloudapps.digital/#worldpay-setup-for-3d-secure

Fix link to documentation about Worldpay 3D Secure setup

---

app/controllers/transactions/transaction_download_controller.js
app/controllers/transactions/transaction_list_controller.js
app/services/clients/connector_client.js
app/services/clients/old_base_client.js
app/utils/filters.js
app/utils/get_query_string_for_params.js
app/utils/transaction_view.js
app/views/dashboard/_activity.njk
app/views/transactions/filter.njk
test/integration/pagination_ft_tests.js
test/integration/transaction_details_ft_tests.js
test/integration/transaction_download_ft_tests.js
test/integration/transaction_list_ft_tests.js
test/integration/transaction_search_ft_tests.js
test/unit/services/transaction_service_test.js
test/unit/utils/filters_test.js

Delete REFUNDS_IN_TX_LIST feature flag
- Removed refund reporting enabled check from query string
- Returning both sets of statuses for Refund and Charge
- Removed conditional display of statuses from njk templates
- Updated connector client to use the new v2 version of the API
- Updated filters not to pass `state` back to connector anymore
- Fixed tests to use the new v2 endpoint
- Fixed tests not to check for `state` in the url sent to connector
as this is not happening anymore. Anyone can have multiple state select
- Added missing 'use strict' to files, replaced `var` with `const` or
`let`
with @kakumar

PP-3382 Delete REFUNDS_IN_TX_LIST feature flag

---

app/controllers/transactions/transaction_detail_controller.js
app/controllers/transactions/transaction_download_controller.js
app/controllers/transactions/transaction_list_controller.js
app/models/TransactionEvent.class.js
app/models/charge.js
app/utils/filters.js
app/utils/json_to_csv.js
app/utils/states.js
app/utils/transaction_view.js
package.json
test/fixtures/user_fixtures.js
test/integration/json/transaction_download.json
test/integration/json/transaction_download_refunds.json
test/integration/json/transaction_download_spreadsheet_formula_injection.json
test/integration/old_transaction_details_ft_tests.js
test/integration/old_transaction_download_ft_tests.js
test/integration/old_transaction_list_ft_tests.js
test/integration/transaction_list_ft_tests.js
test/ui/transaction_details_ui_tests.js
test/ui/transaction_list_ui_tests.js
test/ui/transaction_search_ui_tests.js
test/unit/models/charge_test.js
test/unit/utils/filters_test.js
test/unit/utils/states_test.js
test/unit/utils_filters_test.js

This might look like it contains a lot, but effectively all it does is transforming incoming connector states to the new display states and transform back the outgoing display states to connector states. 
The presentation logic of old display states and the new display states are very different therefore it needed a complete re-write. In order to make thing easier and more reasonable we've left the old states logic as is and prefixed with `old_`   in every function. Depending on the feature flag (to display new states) the core components call wither the new function or the `old_` function.
existing tests, didn't help much here either. They were not very reflective of the current state of the states and was very hard to reason about. So renamed all the existing tests to `old_` prefixed …

PP-3377 change payment states as to new display states

---

app/browsered/field-validation.js
app/browsered/polyfills.js

Temporary fix for failing smoke tests because of the use the `closest` element not supported in PhantomJS.
A Polyfill for `closest` element has been embedded in the code which can be removed once smoke tests stop relying on phantomjs.

PP-3489 Temporary fix for failing smoke tests

---

app/controllers/payment-links/get-disable-controller.js
app/controllers/test_with_your_users/disable_controller.js
app/services/clients/products_client.js
test/unit/clients/product_client/product/disable_test.js
test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
test/unit/clients/product_client/product/get_by_product_external_id_test.js
test/unit/controller/payment-links/get-manage-controller.test.js
test/unit/controller/payment-links/get_disable_controller_test.js
test/unit/controller/test_with_your_users_controller/disable_controller_test.js
test/unit/controller/test_with_your_users_controller/links_controller_test.js

`pay-products` was updated to force all product operations to supply the gateway account as a parameter for access control purposes and prevent insecure object reference. This change updates product client to reflect these api changes:
* Find a product by external id and by *gateway account id*,
`/gateway-account/{gatewayAccountId}/products/{productExternalId}`
* Disable a product by external id and by *gateway account id*,
`/gateway-account/{gatewayAccountId}/products/{productExternalId}/disable`
* Find all active products by *gateway account id*,
`/gateway-account/{gatewayAccountId}/products`

PP-3441 Updated product client to reflect API changes

---

Jenkinsfile

There is a perception that disabling e2e by default is causing
too many problems in master. This flips the deafult behaviour to run
e2e on PRs, but it is still possible to disable them.

BAU Run e2e by default on PRs

---

app/paths.js
app/services/clients/connector_client.js
app/utils/navBuilder.js
app/views/includes/settings-read-only.njk
app/views/payment_types.njk
app/views/payment_types_select_type.njk
app/views/payment_types_summary.njk
test/integration/payment_types_select_brand_ft_tests.js
test/integration/payment_types_select_summary_ft_tests.js
test/integration/payment_types_select_type_ft_tests.js
test/ui/navigation_ui_tests.js
test/ui/payment_types_select_brand_ui_tests.js
test/ui/payment_types_select_type_ui_tests.js
test/ui/payment_types_summary_ui_tests.js

With direct debit coming soon we will have two payment types.
So we need to rename the current payment types to be card types,
so things aren’t confusing.
I went further a replaced every single instance of payment with card, including file names.
It worked but would have required a major e2e rewrite too and it didnt seem worth it.

PP-3432 - Renaming Payment types to Card types

---

app/utils/states.js
test/integration/transaction_list_ft_tests.js
test/unit/utils/filters_test.js
test/unit/utils/states_test.js

only relate to the selected payment state
Previously the state dropdown was mapping all the errors to failed. We
want to be able to search by each type of error. Needed to map the
errors to their own code and pass this to connector. Connector has
already been updated to handle these new codes. Will come back and
remove old mappings once they have been removed from the connector
response. This had to be done in a number of steps to preserve
backwards compatibility.
with @kakumara

PP-3498 Results from 'State' dropdown on transactions filter should

---

app/utils/states.js
app/utils/transaction_view.js
test/unit/utils/states_test.js

If the user does not have the new states feature flag enable they
should still see the old display values. As we have changed connector
to return the new states we need to map those new states to  the old
display values. Will all be deleted once we get rid of the feature flag.
with @kakumara

PP-3498 Handle new states with old display value

---

app/controllers/toggle_3ds_controller.js
app/views/3d_secure/index.njk
test/ui/toggle_3ds_ui_tests.js

Fixed missing helper text for WorldPay
- Fixed getting the payment_provider from the correct object
- Added CSS id for the missing element for testing
- Added test to check that the element shows up for required permissions
and payment_provider

PP-3449 Fixed missing helper text for WorldPay

---

Jenkinsfile

This is a jenkinsfile update which:
- switches to using separate e2e, accept and zap test jobs
- runs each of these jobs in parallel
- switches each of these jobs on its own param for testing on pull requests

PP-3436 Run e2e, accept and zap separately in parallel

---

app/models/TransactionEvent.class.js
app/utils/states.js
test/integration/transaction_details_ft_tests.js
test/unit/utils/states_test.js

repeated three times
Changed the transaction events to display 'Created', 'Started' and
'Submitted' instead of 'In progress'

PP-3495 Do something about transaction event having "in progress"

---

app/middleware/resolve_service.js
test/fixtures/user_fixtures.js
test/unit/middleware/resolve_service_test.js

Modified `resolve_service` middleware to add `hasDirectDebitGatewayAccount` property which calculates if we the current service has Direct Debit gateway account or not

PP-2984 Add `hasDirectDebitGatewayAccount` dynamic property to `req.service`

---

app/controllers/transactions/transaction_download_controller.js
test/integration/old_transaction_download_ft_tests.js
test/integration/transaction_download_ft_tests.js

Want to test this on a windows machine before deploying so do not merge for now.
The file name for the CSV file contains spaces so is not being handled
very well by Firefox on windows. Replaced spaces with _ and added
quotes around name in header.

WIP PP-3482 Fix CSV download in firefox windows

---

app/controllers/api_keys_controller.js
app/controllers/dashboard/dashboard-activity-controller.js
app/middleware/get_gateway_account.js
app/middleware/resolve_service.js
app/services/clients/direct_debit_connector_client.js
app/services/service_service.js

- Edit service name was failing if a service has a dd gateway account, as we were making
calls to products and connector, receiving a 404
- We are currently not calling edit service name for dd connector, as the endpoint is not
yet implemented

PP-3521 Do not call products and connector when editing service name for a dd account

---

app/assets/sass/application.scss

This is a weird one as we don't use any of the icons that are 404ing so
it doesnt really make sense that they are being compiled or fetched anyway.
But I can’t work out why they are being compiled to the stylesheet but I
can see why they are being compiled with the wrong path. If you don't
decalre the path, Frontend Toolkit assumes you're using Rails which
would be able to resolve the image. We're using Node so we need to
declare $path. So I've done that.
It’s weird that this in included in the stylesheet though as things
we're not using shouldnt be. But I'll fix this and think more about what
is going on.

PP-3555 - Fix broken image path in stylesheet

---

app/views/payment-links/manage.njk

Earlier the gov.uk redirect wasn’t live so it would have broken e2e.
Now it’s live we can use the friendly URL, IRL

PP-3510 - redirect is live so friendly URL can be used

---

app/controllers/edit_merchant_details/get.js
app/controllers/edit_merchant_details/post.js
app/views/merchant_details/edit_merchant_details.njk
test/fixtures/service_fixtures.js
test/unit/controller/edit_merchant_details_controller/get_test.js
test/unit/controller/edit_merchant_details_controller/post_test.js

- Added `Phone number` to Merchant details page. The `Phone number` field is displayed when we have `Direct Debit` gateway account linked to the current service and also is mandatory in that case.

PP-2984 Add Phone number to Merchant details page

---

app/browsered/input-confirm.js
app/controllers/payment-links/post-web-address-controller.js
app/views/payment-links/information.njk
app/views/payment-links/web-address.njk

- if editing title then it shows the web address on load (before it only showed if you typed more characters in the title field, which is fine when first landing but not when returning to edit.
- Validate web address field so that blank web address can’t be submitted

PP-3575 payment link bugs

---

app/views/transactions/paginator.njk
test/ui/pagination_ui_tests.js

Since we made it so that you can filter by multiple states/brands the
logic that passed these filters through pagination broke as it expected
a string not an array. I've changed this and updated the test.
I also noticed we didnt pass email through to pagination, this probably
wasn't picked up before because no one has ever searched so unrefined as
to return that many emails that pagination is necessary. But I've added
it anyway.

PP-3637 - Subsequent paginations didnt include the filters

---

app/controllers/toggle_3ds_controller.js
app/middleware/get_gateway_account.js
app/views/3d_secure/index.njk
app/views/3d_secure/on_confirm.njk
test/ui/toggle_3ds_ui_tests.js
test/unit/controller/toggle_3ds_controller/toggle_3ds_controller_test.js

- Moved all helper text for 3DS Worldpay into one div
- Show/hide 3DS helper text on 3DS confirmation page base don gateway
- Added tests for this cases

PP-3525 Show/hide 3DS helper text for Worldpay only

---

app/controllers/dashboard/dashboard-activity-controller.js
app/views/dashboard/_activity.njk

The dashboard was hardcoded with a filter link that used the new payment
state "payment-success".
If a user does not have the flag then the filter was ignored.
So this checks for the flag and if it’s not present will use "success".

PP-3494 - Dashboard succesful transaction link fix

---

test/unit/services/service_service_test.js

- We are partitioning gateway accounts to make sure we don't call direct debit connector for card accounts and viceversa. The functionality is covered by an end to end test, this PR adds a unit test to make sure the behaviour is as expected
- Also, adding similar tests for the `getGatewayAccount` call

PP-3521 Add unit test for edit service name

---

app/controllers/invite_user_controller.js
app/utils/display_converter.js
app/utils/navBuilder.js
app/utils/pathLookup.js
app/utils/response.js
app/utils/roles.js
app/views/services/team_member_invite.njk
test/integration/invite_users_controller_ft_test.js
test/integration/service_roles_update_ft_test.js

- Strip whitespace automatically
- If an invalid email is put it, pass it back rather than clearing it
- update tests because they weren’t working at all because they expected a `409` when it was a `412`
(also spotted some embarrassing let usage so updated them to const, this is no by exhaustive but y'know. I’ve marked the actual meaningful changes)

PP-3654 fix whitespace around email bug

---

Jenkinsfile

When doing the selenium tests for staging we decided selfservice should
only run DD smoke tests. Updating the Jenkinsfile so that there is
consistency across all the environments
solo @belindac

PP-3602 Remove products and card payments smoke tests

---

Jenkinsfile

Revert commit that amended e2e rather than smoke tests
Only products and products-ui should run products smoke tests
solo @belindac

PP-3602 Reinstate incorrectly removed e2e config, remove products smoke test

---

app/models/charge.js
app/models/email.js
test/unit/models/charge_test.js
test/unit/models/email_test.js
test/unit/services/service_service_test.js
test/unit/services/transaction_service_test.js
test/unit/utils/util_correlation_header_test.js
test/unit/utils/utils_filters_test.js

Removes use of 'nock' to mock http endpoints from the /test/unit/models directory. This is part of our ongoing consolidation work to prepare for contract/pact and browser tests.
Where nock http mocks have been removed, correctly stubbed functions from dependencies have been created, rather than the 'integration' like solution that we had beforehand.

PP-3686 Refactored charge_test in models unit tests, to remove nock http mocks

---

test/unit/middleware/get_email_notification_test.js
test/unit/middleware/has_services_test.js
test/unit/middleware/payment_method_card.test.js

Either replaces uses of nock, and uses properly stubbed functions, or replaces nock references that were not used
This is part of a wider story to entirely remove nock, and implement pact stub based http mocks in contract tests, and remove http mocks from unit tests.

PP-3686 Remove nock from middleware tests

---

app/views/dashboard/_first-steps.njk
app/views/includes/settings-read-only.njk
app/views/payment-links/manage.njk

- Links to manage not create
- Explains why they can’t create
- Replaces instances of 'manage' with 'view'

PP-3658 - Better view only copy for pay links

---

test/unit/clients/base_client/base_client_test.js
test/unit/clients/base_client/wrapper_arguments_test.js
test/unit/clients/base_client/wrapper_request_callback_test.js

Removes the use of nock from our base client unit tests.

PP-3686 remove nock from base client unit tests

---

Jenkinsfile

##WHAT
Rather than contract tests running on PR and non master branches as they currently do, this removes that logic meaning master branch builds being triggers will cause contract tests to also run, and any associated interactions with the pact broker to execute.
I can't see any reasons why this would cause any unwanted side effects running on master currently.

PP-3619 Removed contract test condition on not running when on the master branch

---

Jenkinsfile

A deploy only happens on master branch so adding the conditional is required.
@oswaldquek

PP-3707: Tag consumer pact on deploy

---

app/views/twoFactorAuth/index.njk

This worked without this becuase if null it assumes app. But why not be
explicit.

BAU - Explicitly set APP is being configured

---

app/views/twoFactorAuth/configure.njk
app/views/user_registration/verify_otp.njk

One-time passwords are by definition for one-time use, so there’s no point having browser autocomplete remember them or make suggestions based on past input.
We already had `autocomplete="off"` for the main sign in flow; this adds it for registration of a new user and configuring the sign-in method of an existing user.

Add autocomplete="off" to OTP security code input elements

---

Jenkinsfile
docker/build_and_test.sh

This commit adds `Browser Testing` stage to the build.
Most of the magic happens in https://github.com/alphagov/pay-jenkins-library/blob/master/vars/cypress.groovy
In order to have test node_modules available to other things (specifically
cypress test image), we have gone back to using cp -R for node modules,
rather than ln -s. The symbolic link meant that the node moules were not
available outside of the context of the container.

PP-3813 Run cypress tests as part of build

---

package-lock.json
package.json
server.js

Appmetrics is a very os specific library. To be able to run
a locally built selfservice inside a docker container, we basically
can't run appmetrics, so I have added a flag to disable it.
It is admittedly a slightly confusing flag ('click here if you
don't want to not have the chance to win a house'), but means
appmetrics is enabled by default, reducing amount of other apps
that need to be touched.
This also adds a `start-local` command, which runs the app with nodemon
which reloads app on file changes.

PP-3567 Tweaks to run selfservice locally in docker4mac

---

test/unit/clients/connector_client/connector_client_create_gateway_account_test.js
test/unit/clients/connector_client/connector_get_card_types_test.js
test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js

We want to run the contract tests pertaining to
transactions as part of the pipeline, and build out
connector support for those. We don't want to worry
about other tests. I have marked all those tests we
don't want to worry about for now as `selfservice-to-be`
following precedent for adminusers.

PP-3813 Split connector contract tests

---

test/unit/clients/product_client/payment/create_test.js
test/unit/clients/product_client/payment/get_by_payment_external_id_test.js
test/unit/clients/product_client/payment/get_by_product_external_id_test.js
test/unit/clients/product_client/product/create_test.js
test/unit/clients/product_client/product/delete_test.js
test/unit/clients/product_client/product/disable_test.js
test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
test/unit/clients/product_client/product/get_by_product_external_id_test.js
test/unit/clients/product_client/product/get_by_product_path_test.js
test/unit/clients/product_client/product/update_service_name_by_gateway_account_id_test.js

We have a selfservice-products pact in the pact broker but there are no
provider tests in products to verify the pact yet. This is currently causing
selfservice deploys to fail as the deploy job asks the pact broker "can i deploy
selfservice?". The broker sees there's no compatibility between selfservice and
products and fails the build. Renaming selfservice -> selfservice-to-be will
unblock us for the moment.
@oswaldquek

bau: Rename selfservice consumer

---

test/fixtures/gateway_account_fixtures.js

As far as we can see this is not expected when calling
`/v1/api/accounts/{account_id}`, so removing.

PP-3897 Remove toggle 3ds from pact

---

app/views/includes/footer-categories.njk

Link on selfservice was out of date and doesn’t match pay-frontend

BAU - updating to new status page

---

Jenkinsfile

Adds contract testing from the provider side, to the Jenkins pipeline for the consumer, which in this case is self-service.

PP-3897 Added connector contract tests to the Jenkins pipeline steps

---

Jenkinsfile

As per description. This was disabled while some provider tests were fixed due to running red on master builds. This was due to the pact tag being different on a PR compared to master, so was only found out after the original PR was merged to enable it.

PP-3897 Re-enables contract tests for connector

---

app/routes.js
app/views/404.njk
server.js
test/integration/auth_ft_tests.js
test/unit/middleware/404.test.js

Selfservice would error 500 before this, which is sad.
Because we’re using a wildcard, it has to be last otherwise it will
hijack everything else and that would be bad.

PP-3133 - Adding a 404 page

---

app/assets/sass/helpers/_admin_list.scss
app/controllers/service_users_controller.js
app/services/clients/adminusers_client.js
app/services/user_service.js
app/views/services/team_members.njk
test/fixtures/service_fixtures.js
test/integration/service_users_ft_test.js
test/ui/team_member_list_ui_tests.js

Listing invites for a service in the manage team members section. Also, make the page look a bit more like the prototype by floating the invite team members button and expanding the column from two thirds to full.

PP-3943 Display invites in team members list

---

app/assets/sass/helpers/_admin_list.scss
app/services/clients/adminusers_client.js
app/views/services/team_members.njk
test/ui/team_member_list_ui_tests.js

- The invite list is shown only if there are invites
- Changed spacing between elements
- Also removed two `console.log`. Oooops.

PP-3943 Do not show invite list if empty and tweak ui

---

app/controllers/forgotten_password_controller.js
app/controllers/my-services/get-index-controller.js
app/controllers/register_user_controller.js
app/controllers/two-factor-auth-controller/post-index-controller.js
app/middleware/otp_verify.js
app/models/charge.js
app/models/email.js
app/services/clients/adminusers_client.js
app/services/clients/base_client/base_client.js
app/services/clients/base_client/wrapper.js
app/services/clients/connector_client.js
app/services/clients/public_auth_client.js
app/services/service_registration_service.js
app/services/service_service.js
app/services/transaction_service.js
app/services/user_service.js
app/utils/reflect.js
app/utils/registration_validations.js
docker/build_and_test.sh
package-lock.json
package.json
test/integration/create_service_controller/create_service_controller_create_populated_service_ft_test.js
test/integration/create_service_controller/create_service_controller_otp_verify_ft_test.js
test/integration/forgotten_password_ft_test.js
test/unit/controller/register_service_controller/register_service_controller_test.js
test/unit/controller/validate_invite_controller_test.js
test/unit/middleware/otp_verify_test.js
test/unit/services/auth_service_test.js
test/unit/utils/response_converter_test.js

Performs the not easy task of removing 'q' from self-service, which was an early implementation of ECMAScript Promises before they were natively supported by the version of Node.js we were running in Production.
Unfortunately these were not a simple swap out for regular native promises as the implementation was not like for like, meaning the code had to be re-factored to a simpler version.
Part of this involved swapping out the use of the 'old' base client for the 'new' one which is still currently only half adopted in Self-Service. For various reasons (mostly complexity) it doesn't make sense to completely implement it in this PR as it only directly applied to the Adminusers client. 
Moving over to a new base client had the knock on effect of affecting unit tests as the new base client …

PP-3920 remove q from all node projects

---

app/assets/sass/helpers/_tables.scss
app/controllers/edit_merchant_details/get-edit-controller.js
app/controllers/edit_merchant_details/get-index-controller.js
app/controllers/edit_merchant_details/index.js
app/controllers/edit_merchant_details/post-edit-controller.js
app/middleware/has_services.js
app/paths.js
app/routes.js
app/views/merchant_details/edit_merchant_details.njk
app/views/merchant_details/merchant_details.njk
app/views/services/_service_section.njk
test/unit/controller/edit_merchant_details_controller/get-edit.test.js
test/unit/controller/edit_merchant_details_controller/get-index.test.js
test/unit/controller/edit_merchant_details_controller/post-edit.test.js

_This is a clone of https://github.com/alphagov/pay-selfservice/pull/835 but without the Pact/Cypress stuff which broke things, that we will come back to later_
Rather than showing the form filled in which is U G L Y, no offence, we
now show a summary page if the details have been entered already.
Also Merchant is jargon so renamed it to Organisation, but only for users, still called merchant in the background. I did start renaming it there too, but it got crazy! Especially seeing as to do it properly would have to rename in the java projects and on the DB too

PP-3888 merchant details improvements 

---

Gruntfile.js
app/assets/sass/application.scss
app/assets/sass/modules/_flex_grid.scss
app/assets/sass/modules/_service_switcher.scss
app/browsered.js
app/browsered/autocomplete.js
app/views/services/_service_section_small.njk
app/views/services/index.njk
package-lock.json
package.json

- b8482c8 - tighter layout especially if there are 10 or more services
- 161b087 - Added autocomplete to service page
If a service has 8 or more services then we switch them over to a
slightly more condensed layout and show them an input which allows them
to jump to a specific service quickly.
This has been implemented in Javascript and will only be available for
users with JS. We have used the GOV.UK accessible autocomplete to do all
the heavy lifting.
We have a function that on selection hides all other services, leaving
just the one the user asked for.
Had to also add a little bit of config to the Gruntfile to load in the
styles for the autocomplete.

PP-3928 better view if lots of services

---

app/views/services/index.njk

The service switch filter should only show (and only start to work correctly) when there are 8 services or more.
This adds a small fix to the nunjucks template to ensure this happens.

PP-3928 Ensured the search box on service switcher only shows up when there are 8 services or more

---

app/controllers/my-services/get-index-controller.js
app/services/clients/adminusers_client.js
app/services/clients/connector_client.js
app/services/clients/direct_debit_connector_client.js
app/services/service_service.js
app/utils/reflect.js
test/unit/controller/service_switch_controller_test.js
test/unit/services/service_service_test.js

Previously the services index/switcher page made an initial call to Adminusers to get a list of services with associated gateway ids against them. These were composed into a large collection of Promises which made individual calls to Connector or Direct Debit Connector to get information about external gateways.
In the case where a development/test system has a few services, with perhaps one test gateway account under each one, this resulted in an inefficient but still fairly fast response time. As the number of services/accounts increases, the page starts to considerably slow down, as evident in our production systems.
The new implementation aggregates all gateway ids across all services and requests them in one go, before matching these up against individual services and rendering them …

PP-3928 Reduce the number of outbound requests to get gateway account information

---

package-lock.json
package.json

Lodash 4.17.5 has a vulnerability detailed in CVE-2018-3721.
This PR bumps the version beyond 4.17.x and pins it at 4.17.10

PP-3772 Bumps lodash beyond 4.17.5 which was flagged for having a prototype pollution vulnerability

---

app/controllers/transactions/transaction_download_controller.js
app/utils/json_to_csv.js
test/integration/json/transaction_download_refunds.json
test/integration/transaction_download_ft_tests.js
test/unit/utils/json_to_csv_tests.js

- Connector now returns the user external id for refunds. Selfservice has to get that for each refund and map it to a username by calling adminusers. 
Apologies for the frankly fugly code, but it is necessary as there can be multiple refunds from the same user and adminusers will only return a single result, so we need to store that in a map in order to populate the csv list with correct results.

PP-3493 Add issued by to csv export

---

app/controllers/transactions/transaction_download_controller.js
test/integration/json/transaction_download_refunds.json
test/integration/transaction_download_ft_tests.js

- `user_external_id` is not always present (ie. for refunds coming from
public api). Selfservice should handle this and not send undefined to
adminusers

PP-3493 Ignore undefined user id if refund issued by is not present

---

app/controllers/my-services/get-index-controller.js
app/models/DirectDebitGatewayAccount.class.js
app/services/service_service.js
test/unit/services/service_service_test.js

We were missing filtering gateway accounts for Direct Debit when we list services.
For Direct Debit currently we initialise `req.user.serviceRoles[].service.gatewayAccountIds` with external ids, but for Cards we initialise with internal ids.
We check the gateway accounts' external id first as not to overlap/skip between card payment and direct debit gateway accounts.
Commented out temporary failing test as agreed on the standup we need to merge that to unblock the current work and @brid will fix it.

PP-3975 Filter gatewayAccountIds by external and internal ids

---

.gitignore
test/cypress/integration/user/dashboard_spec.js
test/cypress/integration/user/transaction_details_spec.js
test/fixtures/config/self_service_user.json
test/fixtures/transaction_fixtures.js
test/unit/clients/connector_client/connector_get_transaction_details_test.js

Replaces the test in pay-endtoend which asserts that a refund attempt over the available refund amount, fails.
In order for this to work as a contract/browser test, the following needed do be done:
1. creating a pact interaction and unit test for:
a) viewing a transaction details page
b) posting an invalid refund request
2. creating Cypress browser tests to replicate the test from e2e

PP 3980 replace smartpay refund fail e2e test

---

docker/build_and_test.sh

##WHAT
The naming convention 'to-be' is used in our contract testing pact/contract interaction stage to define an interaction where we don't quite have the provider contract tests ready so the two can be tested in unison.
This PR ensures that 'to-be' pacts are not published to the broker, which ensures they aren't ran on the provider as expectations, which would normally fail.
This is done by simply renaming the pact files with 'to-be' in their filename to a different file extension, publishing the pacts, and then changing them back.

PP-3990 Prevents 'to-be' pacts from being published by changing their file extension before/after being published

---

app/controllers/dashboard/dashboard-activity-controller.js
app/middleware/get_gateway_account.js
app/middleware/x_ray.js
app/routes.js
app/services/auth_service.js
app/services/clients/adminusers_client.js
app/services/clients/base_client/wrapper.js
app/services/clients/connector_client.js
app/services/clients/old_base_client.js
app/services/user_service.js
app/utils/response_converter.js
aws-xray.rules
config/xray-cls.js
package-lock.json
package.json
server.js
test/unit/middleware/get_gateway_account_test.js
test/unit/services/auth_service_test.js

Sets up configuration for fine grained instrumentation of inbound/outbound service calls using AWS x-ray.
This involves:
- Using the x-ray SDK express plugin to automatically create traces and segments on routes.
- Configuring our base clients to pass generated trace id's through to underlying microservices
- Uses 'continuation-local-storage' as a way of persisting segment information down through callback/async chains without having to modify every function in the chain.
- Manual segment creation on our passport/session implementation, as this occurs before/outside a route context
As a proof of concept and a first implementation, the service calls involved in loading the self service dashboard have been modified for x-ray tracing and sub-segment information. This pattern can be repeated …

PP-2493 set up aws x ray in test environment

---

app/views/services/_service_section.njk
app/views/services/_service_section_small.njk
test/unit/controller/service_switch_controller_test.js

When talking about the Bacs scheme specifically, Direct Debit is a proper noun

Change “Direct debit” to “Direct Debit”

---

app/services/clients/base_client/wrapper.js
config/xray-cls.js
package.json

Tidies up some naming of namespace/key names, as well as ensuring 'continuation-local-storage' is explicitly defined as a dependency in package.json.

PP-4133 Tidy up x-ray implementation

---

app/assets/sass/helpers/_forms.scss
app/controllers/create_service_controller.js
app/controllers/edit_service_name_controller.js
app/controllers/register_service_controller.js
app/models/Service.class.js
app/services/clients/adminusers_client.js
app/services/service_service.js
app/utils/service_name_validation.js
app/views/services/add_service.njk
app/views/services/edit_service_name.njk
package.json
test/fixtures/pact_base.js
test/fixtures/self_register_fixtures.js
test/fixtures/service_fixtures.js
test/integration/create_service_controller/create_service_controller_service_naming_ft_test.js
test/unit/clients/adminusers_client/service/create_service_test.js
test/unit/clients/adminusers_client/service/update_service_name_test.js
test/unit/controller/create_service_controller/get_test.js
test/unit/controller/create_service_controller/post_test.js
test/unit/controller/edit_service_name/get_test.js
test/unit/controller/edit_service_name/post_test.js

@georgeracu / @jonheslop
- service name validation has been changed to get a field name as well
as a value
- Added a field to the front end on create service and edit service
- Updated add service clients to pass through the welsh name (if
present)
- Updated the edit service clients to pass through the welsh name
- duplicated a few tests and tweaked for welsh, bit of a cop out, needs
work
@danworth
- Changed `updateServiceName` within `adminusers_client` to use path based
notation e.g. `service_name/cy`.
- Updated and created pact tests for `update_service_name_tests`.
- Updated tests for `create_service_tests`.
- Updated tests for `create_service_controller_service_naming_ft_tests` to
consider `cy`.
- Updated `register_service_controller` to work with `cy` including checking
for …

PP-4096 add welsh service name

---

app/services/service_service.js
package-lock.json
test/unit/services/service_service_test.js

A service_service test was disabled during our work on Direct Debit due to a test failing when trying to split an array of services into regular and direct debit services. 
This involved a check on the format of a particular property on a service object to ensure it has certain contents that identify it as a direct debit service.
Previously the code tried to look at the value of the property, but did not check to see if the property existed in the first place, which in the case of a non direct debit service, it does/might not.
The code fix simply ensures the property exists before checking its value, and the test that previously failed has been un-commented out.

PP-3982 Re-instate service_service test

---

app/controllers/payment-links/get-delete-controller.js
app/controllers/payment-links/post-review-controller.js
app/models/Product.class.js
app/services/clients/public_auth_client.js
test/unit/controller/payment-links/get_delete_controller_test.js
test/unit/controller/payment-links/post_review_controller.test.js

- when creating a payment link, we now create a special token of type `PRODUCTS`. This will not be displayed in the API tokens section of selfservice so it won't be possible to manually revoke it
- The only way to revoke this token is deleting the payment link

PP-3816 Create and delete a products token with payment links

---

app/views/transactions/index.njk

Changes the text on the CSV download link/button to something more intuitive.
As discussed in https://trello.com/c/sAgmvvK5/68-should-we-change-csv-download-link-in-the-admin-tool

PP-4151 Changes copy on csv download link on transactions page

---

app/assets/sass/application-new.scss
app/assets/sass/components/dashboard-activity.scss
app/assets/sass/components/environment-tag.scss
app/assets/sass/components/feedback-banner.scss
app/assets/sass/components/flex-grid.scss
app/assets/sass/components/header.scss
app/assets/sass/components/links-box.scss
app/assets/sass/components/navigation.scss
app/utils/display_converter.js
app/views/dashboard/_activity.njk
app/views/dashboard/_links.njk
app/views/dashboard/index.njk
app/views/includes/header.njk
app/views/includes/phase_banner.njk
app/views/layout-new.njk

d692d14  - Migrate logged in template components to GOV.UK Frontend
- Before starting on body of the Dashboard page need to update the header, nav and feedback  components.
- Also tweaked the spacing in the navigation bar to make it more uniform,
whilst I was there I increased the targets for the links from 23px to
40px which makes them easier to click.
a8f46b0  - Migrate Dashboard components to GOV.UK Frontend
- Ported styles across using new variables and mixins
159200a  - noticed Dashboard wasn’t highlighted when query on index
- The function that matches the current URL to the navigation link shouldn’t worry about the query string so stripping it out.
- This means Dashboard is highlighted even if you filter by a different time period

PP-4192 dashboard using GOV.UK Frontend

---

app/browsered.js
app/views/includes/validation-errors.njk
app/views/services/add_service.njk
app/views/services/edit_service_name.njk

Migrated to GOV.UK Frontend new selectors and added in GOV.UK Frontend’s
JS bundle which gives us a bunch of nice polyfills and also makes the
conditionally revealing checkboxes work all nice.

PP-4194 - add/edit name using GOV.UK Frontend

---

app/services/clients/adminusers_client.js
test/unit/controller/two-factor-auth-controller/post_index_controller.test.js

We forgot to marshall adminusers' response into a `User` object. Not sure how this happened.

BAU - Fix 2FA switch

---

app/views/transaction_detail/_details.njk
test/cypress/integration/user/transaction_details_spec.js
test/fixtures/config/self_service_user.json
test/fixtures/transaction_fixtures.js
test/ui/transaction_details_ui_tests.js
test/unit/clients/connector_client/connector_get_transaction_details_test.js

- Added a label that displays 'Delayed capture: ON' when the charge has
delayed capture enabled. Otherwise it doesn't show anything different
- Added test data for Pact interactions
- Added cypress test and unit test
with @danworth

Pp 4109 add delayed capture to transaction details

---

test/cypress/integration/user/transaction_search_spec.js
test/fixtures/config/self_service_user.json
test/fixtures/transaction_fixtures.js
test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js

Replaces the flakey tests in end to end:
https://github.com/alphagov/pay-endtoend/blob/master/src/test/java/uk/gov/pay/endtoend/tests/selfservice/TransactionSearchIT.java
These do not play nicely with Selenium, and frequently fail to select desired elements on thew page, causing intermittent failures.
This replaces the functionality with Cypress.io browser tests, which rely on contract tests and interactions which stub the self-service -> connector, calls.

PP-4215 Remove flakey transaction filtering, end to end test, with browser/contract implementation

---

app/controllers/service_users_controller.js
app/middleware/resolve_service.js
app/routes.js

The `getCurrentGatewayAccountId()` function in `auth_service.js` looks up
the users Gateway account from the cookie. This cookie persists even
when logged out (for up to 30 days), so when you log back in you end up
on the same service.
But when you login it checks that you’re still a part of that service as
whilst you were gone you could have been removed.
This check was happening without the service middleware before it so it
couldnt find the service and so kicked you back to the first service in
the list.
So I added the missing middlewares and this made it work OK for users
that had the cookie.
For users with no cookies this meant the `currentGatewayAccountId` was set
to an empty object. Which the `resolve_service` middleware skipped over
and assumed meant you shouldn't be here and …

PP-4228 - Remember gateway account from last login

---

app/views/payment-links/index.njk

Change:
“It's quick and easy to create a payment link and you don’t need any technical knowledge.”
… to:
“It’s quick and easy to create a payment link and you don’t need any technical knowledge.”

Replace apostrophe → ' ← with right single quotation mark → ’ ←

---

app/utils/transaction_view.js
app/views/transaction_detail/_details.njk
test/cypress/integration/user/transaction_details_spec.js
test/fixtures/config/self_service_user.json
test/fixtures/transaction_fixtures.js
test/unit/clients/connector_client/connector_get_transaction_details_test.js
test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js

Display total_amount and corporate_card_surcharge properties in transaction details page
- Pass `total_amount` and `corporate_card_surcharge` properties in transaction details page and display appropriate message.
- Add Cypress tests and modified mocked Pact json files and fixtures.
- Update Pact charges state description.
with @stephencdaly and @brid

PP-4130 display surcharge on transaction details

---

app/views/dashboard/_links.njk

The url points to https://docs.payments.service.gov.uk/switching_to_live/#switching-to-live

PP-4330 Use right url for switching to live docs link

---

app/controllers/credentials_controller.js
app/utils/display_converter.js
app/utils/navBuilder.js
test/ui/credentials_ui_tests.js
test/ui/navigation_ui_tests.js

For payment provider `Stripe`, users do not need to manage payment provider credentials as the accounts are procured centrally and possibly automated with Stripe Connect.
So account credentials menu and page are not relevant  if payment provider is 'Stripe'
Changes
- Account credentials - side menu not displayed if payment provider is Stripe
- Error page - 404 page is displayed when `[selfservice url]/credentials` link is accessed directly and when payment provider is Stripe

PP-4305 Handle Stripe gateway accounts

---

app/assets/sass/application-new.scss
app/assets/sass/components/button.scss
app/assets/sass/components/multi-select.scss
app/assets/sass/components/pagination.scss
app/assets/sass/components/transaction-filter.scss
app/assets/sass/components/transaction-list.scss
app/browsered/multi-select.js
app/controllers/transactions/transaction_list_controller.js
app/utils/filters.js
app/utils/transaction_view.js
app/views/includes/multi-select.njk
app/views/transactions/display_size.njk
app/views/transactions/filter.njk
app/views/transactions/index.njk
app/views/transactions/list.njk
app/views/transactions/paginator.njk
test/cypress/integration/user/transaction_search_spec.js
test/integration/transaction_list_ft_tests.js
test/ui/pagination_ui_tests.js
test/ui/transaction_list_ui_tests.js

- Migrated the Transaction filters over to GOV.UK Frontend
- Updated tests to work with new templates
> The biggest change is supplying the states and card brands ready for the
nunjucks rather than doing another for loop in the template. This means
that tests and controllers had to be updated to match the new
object model.
- Finished migrating transactions list page to GOV.UK Frontend 
> Converted the table, pagination and page display size components
> Also put in a couple of checks to capitalise JCB so it doesn’t come out
as JCB or jcb

PP-4336 transactions index migration to GOV.UK Frontend

---

app/controllers/transactions/transaction_download_controller.js
test/fixtures/user_fixtures.js
test/integration/json/transaction_download_refunds.json
test/integration/transaction_download_ft_tests.js

- Change the logic within `transactions_download_controller` to not assume the
order of the `Users` returned by `Adminusers` is the same as the ordering
of the `external_user_ids` it sends in the GET query. This is necessary when
converting the `external_user_id` to the `username` which is ultimately
shown in the downloaded report. The previous implementation assumed the order
of the `Users` which led to incorrect mapping between `exertnal_user_id` and
`username`.
- Updated tests to catch this scenario and ensure correct username is used
regardless of the order of the `Users` returned by `Adminusers`.
Related to support ticket:
https://govuk.zendesk.com/agent/tickets/3421777

PP-4345 Fix refunds download to show correct username

---

app/views/3d_secure/index.njk
app/views/credentials/sandbox.njk
app/views/dashboard/_links.njk
app/views/dashboard/demo-payment/mock-card-details.njk
app/views/dashboard/demo-service/index.njk

The links were just linking to the docs homepage, updated the links so they link directly to where they meant to

BAU - update old style docs links so they work

---

app/assets/sass/components/email-template.scss

Use `overflow-wrap: break-word;` to stop this happening

PP-4354 - custom email text with long strings broke out of container

---

package.json

Nodemon was reloading when there were changes in these files and nothing
will happen if it does, so it might as well not reload on them.
These are are assets that require running npm run compile (to run Grunt)
then this will change, application.js which then will trigger nodemon to
do reload.

BAU - Excluding files that nodemon should ignore

---

Gruntfile.js
app/browsered.js
package-lock.json
package.json

We were including babel-polyfill and also running babelify this seems inefficient. After a google I found this https://github.com/babel/babelify/issues/246 which confirms my suspicions, so stripped out that stuff.
So using grunt-babel instead as a separate job.
JS bundle size decreased from 346.16kB to 217.44.kB

PP-4396 - Optimise grunt workflow for compiling JS

---

app/views/email_notifications/edit.njk

The custom email paragraph let you put any amount of words in, when this
reaced ~10,000 it broke selfservice with non-descript error.
I’ve set the limit to 5000 characters which is around 800 words, which
seems a reasonable limit.

PP-4157 - add valdation to check for max number of characters

---

app/assets/sass/components/multi-select.scss
app/views/transactions/filter.njk

During the conversion to GOV.UK Frontend these all got bumped up one
size on the scale. This meant that the date was cut off, shrinking down
to 16px.

BAU - normalise filter input type sizes

---

package.json

The pact-stub version was pinned at a previous version while a regression was fixed that prevented things from working.
This has now been fixed, so we can track 'latest' again now.

PP-4170 Revert to 'latest' version of pact-stub container

---

app/controllers/edit_merchant_details/get-edit-controller.js
app/controllers/edit_merchant_details/get-index-controller.js
app/controllers/edit_merchant_details/post-edit-controller.js
app/controllers/invite_user_controller.js
app/controllers/service_roles_update_controller.js
app/controllers/service_users_controller.js
app/middleware/resolve_service.js
test/integration/invite_users_controller_ft_test.js
test/integration/service_users_ft_test.js

We discovered that in some cases it is possible for a logged in user to
view and modify data from other services. This PR fixes the bug. 
The basic cause of the bug is that for urls that contain the service id 
we were not correctly checking whether the user had access to that url.
fd93aa2d has a failing test describing the bug and the main fix.
881e48dd ensures that we won't repeat this mistake in future by ensuring
that all controllers use a service id that we have ensured is valid for 
current user.
This probably needs unit tests around the resolve service middleware,
but I think the high level test is enough to show the bug is fixed. I will
do further tests in a separate PR, which will better demonstrate what
resolve_service is supposed to do.

PP-4472 Fix user access bug

---

app/browsered.js
package-lock.json
package.json

This increases the bundle from 138kB to 270kB. Sad times, but I am
having trouble making it apply just the polyfills we need. So this is a
stop gap to get partial refunds working again for older browsers.

PP-4181 - Add babel polyfill to help older browsers

---

app/assets/sass/application.scss
app/assets/sass/components/vertical-align.scss
app/utils/transaction_view.js
app/views/transaction_detail/_details.njk
app/views/transactions/list.njk
test/cypress/integration/user/transaction_search_spec.js
test/test_helpers/html_assertions.js
test/ui/transaction_list_ui_tests.js

- show total amount and indicate that it includes a surcharge when relevant
- add ui test
- add Cypress test for transaction list and skip modifying the old `transaction_list_ft_tests.js` test as it is covered by Cypress and it is asserting on JSON response which is not good way to test integration and ui
with @jonheslop and @DanailMinchev

PP-4488 show corporate card surcharge on transaction list

---

app/assets/sass/components/target-to-show.scss

BAU - line up cancel button with refund button

---

Gruntfile.js
package.json

`grunt-nodemon` was referenced from the Gruntfile build process, this threw
a warning as the dependency was removed and is no longer used.
The import for `grunt-nodemon` was removed.
A package.json dependency `grunt-cli` was also removed as it looks like this is
no longer used by any build process.
Previous behaviour: 
Error was thrown on `npm run compile` for the missing `grunt-nodemon` library
Expected: 
No error thrown as this library is not needed

PP-4523: Remove grunt-nodemon from Gruntfile build

---

test/integration/transaction_list_ft_tests.js

Connector returns `transaction_type: "charge"` for transactions list endpoint, so we should use `charge` instead of `payment `
with @alexbishop1

PP-4508 Use correct transaction type

---

README.md

Cypress README instructions were slightly out of date.
* `test:cypress` -> `cypress:test`
* `server:cypress` -> `cypress:server`
Added additional information on the `./pacts` folder that wasn't
previously explained and causes tests to fail.
Updating minor spelling mistakes and correcting any statements that
aren't completely clear or have simple mistakes (account id -> charge
id).

BAU: Refactor Cypress tests README

---

app/views/transactions/paginator.njk
test/ui/pagination_ui_tests.js
test/unit/utils/filters_test.js

- Pagination template was using the wrong field in the template data
meaning it was expecting to split an array but was actually splitting
a string when there was a single payment state filter

PP-4552 Fix transactions pagination when there is a single state filter

---

server.js

This doesn't do what we think it does ™️
If any environment variable is set for `DIABLE_APP_METRICS` it will
result in `false`, this is because any defined string in JavaScript
converted to Boolean (`!`) will result in `true` - negating this will
always be false.
The current behaviour will disable app metrics if any value is set for
this environment variable (even if it's explicitly false).
Suggestion for extracting core functionality into shared modules made for upcoming work.
Note: This should be checked carefully before pushing to production - it may alter the way environments interpret or set flags

PP-4564: Fix app metrics disabled flag equality

---

package-lock.json
package.json

Our dependency `requestretry` moved the `request` library from a dependency to
a peer dependency in release [2.0.0](https://github.com/FGRibreau/node-request-retry/commit/aafafe3).
A recent [PR](https://github.com/alphagov/pay-selfservice/pull/1050) bumped our version to the latest, including this change. This adds `request` to our
dependencies to ensure the peer dependency is fulfilled and correctly installed.
Note that a number of other peer dependency warning are flagged on `npm install`, these are only used in development but should be addressed.
```
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard-jsx@6.0.2 requires a peer of eslint@>=5.0.0 but none is …
```

BAU: Add request as a peer dependency

---

app/controllers/request-to-go-live/go-live-stage-to-next-page-path.js
app/controllers/request-to-go-live/index/get.controller.js
app/controllers/request-to-go-live/index/post.controller.js
app/paths.js
app/views/request-to-go-live/index.njk
test/cypress/integration/user/request_to_go_live_index_spec.js
test/cypress/plugins/index.js
test/fixtures/config/self_service_user.json
test/fixtures/user_fixtures.js
test/unit/clients/adminusers_client/authenticate/authenticate_test.js
test/unit/clients/adminusers_client/user/get_user_test.js
test/unit/controller/request-to-go-live/go-live-stage-to-next-page-path.test.js

This PR implements "Request to go live" index page and adds Cypress testing.
Routes were added for future workflow pages.
The content/design of the page can change in near future, but currently this implementation is the latest one.
- Add all "request-to-go-live" url paths
- Add "go-live-stage-to-next-page-path" utility
Display `COMPLETED` label for each step depending on `GoLiveStage`
returned from adminusers
- Redirect to the next step depending on `GoLiveStage` returned from
adminusers
- Add "Your service is live" panel which will be removed later when the
new mockup is ready
- Modified the template to have test CSS ids
- Add Cypress tests, including the static fixtures and
modified related Pact tests

PP-4449 "Request to go live" index page implementation and testing

---

app/utils/transaction_view.js
test/integration/transaction_list_ft_tests.js

Card holder name filter was omitted from the CSV download transactions
link, this meant that clicking to download CSV would download all transactions. 
This ensures that it is templated into the download link to prevent this behaviour.
Note: this has been tested locally but the behaviour should be verified live before signing off on the ticket.

PP-4590 fix self service filter csv download

---

app/views/policy/policy.njk

Policy download pages had links styled by the default browser. This
ensures GOV.UK design system classes are applied.

BAU Fix policy download page link styles

---

test/unit/clients/adminusers_client/user/get_user_test.js

- These were temporarily disabled whilst unused fields were removed
from the adminusers get user response

PP-4607 Re-enable user pact tests

---

app/assets/sass/application.scss
app/assets/sass/components/error-label.scss
app/controllers/request-to-go-live/organisation-name/post.controller.js
app/utils/organisation_name_validation.js
app/views/request-to-go-live/organisation-name.njk
test/cypress/integration/request-to-go-live/organisation_name_spec.js

- prevents `organisation-name` characters from exceeding the upper limit of 255-characters, currently set in the db
- removes organisation name default value from user fixture `self_service_user.json`to allow us to simulate realistic user behaviour
- re-use validation provided in `field-validation-checks`
- updates cypress tests to clear cookies prior to running tests to avoid persisting state
- adds new cypress test for validating `organisation-name` character length
- adds margin above error message because its visually more appealing
solo: @cobainc0

PP-4451 Validate Organisation name maximum character length

---

test/fixtures/pact_base.js
test/fixtures/user_fixtures.js

Fixes exception thrown if we try to pactify a JSON object which has null values. Currently we weren't building any pacts with null values but we should be able to

PP-4678 Allow for null values in pact fixtures

---

README.md

- Reorder some parts of the readme so that it makes more sense.
- Remove outdated instructions for changing environment variables.
- Remove redundant instructions about transactions API requests and
developer tokens.
Sanity check I haven't removed any instructions that still apply

PP-4678 Clean up README and make up to date

---

Jenkinsfile

A feature branch of pay-jenkins-library was used to ensure updated
infrastructure was passing in CI, once
https://github.com/alphagov/pay-jenkins-library/pull/94 is merged this
should stay up to date with master.
Depends on https://github.com/alphagov/pay-jenkins-library/pull/94

BAU: Jenkinsfile lib back in line with master

---

README.md
test/cypress/cypress_testing.md
test/cypress/integration/user/dashboard_spec.js
test/cypress/integration/user/merchant_details_spec.js
test/cypress/plugins/index.js
test/cypress/plugins/stubs.js
test/fixtures/fixture_builders.md

- Add readme for how Cypress tests interact with Mountebank and
  other Cypress tips
- Add readme for how fixture builders are used, validated and written
- Add some code comments explaining stubbing
- Remove some redundant code comments in Cypress tests that refer to the old method

PP-4678 Add documentation for new stubbing method for Cypress tests

---

test/unit/clients/adminusers_client/authenticate/authenticate_test.js
test/unit/clients/adminusers_client/service/update_collect_billing_address_test.js
test/unit/clients/adminusers_client/user/get_user_test.js

- First steps towards removing self_service_user.json completely
- Remove pact tests to get service with each go live stage as these are unnecessary now that we don't use pacts to drive Cypress tests

PP-4678 Remove use of self_service_user.json from adminusers tests

---

test/cypress/plugins/stubs.js
test/fixtures/gateway_account_fixtures.js
test/unit/clients/connector_client/connector_patch_email_collection_mode_test.js
test/unit/clients/connector_client/connector_patch_email_confirmation_toggle_test.js
test/unit/clients/connector_client/connector_patch_email_refund_toggle_test.js

- remove usages of static config file which will be removed in future
- modify fixtures for email setting patch requests to be stricter

PP-4678 Remove self_service_user from email patch tests

---

test/cypress/plugins/stubs.js
test/fixtures/service_fixtures.js
test/fixtures/user_fixtures.js
test/integration/login_controller_test.js
test/integration/service_users_ft_test.js
test/integration/transaction_download_ft_tests.js
test/unit/clients/adminusers_client/authenticate/authenticate_test.js
test/unit/clients/adminusers_client/user/assign_servicerole_test.js
test/unit/clients/adminusers_client/user/authenticate_test.js
test/unit/clients/adminusers_client/user/get_multiple_users_test.js
test/unit/clients/adminusers_client/user/get_user_test.js
test/unit/clients/adminusers_client/user/second_factor_test.js
test/unit/clients/adminusers_client/user/update_servicerole_test.js
test/unit/clients/connector_client/connector_get_transaction_details_test.js
test/unit/controller/billing-address-controller/toggle-billing-address-controller.test.js
test/unit/controller/edit_merchant_details_controller/get-edit.test.js
test/unit/controller/edit_merchant_details_controller/get-index.test.js
test/unit/controller/service_switch_controller_test.js
test/unit/middleware/has_services_test.js
test/unit/middleware/resolve_service_test.js
test/unit/models/User.class_test.js
test/unit/models/charge_test.js

- get closer to only having a single fixture to create a user for test purposes, this means that if the user model changes, it only needs to be updated in a single place for all tests
- replace most duplicated fixtures by use of getUserResponse fixture
- deprecate user_fixtures#getUser, this isn't removed yet as it has a lot of usages
Viewing as side-by-side diff might be easier than unified

PP-4678 Remove duplicated user fixtures

---

app/controllers/request-to-go-live/agreement/get.controller.js
app/controllers/request-to-go-live/agreement/index.js
app/controllers/request-to-go-live/agreement/post.controller.js
app/routes.js
app/services/auth_service.js
app/views/request-to-go-live/agreement.njk
test/cypress/integration/request-to-go-live/agreement_spec.js
test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
test/cypress/plugins/stubs.js
test/cypress/utils/request_to_go_live_utils.js
test/unit/clients/publicauth_client/get_tokens_test.js

- fix choose_how_to_process_payments_spec tests
- make 'getUserSuccess' repeatable with different results in stubs
- implement call to adminusers
- update tests

PP-4453 add agreement page

---

test/cypress/plugins/stubs.js
test/fixtures/service_fixtures.js
test/fixtures/user_fixtures.js
test/unit/clients/adminusers_client/service/create_service_test.js
test/unit/clients/adminusers_client/service/update_collect_billing_address_test.js
test/unit/clients/adminusers_client/service/update_merchant_details_test.js
test/unit/clients/adminusers_client/service/update_service_name_test.js
test/unit/controller/edit_merchant_details_controller/post-edit.test.js

- All update service requests return a complete service in the body of the response. Use a single service fixture to build the response for all update requests.

PP-4678 Remove duplicated service fixtures

---

test/cypress/integration/request-to-go-live/organisation_name_spec.js

- we suspect tests are flaky because they end on an action to click a
button that will cause a redirect but doesn't do any asserts
- remove the click actions, they will be added back in in a subsequent
commit along with assertions on the page redirected to
with @cobainc0

PP-4451 Attempt to remedy browser test flakiness

---

test/fixtures/gateway_account_fixtures.js
test/integration/create_service_controller/create_service_controller_create_populated_service_ft_test.js
test/integration/create_service_controller/create_service_controller_otp_verify_ft_test.js

- make it so that there is a single fixture for creating card
gateway account responses
- remove `validGatewayAccountEmailNotificationsResponse` fixture which wasn't used anywhere

PP-4678 Remove duplicated gateway account fixtures

---

test/cypress/integration/user/login_spec.js
test/fixtures/service_fixtures.js
test/fixtures/user_fixtures.js
test/unit/clients/adminusers_client/authenticate/authenticate_test.js
test/unit/clients/adminusers_client/forgotten_password/create_forgotten_password_test.js
test/unit/clients/adminusers_client/forgotten_password/get_forgotten_password_test.js
test/unit/clients/adminusers_client/service/add_gateway_accounts_to_services_test.js
test/unit/clients/adminusers_client/service/create_service_test.js
test/unit/clients/adminusers_client/service/get_service_users_test.js
test/unit/clients/adminusers_client/service/update_collect_billing_address_test.js
test/unit/clients/adminusers_client/service/update_request_to_go_live_stage_test.js
test/unit/clients/adminusers_client/service/update_service_name_test.js
test/unit/clients/adminusers_client/user/assign_servicerole_test.js
test/unit/clients/adminusers_client/user/authenticate_test.js
test/unit/clients/adminusers_client/user/delete_user_test.js
test/unit/clients/adminusers_client/user/increment_session_version_test.js
test/unit/clients/adminusers_client/user/second_factor_test.js
test/unit/clients/adminusers_client/user/update_password_test.js
test/unit/clients/adminusers_client/user/update_servicerole_test.js

- lots of pact tests had consumer 'selfservice-to-be', which meant they
were not published to the pact broker and so not verified against
adminusers
- this commit gets a lot of those tests working against adminusers and
changes the consumer to 'selfservice'
- some pact tests have been removed where they are over-testing
validation which should be tested in adminusers itself, or are testing
behaviour that does not exist

PP-4678 Make more adminusers pact tests run against provider

---

test/cypress/integration/request-to-go-live/organisation_name_spec.js
test/cypress/plugins/stubs.js
test/cypress/utils/request_to_go_live_utils.js
test/fixtures/service_fixtures.js
test/unit/clients/adminusers_client/service/update_merchant_name_test.js

Add contract test for merchant details PATCH request
- new pact test `update_merchant_name_test` verifies that a
request to the PATCH endpoint in adminUsers updates the merchant name
successfully
Fixes flaky browser tests
- adds missing assertions to the end of tests where previous flaky behaviour was exhibited. See SHA: 143a9b2
- refactors `organisation_name_spec` to incorporate new utils in `request_to_go_live_utils`.

PP-4451 organisation name page

---

test/cypress/integration/dashboard/dashboard_spec.js
test/cypress/integration/settings/email_notifications_spec.js
test/cypress/integration/transactions/transaction_details_spec.js
test/cypress/integration/transactions/transaction_search_spec.js
test/fixtures/gateway_account_fixtures.js

- Add `payment_provider` field to gateway account fixture so we can set it to different values for Cypress tests.
- Update existing Cypress tests that assert on page title, as test accounts contain the payment provider in the page title. It wasn't previously there because the stubbed gateway account response wasn't returning a `payment_provider`

PP-4448 Add payment_provider field to gateway account fixture

---

app/views/self_create_service/resend_otp.njk
test/ui/self_create_service_ui_tests.js

Currently pay-adminusers saves and returns international telephone number format starting with `+44` (UK example).
The current validation in selfservice still expects numbers only telephone numbers.
This PR modifies the value of the input to be reformatted in numbers only international telephone number.
Once the validation of the selfservice can handle any format we need to remove this formatting.

PP-4759 international phone number support backward compatablity

---

app/views/user_registration/re_verify_phone.njk
app/views/user_registration/register.njk
test/ui/register_user_ui_tests.js

Currently pay-adminusers saves and returns international telephone number format starting with `+44` (UK example).
The current validation in selfservice still expects numbers only telephone numbers.
This commit modifies the value of the input to be reformatted in numbers only international telephone number.
Once the validation of the selfservice can handle any format we need to remove this formatting.

PP-4759 international phone number support backward compatibility - part 2

---

app/assets/sass/application.scss
app/assets/sass/components/links-box.scss
app/assets/sass/components/links-container.scss
app/controllers/dashboard/dashboard-activity-controller.js
app/controllers/dashboard/dashboard-activity-controller.test.js
app/views/dashboard/_links.njk
test/cypress/integration/dashboard/dashboard_links_spec.js
test/cypress/integration/dashboard/dashboard_spec.js
test/cypress/plugins/stubs.js
test/cypress/utils/common_stubs.js
test/fixtures/gateway_account_fixtures.js
test/integration/login_controller_test.js
test/ui/navigation_ui_tests.js

Move logic for deciding which links will be displayed from the Nunjucks template to the controller. This allows us to know how many links will be displayed, and so format them correctly into either 2 or 3 columns with the correct borders on the links. This is required as the logic gets a bit more complicated when we add in the "request to go live" link
Move the decision for whether to display a bottom border on the links from the template, where we were conditionally adding a css class. We now have a css rule using the nth-child selector to decide whether a link box should have a border.
Add Cypress tests for displaying the links.

PP-4448 Modify logic for displaying links on dashboard

---

app/controllers/request-to-go-live/index/get.controller.js
app/views/policy/document-downloads/contract_for_non_crown_bodies.njk
app/views/policy/document-downloads/memorandum_of_understanding_for_crown_bodies.njk
app/views/request-to-go-live/index.njk
test/cypress/integration/request-to-go-live/agreement_spec.js
test/cypress/integration/request-to-go-live/index_spec.js
test/cypress/integration/request-to-go-live/organisation_name_spec.js

Show the next steps box saying we are creating the live service when the current go live stage is `AGREED_TERMS_STRIPE`, `AGREED_TERMS_WORLDPAY`, `AGREED_TERMS_SMARTPAY` or `AGREED_TERMS_EPDQ` and not when it’s `LIVE`.

PP-4846 Go live task list: show next steps box at right point

---

app/controllers/dashboard/dashboard-activity-controller.js
app/views/dashboard/_links.njk
test/cypress/integration/dashboard/dashboard_go_live_link_spec.js

Replace the "Next steps to go live" link with the "Request a live account" link for card accounts.
There are three variants of the link which are displayed under the following circumstances:
1. If the request to go live process has not been started, the "Request a live account" link is shown, which links to the request to go live status page.
2. If the request to go live process has been partially completed, the "Setting up your live account" link is shown, which links to the request to go live status page.
3. If the request to go live process has been completed, but the account has not yet been set up, the "Your live account" text is shown, which is not a link.
For direct debit accounts, the "Next steps to go live" link to the documentation is still shown, as before.

PP-4448 Add request to go live link to dashboard

---

app/models/StripeAccountSetup.class.js
app/services/clients/connector_client.js
test/fixtures/stripe_account_setup_fixtures.js
test/unit/clients/connector_client/connector_get_stripe_account_setup_test.js
test/unit/clients/connector_client/connector_set_stripe_account_setup_flag_test.js

Add method to connector_client to call the GET stripe account setup endpoint. The response of this request is mapped into a new StripeAccountSetup model.
Add method to call the PATCH stripe account setup endpoint to set a flag for an account setup task being completed.
Add pact tests for these interactions.

PP-4462 Add client methods to get and update Stripe setup flags

---

app/browsered/field-validation-checks.js
app/browsered/field-validation.js
app/controllers/live-account-setup/bank-details/bank-details-validations.js
app/controllers/live-account-setup/bank-details/bank-details-validations.test.js
test/unit/browsered/field_validation_checks_test.js

Add validation checks to be used by both the client-side javascript validation and the server side validation to validate the account number and sort code.
Add bank-details-validation.js which will be used by the controller to perform the server-side validation.
with @DanailMinchev

PP-4462 Add bank details validation

---

app/routes.js
test/fixtures/user_fixtures.js

Use more granular permissions for Stripe setup pages and use `update` permission for all of the request to go live pages, except index page which makes sense to allow users with `read` permission to see the status

PP-4462 bank details page new permissions

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/views/stripe-setup/bank-details/check-your-answers.njk
app/views/stripe-setup/bank-details/index.njk
test/cypress/integration/stripe-setup/bank_details_spec.js

Add template for the confirm your answers page.
Add logic to the bank details post controller to handle navigation
back to the index page to change bank details or to submit the details
based on a hidden form field.
with @DanailMinchev

PP-4462 Add bank details confirm your answers page

---

app/middleware/stripe-setup/check-bank-details-not-submitted.js
app/middleware/stripe-setup/check-bank-details-not-submitted.test.js
app/middleware/stripe-setup/restrict-to-live-stripe-account.js
app/middleware/stripe-setup/restrict-to-live-stripe-account.test.js

This PR adds two middelwares which can be used for Stripe setup page validations:
- Restrict to live Stripe account middleware
- Check bank details not submitted middleware

PP-4462 Stripe setup middlewares

---

app/browsered/field-validation.js

Improve the error summary when it’s created by JavaScript running in the browser and there are errors with fields that have labels that are entirely visually hidden:
- Add support for a new `data-validate-override-label` attribute on a form field `label` element. The value of this attribute is the ID of another form field. When building the error summary, the label belonging to this other form field will be used instead of the original form field’s label. This is intended to be used when the original form field’s label is entirely visually hidden but another form field’s label accurately describes it (e.g. the second line of a postal address, where the label for the first line also works for the second).
- In the error summary, filter the list of field labels so that only the first field …

PP-4463 Better JS error summaries for fields with hidden labels

---

app/controllers/stripe-setup/bank-details/get.controller.js
app/controllers/stripe-setup/bank-details/post.controller.js
app/routes.js
test/cypress/integration/stripe-setup/bank_details_spec.js
test/cypress/plugins/stubs.js

Stripe setup: apply restrictToLiveStripeAccount and checkBankDetailsNotSubmitted middelwares
- Apply restrictToLiveStripeAccount middleware which is restricting the access to only live Stripe accounts
- Apply checkBankDetailsNotSubmitted middelware which is checking if the bank details were already submitted

PP-4462 Stripe setup: apply restrictToLiveStripeAccount and checkBankDetailsNotSubmitted middelwares

---

app/services/clients/stripe/stripe_client.js

- Set Stripe API version to latest `2019-02-19` version in the SDK client,
because we want to use latest version and not the one which is currently
set on a global account level (in the Stripe Dashboard).
- Later, once we have migrated to the new version (including `pay-connector` and `webhooks`)
we should remove this header

PP-4462 Set Stripe API version in the client

---

app/models/StripeAccount.class.js
app/services/clients/connector_client.js
test/fixtures/stripe_account_fixtures.js
test/unit/clients/connector_client/connector_get_stripe_account_test.js

- Add `getStripeAccount()` method to connector client which is querying
`/v1/api/accounts/{accountId}/stripe-account` endpoint to retrieve
associated Stripe Account ID from the gateway account
- Add related Pact interactions

PP-4462 Add getStripeAccount() method to connector client

---

app/browsered/field-validation-checks.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
app/views/stripe-setup/responsible-person/index.njk

Our current client-side (in-browser) validation framework isn’t flexible enough to support the level of date of birth validation we want on the Stripe responsible person page. If we had this date of birth validation only in the server-side code then the page would behave strangely if there were multiple errors (some would be caught client-side, others wouldn’t be caught until the form is actually POSTed to the server).
Remove the client-side validation for the responsible person page to avoid the issue. The validation was only applied when the user pressed the submit button (as opposed to when the focus leaves the field, for example), so the server-side validation offers the same experience, just a little slower.
Move the postcode validation logic out of JavaScript that gets served to …

PP-4463 Remove responsible person client-side JavaScript validation

---

app/browsered/field-validation.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.test.js
app/views/stripe-setup/responsible-person/index.njk

Add server-side validation for the date of the birth on the Stripe responsible person page. Requires a date of birth in past and uses the error messages described in the GOV.UK Design System at https://design-system.service.gov.uk/components/date-input/.

PP-4463 Server-side responsible person date of birth validation

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.test.js
app/views/stripe-setup/responsible-person/check-your-answers.njk

- On the Stripe responsible person page, make it so that if someone enters a date of birth that is otherwise valid but does not use a four-digit year, a specific “Date of birth must have a four-digit year” error message is shown.
- Name some anonymous functions.
- Trim whitespace from the beginning and the end of the responsible person form submission. This has the desired side-effect that all-whitespace fields will fail validation in the same way empty ones do.
- If a form submission to the Stripe responsible person page does not contain a field at all, default it to the empty string. If the field is mandatory, the existing validation will fail, which is what we want.
- On the check answers page, don’t show a blank line if there is no address line 2 and format the date of birth nicely …

PP-4463 Tidy up responsible person form

---

app/views/includes/footer-categories.njk

We’ve established that “Crown” should always begin with a capital letter (see https://www.gov.uk/bona-vacantia for example) and we use an initial capital elsewhere in the admin tool.

Capitalise the first letter of “Crown” in the footer

---

app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.test.js
app/views/stripe-setup/responsible-person/index.njk

- On the form, change “Before you can make any payments” to “Before you can take any payments”
- Change the error message when the user does not enter a four-digit date of birth from “Date of birth must have a four-digit year” to “Year must have 4 numbers”

PP-4463 Responsible person page copy changes

---

app/views/digital-wallet/_digital_wallet_not_supported_message.njk
app/views/digital-wallet/enable-apple-pay.njk
app/views/digital-wallet/enable-google-pay.njk
app/views/digital-wallet/summary.njk
test/ui/digital_wallet_ui_tests.js

Fixes an edge case whereby if a non-supported gateway user discovers the digital-wallet URL they can enable digital wallet. 
Go to `/digital-wallet` as a non worldpay user should show not supported message.
Note: The additional tests only test the negative path as we already have happy path Cypress tests for these routes.

PP-4819: do not display option to enable wallet for not supported gateways

---

app/services/clients/stripe/stripePerson.model.js
app/services/clients/stripe/stripePerson.model.test.js
app/services/clients/stripe/stripe_client.js

Add `StripePerson` model object, which represents the details about a responsible person in the format that the Stripe Connect Persons API expects.

PP-4463 Add StripePerson model object for use with Stripe client

---

app/controllers/stripe-setup/responsible-person/get.controller.js
app/middleware/stripe-setup/check-responsible-person-not-submitted.js
app/middleware/stripe-setup/check-responsible-person-not-submitted.test.js

Middleware to check that the Stripe responsible person flag is not already set before allowing access to the page.
Heavily based on the equivalent middleware for the bank account details flag.

PP-4463 Middleware to check responsible person flag not set

---

package-lock.json
package.json

Not everyone has linter plugins installed in their chosen editors, this means PRs fail on Jenkins for silly things like curly bracket spacing or identation.
This PR adds Husky a git hooks tool and lint-staged which make it easy to automatically lint all JS changes that have been staged for commit. If it spots errors it can fix it does or throws an error detailing what needs changing.
This will help improve the quality of code we’re shipping.

PP-4904 - Add husky and lint-staged

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js

- Before it was using `rawAccountNumber` instead of `sanitisedAccountNumber` which was copied by mistake.
- The `rawAccountNumber` will still be valid as `sanitisedAccountNumber` are the same in terms of valid value handled by validation

PP-4462 Use sanitised account number for Stripe bank account submission

---

app/services/clients/connector_client.js
test/integration/transaction_download_ft_tests.js

- Resolves full connector URL from pagination link (next_page) to fetch all transactions from connector
- `next_page` reference from connector can now be full_url (http://connector/v2/...) or only context (/charges)
_**Part of removing reliance of selfservice on connector to provide URL to traverse through transactions**_
Currently, connector provides pagination urls (full URLs based on injected UriInfo) when queried for transactions. The URLs generated by connector have wrong port number (unknown to selfservice). As the selfservice is aware of connector URL it only needs to know URI context to traverse through pagination links.
All tests should pass

PP-4735 Resolve Connector URL

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
app/controllers/stripe-setup/responsible-person/responsible-person-validations.test.js

• The `uk-postcode` package we use strips all non-alphanumeric characters from postcodes, so if someone enters “AB!1 2CD” (trying to enter “AB11” but holds down the shift key too long), `uk-postcode` will treat like as “AB1 2CD”, which will validate successfully even though the user made a mistake. Work around this by checking that the input consists only of alphanumeric characters and spaces before passing to `uk-postcode`.
• When presenting the postcode to the user on the check answers page, normalise it (so “ab112cd” will become “AB11 2CD”).

PP-4463 Responsible person home address postcode tweaks

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js

When the user successfully fills in the responsible person form, send the details to Stripe via the Stripe SDK (2019-02-19 API version) and tell connector to flip the flag saying that the details have been submitted for this gateway account.
Add tests for this part of the controller (other parts of the controller — validation, navigation back and forth between the form and the check answers page etc. — will be tested by Cypress tests).

PP-4463 Send responsible person details to Stripe

---

app/views/stripe-setup/responsible-person/index.njk

The IDs were kind of long and the way the date input component concatenates IDs resulted in ones that were a bit weird.
The IDs largely match the names of the fields now.

PP-4463 Rename some IDs on the Stripe responsible person form

---

app/services/clients/connector_client.js
app/services/service_service.js
test/unit/services/service_service_test.js

- connector service name is actually used by email notification

PP-4926 revert changes not to send service name to connector

---

app/controllers/edit_merchant_details/get-index-controller.js
test/fixtures/service_fixtures.js
test/unit/controller/edit_merchant_details_controller/get-index.test.js

When organisation details are incomplete, i.e. name or mandatory address fields are not present, take the user to the edit details page with existing details pre-filled rather than the view details page. This
fixes the 500 error thrown when the country code was not set on the view details page.

PP-4939 Fix error navigating to Organisation Details when name is set

---

app/paths.js
app/routes.js
test/cypress/integration/stripe-setup/responsible_person_spec.js
test/fixtures/user_fixtures.js

- Add routes and paths so the Stripe responsible person page is generally available
- Add Cypress tests for responsible person page
I know it’s large but it’s mostly fairly short, independent Cypress tests.

PP-4463 Responsible person page: paths, routes and Cypress tests

---

app/middleware/stripe-setup/check-vat-number-company-number-not-submitted.js
app/middleware/stripe-setup/check-vat-number-company-number-not-submitted.test.js

- Add `check-vat-number-company-number-not-submitted` middleware which checks [vat_number_company_number](https://github.com/alphagov/pay-connector/blob/20c4e66c45f96d2663884596c2be8ce24b9c1074/src/main/java/uk/gov/pay/connector/gatewayaccount/model/StripeAccountSetup.java#L18) flag is not `true` when querying [/v1/api/accounts/{accountId}/stripe-setup](https://github.com/alphagov/pay-connector/blob/20c4e66c45f96d2663884596c2be8ce24b9c1074/src/main/java/uk/gov/pay/connector/gatewayaccount/resource/StripeAccountSetupResource.java#L42) endpoint.

PP-4949 Check VAT number company number not submitted middleware

---

app/controllers/request-to-go-live/organisation-address/get.controller.js
app/controllers/request-to-go-live/organisation-address/index.js
app/paths.js
app/routes.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/request-to-go-live/organisation_address_spec.js

- Add get controller and route for organisation address page.
- Add template for page.
- Add cypress tests for the page rendering correctly and pre-filling
existing organisation details.
- The elements for validation errors have been added but server-side
validation has not been set up or tested as part of this commit.

PP-4976 Add organisation address page

---

app/middleware/stripe-setup/check-responsible-person-not-submitted.js
app/middleware/stripe-setup/check-responsible-person-not-submitted.test.js
app/views/stripe-setup/responsible-person/index.njk

- Remove “Before you can take payments” heading from page
- Add period to end of error message shown if responsible person already nominated

PP-4463 Minor content tweaks for Stripe responsible person page

---

app/controllers/register_service_controller.js
app/controllers/register_user_controller.js
app/middleware/otp_verify.js
app/middleware/validate_registration_invite_cookie.js
app/utils/registration_validations.js
app/utils/validation/telephone-number-validation.js
app/utils/validation/telephone-number-validation.test.js
test/unit/controller/register_service_controller/register_service_controller_test.js
test/unit/utils/registration_validations_test.js

- Extract the phone number validation out of registration_validations into its own module telephone-number-validation so it can be re-used for validating other forms.
- Fix promise reject calls not returning an error in registration_validations which was rejected by linter.
We manually tested the following scenarios to check the errors are still displayed correctly to the user:
1. Enter invalid inputs for fields on register new service page
2. Enter invalid OTP code (not numbers) for validate OTP for service invite
3. Enter invalid telephone number on resend OTP code for service invite
1. Enter invalid input on invite user form
2. Enter invalid OTP code (not numbers) for validate OTP for user invite
3. Enter invalid telephone number on resend OTP code for user invite

PP-4976 Extract telephone number validation to its own module

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/utils/validation/server-side-form-validations.js
app/utils/validation/server-side-form-validations.test.js

- Move and rename responsible-person-validations to server-side-form-validations as most of these validations can be reused for the organisation address page.
- Add method to validate phone number field to server-side-form-validations
- Modify validate PostCode method to take a countryCode and only perform UK postcode validation for country code GB

PP-4976 Move server side validations so they can be reused

---

app/services/clients/stripe/stripeBankAccount.model.js
app/services/clients/stripe/stripeBankAccount.model.test.js
app/services/clients/stripe/stripePerson.model.js
app/views/stripe-setup/bank-details/check-your-answers.njk
app/views/stripe-setup/bank-details/index.njk
app/views/stripe-setup/responsible-person/check-your-answers.njk
app/views/stripe-setup/responsible-person/index.njk
test/cypress/integration/stripe-setup/bank_details_spec.js
test/cypress/integration/stripe-setup/responsible_person_spec.js

- Modified Stripe setup Cypress tests to use `within` function and use `ids` for forms
- Changed bank details Cypress test to use rest parameter syntax as in responsible person tests
- Removed `stripe-setup-` prefix from template ids, because it was too long
- Use `optional()` explicitly to document that the field is optional in models
- Remove normalisation from the models as it is handled in the controllers
- Other cosmetic changes
Co-authored-by: Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk> / @cobainc0

PP-4949 Various code improvements

---

app/controllers/request-to-go-live/organisation-address/index.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/routes.js
app/views/request-to-go-live/organisation-address.njk
test/cypress/integration/request-to-go-live/organisation_address_spec.js

Add post controller for the organisation page with server-side validation. Currently this will not submit the organisation details if validation is not successful.
Use error messages produced by the validation in the template, rather than error messages hardcoded in the template.
Co-authored-by: @SandorArpa

PP-4976 Add validation for organisation address page

---

app/controllers/edit_merchant_details/post-edit-controller.js
app/controllers/request-to-go-live/organisation-name/post.controller.js
app/models/ServiceUpdateRequest.class.js
app/models/ServiceUpdateRequest.class.test.js
app/services/ServiceUpdateRequest.class.js
app/services/clients/adminusers_client.js
app/services/service_service.js
test/unit/clients/adminusers_client/service/update_service_test.js

Replace updateMerchantDetails method with a more general updateService method. This updateService method can be used for all service update patch requests, and should replace other methods that make these requests.
Add a ServiceUpdateRequest model to construct the request payload with ops and paths defined as constants.

PP-4976 Use a model to construct update service requests

---

test/cypress/integration/dashboard/dashboard_go_live_link_spec.js
test/cypress/integration/dashboard/dashboard_links_spec.js
test/cypress/integration/dashboard/dashboard_spec.js
test/cypress/integration/request-to-go-live/agreement_spec.js
test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
test/cypress/integration/request-to-go-live/index_spec.js
test/cypress/integration/request-to-go-live/organisation_name_spec.js
test/cypress/integration/settings/allow_apple_pay_spec.js
test/cypress/integration/settings/allow_google_pay_spec.js
test/cypress/integration/settings/email_notifications_spec.js
test/cypress/integration/settings/merchant_details_spec.js
test/cypress/integration/stripe-setup/bank_details_spec.js
test/cypress/integration/stripe-setup/responsible_person_spec.js
test/cypress/integration/transactions/transaction_details_spec.js
test/cypress/integration/transactions/transaction_search_spec.js
test/cypress/integration/user/login_spec.js
test/cypress/plugins/index.js
test/cypress/utils/request_to_go_live_utils.js

Meant to just rename a method in request_to_go_live_utils but mistakenly propagated the rename too far. Fixed this.

PP-4976 Fix cypress setupStubs task accidentally renamed

---

app/controllers/edit_merchant_details/get-edit-controller.js
app/controllers/edit_merchant_details/post-edit-controller.js
app/controllers/request-to-go-live/organisation-address/post.controller.js
app/utils/validation/server-side-form-validations.js
app/utils/validation/server-side-form-validations.test.js
app/views/merchant_details/edit_merchant_details.njk
test/cypress/integration/request-to-go-live/organisation_address_spec.js
test/unit/controller/edit_merchant_details_controller/post-edit.test.js

- Make validation pattern match that for the new request to go live organisation address page
- Use async/await in post-edit-controller and handle all errors
- Move the setting of some session variables for the get controller to a better place
- Modify tests to be unit tests rather than integration tests
- Add improved tests for checking the update of merchant details

PP-4976 Improve organisation details page post controller

---

app/controllers/request-to-go-live/choose-how-to-process-payments/get.controller.js
app/controllers/request-to-go-live/go-live-stage-to-next-page-path.js
app/controllers/request-to-go-live/index/get.controller.js
app/views/request-to-go-live/index.njk
test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
test/cypress/integration/request-to-go-live/index_spec.js
test/cypress/integration/request-to-go-live/organisation_name_spec.js
test/unit/controller/request-to-go-live/go-live-stage-to-next-page-path.test.js

- Completing the "Organisation Name" page will now direct the user to
the "Organisation Address" page.
- The "Choose How To Process Payments" page now expects the go live
stage to be "ENTERED_ORGANISATION_ADDRESS"
- When the user has entered the organisation name, but not the address,
the progress label in the task list is "IN PROGRESS"

PP-4983 Include organisation address in request to go live flow

---

app/controllers/edit_merchant_details/post-edit-controller.js
app/views/merchant_details/edit_merchant_details.njk
test/cypress/integration/settings/merchant_details_spec.js
test/unit/controller/edit_merchant_details_controller/get-edit.test.js

The 'errors' object returned by the post controller now contains error messages as the values, where previously there was just a boolean to indicate there was an error.
Use these error messages in the template rather than the existing static text.
This modifies some of the error messages, but makes them more consistent with the design system.

PP-4976 Use controller errors on the edit merchant details page

---

app/browsered/field-validation-checks.js
app/browsered/field-validation.js
app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.js
app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.test.js
test/unit/browsered/field-validation-checks.company-number.test.js

Validation for company numbers, accepting these formats:
01234567 (England and Wales limited company: 0 then 7 digits)
OC123456 (England and Wales LLP: OC then 6 digits)
LP123456 (England and Wales limited partnership: LP then 6 digits)
SC123456 (Scotland limited company: SC then 6 digits)
SO123456 (Scotland LLP: SO then 6 digits)
SL123456 (Scotland limited partnership: SL then 6 digits)
NI123456 (Northern Ireland limited company: NI then 6 digits)
R0123456 (NI pre-partition limited company: R0 then 6 digits)
NC123456 (NI LLP: NC then 6 digits)
NL123456 (NI limited partnership: NL then 6 digits)
Any number of spaces are allowed anywhere and the case of the letters does not matter.
Certificates of incorporation for limited companies in England and Wales do not include the initial 0 in the …

PP-4949 Company number validation

---

app/services/clients/adminusers_client.js
test/fixtures/service_fixtures.js

When creating a new service, don’t send the `"name"` property in the JSON payload. Continue sending an appropriate `"service_name"` property, which adminusers will also pick up.

PP-5061 Don’t send "name" property to adminusers for new service

---

app/controllers/payment-links/get-information-controller.js
app/models/supported-language.js
app/views/payment-links/information.njk
test/cypress/integration/payment-links/create_payment_link_spec.js

- Add a supported-language enum to hold the supported language values.
- Display the "/create-payment-link/information" page with Welsh specific instructions if the query parameter "language=cy" is provided.
- Add Cypress tests covering the information page.

PP-5013 Display Welsh specific instructions on payment link information page

---

app/controllers/payment-links/get-information-controller.js
app/controllers/payment-links/get-reference-controller.js
app/controllers/payment-links/post-information-controller.js
app/views/payment-links/reference.njk
app/views/payment-links/review.njk
test/cypress/integration/payment-links/create_payment_link_spec.js
test/unit/controller/payment-links/get_reference_controller.test.js

- Store whether the payment link is Welsh in the session for the payment link flow.
- When displaying the "reference" page of the create payment link flow, get whether the payment link is Welsh from the session and use this to display Welsh-specific instructions if the value is true.
- Add cypress tests for the reference page.

PP-5013 Add Welsh instructions on payment link reference and review pages

---

app/controllers/digital-wallet/post-enable-google-pay-controller.js

use `async` `await` to order Google Pay PATCH requests 
Previously we were using `Promise.all` this caused a potential race condition where one PATCH happened before the other completed causing an exception in Connector.
Cypress tests should pass, functionality should work reliably on environment.

PP-4819: use async await to order Google Pay requests

---

app/browsered/field-validation-checks.js
test/unit/browsered/field-validation-checks.vat-number.test.js

Be more strict about the rules for VAT numbers:
• “GB” then 9 digits (standard)
• “GB” then 12 digits (branch trader)
• “GBGD” then a number from 000 to 499 (government departments)
• “GBHA” then a number from 500 to 599 (health authorities)

PP-4949 Improve VAT number validation

---

app/controllers/digital-wallet/post-enable-google-pay-controller.js

Bug fix after #1372 
PATCH requests were in the wrong order! We should PATCH the Gateway Account ID first so that if it is invalid the boolean is not enabled.
Tests should pass, ordering should make sense.

swap order of Google Pay patches

---

app/controllers/stripe-setup/vat-number-company-number/check-your-answers/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/company-number/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/company-number/post.controller.js
app/controllers/stripe-setup/vat-number-company-number/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/vat-number/post.controller.js
test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/index_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/navigation_spec.js

- If user tries to go further forward than they should (e.g. go to company number page when not entered VAT number), take them back to the right place
- If user goes from check answers to change VAT number, take them directly back to check answers, skipping company number because they’ve already entered it
- Tests for the above navigation and also tests to make sure the user can go back to an earlier page in the flow
Co-Authored-By: Alex Bishop <alexbishop1@users.noreply.github.com>

PP-4949 Add non-linear navigation for VAT number and Company Number pages

---

app/controllers/stripe-setup/vat-number-company-number/check-your-answers/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/check-your-answers/post.controller.test.js
app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.js
app/controllers/stripe-setup/vat-number-company-number/company-number/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/company-number/post.controller.js
app/controllers/stripe-setup/vat-number-company-number/get.controller.js
app/controllers/stripe-setup/vat-number-company-number/vat-number/post.controller.js
app/views/stripe-setup/vat-number-company-number/company-number.njk
test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/index_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/navigation_spec.js

Rename `companyNumberMode` (and variants) to `companyNumberDeclaration` to better reflect its purpose (storing the service’s answer — or declaration — of whether they have a company number or not).
Also change the possible values from the strings `"yes"` or `"no"` to the strings `"true"` or `"false"`.
Co-Authored-By: Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>

PP-4949 Rename companyNumberMode to companyNumberDeclaration

---

app/views/stripe-setup/vat-number-company-number/company-number.njk
app/views/stripe-setup/vat-number-company-number/vat-number.njk

- Use curly quotes around example input next to form fields
- Don’t quote attribute names in Nunjucks macros unless necessary
- Add `spellcheck="false"` to VAT number and company number inputs
Co-Authored-By: Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>

PP-4949 Minor Stripe VAT number and company number page changes

---

app/browsered/field-validation-checks.js
app/browsered/field-validation.js
app/views/stripe-setup/vat-number-company-number/company-number.njk
test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js

Disable client-side JavaScript validation of company number because it will validate the contents of the company number field even if the user has changed their mind and said they do not have a company number. The server-side validation, which remains in place, is more sophisticated and does not suffer from this deficiency.
Add a test for the above scenario.

PP-4949 Disable client-side validation of company number

---

app/controllers/payment-links/post-review-controller.js
app/services/clients/products_client.js
test/fixtures/product_fixtures.js
test/unit/clients/product_client/product/create_test.js
test/unit/controller/payment-links/post_review_controller.test.js

Send language when creating a payment link, getting the language from whether the payment link is Welsh or not.
When no language is provided to the create product client, such as for creating a demo payment, default to English.

PP-5012 Send language when creating product

---

app/controllers/payment-links/get-amount-controller.js
app/views/payment-links/amount.njk
app/views/payment-links/information.njk
app/views/payment-links/reference.njk
test/cypress/integration/payment-links/create_payment_link_spec.js

We decided we do not want to display these examples for Welsh payment link creation as they are in English

PP-5012 Remove examples for Welsh payment links

---

app/views/payment-links/edit.njk

This hidden field was not used and was causing NAXSI to block if there were any special characters in the service name, as the service name was not whitelisted for this URL

PP-5012 Remove service-name field on edit payment link

---

app/services/clients/connector_client.js

Connector is already capable of handling Strings and Booleans. But we would like to use true booleans in place of "boolean strings". 
Solo: @cobainc0

PP-5108 Use true booleans instead of strings

---

app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js
app/services/clients/stripe/stripe_client.js

Stripe creates a blank "person" on a test account when it is created. Therefore rather than creating a new person, we need to update the existing person.
We update the final person returned when we call Stripe to list the persons as this will be the first person created.

PP-5153 Update existing Stripe person

---

test/mocha.opts

We get the docker build stage of CI builds failing regularly due to a timeout when running tests which use pact interactions.
Increasing the timeout from the default of 2s to 5s to hopefully avoid this happening so regularly.

BAU Increase timeout for mocha tests

---

app/views/transaction_detail/_metadata.njk
app/views/transaction_detail/index.njk
test/cypress/integration/transactions/transaction_details_spec.js
test/fixtures/transaction_fixtures.js

Add metadata to transactions details page, should not show if there is no metadata for the charge.

PP-4889 Add metadata to transaction detail page.

---

app/assets/sass/components/dashboard-activity.scss

We were using greys to show hover and focus. This isnt great because the
contrast is low and also worsens the text contrast. Using a yellow
outline mimics the standard behaviour and increase contrast.

BAU - improve hover and focus styles for dashboard total links

---

app/views/transaction_detail/_details.njk
test/cypress/integration/transactions/transaction_details_spec.js
test/fixtures/transaction_fixtures.js

Self service currently just fetches the charge end point for any
transaction -- this means that refunds are displayed with the charges
`fee` and `net_amount` columns. This factors this in until a more
specific method of searching for refunds or charges is implemented.

PP-4997: hide fee and net amounts for refund details

---

test/fixtures/gateway_account_fixtures.js
test/unit/clients/connector_client/connector_patch_apple_pay_toggle_test.js
test/unit/clients/connector_client/connector_patch_google_pay_toggle_test.js

Add pact tests for gateway accounts supporting digital wallets
- connector now expects boolean values for `allow_google_pay` & `allow_apple_pay` flags
Solo: @cobainc0

PP-5108 Add pact tests for wallet payments

---

app/utils/json_to_csv.js

Ensure net amount is negative for CSV downloads if the transaction is a
refund. Not how it could potentially be best represented but done this
way for consistency.

PP-4997 Negative net amount following standard

---

app/views/transactions/filter.njk

Small but embarrassing mistake

BAU - use an not a as word after is option

---

app/views/payment-links/information.njk

Details shouldn’t have an error label because it’s optional

BAU - Details has title error label

---

app/views/transaction_detail/_details.njk

We were incorrectly showing a timeout error message to users, so this
change will display an appropriate system cancellation message in the
transaction `detail` template
Solo: @cobainc0

PP-5112 Fix System cancelled error message

---

app/views/transaction_detail/_details.njk
test/cypress/integration/transactions/transaction_details_spec.js

- On the transaction details page, we were checking whether the transaction_type of the charge was a 'refund' to decide whether to display the 'PSP fee' row. However, the connector charge endpoint does
not return this field, so this check always resolves as true.
- The cypress test for this was passing because it was using an incorrect fixture which was not validated by a pact test, which will be amended in a separate PR.

PP-5199 Remove transaction type check for displaying psp fee

---

test/cypress/integration/transactions/transaction_details_spec.js
test/fixtures/transaction_fixtures.js
test/unit/clients/connector_client/connector_get_transaction_details_test.js
test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js

* Set the provider to "selfservice" and make the Pact states match the states that exist in connector.
* Modify test fixtures so they produce the correct pacts.
* Modify Cypress tests to work with the modified fixtures.

PP-5199 Enable transactions pact tests

---

app/routes.js
app/utils/navBuilder.js
test/fixtures/user_fixtures.js
test/integration/partnerapp/handle_redirect_to_gocardless_connect_test.js
test/ui/navigation_ui_tests.js

- Resolving gateway account was failing when navigating to the link account page, as the get gateway account middleware was expecting the service to have already been resolved. It then ended up resolving the wrong gateway account. The permissions middleware resolves the service so adding this to the stack fixes the issue.
- Use a new specific permission that was added for accessing this setting.
- Simplify navigation_ui_tests by having just 2 tests to check that the correct links are shown for card/direct debit gateway accounts when the user has all permissions.
Co-authored-by: Rory Malcolm <rory.malcolm@digital.cabinet-office.gov.uk>

PP-5193 Check permission for link gocardless account

---

app/middleware/get_gateway_account.js
test/unit/middleware/get_gateway_account_test.js

We support 3DS for ePDQ and Smartpay, and no longer need these flags

PP-5281 Remove {EPDQ,SMARTPAY}_3DS_ENABLED feature flags

---

app/routes.js

This stops the cookie message showing all the time, the route wasnt
accessible because the controller required things only accessible within
auth so it errored because it couldnt resolve

PP-5185 - settings needs to be included within authenticated paths

---

app/utils/navBuilder.js
test/ui/navigation_ui_tests.js

There is no settings index for Direct Debit so we need to link to the
first available setting, API keys.

PP-5185 - Settings link is set dependent on payment Type

---

app/views/includes/phase_banner.njk

So right now it says 'Test Account' or 'Live account' can just be 'Test' and 'Live'

PP-5339 - remove account from phase tag so it's just live or test

---

app/utils/navBuilder.js
test/ui/navigation_ui_tests.js

- Linking a Go Cardless account for a direct debit gateway account is now done by clicking a button on the dashboard, so remove the old link on the settings page to initiate this.

PP-5266 Remove link Go Cardless account settings link

---

app/views/dashboard/demo-payment/edit-amount.njk
app/views/login/otp-login.njk
app/views/payment-links/amount.njk
app/views/payment-links/edit-amount.njk
app/views/stripe-setup/bank-details/index.njk
app/views/transactions/filter.njk
app/views/twoFactorAuth/configure.njk

The Design System team have done some accessibility testing on `input
type="number"` and deemed them problematic. They have suggested using
`input type="text" inputmode="numeric" pattern="[0-9]*"`
instead as documented here https://github.com/alphagov/govuk-frontend/issues/1449

PP-5366 - use inputmode and pattern attribute on numeric fields

---

app/views/login/otp-login.njk
app/views/transactions/filter.njk
app/views/twoFactorAuth/configure.njk

In some modern browsers when a pattern attribute is added a native
browser message pops up and blocks form submission. They’re not helpful
and just suppress our more helpful error messages.
Thanks @nickcolley for the tip https://github.com/alphagov/govuk-design-system/issues/941#issuecomment-506286337

PP-5366 - Suppress native browser validation

---

app/assets/sass/components/phase-tag.scss
app/views/includes/feedback-banner.njk
app/views/includes/header.njk

Having it up top raises more questions than it answers. This way gives
in a little more context

PP-5382 - move beta tag from header to footer

---

app/views/team-members/edit-phone-number.njk

Because http://notaverb.com/login and https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#sign-in-or-log-in

PP-5384 Change “login” to “sign in” on phone number change page

---

test/fixtures/transaction_fixtures.js

Pacts should not be written expecting values to be null. Pacts
are about the subset of a response that is necessary for the
consumer. Unless the consumer postively uses the fact that a
value is null, it should not write it in to the contract.

PP-5355 Don't add null to pact

---

app/views/dashboard/index.njk
app/views/digital-wallet/apple-pay.njk
app/views/digital-wallet/google-pay.njk
app/views/feedback/index.njk
app/views/payment-links/_nav.njk
app/views/payment-links/amount.njk
app/views/payment-links/edit-amount.njk
app/views/payment-links/edit-reference.njk
app/views/payment-links/edit.njk
app/views/payment-links/index.njk
app/views/payment-links/information.njk
app/views/payment-links/reference.njk
app/views/payment-links/review.njk
app/views/payment-links/web-address.njk
app/views/request-to-go-live/agreement.njk
app/views/request-to-go-live/choose-how-to-process-payments.njk
app/views/request-to-go-live/index.njk
app/views/request-to-go-live/organisation-address.njk
app/views/request-to-go-live/organisation-name.njk
app/views/stripe-setup/bank-details/check-your-answers.njk
app/views/stripe-setup/bank-details/index.njk
app/views/stripe-setup/responsible-person/check-your-answers.njk
app/views/stripe-setup/responsible-person/index.njk
app/views/stripe-setup/vat-number-company-number/check-your-answers.njk
app/views/stripe-setup/vat-number-company-number/company-number.njk
app/views/stripe-setup/vat-number-company-number/vat-number.njk
app/views/transactions/index.njk

As of PR #1555 we don’t need this extra margin between the body and the
phase banner as it’s handled automatically by the design system.

BAU - remove extra margin from page content

---

app/controllers/partnerapp/handle_redirect_to_gocardless_connect.js
app/views/dashboard/_connected-to-gocardless.njk
app/views/dashboard/_link-to-gocardless.njk
app/views/dashboard/index.njk
app/views/oauth/gocardless_complete.njk
test/cypress/integration/dashboard/dashboard_gocardless_spec.js
test/cypress/integration/partnerapp/handle_redirect_from_gocardless_spec.js
test/cypress/integration/partnerapp/handle_redirect_to_gocardless_spec.js
test/integration/partnerapp/handle_redirect_to_gocardless_connect_test.js

Update the copy on the dashboard and the page we show when the connect process is complete for GoCardless accounts.
Return a 404 and render the 404 page if the account isn't a direct debit account rather than just returning a 400.
Specification for copy: https://docs.google.com/document/d/1cFX_-FjLW7aGEHm8XKL88ltVBmVd5_5wHHQhpmogMvk/edit?ts=5d025a82

PP-4437 Update copy for GoCardless connect

---

Dockerfile

By having bash as PID 1, we have a problem. Signals sent to the container (e.g.
SIGTERM to shut it down) will not reach npm - bash will not pass them on. This
means that shutting the container down is done uncleanly. Once the SIGTERM is
ignored, the container orchestrator will then send a SIGKILL and forcibly exit
the process.
We could make npm PID 1 instead but this creates further problems - If npm
creates any child processes and those processes (or any of their children) die,
npm will be the parent of them and will not know to waitpid() on them, so they
will remain zombies forever.
tini solves these problems - it will correctly reparent orphaned child
processes and pass signals through to npm.

RED-116: Use tini in docker to run node

---

app/assets/sass/components/environment-tag.scss
app/assets/sass/components/header.scss

In the past we used yellow to denote test accounts but this was not
really kosher, but we got away with it. Now the yellow is way more
yellow it looks pretty out there so we’re switching to grey.
This will all get redesigned entirely soon so its just temporary

PP-5560 - Yellow should only be used for focus

---

cypress.json

Videos add a time overhead to test runs and we never look at them.
Disable them to speed up ci builds.

BAU Disable cypress videos

---

test/fixtures/ledger_transaction_fixtures.js
test/unit/clients/ledger_client/ledger_get_transaction_events_test.js
test/unit/clients/ledger_client/ledger_pact_test_provider.js
test/unit/clients/ledger_client/ledger_search_transaction_test.js

- add pact tests
- create a pact provider helper class. This is needed so the tests can share the pre-configured ledger_client's port.
- update transaction fixtures accordingly

PP-5537 add get events and search ledger transactions pact tests

---

app/browsered/field-validation-checks.js

We can use a library function to parse URLs and extract their protocol rather
than relying on string manipulation.

Improve validation of HTTPS URLs

---

test/fixtures/ledger_transaction_fixtures.js
test/unit/clients/ledger_client/ledger_get_transaction_events_test.js
test/unit/clients/ledger_client/ledger_pact_test_provider.js

- add pact test that verifies the interaction between ledger and selfservice for get transaction events
- add relevant methods to fixtures
- add a provider class (wrapper around Pact). We don't want to refactor ledger_client to make port configurable for tests' sake. Using this provider allow us to share the pre-configured port between Ledger pact tests.
- refactor get transaction details test to use the new provider class

PP-5537 add Ledger get transaction events pact test

---

test/fixtures/ledger_transaction_fixtures.js
test/unit/clients/ledger_client/ledger_search_transaction_test.js

- add pact test to cover a transaction search between selfservice and ledger
- add new methods to fixtures

PP-5537 add search ledger transactions pact test

---

app/services/clients/ledger_client.js
app/services/clients/utils/ledger_legacy_connector_parity.js
test/unit/clients/ledger_client/ledger_search_transaction_test.js
test/unit/clients/ledger_client/legacy_connector_parity_util_test.js

- When searching transactions, payment related fields (card details, reference, gateway_transaction_id, and so on) are displayed for refund transaction.
Ledger now returns payment transaction as nested object for refund

PP-5657 Map Payment fields to Refunds

---

app/controllers/transactions/transaction_download_controller.js
app/services/clients/utils/ledger_legacy_connector_parity.js

CSV downloads are breaking on ledger path, ledger does not always
provide refund summary (if external user didn't submit refund). This
checks for that.

PP-5565 Fix refund summary not available CSV download

---

app/browsered/field-validation-checks.js
app/views/payment-links/information.njk

We were previously not allowing special characters which were whitelisted by NAXSI. Update the validation rule to only disallow characters that NAXSI will block, and update the error message
displayed to the user appropriately.
Also add the field validation to the "Details" field on the payment link information screen, as this would previously not warn if disallowed characters were entered and instead show a generic error page.

PP-5560 Loosen payment link validation

---

app/assets/sass/components/multi-select.scss

PP-5736 - Add accessible focus states to multi selects

---

app/utils/logger.js
app/utils/sentry.js
package-lock.json
package.json
server.js

Send error level log messages to Sentry. Using the log level to
control when messages are sent to Sentry seems intuitive and since we now
require a common logger throughout the application it offers a
convenient point to add Sentry.
Unhandled exceptions will be caught by the Sentry error middleware added
within server.js as per the guidlines when using Sentry with Express.
When initialising Sentry a beforeSend filter is added to remove the
request element from the event if it exists. The request element contains the
data from a failed request and this can include sensitive information such
as card numbers. We may want to introduce more refined filtering to allow
non-sensitive information from a failed request to go to Sentry at a
later date.
app/utils/sentry.js and more elements of …

PP-5755 Add Sentry

---

app/utils/sentry.js

When we enable Sentry we effectively override the original `error`
function on the logger so that we call `Sentry.captureException` before
proceeding to log the error by calling the original `error` function on
the logger. Since `logger.error` can be called with various arguments it
isn't sufficient to simple call `originalLogger.error(msg)` since this
can lose structured arguments of the form `logger.error( "some message",
{ key: "value" } )`. By passing the spread `arguments` that were
provided we should end up with the original log message had we not
inserted Sentry.
Furthermore, by creating the message for the `Error` we send to Sentry by
`JSON.stringify`'ing the arguments provided we capture richer
information than simplying taking only the message which would be
`arguments[0]`. …

PP-5755 Pass original logger.error arguments after Sentry

---

app/views/forgotten_password/new_password.njk
app/views/self_create_service/register.njk
app/views/user_registration/register.njk

Add the `autocomplete="new-password"` attribute where the user enters a new password. This gives a hint to web browsers and password managers that they shouldn’t automatically fill in a new password but that they might want to suggest a new randomly- generated new password.
References:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-new-password
https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands
https://hacks.mozilla.org/2019/10/firefox-70-a-bountiful-release-for-all/

Add autocomplete="new-password" attribute where appropriate

---

app/utils/display_converter.js
app/utils/format-PSP-name.js
app/views/includes/phase_banner.njk
server.js
test/cypress/integration/dashboard/dashboard_spec.js
test/cypress/integration/settings/email_notifications_spec.js
test/cypress/integration/transactions/transaction_details_spec.js
test/cypress/integration/transactions/transaction_search_spec.js
test/integration/get_gateway_account_ft_test.js
test/unit/utils/format-PSP-name.test.js

Before we use to just capitalise them which doesn't looks great for ePDQ as it came out like Epdq, which is a shame. Now it comes out how it should do

BAU - add function that can format PSP names nicely

---

app/utils/logger.js
test/test_helpers/supress_logs.js

Add an 'environment' field to the logs, so that it is possible to filter
by environment using a Splunk text search. Splunk does currently extract
the environment from the source if it is explicitly searched on using
e.g. the term 'environment="production-2"', but some of our reports use
a text search so will not pick up on all log lines.
The text search continues to work for many logs where the environment is
included in some way in the log message, but not for others where it
isn't so it makes sense to get rid of this ambiguity.
In the apps producing the logs, we get the environment from an
environment variable which is already configured for use by Sentry.

PP-5777 Add environment field to logs

---

app/utils/response.js

We were logging a line at error level whenever an error page was
displayed, but we display the error page for events such as trying to
redeem an expired invite.
Only log an error if the status code is 500, not for other statuses.
Also move information in the log line into structured key/values.

PP-5760 Don't log error when error page shown for BAU errors

---

app/utils/request_logger.js

This PR ensures that errors involving user authentication aren't sent to Sentry. This is done by changing the logger in logRequestFailure to log at .info level.

PP-5760 Changes logRequestFailure to log at info level

---

app/services/clients/connector_client.js

Our microservices can return failure status codes for a variety of
reasons, and often they won't be errors. Don't log the response at error
level and leave it for services/controllers to determine if the status
means there is an error.

PP-5760 Log connector failure responses at INFO level

---

app/controllers/invite_user_controller.js

Description:
- We log to Sentry when we don't sending an invitation to a user that already exists
- To fix this I've moved the logger underneath the default statement

PP-5760-Remove logging invitation error for existing user

---

app/controllers/edit_service_name_controller.js

If a service has a Welsh name set, and the user goes to edit the service
name, when they click submit, the Welsh name is removed.
This was because on the edit name page there isn't a checkbox that the
controller was expecting to indicate whether to add a Welsh name.

BAU Fix editing a Welsh service name

---

app/controllers/create_service_controller.js
app/controllers/forgotten_password_controller.js
app/controllers/invite_user_controller.js
app/controllers/invite_validation_controller.js
app/controllers/login/otp-login-controller.js
app/controllers/login/send-again-post-controller.js
app/controllers/partnerapp/handle_gocardless_connect_get.js
app/controllers/payment-links/get-edit-amount-controller.js
app/controllers/payment-links/get-edit-information-controller.js
app/controllers/payment-links/post-edit-controller.js
app/controllers/register_service_controller.js
app/controllers/register_user_controller.js
app/controllers/service_roles_update_controller.js
app/controllers/service_users_controller.js
app/controllers/test_with_your_users/links_controller.js
app/controllers/transactions/transaction_detail_controller.js
app/middleware/csrf.js
app/middleware/get_email_notification.js
test/integration/service_roles_update_ft_test.js
test/integration/transaction_details_ft_tests.js
test/unit/controller/create_service_controller/get_test.js
test/unit/controller/create_service_controller/post_test.js

When we display an error page for a BAU error rather than an internal error, specify a non-500 status code so that it doesn't send a 500 status by default. This also prevents an error from being logged for these cases.
The first commit in the PR has some refactoring to improve the way we require the response methods.
I'd recommend looking at the 2 commits separately, as it will be easier to see the changes.

PP-5760 Specify status code when rendering error page

---

test/unit/clients/product_client/product/get_by_gateway_account_id_test.js

Randomisation of the "price" field in a pact was causing the pact broker to think that the pact had changed between each version, causing verification woes.

BAU Fix randomisation in products pacts

---

app/controllers/credentials_controller.js
app/controllers/dashboard/dashboard-activity-controller.js
app/controllers/transactions/transaction_download_controller.js
app/middleware/error_logger.js
app/models/email.js
app/services/clients/connector_client.js
app/services/service_registration_service.js
app/services/transaction_service.js
app/utils/request_logger.js
test/unit/middleware/error_logger_test.js

These dashes were there previously because before we logged in JSON the
logger would concatenate the JSON object it was passed as a second
parameter into the line.
Now, however, the keys in this JSON object are merged into the top-level
JSON object for the logline, so there is a hanging dash on the end of
the message which makes it appear that the message is incomplete. Remove
these.

PP-5760 Remove trailing dashes in log lines

---

app/controllers/two-factor-auth-controller/post-configure-controller.js

Adminusers does some validation on the OTP code that selfservice doesn't
perform, meaning it can return a 400 if the code is not numeric or is
blank.
In selfservice we were treating this as an internal server error, when
it is actually a user input error. Change this to treat a 400 response
as a user input error.
Also don't log user input errors, only log if there was an unexpected
error.

PP-5760 Don't log error for invalid OTP code

---

test/fixtures/ledger_transaction_fixtures.js
test/unit/clients/ledger_client/ledger_search_transaction_test.js

- add a pact tests that filters transaction by from date
- take the opportunity to fully pact test refund with parent transaction

PP-5770 add pact tests for filtering by from_date

---

app/views/login/login.njk

On the admin tool login page, change the password field’s `autocomplete=off` to `autocomplete=current-password`.
WCAG 2.1 AA requires us to [identify input purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose), which can be achieved by always using the [appropriate `autocomplete` attribute for a form field if there is one](https://www.w3.org/WAI/WCAG21/Techniques/html/H98). For password fields, this is
[`autocomplete=current-password`](https://www.w3.org/TR/WCAG21/#input-purposes).

BAU Use autocomplete=current-password for login page password

---

app/views/payment-links/edit-amount.njk

_Originally authored by @quis as https://github.com/alphagov/pay-selfservice/pull/1749_
---
`heading-small` is the class used by GOV.UK Elements. This app doesn’t include the GOV.UK Elements CSS. It does include the GOV.UK Frontend CSS, where `govuk-heading-s` can be found.

Use GOV.UK Frontend not GOV.UK Elements heading

---

app/views/services/add_service.njk

_Originally authored by @quis as https://github.com/alphagov/pay-selfservice/pull/1757_
---
GOV.UK style is to use _Sentence case_ not _Title Case_ for buttons etc.

Fix capitalisation on add service button

---

.hadolint.yaml
Dockerfile
docker/build_and_test.Dockerfile
package-lock.json
package.json
start.js

Pin Docker base image to `node@alpine-12.13.1` (this replaces using alpine and separately installing `nodejs`)
Fix older dependency versions.
Supersedes https://github.com/alphagov/pay-selfservice/pull/1759

PP-5890 Self service uses Node LTS (12.13.1)

---

app/views/transaction_detail/index.njk
test/cypress/integration/transactions/transaction_details_spec.js

* `reference` is being used by services to include personal information
like paying user name
* we send our page titles to google analytics - this is an issue with PII
* patch the page title to use transaction ID (in our control) vs.
reference (out of our control)
Supersedes https://github.com/alphagov/pay-selfservice/pull/1770

PP-5918 Remove reference from transaction detail title (PII)

---

app/views/credentials/smartpay.njk
app/views/your-psp/_smartpay.njk
test/ui/credentials_ui_tests.js

We were using “Merchant code” in some places and “Merchant ID” in others. SmartPay themselves variously use “Merchant account”, “Account code” or “MerchantAccount” and add to the confusion by having a higher-level container for these things called either an “Account” or “Company” depending on where you are.
“Merchant account code” is the name our tech writer thinks will be clearest.

PP-5827 For SmartPay, use “Merchant account code” consistently

---

app/views/includes/head.njk

We send analytics to the cross gov google analytics app too. They (GOV.UK) have some
script that flags when personal information isn't redacted. While we have
redacted the front part of the email (i.e. everything before the "@"), it's
possible the GOV.UK script is still flagging the emails even though the front
part is redacted. Removing the entire email might solve the problem.

zd3866092: Redact entire email

---

app/middleware/logging_middleware.js

Logging middleware was throwing an error when attempting to log, as `logging.requestLogFormat` in pay-js-commons had been modified, but the consuming module hadn't been updated to work with the changes.

BAU Fix logging incoming requests

---

app/views/includes/head.njk

Reverts alphagov/pay-selfservice#1785
For some reason this doesn't appear to work. Some emails are redacted, some aren't.

Revert "zd3866092: Redact entire email"

---

app/views/includes/head.njk

Complying with ICO guidance around cookie consent we can't set non-essential cookies without consent being granted. In the short term then we have to disable Google Analytics as it stores cookies.

PP-5977 Disable google analytics

---

app/controllers/transactions/transaction_refund_controller.js
app/models/charge.js
test/unit/controller/refunds_controller_test.js

- Pass user email for refunds as Connector can receive `user_email` on refunds endpoint https://github.com/alphagov/pay-connector/pull/1996

PP-5965 Send user email for refunds

---

app/controllers/two-factor-auth-controller/post-configure-controller.js
app/controllers/two-factor-auth-controller/post-resend-controller.js
app/services/auth_service.js
app/views/login/otp-login.njk
app/views/login/send_otp_again.njk
app/views/self_create_service/register.njk
app/views/self_create_service/resend_otp.njk
app/views/self_create_service/verify_otp.njk
app/views/transaction_detail/_details.njk
app/views/twoFactorAuth/configure.njk
app/views/twoFactorAuth/index.njk
app/views/user_registration/re_verify_phone.njk
app/views/user_registration/register.njk
app/views/user_registration/verify_otp.njk
test/cypress/integration/user/login_spec.js
test/ui/login_ui_tests.js
test/ui/self_create_service_ui_tests.js
test/unit/controller/two-factor-auth-controller/post_configure_controller.test.js

We’re inconsistent about whether we use “security code” or “verification code”. Standardise on “verification code” as recommended by @tracy-content.

PP-6000 Change “security code” to “verification code” in content

---

test/unit/clients/connector_client/connector_get_multiple_gateway_accounts_test.js

This pact test was disabled as there was not previously a provider state
in connector. There now is, so enable it.

PP-5996 Enable get multiple gateway accounts pact test

---

test/cypress/integration/my-services/add_new_service_spec.js
test/cypress/integration/settings/payment-types-spec.js
test/cypress/integration/transactions/transaction_details_spec.js
test/cypress/plugins/stubs.js
test/fixtures/transaction_fixtures.js

Refactor the stubs configuration file to reduce code duplication by adding a method to setup stubs which have an uncomplicated configuration.
Make all predicates in the stubs use 'deepEquals' to ensure we are matching entirely on request bodys.

PP-6008 Refactor Cypress stubs configuration

---

package.json
test/cypress/integration/my-services/add_new_service_spec.js
test/cypress/plugins/index.js
test/cypress/plugins/stubs.js
test/cypress/support/index.js

In Cypress tests, it is sometimes desired to verify that a HTTP request
to an external service is made to verify the behaviour of a task. The
default behaviour of Mountebank, which is the stub server used by
Cypress tests, is to return a 200 response with an empty body in
response to all requests a matching stub does not exist for. Therefore,
tests will only fail if a stub we expect to be called is not called if
we expect a non-200 response or the application uses the body of the
response in some way.
The example this is implemented for in this commit is adding a new
service. We want to verify that the appropriate calls are made to
adminusers and connector to perform the actions that add the service.
Without verifying these requests are made with the expected request
body, we cannot be …

PP-6008 Add ability to verify stubs have been called in Cypress tests

---

dev.yml
manifest.yaml
package-lock.json
package.json

Add cf manifest.yaml to run selfservice using node buildpack.
Using node 12.11.1 as that is lowest 12.x version supported by
PaaS.
To push run e.g.
```
cf push \
--var adminusers_url=http://adminusers-dev-dom.apps.internal \
--var card_connector_url=http://card-connector-dev-dom.apps.internal \
--var ledger_url=http://ledger-dev-dom.apps.internal \
--var selfservice_url=pay-selfservice-dev-dom.london.cloudapps.digital \
--var public_auth_url=http://publicauth-dev-dom.apps.internal \
--var products_url=http://products-dev-dom.apps.internal \
--var direct_debit_connector_url=http://directdebit-connector-dev-dom.apps.internal
```

PP-6029 Buildpack manifest

---

test/cypress/integration/my-services/update_service_name.js
test/cypress/plugins/stubs.js
test/cypress/utils/common_stubs.js

Description:
- Replaces MyServicesIT.editServiceName_shouldSucceed_ForADirectDebitAccount in self-service end-to-end with Cypress test update_service_name.js
- Adds Cypress test for updating Welsh service name

PP-6008-Update-dd-service-name-cypress test

---

test/cypress/plugins/index.js
test/cypress/plugins/stubs.js

If we haven't set up any stubs for a test, then a call to
mountebank/imposters/8000 will return a 404 and cause an error to be
thrown when verifying the number of times a stub has been called.
Fix this by swallowing a 404 response from mountebank.

PP-6008 Don't verify stubs if no stubs setup

---

app/controllers/payment-types/get.index.controller.js

Accepting Unionpay has to be enabled with PSPs in same
way Amex does, so add helpful hint for Unionpay. Refraining
from any serious refactoring of this controller/path.

PP-5340 Add hint on accepting unionpay

---

test/fixtures/pact_base.js

Previously, if the response body in a pact contained an array, we would
only match on the type for each element in the array. This meant that
for arrays of object, we would only verify that each element was an
object, rather than matching on each field in the object.
Modify logic for generating pact files so that for arrays of objects, we
add matchers for the fields in the object.
This means that, for example the following:
```
"matchingRules": {
"$.body.events[0]": {
"match": "type"
},
"$.body.events[1]": {
"match": "type"
}
}
```
becomes:
```
"matchingRules": {
"$.body.events[0].amount": {
"match": "type"
},
"$.body.events[0].state.status": {
"match": "type"
},
...
"$.body.events[1].amount": {
"match": "type"
},
"$.body.events[1].state.status": {
"match": "type"
},
...
}
```

PP-6010 Improve how we match on arrays in pact files

---

app/controllers/transactions/transaction_download_controller.js
app/services/clients/ledger_client.js
app/services/transaction_service.js
app/utils/get_query_string_for_params.js
test/integration/json/transaction_download.json
test/integration/transaction_download_ft_tests.js

- Selfservice now contains a feature flag, USE_LEDGER_BACKEND_CSV, which when set to true, will ensure that when downloading CSVs it will do so using the accept: text/csv header
- Adds a test to ensure that the information it receives is correct and that the feature flag modifies the headers of the outgoing requests for the CSV

PP-5972 Selfservice uses Ledger accept text/csv

---

package.json

Some tests rely on the "matches" array being present in the stub server response to assert the stub is called an expected number of times. This feature requires mountebank to be started in debug mode.
The `verifyStubs` test callback relies on the `matches` property being present: https://github.com/alphagov/pay-selfservice/blob/e9482de88ff1eb19f6e1d881ad65bd301b7f31e6/test/cypress/plugins/index.js#L80
This is only present when the `--debug` flag is passed when mountebank is started: http://www.mbtest.org/docs/api/overview#get-imposter

PP-6037: Run mountebank stub server in debug mode

---

app/controllers/transactions/transaction_download_controller.js
app/utils/get_query_string_for_params.js

Include `fee_headers` flag if a Stripe gateway account is included in the CSV report.

PP-6069 Send include fee headers param to ledger

---

app/controllers/transactions/transaction_download_controller.js

`feeHeaders` should be applied before it's used to generate the request URL.

PP-6069 Fix; alter filters before using them

---

package.json

PaaS node buildpack no longer supports 12.11.1. To avoid having to keep
bumping the engine version whilst maintaining compatibility with our
existing docker image build process, this pins the major version whilst
accepting minor and pataches releases greater than 12.11.1.

PP6031 Bump engine version

---

env-map.yml
manifest.yml

Adds the env-map build pack and related .yml config to map data provided by the app-catalog user-provided service from VCAP_SERVICES env variable into separate environment variables.

PP-6085: Add env-map buildpack provided variables

---

app/views/transaction_detail/_details.njk
test/cypress/integration/transactions/transaction_details_spec.js

If the `allow_moto` flag is true for the gateway account, show a 'MOTO:' row on the transaction details page with a value of 'Yes' or 'No'.
If the `allow_moto` flag is false for the gateway account, do not show the 'MOTO:' row on the transaction details page.
Add a Cypress test for this behaviour.

PP-5956 Display whether a payment is MOTO on transaction details page

---

manifest.yml

The routes are set when the space is setup by the terraform in
pay-omnibus. Remove the route attribute from the manifest.

PP-6085 Remove route from manifest

---

app/controllers/transactions/transaction_download_controller.js
app/utils/get_query_string_for_params.js
test/integration/transaction_download_ft_tests.js

Include the query parameter `moto_header=true` if the account has moto payments enabled when calling ledger to stream the CSV download.
Improve the tests for the backend ledger CSV creation.

PP-6076 Request CSV with moto header if account has moto enabled

---

app/views/payment-links/edit-reference.njk
app/views/payment-links/information.njk
app/views/payment-links/reference.njk
test/cypress/integration/payment-links/create_payment_link_spec.js

- When creating a Payment Link, add new guidance which states not to use PII information.
- Add new hint text for Adding / Editing Payment Reference - which states not to add PII information.
IMPORTANT NOTE: Please check Welsh as well.

PP-5989 Update guidance on payment links so that people don't include PII

---

app/controllers/payment-links/index.js
app/controllers/payment-links/metadata/resource-controller.js
app/middleware/experimental_features.js
app/models/Service.class.js
app/paths.js
app/routes.js
app/services/clients/products_client.js
app/views/payment-links/metadata/edit-metadata.njk
test/unit/middleware/experimental_features_test.js

* resource controllers for GETting add metadata to payment link page
* initial template for column header and cell value form
* restrict access to pages and POST routes by `experimental_features_enabled` flag

PP-6152 Add metadata to payment link page

---

app/views/includes/cookie-message.njk

Add a missing space in the cookie message “Find out more about cookies” link between the `class` and `href` attributes.

Add a missing space in cookie message link

---

app/views/your-psp/_worldpay.njk

Link was missing to go to the documentation for connecting a Worldpay account to pay.

BAU Add link to Worldpay go live documentation

---

app/controllers/payment-links/get-edit-controller.js
app/paths.js
app/utils/replace_params_in_path.js
app/views/payment-links/edit.njk
test/unit/utils/replace_params_in_path_test.js

On the page for each individual payment link, add a section for reporting columns (metadata associated with the payment link), complete with links to add a new reporting column and edit the
existing ones. Reporting columns are sorted alphabetically (case-insensitively) by metadata key.
The reporting columns section is only shown if the `experimentalFeaturesEnabled` flag is set on the service.
While the reporting columns section uses the [summary list component from the GOV.UK Design System](https://design-system.service.gov.uk/components/summary-list/), it uses HTML rather than the Nunjucks macro. This is because the number of rows in the table is dynamic (it’s produced by iterating over the metadata keys) and there’s no nice way to tell the summary list component Nunjucks macro that we …

PP-6156 Add metadata to page for individual payment link

---

app/views/payment-links/edit.njk
test/cypress/integration/payment-links/edit_payment_link_spec.js

On the edit payment link page, check for the existence of the reporting columns and the button to add new ones. This test is carefully designed to check the columns are presented in
alphabetical order case-insensitively and that the URLs to change each piece of metadata correctly URL-encode the key name.

PP-6156 Check for reporting columns on edit payment link page

---

app/controllers/payment-links/index.js
app/controllers/payment-links/metadata/resource-controller.js
app/paths.js
app/routes.js
app/services/clients/products_client.js
app/views/payment-links/metadata/edit-metadata.njk
test/unit/controller/payment-links/metadata/paymentlink_metadata_resource.test.js

Depends on https://github.com/alphagov/pay-selfservice/pull/1888
Basic delete functionality for metadata for payment links, includes all the gubbins, flow can be changed with user testing as needed.

PP-6157 Delete payment link metadata

---

app/middleware/permission.js
test/cypress/integration/request-to-go-live/agreement_spec.js
test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
test/cypress/integration/request-to-go-live/index_spec.js
test/cypress/integration/request-to-go-live/organisation_address_spec.js
test/cypress/integration/request-to-go-live/organisation_name_spec.js
test/cypress/integration/stripe-setup/bank_details_spec.js
test/cypress/integration/stripe-setup/responsible_person_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/index_spec.js
test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js

- When we call `res.render()` when a user has invalid permissions, we
should throw a 401 response instead of the current 200.

BAU Invalid Permissions Return 401

---

env-map.yml
manifest.yml

Set the `METRICS_HOST` and `METRICS_PORT` from the app-cataloge to send
metrics to the carbon-relay app.

PP-6254 Add cabon-relay

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/all-service-transactions/get-controller.js
app/controllers/my-services/get-index-controller.js
app/views/services/index.njk

* explicitly check value is `"true"` in favour of checking for truthy
value
* pass env into template to be able to make comparison
* fix for filtering gateway account ids that the user has access to

PP-6303 Fix feature flag multi account reporting

---

app/controllers/all-service-transactions/get-controller.js
app/controllers/transactions/transaction_list_controller.js
app/views/transactions/filter.njk

- Currently on the 'all services transactions' page the clear filter
button redirects users to the transactions page for the service they are
logged in on.
- This fixes this by providing a context specific clear route that will
redirect users back to the page they are viewing, without filters.

PP-6303 Clear Filter Redirect Fix

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/all-service-transactions/get-controller.js
app/controllers/transactions/transaction_detail_redirect_controller.js
app/utils/get_query_string_for_params.js
app/utils/valid_account_id.js
test/unit/utils/valid_account_ids_test.js

* move gateway account filtering out to util library
* pass `live` flag through to Ledger to exclude any test data from the query
Depends on Ledger support for `live` in https://github.com/alphagov/pay-ledger/blob/master/src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java

BAU Exclude test accounts from all transactions

---

app/controllers/transactions/transaction_detail_controller.js
app/routes.js
app/views/all_service_transactions/index.njk
app/views/services/index.njk
app/views/transaction_detail/_details.njk
app/views/transaction_detail/index.njk

**My services page:**
* update text on link to read 'View transactions from all live services" (screenshot 1)
* move links on services overview page to be in a full column (screenshot 1)
**Transaction list:**
* add back links to my service page from all service transactions (screenshot 2)
**Transaction details (IFF coming from all service transactions):**
* add back links to all service transactions from transaction detail with updated text (screenshot 3)
* hide service navigation on transaction detail page as we're not currently in a service context (screenshot 3)
* add service name to the transaction detail page (screenshot 3)
**Fixes:**
* delete backLink context URL every time that it's used, this will avoid
the cookie session continuing to believe it's in the all services view
* …

BAU Refine all service transactions UX

---

app/controllers/policy/supportedPolicyDocuments.js
app/views/includes/footer-categories.njk
app/views/policy/document-downloads/pci_dss_attestation_of_compliance.njk

- Add a link in the footer under "Legal terms" to a new "Attestation of
Compliance for PCI" page. This contains a link to download a document
from S3.
Co-authored-by: Iqbal Ahmed <iqbal.ahmed@digital.cabinet-office.gov.uk>

PP-6239 Add page to download PCI attestation of compliance

---

app/views/login/login.njk
app/views/login/otp-login.njk

- Added ID attributes to button on login/otp page, so that the elements can be selected  by ID instead of using `class=govuk-button`. Since we are adding cookie pages, it will have additional buttons with class `govuk-button` which will confuse integration tests as well as e2e tests when logging in for the tests

PP-6285 Add id to login/otp button

---

app/browsered/cookie-functions.js
test/cypress/integration/cookie-banner/cookie-banner-spec.js
test/unit/browsered/cookie-functions.test.js

- Specify the domain when settings the analytics cookie so the product pages can share same cookie
- Removed analytics cookie testing from cypress tests as cypress doesn't work with cookies with domain `.localhost` which is what is needed for us

PP-6278 Specify domain when setting analytics cookie

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/all-service-transactions/get-controller.js
app/controllers/transactions/transaction_list_controller.js
app/utils/valid_account_id.js
app/views/transactions/list.njk
test/unit/utils/valid_account_ids_test.js

* for all service transactions an individual gateway account
configuration cannot be used to determine if optional headers should be
shown on the transaction list or transaction download
* instead reduce all gateway accounts available to the session so that
if any of them meet the criteria the headers will be shown

PP-6345 All service transactions support optional headers (stripe, moto)

---

app/controllers/digital-wallet/post-google-pay-controller.js
app/views/digital-wallet/apple-pay.njk
app/views/digital-wallet/google-pay.njk
app/views/includes/side_navigation.njk

At some point, we stopped sending the merchant ID to connector. This means that although we were changing the `allow_google_pay` setting on the gateway account, it never appeared as enabled because when connector returns the setting, it checks that the merchant ID is there.
Fix the routes that the form on the apple/google pay settings page post to.
Also fix an issue where it was not possible to turn off google pay due to the `required: "true"` attribute on the merchant ID field. Instead do server side validation for this.
The tests need to be improved for this, but as it was already broken, this PR just aims to get it working again.
Stop alignment being messed up when a flash message shown. This was happening when errors were shown for the google pay settings page.
Added some padding to …

PP 6466 Fix Google pay settings page

---

test/fixtures/payout_fixtures.js

Add basic payout fixture, this will be used to verify the shape of data
between consumer and producer (pact) and during development.

PP-6490 Payout data fixtures

---

app/services/clients/ledger_client.js

This wrapper allows Ledger to fetch payouts for a given gateway account
string and page number.
This wrapper will be covered by the following tests when used:
* Consumer pact tests will validate the shape of the data as well as
verifying the correct params are provided to the right endpoint. This
will also make sure the data is returned as expected.
* Integration tests for any controllers that use the wrapper (see https://github.com/alphagov/pay-selfservice/pull/2002)

PP-6487 Ledger payout API endpoint client wrapper

---

app/controllers/payouts/payouts_service.js
app/controllers/payouts/user_services_names.js
test/fixtures/payout_fixtures.js
test/unit/controller/payouts/payouts_service_test.js
test/unit/controller/payouts/user_services_names_test.js

Depends on https://github.com/alphagov/pay-selfservice/pull/2000
According to the discovery design document for the payout MVP, we will
be displaying payouts for all services grouped by date.
It is also necessary to provide the services name for each payout entry,
as this information isn't available to the payout (from Ledger) there
will also be a requirement to compliment payouts with the service name.
This adds a service helper method to accept a flat list of payouts and return a
grouped object indexed by date.
If a user object is provided (see User model), this will also add the
service name to each payout object according to the gateway account
assigned to that payout.
Example usage:
```
groupPayoutsByDate([{
id: '...'
paid_out_date: '2019-09-01T01...'
})
/*
{
'2019-09-01': {
date: …
```

PP-6487 Payouts service for grouping payouts

---

app/controllers/payouts/payouts_service.js
test/integration/payouts/payouts_service_it_test.js

Depends on https://github.com/alphagov/pay-selfservice/pull/2001
Service level abstraction to fetch payouts from Ledger and format them
as required in the template.
Cover with integration test that verifies the ledger client wrapper is
calling the correct backend route and the shape of the response is
expected by the service formatter.

PP-6487 Payouts service gets payouts

---

app/controllers/payouts/payout_list_controller.js
app/paths.js
app/routes.js
app/utils/display_converter.js
app/views/payouts/list.njk

Depends on https://github.com/alphagov/pay-selfservice/pull/2002
Adds payout controller and basic view based on the payout services
already implemented.
This will list all payouts showing their amount and associated service,
according to the story it will not:
* allow pagination through payouts
* provide a download link for the transactions
Includes the controller in the main server router with new `/payouts`
path.

PP-6487 Add payouts page

---

app/views/payouts/list.njk
test/cypress/integration/payouts/payouts_list_spec.js
test/cypress/plugins/stubs.js

Depends on https://github.com/alphagov/pay-selfservice/pull/2003
Cypress will use mounteback to stub ledger payout requests, this adds a
helper to the stubs file that can then be called by the cypress test.
Verify end to end that the payout page will respond and format results
correctly.

PP-6487 Payout page ends coverage

---

app/controllers/payouts/payout_list_controller.js
app/controllers/payouts/payouts_service.js
app/services/clients/ledger_client.js
app/views/payouts/list.njk
app/views/payouts/paginator.njk
test/cypress/integration/payouts/payouts_list_spec.js
test/cypress/plugins/stubs.js
test/fixtures/payout_fixtures.js
test/integration/payouts/payouts_service_it_test.js

Include pagination object in result from payout search in the payouts
service response. 
This uses the `Paginator` utility also used by
transactions and has a very similar template to ensure the user
experience is the same across both components.
Service integration tests should cover the shape of the payouts search result, the pagination component linking through query string -> controller -> server -> ledger client is covered in Cypress.

PP-6492 Payouts page pagination component

---

app/controllers/payouts/payouts_service.js
test/unit/controller/payouts/payouts_service_test.js

Swap the direction of the payout service grouping utility to order the
groups by descending date. Verify that entries in any given order will
be collected into ordered groups.

PP-6492 Payout page order entries descending

---

app/controllers/payouts/payout_list_controller.js
app/utils/get_query_string_for_params.js
app/views/payouts/list.njk

Add 'Payout transactions' column to payout page. This filters the
transaction download by `gateway_payout_id`. 
This uses the permissions/ method already implemented for all live service transactions 
to ensure the user has access to the transactions in the payout they are filtering on.

PP-6596 Payouts transactions download link

---

app/routes.js

Navigating to payout pages would crash without authentication as the
paths hadn't been registered behind the auth middleware. This wouldn't
reveal any sensitive information but would give some indication to the
internal URL structure.
Fix this by passing all `payouts` path correctly to the authentication
middleware.

PP-6591 Payouts routes passed through auth middleware

---

app/controllers/payouts/payouts_service.js
app/views/payouts/list.njk
test/cypress/integration/payouts/payouts_list_spec.js
test/cypress/plugins/stubs.js
test/integration/payouts/payouts_service_it_test.js

Cleans up payout page markup to match the current design proposal for
the first feature iteration.
* Update title copy to read 'Payments to your bank account'
* Right align amount title
* Remove horizontal line unless there are no payouts
* Add margin following top level description

PP-6591 Update markup to match design doc parity

---

app/controllers/payouts/payout_list_controller.js

This should be referring to https://github.com/alphagov/pay-js-commons/blob/master/src/logging/keys.js#L46

PP-6591 Fix standard logging key for payout page

---

app/assets/sass/application.scss
app/assets/sass/components/account-status-panel.scss
app/controllers/dashboard/dashboard-activity-controller.js
app/views/dashboard/_stripe_account_setup_banner.njk
app/views/dashboard/index.njk
test/unit/controller/dashboard/dashboard-activity-controller.test.js

- Added account status panel to Dashboard which is shown when feature flag `ENABLE_ACCOUNT_STATUS_PANEL` is `true`
and Stripe account is not fully setup
- Add details button in the panel points to `routes.stripeSetup.accountSetup` which is to be added when Stripe onboarding
design is finalised and implemented
- Message is tentative and to be updated after design is finalised
- Also removed Xray tracing for dashboard controller as we are using it (removed from frontend) and could potentially be removed from other places too.
Panel looks like below (content to be updated after the design is finalised)

 PP-6633 Add account status panel

---

app/controllers/dashboard/dashboard-activity-controller.js
app/views/dashboard/_stripe_account_setup_banner.njk
test/unit/controller/dashboard/dashboard-activity-controller.test.js

- Displays Stripe account status panel only for users with permission `stripe-account-details:update`
- Refactor `LedgerClient.transactionSummary` promise chain to async/await format to be consistent with await usage within dashboard activity controller
- Added/updated relevant tests
with @iqbalgds

PP-6633 Show account status panel for relevant users

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/all-service-transactions/get-controller.js
app/controllers/payouts/payout_list_controller.js
app/controllers/transactions/transaction_detail_redirect_controller.js
app/utils/permissions.js
test/fixtures/user_fixtures.js
test/unit/utils/permissions_test.js

Re-introducing permissions code following analysis of backend/ consumer
behaviour.
Reference https://github.com/alphagov/pay-selfservice/pull/2034
---
The default behaviour in newer backend routes is require a gateway
account id to be passed in to any resource, passing in nothing `key=[]`
or
in the case of comma separated values `key=` will either filter the data
for no account ids (resulting in nothing returned) OR return `400`
requiring something to be set or non empty values.
In the case of the frontend accounts route being called in this utility,
passing no accounts will treat the route as if there is no filter and
return all accounts.
This behaviour will be patched in the backend as part of this ticket.
Patch this behaviour and avoid an unnecessary call to the backend by
simply …

PP-6627 Patch and add multi service permissions

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/all-service-transactions/get-controller.js
app/controllers/payouts/payout_list_controller.js
app/controllers/payouts/payouts_service.js
app/controllers/transactions/transaction_list_controller.js
app/services/clients/ledger_client.js
app/services/transaction_service.js
app/utils/permissions.js
app/utils/response.js
test/integration/payouts/payouts_service_it_test.js
test/unit/clients/ledger_client/ledger_search_payout_test.js
test/unit/utils/permissions_test.js

This code has evolved without knowing the different types of use cases, clean up naming and anti-patterns so that everything is processed in a predictable, clear to understand way.
> On consumers of the multi service permissions, explicitly handle the
base case of having no associated service with permissions (these should
generally not be linked but there is a chance they can be navigated to).
> The multi service permissions library was previously responsible for
preparing the actual query string that was then passed to the backend
for filtering. This caused an issue where it was using a format unknown
by the standard backend routes.
> * move all parsing of query strings to the clients
> * all parsing of params is done by the `qs` library according to the
same formats, there should be no …

PP-6660 Refactor multi service permissions

---

app/browsered/field-validation-checks.js
app/controllers/your-psp/get-flex-controller.js
app/controllers/your-psp/post-flex-controller.js
app/controllers/your-psp/worldpay-3ds-flex-validations.js
app/controllers/your-psp/worldpay-3ds-flex-validations.test.js
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/flex.njk
test/cypress/integration/settings/your-psp-spec.js
test/unit/browsered/field-validation-checks-worldpay-3ds-flex.test.js

Trim leading and trailing whitespace from entered Worldpay 3DS Flex credentials and validate them according to the following rules:
- Organisational unit ID: 24 lower-case hexadecimal characters e.g. “1234567890abcdef12345678”
- Issuer: 24 lower-case hexadecimal characters e.g. “1234567890abcdef12345678”
- JWT MAC key: a UUID ID in its lowercase canonical textual representation e.g. “abcdef12-3456-7890-abCd-ef1234567890”.
Trimming is because users will almost certainly be copying and pasting these values, so may unintentionally copy leading ortrailing whitespace.
If validation fails, display a standard error summary with error messages saying “Enter your organisational unit ID in the format you received it” or similar, and represent the form with the trimmed organisational unit ID and …

PP-6494 Trim and validate Worldpay 3DS Flex credentials

---

app/controllers/stripe-setup/add-psp-account-details/get-controller.js
app/controllers/stripe-setup/add-psp-account-details/get-controller.test.js
app/controllers/stripe-setup/add-psp-account-details/index.js
app/paths.js
app/routes.js
app/views/stripe-setup/go-live-complete.njk

- Added '/stripe/add-psp-account-details' route and controller which
redirects to the next page of details to fill out depending on what
has already been filled out.
- If all details have been filled out, render the setup complete page.
The copy for this has not been added as part of this commit.

PP-6638 Add Stripe account details flow controller

---

app/controllers/stripe-setup/bank-details/post.controller.js
app/controllers/stripe-setup/bank-details/post.controller.test.js
app/controllers/stripe-setup/responsible-person/post.controller.js
app/controllers/stripe-setup/responsible-person/post.controller.test.js
app/controllers/stripe-setup/vat-number-company-number/check-your-answers/post.controller.js
app/controllers/stripe-setup/vat-number-company-number/check-your-answers/post.controller.test.js

If the `ENABLE_ACCOUNT_STATUS_PANEL` environment variable is set to true, redirect to the new `/stripe/add-psp-account-details` route when details are saved on each page . This route determines the next page in the add account details flow to show the user.
If the feature flag is not enabled, redirect to the dashboard as was done previously.
Refactor edited tests to use async/await and reduce the number of lines of test code a bit.

PP-6638 Redirect to account details redirect route

---

app/controllers/stripe-setup/stripe-setup-link/index.js
app/controllers/stripe-setup/stripe-setup-link/stripe_setup_dashboard_redirect_controller.js
app/paths.js
app/routes.js
test/integration/stripe_setup_dashboard_redirect_controller_it_test.js
test/unit/controller/stripe-setup/stripe_setup_dashboard_redirect_controller_test.js

e9d3ecf96d694719efd42f6fc08edcf15168ca5f
> - add new controller that sets the live gateway account id to that of
the  given service then redirects to the dashboard
> - if the user has no access to the given service the it redirects to
the dashboard without setting the gateway account

PP-6635 Redirect to live account dashboard route

---

test/integration/add_psp_details_ft_tests.js

Add functional test to test the scenario where all details have been entered and the "Go live complete" page should be rendered.
Other scenarios are already tested by unit tests for the controller.

PP-6628 Add integration test for add stripe PSP details route

---

app/views/stripe-setup/responsible-person/index.njk

Was removed by 154a11b9730102d28d01377d61ddc096e1a3fcd0 but we want to add it back in until we have some updated content that has words to the same effect.

PP-6634 Add back in text on responsible person page

---

app/views/dashboard/_live_account_requested_banner.njk
app/views/dashboard/index.njk
test/unit/controller/dashboard/dashboard-activity-controller.test.js

If the user has requested a live account, and a live account has not
yet been created, display a banner on the dashboard.
Only show the banner if the user has the permission 'go-live-stage:read'
which indicates they are an admin with permission to make a request to
go live.

PP-6672 Add live account requested banner

---

app/assets/sass/components/account-status-panel.scss
app/assets/sass/components/request-to-go-live.scss
app/views/dashboard/_stripe_account_setup_banner.njk

- Dashboard > Stripe Panel
- Update styling - make text in the Stripe banner to be 2/3 width
- Make the border of the panel to be 5px.
- Request to go live
- Fix styling but on the 'list of things' to do page - now it shows number steps.

PP-6651 Stripe Onboarding fixes

---

app/utils/filters.js
app/utils/transaction_view.js
app/views/transactions/filter.njk
test/cypress/integration/transactions/transaction_list_pagination_spec.js
test/cypress/integration/transactions/transaction_search_spec.js
test/cypress/plugins/stubs.js

- When a user visits the `/transactions` page, the search that is run automatically only lists transactions from 1 month ago. This will use the same day in the previous month, or if that date does not exist then the last day of the previous month.
- When a user clears the "From date" filter and clicks "Filter", the search is performed with no from date limit.
- The "Clear Filter" button has been renamed to "Reset filters" and will revert to searching for unfiltered transactions limited to 1 month ago.

PP-6644 Set default from date for unfiltered transaction search

---

app/controllers/my-services/get-index-controller.js
app/utils/permissions.js
app/views/services/index.njk
test/cypress/integration/my-services/my_services_links_spec.js

* remove feature flag that has been enabled in all environments.
* only show all service transactions link if a user has access to live
services that they would have permissions to see.

PP-6709 Only show all service transactions link for live service users

---

app/controllers/edit_merchant_details/post-edit-controller.js
app/views/merchant_details/edit_merchant_details.njk
test/cypress/integration/settings/merchant_details_spec.js
test/unit/controller/edit_merchant_details_controller/post-edit.test.js

Previously, it was only possible to edit if the service had a direct debit account.
However, we collect the phone number as part of the go live process as we send it to Stripe.
Make this editable on the organisation details page. Also make it mandatory. As we require it for accounts that are going live anyway, it seems acceptable to always require it.

PP-6717 Allow editing organisation number for all services

---

package.json

PaaS node buildpack version 1.7.18 supports 12.16.3 as the current
highest version of node 12.X. This change should only effect the version
of Node that is selected when deploying to PaaS.
```
-----> Nodejs Buildpack version 1.7.18
**WARNING** buildpack version changed from 1.7.13 to 1.7.18
-----> Installing binaries
engines.node (package.json): ^12.18.1
engines.npm (package.json): unspecified (use default)
**WARNING** Node version in .nvmrc ignored in favor of 'engines' field in package.json
**ERROR** Unable to install node: no match found for ^12.18.1 in [10.19.0 10.20.1 12.16.2 12.16.3 13.12.0 13.14.0]
```

BAU select node version compatible with PaaS buildpack

---

app/middleware/stripe-setup/check-company-number-not-submitted.js
app/middleware/stripe-setup/check-company-number-not-submitted.test.js
app/middleware/stripe-setup/check-vat-number-not-submitted.js
app/middleware/stripe-setup/check-vat-number-not-submitted.test.js
app/services/clients/stripe/stripeCompany.model.js
app/services/clients/stripe/stripeCompany.model.test.js

We currently have single task (`vat_number_company_number`) for which  we record both `vat number` and `company registration number`, show respones in check your answers page and submit to Stripe at once.
This task is to be split into `vat_number` and `company_number` tasks as check your answers page will be removed and data is to be submitted to Stripe as soon as relevant form (vat number/ company registrationnumber) is submitted.
- Added new middleware to use for new vat_number and company_number tasks (to be introduced) to show error if task is already completed.
- vatId is now optional on StripeCompany model as this information will not we available for company_number task.

PP-6688 Middleware for vat_number and company_number checks

---

test/cypress/integration/dashboard/dashboard_stripe_add_details.js
test/cypress/integration/settings/3ds-spec.js
test/cypress/integration/stripe-setup/vat_number_spec.js
test/cypress/integration/transactions/transaction_details_spec.js
test/cypress/integration/transactions/transaction_search_spec.js
test/cypress/utils/common_stubs.js

- Removes usage of `vat_number_company_number` reference from stubs as we no longer have this task.
- Replaces with `vat_number` and `company_number`

PP-6688 Remove var_number_company_number reference

---

app/assets/sass/components/account-status-panel.scss
app/controllers/dashboard/dashboard-activity-controller.js
app/middleware/get_gateway_account.js
app/services/clients/stripe/stripe_client.js
app/views/dashboard/_stripe_account_setup_banner.njk
app/views/dashboard/index.njk
app/views/includes/phase_banner.njk
test/unit/controller/dashboard/dashboard-activity-controller.test.js

- Update `stripe_client.js` - add new method to get Stripe account details directly from Stripe.
- This method has 1 second timeout and will allow the Dashboad to continue to display even if the call fails.
- Update Dashboard controller
- Get stripe account id from Connector
- Use new method in `stripe_client` to get Stripe account details
- Update integration test
- Update Stripe banner nunjucks file
- Checks for the current_deadline, if that exists then a date is shown in the banner
- If payouts_enabled = false then a restricted banner is shown.
When Stripe returns a `current_deadline` - display that in the banner:
When Stripe returns `payouts_enabled=false` - display a restricted banner:
When Stripe returns `payouts_enabled=false` and all Stripe details have been filled on - display a …

PP-6662 Dashboard > Stripe Onboarding banner > include status

---

app/services/clients/zendesk_client.js
config/zendesk.js

- Assigns a form ID (`Pay Support`) that we want to use for `request to go live` Zendesk tickets
Tested locally and form is correctly set for the ticket ZD#4155552

PP-6581 Assign form id to request to go live requests

---

app/services/clients/base_client/wrapper.js
app/utils/request_logger.js

Use structured logging arguments for all log lines produced when making outgoing requests and consistently include the available information for all log lines.

PP-6771 Use structured arguments when logging outgoing requests

---

app/controllers/all-service-transactions/download-transactions.js
app/controllers/transactions/transaction_download_controller.js
app/services/clients/base_client/wrapper.js
app/services/clients/ledger_client.js
app/services/transaction_service.js
app/utils/request_logger.js

Log the filters that are applied to transaction searches and CSV downloads as well as the gateway account ids.
Additionally log a `multiple_accounts` field, which has a boolean value, to quickly get whether the request was for all gateway accounts for a user.
The intention of this is to be able to easily group requests by their filters in Splunk so we can see which combinations of filters cause the search to take longer.
Extract logging when csv streaming is complete to a function in transaction_service to reduce duplication.

PP-6771 Log filters for transaction search and download

---

test/fixtures/ledger_transaction_fixtures.js

Ledger will no longer provider `reference` as part of the refund
`TransactionView`. Reference from Connector had always referred to
`gateway_transaction_id` which is now moved into its own attribute.

PP-6657 Remove reference from refund pact contract

---

Jenkinsfile

Description:
- Before we can turn off the direct debit smoke test we need to ensure that no pipeline calls it. This ensures that the self-service Jenkins pipeline doesn't call the direct debit smoke Jenkins function
- This also ensures that the direct debit portion of the end to end test suit won't be run

PP-6763 - Remove direct debit smoke and end test from publicapi Jenkins pipeline

---

app/services/clients/ledger_client.js
app/services/clients/utils/ledger_legacy_connector_parity.js
app/services/transaction_service.js
test/cypress/plugins/stubs.js
test/fixtures/ledger_transaction_fixtures.js
test/unit/clients/ledger_client/ledger_search_transaction_test.js
test/unit/clients/ledger_client/legacy_connector_parity_util_test.js

`payment_details` are now available as a top level attribute on refunds.
These should be used in favour of relying on the nested
`parent_transaction` entity.
Remove `with_parent_transaction` from transaction searches as this
information is now stored flat and the query parameter deprecated.

PP-6758 Update search consumer to use payment details

---

test/cypress/integration/transactions/transaction_search_spec.js
test/fixtures/ledger_transaction_fixtures.js
test/fixtures/transaction_fixtures.js

- Asserts details of the transaction search results in cypress tests
- Uses example domain for emails

PP-6758 Assert transaction search results

---

app/views/merchant_details/edit_merchant_details.njk
app/views/request-to-go-live/organisation-name.njk
test/unit/controller/edit_merchant_details_controller/get-edit.test.js

- Improved hint text for org name to make it clear for service users entering org name.
- Uses html instead of nunjucks template as html line breaks are escaped if added to nunjucks text

PP-6820 Improve hint for org name

---

app/controllers/stripe-setup/add-psp-account-details/get-controller.js
app/controllers/stripe-setup/add-psp-account-details/get-controller.test.js
app/middleware/stripe-setup/check-bank-details-not-submitted.js
app/middleware/stripe-setup/check-bank-details-not-submitted.test.js
app/middleware/stripe-setup/check-company-number-not-submitted.js
app/middleware/stripe-setup/check-company-number-not-submitted.test.js
app/middleware/stripe-setup/check-responsible-person-not-submitted.js
app/middleware/stripe-setup/check-responsible-person-not-submitted.test.js
app/middleware/stripe-setup/check-vat-number-not-submitted.js
app/middleware/stripe-setup/check-vat-number-not-submitted.test.js
test/cypress/integration/stripe-setup/bank-details.cy.test.js
test/cypress/integration/stripe-setup/company-number.cy.test.js
test/cypress/integration/stripe-setup/responsible-person.cy.test.js
test/cypress/integration/stripe-setup/vat-number.cy.test.js

- We have getAccount (get-gateway-account.js) middleware where we get make a call to connector to get current stripe setup and is added to req.account object.
We can remove getStripeSetup calls from controllers as it is taken care in middle and information available on req object

PP-6848 Remove additional call for stripe setup

---

app/assets/sass/components/flash.scss
app/views/dashboard/_stripe-account-setup-banner.njk
app/views/includes/flash.njk

Was appearing inside the go-live-banner.
We possibly shouldn't use a flash message for these errors, but it now looks like this:

PP-6863 Fix flash message on dashboard

---

app/views/all-service-transactions/index.njk
app/views/transactions/index.njk

Add an integrity check to ensurethe file we receive from the CDN is the 
one expected.
Future work may see these files removed entirely (in favour of HTML
standards) or bundled and served by the application.
is being served by the CDN
browsers and no console errors or warnings are shown

PP-6716 Add integrity checks for CDN scripts

---

test/cypress/integration/transactions/transaction-details.cy.test.js

- Merge into 2 tests that checks then entire Transaction page in one go.
- Test 1 - show a page with all optional data.
- Test 2 - show page with no optional data.
- Test 2 - show transaction events

PP-6864 refactor transaction details cypress test

---

test/cypress/integration/request-to-go-live/organisation-address.cy.test.js

- Stop typing in long string to test validation for address line 2 as this isn't worthwhile for the amount of time taken.
- Roll test for validation of postcode into the other test checking validations
- Don't re-fill the form multiple times, instead stay on the same page and edit fields in different test cases to save time. Using cy.Cookies.preserveOnce allows for this.

PP-6864 Improve organisation address cypress tests

---

test/cypress/integration/request-to-go-live/organisation-name.cy.test.js
test/cypress/utils/request-to-go-live-utils.js

Re-organise stubbing to set up the stubs in the individual `it` blocks to avoid overly complicated stubs with repeat behaviour.
Remove some of the duplication that exists in the test.

PP-6864 Improve organisation name cypress test

---

test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/utils/gateway-account-stubs.js

The repeat behaviour was required because we were setting up all the stubs in the `beforeEach` for a `describe` block in a Cypress test.
By move the stub setup to the individual `it` blocks where the stubs will be called, we can avoid this behaviour and make the stub setup less confusing.

PP-6864 Remove gateway account stub with repeat behaviour

---

test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
test/cypress/integration/my-services/add-new-service.cy.test.js
test/cypress/integration/my-services/my-services-links.cy.test.js
test/cypress/integration/my-services/update-service-name.cy.test.js
test/cypress/integration/request-to-go-live/organisation-address.cy.test.js

Can call with multiple cookie names, so just make a single call each time

PP-6864 Remove additional Cypress.Cookies.preserveOnce calls

---

test/cypress/integration/stripe-setup/responsible-person.cy.test.js
test/ui/responsible-persion.ui.test.js

We had a cypress test that tested an edge case of template logic that both address line 1 and address line 2 display the same error summary in the summary list, and if there are errors for both fields, it is only displayed once.
To do this test, we had to type a very long string for address line 2 as this is the only error that can be simulated.
As this is template logic, it is suited to a template test. So replace the cypress test with some simple template tests for this.

PP-6864 Replace test for responsible person template logic

---

test/cypress/integration/request-to-go-live/agreement.cy.test.js
test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/user-stubs.js
test/cypress/utils/request-to-go-live-utils.js

- Make it more obvious what the stub that returns different responses to a get user request does and why we use it
- Fix some stylistic points like test naming
- Remove some duplication in the tests

PP-6864 Improvements to request to go live tests

---

test/cypress/integration/dashboard/dashboard-go-live-link.cy.test.js

These were supposedly flakey, re-enable so we can work out why and fix them

PP-6864 Re-enable skipped cypress tests

---

package.json

Accidentally committed change to package.json to stop running snyk on
`npm test`. Add back in.

PP-6951 Add back snyk check accidentally removed

---

app/controllers/transactions/transaction-refund.controller.js
app/services/transaction.service.js
app/views/transaction-detail/index.njk
test/cypress/integration/transactions/transaction-details.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/transaction-stubs.js
test/unit/controller/transaction-refund.controller.it.test.js

Use a custom flash rather than 'generic' and 'genericError' to pass success/failure message with the redirect after a refund request has been processed.
Then in the template for the transaction details page, handle these custom flash messages to display them how we want. This allows for having a title in the message that we were before creating by passing HTML markup in the flash message string.
Add an additional Cypress test for the refund success case.

PP-6951 Use custom flash to show refund message

---

package.json

- Updated npm `test` script - extracted the mocha command into a new script: `test:clean-pacts-run-mocha`
- Created new npm script: `test:local`
- Does not run the Snyk command.
- Uses the new `test:clean-pacts-run-mocha`

PP-6780 Do not run Snyk when running unit tests locally

---

app/controllers/payment-links/get-amount.controller.js
app/controllers/payment-links/get-information.controller.js
app/controllers/payment-links/get-reference.controller.js
app/controllers/payment-links/get-web-address.controller.js
app/controllers/payment-links/post-amount.controller.js
app/controllers/payment-links/post-information.controller.js
app/controllers/payment-links/post-reference.controller.js
app/controllers/payment-links/post-web-address.controller.js
app/views/macro/error-summary.njk
app/views/payment-links/amount.njk
app/views/payment-links/information.njk
app/views/payment-links/reference.njk
app/views/payment-links/web-address.njk
test/unit/controller/payment-links/get-amount.controller.ft.test.js
test/unit/controller/payment-links/get-information.controller.ft.test.js
test/unit/controller/payment-links/get-reference.controller.ft.test.js
test/unit/controller/payment-links/post-amount.controller.ft.test.js
test/unit/controller/payment-links/post-information.controller.ft.test.js
test/unit/controller/payment-links/post-reference.controller.ft.test.js
test/unit/controller/payment-links/post-web-address.controller.ft.test.js

Previously we were passing validation errors from the POST controller when we redirect to the GET controller in flash messages in a confusing way.
These also contained HTML markup constructed by the controller which is not advised.
Make this work in a more sensible way by putting the validation errors as well as the submitted form values into the session cookie in a "recovered" object. Then in the GET controller after redirect, retrieve from here and delete the object from the session.
Create a nunjucks macro "errorSummary" which takes a list of errors and displays them in the design system error summary component when required. This simplifies the repeated template logic. And can be used in other existing places where we show an error summary.

PP-7002 Display errors better for create payment link journey

---

.secrets.baseline
package-lock.json
package.json

Snyk is no longer required in the repo as we use the Snyk Github integration instead:
ihttps://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration
- Uninstalled the npm module using `npm uninstall snyk --save` - used the same version of Node as configured in the package.json file: 12.16.3
- This updated the package-lock.json
- This resulted in quite few updates to the package-lock.json
- Removed all references from package.json
- Removed npm scripts referenceing Snyk commands
- Removed Snyk config

PP-6780 Remove Snyk from Repo

---

app/controllers/credentials.controller.js
app/controllers/user/phone-number/post.controller.js
app/views/team-members/edit-phone-number.njk
test/cypress/integration/user/edit-phone-number.cy.test.js

Avoid passing HTML markup in flash messages to display validation error. Instead re-render the form, passing errors to template.

PP-7002 Display error messages properly for edit phone number

---

app/controllers/payment-links/get-edit-amount.controller.js
app/controllers/payment-links/get-edit-information.controller.js
app/controllers/payment-links/get-edit-reference.controller.js
app/controllers/payment-links/get-edit.controller.js
app/controllers/payment-links/post-edit-amount.controller.js
app/controllers/payment-links/post-edit-information.controller.js
app/controllers/payment-links/post-edit-reference.controller.js
app/controllers/payment-links/post-edit.controller.js
app/middleware/express-unhandled-error-handler.js
test/unit/controller/payment-links/get-edit-amount.controller.test.js
test/unit/controller/payment-links/get-edit-information.controller.test.js
test/unit/controller/payment-links/get-edit-reference.controller.test.js
test/unit/controller/payment-links/post-edit-amount.controller.ft.test.js
test/unit/controller/payment-links/post-edit-information.controller.ft.test.js
test/unit/controller/payment-links/post-edit.controller.ft.test.js

It is currently only possible to edit one payment link at a time due to how we use the session for this journey. So editing 2 payment links in different browser tabs isn't possible and results in unexpected behaviour currently.
Handle this by:
- If on the summary page for editing the payment link and the ID in the URL doesn't match that in the session, clear the session and show the page for the payment link with id from the URL.
- If trying to visit a page to edit individual details of a payment link and the ID in the URL does not match the ID in the session, put the user back on the "Manage payment links" page with an error message.
- If attempting to make a POST request to update a payment link and the ID in the URL does not match the ID in the session, also put the user back on the …

PP-7002 Handle edit payment link conflicts better

---

app/controllers/payment-links/post-review.controller.js
app/controllers/two-factor-auth-controller/post-configure.controller.js
app/views/includes/flash.njk
app/views/macro/success-notification.njk
app/views/payment-links/manage.njk
app/views/team-members/team-member-profile.njk
app/views/transaction-detail/index.njk
test/cypress/integration/payment-links/create-payment-link.cy.test.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/integration/user/edit-phone-number.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/products-stubs.js
test/cypress/stubs/token-stubs.js
test/fixtures/token.fixtures.js
test/unit/controller/payment-links/post-review.controller.ft.test.js

When removing markup passed in flash messages, there was a content regression meaning all success messages were displayed with the govuk paragraph formatting, when before usually were either just a header or a header followed by a paragraph.
Make it so that all notifications shown using the 'generic' flash put the content in a h2.
For cases where we want a header and a paragraph, use a different flash key and handle this in the individual templates that show the the notifications.
Create a nunjucks macro for re-use of the notification component.

PP-7002 Always display generic flash messages as headers

---

app/controllers/two-factor-auth-controller/get-configure.controller.js
app/controllers/two-factor-auth-controller/post-configure.controller.js
app/views/two-factor-auth/configure.njk
test/unit/controller/two-factor-auth-controller/get-configure.controller.ft.test.js
test/unit/controller/two-factor-auth-controller/post-configure.controller.ft.test.js

Put errors in a 'recovered' object on the session and get them in the GET controller after redirect. Then pass errors into the template and use them to to display the error summary component.
Improve the validation message to indicate that the code may have expired. This new error message is taken from another place we validate 2fa auth messages.
Minor code improvements including using async/await.

PP-7002 Don't pass markup in flash message for 2fa controller

---

app/controllers/settings/get.settings.controller.js
app/controllers/toggle-moto-mask-card-number/index.js
app/controllers/toggle-moto-mask-card-number/toggleMotoMaskCardNumber.get.controller.js
app/controllers/toggle-moto-mask-card-number/toggleMotoMaskCardNumber.post.controller.js
app/controllers/toggle-moto-mask-security-code/index.js
app/controllers/toggle-moto-mask-security-code/maskSecurityCode.get.controller.js
app/controllers/toggle-moto-mask-security-code/maskSecurityCode.post.controller.js
app/paths.js
app/routes.js
app/services/clients/connector.client.js
app/views/includes/settings-read-only.njk
app/views/settings/index.njk
app/views/toggle-moto-mask-card-number/index.njk
app/views/toggle-moto-mask-security-code/index.njk
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/gateway-account.fixtures.js
test/fixtures/user.fixtures.js
test/ui/toggle-collect-billing-address.ui.test.js
test/unit/clients/connector-client/connector-patch-moto-mask-card-number.pact.test.js
test/unit/clients/connector-client/connector-patch-moto-mask-security-code.pact.test.js

Description:
- Add new routes:
- /moto-mask-card-number
- /moto-mask-security-code
- Added new controllers
- Updated connector client
- toggleMotoMaskCardNumberInput
- toggleMotoMaskSecurityCodeInput
- Updated settings page with new section for updating Moto mask settings
- Updated pact tests
- Updated cypress tests

PP-6958 Mask credit card number and security code for Moto

---

app/paths.js

Description:
- Currently the public facing urls are moto-mask-card-number & moto-mask-security-code. We are modifying then to be moto-hide-card-number & moto-hide-security-code respectively.

PP-6958 public facing url should contain 'hide' not 'mask'

---

.secrets.baseline
app/controllers/forgotten-password.controller.js
app/services/user.service.js
app/utils/validation/server-side-form-validations.js
app/utils/validation/server-side-form-validations.test.js
app/views/forgotten-password/index.njk
app/views/forgotten-password/new-password.njk
test/integration/forgotten-password.ft.test.js
test/unit/controller/edit-merchant-details-controller/post-edit.controller.test.js

Currently, if an email address is entered that no account is found for, we would attempt to redirect to the URL for resetting the password resulting in a confusing error message being displayed.
Instead, handle a 404 from adminusers by displaying a sensible error message and redirecting to the same page to enter an an email address to request a password reset.
Fix this and also fix the following:
- Display error messages properly using the error summary component and inline error messages.
- Make the controller easier to read by using async/await.
- Don't use anonymous functions for controllers.
- Move password validation out of the service and into the common server-side-form-validations module so we can distinguish between errors from adminusers and errors from selfservice. While doing …

BAU Fix displaying errors for forgotten password controller

---

.secrets.baseline
app/controllers/forgotten-password.controller.js
test/integration/forgotten-password.ft.test.js

Prevent email enumeration attempts by not telling users that an account
doesn't exist when an email address is entered for a non-existent
account.
Instead, show that page that says we have sent an email.

BAU Don't tell user account doesn't exist for password reset

---

app/views/request-to-go-live/choose-how-to-process-payments.njk
app/views/request-to-go-live/organisation-address.njk
app/views/settings/index.njk
test/cypress/integration/request-to-go-live/organisation-address.cy.test.js

Replace ' apostrophes (U+0027) with ’ right single quotation marks (U+2019) in possessive nouns in user-facing text on admin tool pages.
Because it was annoying me.

BAU — Replace apostrophes with right single quotation marks

---

app/views/stripe-setup/vat-number/index.njk

- The label tag was outside the H1 tag.
- This has been moved into the H1 tag.

PP-7079 DAC Audit - Stripe Setup > VAT number heading - move the label tag inside the heading tag

---

app/views/digital-wallet/google-pay.njk

Description:
- On selfservice.payments.service.gov.uk/digital-wallet/google-pay the link to the Google Pay documentation is broken. This PR provides the correct link

BAU - Fix broken link to Google Pay documentation

---

app/views/services/_service-section-small.njk

- Add hidden spans for accessibility on the services page when number of services >= 7

PP-7097 DAC Audit - Fix bug with Services > More then 7 services - hidden spans not showing up on links

---

app/browsered/target-to-show.js
app/views/payment-links/_product.njk

- When someone clicks `Payment Link > Delete` - then the `heading` of the delete box is put into focus.
- This means a blue outline is displayed around the `Are you sure you want to delete this link?` heading
- Change the heading to the H2
- Also need to add a `tabindex=0` to the heading - to allow it to be focused -see: https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex
Screen shot:

PP-7092 DAC Audit - Delete Payment Link > Focus heading & change to H1

---

app/views/api-keys/_keys.njk
app/views/api-keys/index.njk

- Would take too long to update the tabs to work fully with the Design Sytem tabs component.
- Therefore, removed the tabs and replaced with plain links.

PP-7090 DAC Audit - Api keys page > Replace tabs with links

---

app/assets/sass/components/dashboard-activity.scss
app/views/dashboard/_activity.njk

- Make the 3 headings above the different types of transaction amount boxes into links.
- Remove the links from the amount boxes.
Screenshot:

PP-7094 DAC Audit - Dashboard - update links

---

app/browsered/copy-text.js
app/views/api-keys/create.njk

- In the `create API key` flow, when you press the button `Copy API key to clopboard`, it does the following:
- Button contains a data attribute with a selector to a hidden div that has `aria-live=assertive`
- When the button is pressed, it also updates the div with the message `Copy API key to clipboard`
- This message is read out by screen readers.
Screenshots:

PP-7108 DAC Audit - Copy API key > Add "aria-live" region

---

app/assets/sass/application.scss
app/assets/sass/components/prototype-links.scss
app/views/dashboard/demo-service/confirm.njk

- Add the CSS `word-break: break-all` - so that long urls are wrapped across multiple lines.
- Add new SCSS file for prototype links.
Screenshot: Long Prototype urls now wrap onto multiple lines when you zoom in 400%.

PP-7110 DAC Audit - Prototype links > Fix reflow issue.

---

app/views/transactions/filter.njk

- On the transactions page, wrap the `Card brand` and `Payment status` with `fieldset` and `legend` tags
- The page will still look the same.

PP-7101 DAC Audit - Transactions Page > Add `fieldset` and `legend` tag

---

app/controllers/dashboard/dashboard-activity.controller.js
app/views/dashboard/_activity.njk

The links used state strings that do not map to any of the states expected by the transactions list page. It is possible, these are old representations of the states.
Update the links so that they filter the transactions list correctly.

PP-7094 Update links on dashboard to use correct states

---

app/views/transaction-detail/_refund.njk

Add the `preventDoubleClick` attribute to the refund payment button.
This "debounces" event propagation for clicks for 1 second after the
button is pressed.
This can only prevent subsequent clicks for 1 second.
This is a temporary fix which will help solve double clicking however as
this is a terminal POST request a further script should be added to
fully disable the button until the action is completed.

PP-7214 "Debounce" refund button submission

---

.secrets.baseline
app/controllers/register-service.controller.js
app/views/self-create-service/register.njk
test/integration/self-registration/self-registration-create-user-account.ft.test.js
test/unit/controller/register-service-controller/register-service.controller.test.js

- Use async/await to make code easier to follow.
- Store errors and recovered form data in a 'recovered' object on the session, and display using the error summary component rather than using req.flash.
- Improve error messages to make them more better/more consistent with error messages we show in other places.
- Don't directly display errors originating from adminusers to the user, instead identify errors based on the status code and display messages defined in selfservice.
- Use the `server-side-form-validations.js` module for all validation, working towards retiring the `registration-validations.js` module.

PP-7288 Refactor create user account part of self registration journey

---

app/controllers/register-service.controller.js
test/integration/self-registration/self-registration-create-user-account.ft.test.js

Weren't clearing the recovered session after redirecting, so refreshing the page would cause errors to be re-displayed when we would expect the form and the errors to be cleared.

PP-7228 Clear recovered session after redirect

---

app/controllers/my-services/get-index.controller.js
app/services/clients/connector.client.js
app/services/service.service.js
test/unit/controller/service-switch.controller.it.test.js
test/unit/services/service.service.test.js

This is the first PR - the Nunjuks work will be done in another PR:
- Remove the backend Node JS for Direct Debit on the services page.
- Update the connector client
- getGatewayAccounts - Use the `baseClient` instead of `oldBaseClient`
- Update relevant tests
- Update Nock requests to work with requests that use the new `baseClient`

PP-7304 Remove Direct Debit from services page

---

app/controllers/api-keys/post-create.controller.js
app/controllers/payment-links/post-review.controller.js

Update controllers that deal with creating potentially external API
keys. Use more up to date Node guidance to make the code clearer.
* Use clearer variable naming
* Use async/ await
* Handle errors using `next` and middleware where appropriate
* Name any large anonymous methods
* Simplify object construction

PP-5236 Cleanup token creation controllers

---

app/controllers/api-keys/post-create.controller.js
app/controllers/payment-links/post-review.controller.js
test/unit/controller/api-keys/post-create.controller.ft.test.js
test/unit/controller/payment-links/post-review.controller.ft.test.js

Include the account type for the gateway account that is requesting a
new API key. This is applied to both account API keys and API keys
associated with payment links for the account.
Entirely internal and ad-hoc features like demo payments to test with
your users are not included -- with this set up API keys generated with
those features will not provide token account type and will not
expect a prefix on the resulting token.
Update mocks to guarantee the account type is being correctly propagated
through to public auth.
- All integration, cypress and end to end tests should continue to pass; that latest version of public auth master will accept this parameter and should respond with success

PP-5236 Api key create requests pass through account type

---

app/controllers/api-keys/post-create.controller.js
app/controllers/make-a-demo-payment/go-to-payment.controller.js
app/controllers/test-with-your-users/submit.controller.js
test/unit/controller/api-keys/post-create.controller.ft.test.js
test/unit/controller/make-a-demo-payment-controller/go-to-payment.controller.ft.test.js
test/unit/controller/test-with-your-users-controller/submit.controller.ft.test.js

Self service creates tokens for 4 main reasons:
* generating card API tokens for users
* creating new payment links
* demo payments feature
* test with your users feature
In each of these cases we should be passing a "type" parameter, this
translates to a public auth `TokenSource` which tells public auth if
this api key is intended to be used for an API client or internally as
one of our products.
Payment links and the two testing features we provide all work by
creating products and running test payments through those. As the public
auth token will be used by a "product" this type should be specified.
Update the generate API key route to no longer rely on the default
source (API).

PP-6129 Specify token "source" for token creation

---

app/browsered/multi-select.js
app/views/includes/multi-select.njk
test/cypress/integration/transactions/transaction-list-pagination.cy.test.js
test/cypress/integration/transactions/transaction-search.cy.test.js

- Add JS to toggle 'aria-expanded=true/false' on the button
- Fix ID of the button to match the label
- Update Cypress tests to use the new ID for:
- Transaction > Card brand filter multi-select
- Transaction > Status filter multi-select

PP-7207 DAC Audit - Transactions > Multi-select for Card Brand & Payment Status

---

app/browsered/multi-select.js
app/views/transactions/filter.njk

- Fix aria-expanded - so it is only set on the button.
- Add an extra 'fieldset' tag to wrap the container for the checkboxes.

PP-7207 DAC Audit > Transactions > Multi-select bug updates

---

app/views/payment-links/manage.njk

This flag should have been removed when reporting columns for payment
links was released. This will always show the helper text providing
information about reporting columns to the user. This pattern will be
further iterated on by bringing reporting columns in-line with payment
creation.

PP-7299 Remove experimental flag around payment link helper text

---

app/services/clients/connector.client.js
test/unit/clients/connector-client/connector-patch-integration-version-3ds.pact.test.js

Add support for sending a PATCH request to `/v1/api/accounts/{accountId}` on connector with a body like this:
```json
{
"op": "replace",
"path": "integration_version_3ds",
"value": 2
}
```

PP-7416 Allow selfservice to set 3DS Secure integration version

---

app/controllers/payment-links/get-manage.controller.js
app/views/payment-links/manage.njk
test/cypress/integration/payment-links/create-payment-link.cy.test.js

Payment links created in test and live environments have very different
use cases; the wording for the payment link creation references the
payment link being "live" which conflicts with our use of this status
for accounts.
Add a separate path for test and live accounts to provide users
additional information if they are just testing.
**Payment link created in a test account**
**Payment link created in a live account**

PP-7409 Add test vs. live content for payment link created message

---

.secrets.baseline
app/controllers/your-psp/get.controller.js
app/controllers/your-psp/index.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/paths.js
app/routes.js
app/views/your-psp/_worldpay-flex.njk
app/views/your-psp/flex.njk
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/gateway-account.fixtures.js

Add a button to the ‘Your PSP’ page for Worldpay accounts to enable or disable 3DS Flex.
The enable button is shown only if it’s a Worldpay account, 3DS is enabled, 3DS Flex is disabled and there are 3DS Flex credentials.
The disable button is shown only if it’s a Worldpay account, 3DS is enabled and 3DS Flex is enabled.
No button is shown in other circumstances, meaning, for example, that a service cannot enable 3DS Flex if they have not entered 3DS Flex credentials.
The page that’s requested when the button is pressed requires the `toggle-3ds:update` permission whereas the page it’s displayed on requires the `gateway-credentials:read` permission. This is a less than ideal but only the `admin` role has either of these so the button won’t be shown to anyone who can’t press it.
Remove the …

PP-7416 Add button to enable or disable Worldpay 3DS Flex

---

app/controllers/create-service.controller.js
app/controllers/register-service.controller.js
app/services/clients/adminusers.client.js
app/services/service-registration.service.js
app/services/service.service.js
test/integration/self-registration/self-registration-otp-verify.ft.test.js
test/integration/service-registration.service.it.test.js
test/unit/clients/adminusers-client/service/create-service.pact.test.js
test/unit/controller/create-service-controller/post.controller.test.js

Log when new service is created:
- as part of user registration
- when an existing user adds a new service
Refactor surrounding code to conform to best practices.
For the create service response from adminusers, transform the response using the `Service` model, like we do for other responses.

PP-7458 Log when new service is created

---

app/controllers/your-psp/post-flex.controller.js

Stop enabling 3DS when Worldpay 3DS Flex credentials are entered. We don’t enable 3DS Flex when credentials are entered any more (there’s now a button for that) so it doesn‘t make any sense to enable 3DS in general.
Also remove code that handles the logic for the ‘Remove credentials’ button because that button is no longer present now we have the button to enable or disable 3DS Flex.

PP-7416 Stop enabling 3DS when 3DS Flex credentials entered

---

app/controllers/my-services/get-index.controller.js
app/models/Service.class.js
test/unit/controller/service-switch.controller.it.test.js

At some point the ordering of services on the “My services page” changed. We weren’t doing any explicit ordering of services so were just relying on the order returned by the database.
This could have been when we bulk updated the “created_date” recently, but it's unclear.
Explicitly order on the id as we think that’s how services were previously ordered.
Hiding whitespace changes in GitHub will make this easier to review as some indentation was changed.

PP-7458 Order services by ID

---

app/errors.js
test/unit/errors.test.js

Add custom error classes. These will be handled by a catch-all error handler at the end of the express stack which will render the appropriate error page.

PP-7491 Add error classes

---

app/services/clients/adminusers.client.js
app/services/clients/connector.client.js

Added client methods to get gateway accounts and service by external ID. These will be used by new getGatewayAccountAndService middleware (https://github.com/alphagov/pay-selfservice/pull/2399)
- Added `getAccountByExternalId` to connector client to retrieve gateway account by external ID
- Added `getServiceByExternalId` & `getServiceForGatewayAccount` to adminusers client to get service by external ID or for gateway account

PP-7489 Add adminusers and connector clients methods

---

app/controllers/payment-links/metadata/metadata-form.js
scripts/tunnel.sh
test/unit/controller/payment-links/metadata/paymentlink-metadata-form.test.js

PP-7360 Add Payment Links flow > Add Reporting Columns
- Add new validation to `metadata-form.js`
- Make sure metadata headers and values < 50
- Make sure metadata headers are unique
PP-7360 Update tunnel script - add products
- Update script so that when you tunnel into test is also tunnels to 'products'
- So that you can setup Payment Links in a local instance of Self service that tunnels to test.

Pp 7360 payment link reporting columns

---

.secrets.baseline
app/middleware/get-service-and-gateway-account.middleware.js
app/paths.js
test/unit/middleware/get-service-and-gateway-account.middleware.test.js

- Added new middleware to get account and service based on URL path params
Middleware expects atleast one parameter (gatewayAccountExternalId or serviceExternalId) to be available on request to get gateway account/service. If both are available, additionally checks for gatewayAccount to be part of the service.

PP-7489 Add account and service middleware

---

app/controllers/service-users.controller.js
app/controllers/two-factor-auth-controller/get-configure.controller.js
app/controllers/two-factor-auth-controller/post-configure.controller.js
app/controllers/two-factor-auth-controller/post-index.controller.js
app/controllers/two-factor-auth-controller/post-resend.controller.js
app/controllers/user/phone-number/post.controller.js
app/paths.js
app/routes.js
app/views/includes/header.njk
app/views/includes/propositional-navigation.njk
app/views/team-members/edit-phone-number.njk
app/views/team-members/team-member-profile.njk
app/views/two-factor-auth/configure.njk
app/views/two-factor-auth/index.njk
test/unit/controller/two-factor-auth-controller/get-configure.controller.ft.test.js
test/unit/controller/two-factor-auth-controller/get-index.controller.ft.test.js
test/unit/controller/two-factor-auth-controller/post-configure.controller.ft.test.js
test/unit/controller/two-factor-auth-controller/post-index.controller.ft.test.js

Not all authentication middleware was run on these routes. This means we weren't checking that the user has a valid session and we weren't applying CSRF checks to the POST route.
Group "/my-profile/" paths in object within paths object.
Previously, "/my-profile/phone-number" wasn't added to the authenticated paths array, so not all authorisation middleware was included on this route. This means we weren't checking that the user has a valid session and we weren't applying CSRF checks to the POST route.
Add `paths.profile` to the authenticated routes array so all paths under it have the authorisation middleware and CSRF middleware applied.

PP-7488 Ensure authentication middleware is included on all routes that require authorisation

---

test/unit/routes.test.js

Add test to ensure that authorisation middleware is called for all routes that require authentication.
Achieve this by specifying in the test which paths do not require authentication. Then check all route setup calls to ensure that the authorisation middleware is used for routes with paths that are not in this list.
This will ensure that the middleware is used for any new routes that are registered, unless they are explicitly added to the exclude list.
When the new authentication middleware has been added, will modify to check if the new middleware is run instead. And can be updated to remove checks for the old middleware when we have fully replaced it.

PP-7488 Add unit test to ensure authorisation middleware used

---

app/middleware/user-is-authorised.js
test/fixtures/service.fixtures.js
test/unit/middleware/user-is-authorised.test.js

Add middleware that will replace existing authorisation middleware and be used alongside the new middleware to resolve the service and gateway account from the URL path params.
This middleware optionally takes a permission string and checks:
- That the user is logged in and has a valid session
- The the middleware to resolve the service from the URL path param has successfully resolved a service if there is a service/gateway account id path param
- That the user has a service role for the resolved service
- If a permission has been specified, that the user has the permission for the resolved service
- Existing auth middleware calls `csrf.ensureSessionHasCsrfSecret(req, res, next)`. I haven't added anything to do this on the assumption that we'll change how CSRF is implemented as part of …

PP-7488 Add authorisation middleware

---

app/middleware/get-service-and-gateway-account.middleware.js
app/middleware/has-services.js
test/unit/middleware/get-service-and-gateway-account.middleware.test.js

- Extends gateway account object (get account and service middleware) with additional attributes similar to get-gateway-account.js middleware

PP-7489 Extend gateway account object

---

app/services/clients/adminusers.client.js

- Removed clients methods as these are not currently used. We are using service details available on user object to set on request and using it further in the code base.

PP-7489 Remove unused client methods

---

app/controllers/payment-links/get-amount.controller.js
app/controllers/payment-links/get-delete.controller.js
app/controllers/payment-links/get-disable.controller.js
app/controllers/payment-links/get-edit-amount.controller.js
app/controllers/payment-links/get-edit-information.controller.js
app/controllers/payment-links/get-edit-reference.controller.js
app/controllers/payment-links/post-edit-amount.controller.js
app/controllers/payment-links/post-edit-information.controller.js
app/controllers/payment-links/post-edit-reference.controller.js
app/controllers/payment-links/post-edit.controller.js
app/controllers/payment-links/post-review.controller.js
app/paths.js
app/routes.js
app/views/dashboard/_links.njk
app/views/payment-links/_nav.njk
app/views/payment-links/edit-amount.njk
app/views/payment-links/edit-information.njk
app/views/payment-links/edit-reference.njk
app/views/payment-links/edit.njk
test/unit/controller/payment-links/get-delete.controller.ft.test.js
test/unit/controller/payment-links/get-disable.controller.ft.test.js
test/unit/controller/payment-links/post-edit.controller.ft.test.js
test/unit/controller/payment-links/post-review.controller.ft.test.js

As the root page for managing payment links is now nested in the
`paymentLinks.manage` attribute, rename the key to `index`.

PP-7482 Payment links rename manage payment link index

---

app/middleware/error-handler.js
test/unit/middleware/error-handler.test.js

Log when we handle various errors so it's easier to trace what's happened for a request.
Log any useful info we have on the `req` - the user external id, service external id and gateway account id.

PP-7488 Improve logging in error handler

---

app/middleware/get-service-and-gateway-account.middleware.js
test/unit/middleware/get-service-and-gateway-account.middleware.test.js

Connector returns `gateway_account_id` as a `Number` value, AdminUsers
service `gateway_account_ids` as `String`s.
Update the test to realistically reflect this and fail. Update the
middleware to cast number to string so they can be compared with
`Array.includes`.

PP-7489 Get request data middleware normalise gateway account as string

---

app/controllers/payment-links/get-edit.controller.js
app/controllers/payment-links/get-review.controller.js
app/controllers/payment-links/get-update-reporting-column.controller.js
app/controllers/payment-links/metadata/metadata-form.js
app/controllers/payment-links/post-update-reporting-column.controller.js
app/paths.js
app/utils/payment-links.js
app/views/payment-links/reporting-columns/_manage-reporting-columns.njk
test/cypress/integration/payment-links/edit-payment-link.cy.test.js
test/unit/controller/payment-links/metadata/paymentlink-metadata-form.test.js

Fixes a bug with representing reporting column keys in the URL. These keys should 
be URL encoded, this was removed in order to try and support the current and proposed 
implementations of reporting columns, it is not optional however.
Additionally avoid allowing the backspace character from being included in the key/ value. 
Reporting columns are stored as JSON metadata, they are validated across
multiple services and stored as JSONB in Postgres. In order to reduce
the number of places edge cases could arise, don't allow characters that
could either interfere with the URL structure or JSON keys.

PP-7630 Fix reporting columns URL encoded key

---

app/controllers/payment-links/post-review.controller.js
app/services/clients/products.client.js
test/fixtures/product.fixtures.js
test/unit/controller/payment-links/post-review.controller.ft.test.js

The create and manage flow both now curate and validate metadata in the
payment link session, allowing the user to safely create, update and
delete metadata.
The backend now supports receiving a complete metadata object, pass this
through to the API calls.

PP-7509 Pass session metadata through to products calls

---

app/services/clients/connector.client.js
test/fixtures/worldpay-3ds-flex-credentials.fixtures.js
test/unit/clients/adminusers-client/user/authenticate.pact.test.js
test/unit/clients/connector-client/connector-post-worldpay-check-3ds-flex-config.pact.test.js

This change
- adds a new function `postCheckWorldpay3dsFlexCredentials` which makes a call to a connector application to check Worldpay 3DS Flex credentials.
- adds a PACT test to test the function to ensure that it can handle a happy scenario correctly.
- fixes authenticate PACT tests failures.

PP-7422: Add a function to call to connector to check Worldpay 3DS Flex credentials

---

app/controllers/payment-links/get-edit.controller.js

When the flag is enabled for reporting columns that are managed in the
session flow, consistently remove the backend product metadata as it
won't include the changes that have been made since the edit session has
started.
The other values that are managed in the flow are "merged" with the
backend product every time the payment link "edit" page is loaded, this
works because these values will always be replaced. As reporting columns
can be edited and even entirely removed, the session version should be
considered the true copy until submission.

PP-7509 Always delete backend product metadata when using in-flow reporting columns

---

app/controllers/payment-links/metadata/metadata-form.js
app/controllers/payment-links/post-update-reporting-column.controller.js
test/unit/controller/payment-links/metadata/paymentlink-metadata-form.test.js

Updating reporting columns should catch all errors that could happen
during controller execution.
Add logs with salient information requested in the ticket for tracking
volumes of in-session changes.
Fix duplicate check to make it in-line with the products and public api
backend.

PP-7509 Log salient reporting column actions

---

app/controllers/payment-links/post-edit.controller.js
app/controllers/payment-links/post-review.controller.js

- Add logging messages when the backend is called to:
- Add new Payment link
- Edit existing Payment link
Include `has_metadata` from the ticket and additional information about
the gateway account creating or updating the payment link.

PP-7509 Payment link update (create and edit) logging

---

app/errors.js
app/middleware/error-handler.js
app/middleware/permission.js
app/middleware/user-is-authorised.js
app/routes.js
test/unit/middleware/error-handler.test.js
test/unit/middleware/permission.test.js
test/unit/middleware/user-is-authorised.test.js
test/unit/routes.test.js

We've decided that our new pattern for setting up routes will be to create various routers for the different route paths. Something like the following:
- Service router - sets up all routes for pages related to a specific service
- Account router - sets up all routes for pages related to a specific account
- Some other router(s) for other logged in routes such as user profile settings and all services views
We can then initialise the authorisation middleware (user-is-authorised.js) on the router level rather than on each individual route as this middleware must be run on every logged in route.
The permissions middleware requires initialisation with a specific permission string which will depend on the route, so must be included on individual routes and therefore needs to remain separate. …

PP-7488 Remove permission check from new authorisation middleware

---

app/middleware/get-service-and-gateway-account.middleware.js
test/unit/middleware/get-service-and-gateway-account.middleware.test.js

- Removed most of the logging as error handler middleware is logging the details now for errors thrown and adds additional context.
- getGatewayaccountAndService middleware doesn't throw exceptions anymore if service or gateway account are not found. Authorisation middleware will check for service/gateway account and user access and throws relevant error
- Refactored tests following story review comments to make sure assertions are always reached

PP-7489 Remove logging from gatewayAccountAndService middleware

---

app/browsered/multi-select.js
app/controllers/my-services/get-index.controller.js
app/controllers/your-psp/get.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
app/middleware/resolve-service.js
app/services/service-registration.service.js

Skip running this middleware if the service has already been resolved. This is because the `permissions.js` middleware also returns this middleware. We are changing to a different middleware to resolve the service as part of https://payments-platform.atlassian.net/browse/PP-7520 so this is to enable that switchover while it is in progress. We can remove the resolve service middleware when this is done.
Bundled in a commit to run the linter. It's only `resolve-service.js` that has code changes.

PP-7488 Skip resolve service middleware if service already resolved

---

app/controllers/your-psp/post-flex.controller.js
app/views/your-psp/flex.njk
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/fixtures/worldpay-3ds-flex-credentials.fixtures.js

This change adds two tests to Cypress to test the following scenarios.
1. Connector returns result = invalid after checking Worldpay 3DS Flex credentials.
2. Connector fails while checking Worldpay 3DS Flex credentials.
I ran both mocha tests and cypress tests. They passed. I verified responses from stubs and they were valid.

PP-7422: Add tests on checking Worldpay 3DS Flex credentials

---

app/controllers/billing-address/toggle-billing-address.controller.js
app/middleware/get-service-and-gateway-account.middleware.js
app/paths.js
app/routes.js
app/utils/format-account-paths-for.js
app/utils/format-accounts-paths-for.test.js
app/views/settings/index.njk
server.js
test/fixtures/gateway-account.fixtures.js
test/unit/controller/billing-address-controller/toggle-billing-address.controller.ft.test.js

Introduces a new sub router architecture for admin tool routes. This
allows account specific pages to sit behind the account router and have
common middleware taken care of. It also uses the new middleware
following the proposed middleware architecture design that adhere to
best error handling practice and don't directly respond to the HTTP
request.
To prove/ test the proposed router architecture, update the toggle
billing address feature page to use the new account URL structure.

PP-7520 Account URL structure

---

app/controllers/payment-types/post-index.controller.js
app/routes.js
app/utils/display-converter.js
app/utils/nav-builder.js
test/cypress/integration/dashboard/dashboard-go-live-link.cy.test.js
test/cypress/integration/settings/payment-types.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/utils/request-to-go-live-utils.js

- Update routes for the Settings > Payment Types - so that the gateway account
external id is part of the URL
- Added new "get gateway account by external ID" stub for Cypress, this
can now be used for any pages using the new middleware that will fetch
accounts from `/v1/api/accounts/external-id/:id`.
- Updated Cypress tests for payment links page.
With @iqbalgds 
With @SandorArpa

PP-7520 Payment types page uses new account URL structure

---

test/fixtures/user.fixtures.js
test/test-helpers/pact/pactifier.js
test/unit/clients/adminusers-client/user/get-multiple-users.pact.test.js

Want to remove the pact dependency so that fixtures can be used directly by Cypress test code, which cannot use Node dependencies.
The pact dependency is currently used to construct pacts for responses which include the appropriate matchers.
To do this:
- Remove `.getPactified()` methods returned by fixtures. Instead, "pactify" the response in the pact test itself.
- Add utility to return "pactifiers" to pactify certain responses.
- Remove `getPlain()` and `getObject()` methods returned by fixtures and just return the raw response object. We can construct the models returned by `getObject()` wherever we need them easily enough.

PP-7588 Demonstrate how pact dependency will be removed from fixtures

---

.secrets.baseline
test/cypress/plugins/stubs.js
test/fixtures/go-live-requests.fixture.js
test/fixtures/invite.fixtures.js
test/fixtures/self-register.fixtures.js
test/integration/invite-users.controller.ft.test.js
test/integration/invite-validation.controller.ft.test.js
test/integration/self-registration/self-registration-create-user-account.ft.test.js
test/integration/self-registration/self-registration-otp-resend.ft.test.js
test/integration/self-registration/self-registration-otp-verify.ft.test.js
test/integration/self-registration/self-registration-service-naming.ft.test.js
test/integration/service-registration.service.it.test.js
test/integration/service-users.ft.test.js
test/unit/clients/adminusers-client/invite/complete-service-invite.pact.test.js
test/unit/clients/adminusers-client/invite/complete-user-invite.pact.test.js
test/unit/clients/adminusers-client/invite/generate-invite-otp-code-user.pact.test.js
test/unit/clients/adminusers-client/invite/get-invite.pact.test.js
test/unit/clients/adminusers-client/invite/invite-user.pact.test.js
test/unit/clients/adminusers-client/invite/resend-otp-code.pact.test.js
test/unit/clients/adminusers-client/invite/submit-service-registration.pact.test.js
test/unit/clients/adminusers-client/invite/verify-otp-code.pact.test.js
test/unit/clients/adminusers-client/invite/verify-service-otp-code.pact.test.js
test/unit/clients/adminusers-client/service/govuk-pay-agreement-post-email-address.pact.test.js
test/unit/clients/adminusers-client/service/stripe-agreement-post-ip-address.pact.test.js

Remove pact dependency from `go-live-requests.fixture.js`, `invite.fixtures.js` and `self-register.fixtures.js`
Remove some fixtures from `self-register.fixtures.js` that were constructing requests to selfservice endpoints for functional tests as it makes more sense to just declare these in the tests themselves.

PP-7588 Remove pact dependency from some more fixtures

---

test/cypress/integration/request-to-go-live/index.cy.test.js
test/cypress/plugins/index.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js
test/cypress/stubs/go-cardless-connect-stubs.js
test/cypress/stubs/products-stubs.js
test/cypress/stubs/stub-builder.js
test/cypress/stubs/user-stubs.js

Start simplifying the process for generating stubs which are pushed to Mountebank to stub out requests to other services.
This commit demonstrates how this will be done, by moving generating the stub in the format expected by Mountebank and using our fixtures into the stub helper files. Previously this was done in the `stubs.js` file, which made the code quite opaque and confusing.
To allow for this, the `setupStubs` Cypress command will deal with either:
1. An object with name and opts fields to constuct a stub from the `stubs.js` file as it does now
2. An already build Mountebank stub which it will not alter and send directly to Mountebank.

PP-7588 Start simplifying Cypress stub creation

---

test/cypress/integration/settings/3ds.cy.test.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/plugins/stubs.js
test/cypress/stubs/gateway-account-stubs.js

Move gateway account stubs out of stubs.js and construct them directly in the gateway-account-stubs helper file.
Remove some stubs for patch requests which were never actually hit due to mis-configuration of the stubs. As these stubs just return 200 without a body they are unnecessary as Mountebank returns a 200 by default for any request that does not match a stub.

PP-7588 Move gateway account stubs

---

app/controllers/request-to-go-live/agreement/post.controller.js

We now store the date a service was greated on. Include it in the request to go live Zendesk ticket so we have more information about the time taken between creating the test service and requesting a live account when we look at these tickets.

PP-7295 Send service created date in go-live zendesk ticket

---

app/controllers/request-to-go-live/agreement/post.controller.js
app/models/Service.class.js

We convert the service response from adminusers using a model class.
Update the model to contain a `createdDate` property and user this when building the Zendesk ticket

PP-7295 Fix created date not included in zendesk ticket

---

app/controllers/credentials.controller.js
app/controllers/payment-types/get-index.controller.js
app/controllers/payment-types/post-index.controller.js
app/controllers/toggle-3ds/3ds.post.controller.js
app/controllers/your-psp/post-flex.controller.js
app/services/clients/connector.client.js
app/services/email.service.js
app/services/service-registration.service.js

- Moves connector client instantiation out of request methods so connector client object is instantiated once and not per request
- Removed request logging from email.service & credentials.controller as both of these now uses new baseclient which logs the same

PP-7585 Instantiate connector client as singleton and cleanup logging

---

app/services/clients/connector.client.js

- Fixes connector client method `postAcceptedCardsForAccount`: Incorrect data is being sent to connector. It should just be `payload` from controller.
Caused by https://github.com/alphagov/pay-selfservice/commit/7b793b5d944652fbf7ef17790f25950d5e846794#diff-0a8d6b0be878b39296cfff51f4a3c04eef6f05c5a39740158c1f2a4e86001190L390

PP-7585 Fix client method postAcceptedCardsForAccount

---

app/controllers/forgotten-password.controller.js
app/controllers/service-users.controller.js
app/controllers/transactions/transaction-detail.controller.js
app/controllers/two-factor-auth-controller/post-index.controller.js
app/controllers/two-factor-auth-controller/post-resend.controller.js
app/controllers/user/phone-number/post.controller.js
app/services/auth.service.js
app/services/clients/adminusers.client.js
app/services/service-registration.service.js
app/services/service.service.js
app/services/transaction.service.js
app/services/user-registration.service.js
app/services/user.service.js
app/services/validate-invite.service.js
test/unit/clients/adminusers-client/invite/complete-service-invite.pact.test.js
test/unit/clients/adminusers-client/invite/complete-user-invite.pact.test.js

- Refactored adminUsers client methods to move `correlationId` to each individual call rather than being set at the instance level.  This allows code that calls this adminUsers client to instantiate once using singleton pattern.
- Updated code to instantiate adminUsers client once rather than per call

PP-7585 Refactor adminUsers client to remove instance correlationId

---

app/controllers/your-psp/post-flex.controller.js
test/cypress/integration/settings/your-psp.cy.test.js
test/cypress/stubs/gateway-account-stubs.js

This change updates post-flex controller to save valid Worldpay 3DS Flex credentials only and only if the result is valid. This change is necessary because the result can contain the value other than "valid" and "invalid". It adds 1 more test to Cypress to test the following scenario.
1. Connector returns result = bad data after checking Worldpay 3DS Flex credentials.
Please note that Self Service application has no way to check that response's body is null or empty before processing it. If the response contains no body or other data,  post-flex controller will attempt to retrieve result from the response's body and this will cause Self Service application to display a generic problem page.

PP-7422: Handle bad result returned by connector

---

app/controllers/edit-service-name.controller.js
app/services/service.service.js
test/unit/controller/edit-service-name/post.controller.test.js
test/unit/services/service.service.test.js

Refactor code to use aync/await
- Update 'edit-service-name' controller
- Update 'service.service' calls to connector when editing a service name
- Update tests

PP-7595 Refactor Edit Service Name controller to use Async / Await

---

app/views/includes/flash.njk
app/views/macro/success-notification.njk
app/views/payment-links/manage.njk
app/views/team-members/team-member-profile.njk
app/views/transaction-detail/index.njk
test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
test/cypress/integration/payment-links/create-payment-link.cy.test.js
test/cypress/integration/payment-links/delete-payment-links.cy.test.js
test/cypress/integration/settings/3ds.cy.test.js
test/cypress/integration/settings/allow-apple-pay.cy.test.js
test/cypress/integration/settings/allow-google-pay.cy.test.js
test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
test/cypress/integration/transactions/transaction-details.cy.test.js
test/cypress/integration/user/edit-phone-number.cy.test.js

Use the new design system notification banner component https://design-system.service.gov.uk/components/notification-banner/ when we display success messages back to the user.
Previously, looked like this:
Now looks like this:

BAU Use design system notification banner component

---

test/integration/auth.ft.test.js
test/integration/get-gateway-account.ft.test.js
test/integration/login.controller.test.js
test/integration/login.ft.test.js
test/test-helpers/mock-session.js

Functional tests use helper functions in `mock-session.js` to create
the express app with the desired session.
Clean this up by making it more clear how and when the current
gateway account cookie is set by the helper methods.

PP-7583 Cleanup mock session test helper

---

app/utils/display-converter.js
app/utils/nav-builder.js

Fix the nav builder so that highlighting the current page in both the top navigation bar and the side settings navigation is highlighted:
- when the URL contains the `/account/ACCOUNT_EXTERNAL_ID/` prefix.
- for pages it didn't previously work for because they weren't included in the list of paths to match on.

PP-7583 Fix nav builder

---

.secrets.baseline
app/controllers/payment-types/post-index.controller.js
app/controllers/toggle-3ds/3ds.post.controller.js
app/paths.js
app/routes.js
app/utils/nav-builder.js
app/views/settings/index.njk
app/views/toggle-3ds/index.njk
test/cypress/integration/settings/3ds.cy.test.js
test/cypress/stubs/user-stubs.js
test/integration/payment-types/payment-types.it.test.js

Use the account router for these routes so that the URL contains the
account external ID and we use our new middleware for resolving the
service/account and checking the user is authorised.

PP-7583 Move 3ds routes to use account URL structure

---

.secrets.baseline
app/controllers/digital-wallet/post-apple-pay.controller.js
app/controllers/digital-wallet/post-google-pay.controller.js
app/paths.js
app/routes.js
app/utils/nav-builder.js
app/views/billing-address/index.njk
app/views/digital-wallet/apple-pay.njk
app/views/digital-wallet/google-pay.njk
app/views/settings/index.njk
test/cypress/integration/settings/allow-apple-pay.cy.test.js
test/cypress/integration/settings/allow-google-pay.cy.test.js

Move apple/google pay settings URLs to use new account URL structure.
Also remove some paths from the authenticatedPaths array in routes.js as all the required middleware is now called for all routes using the account router.

PP-7583 Move digital wallet routes

---

app/controllers/my-services/post-index.controller.js
app/models/GatewayAccount.class.js
app/routes.js
app/utils/flatten-nested-values.js
app/utils/flatten-nested-values.test.js
app/utils/gateway-account-urls.js
app/utils/gateway-account-urls.js.test.js
app/views/services/_service-switch.njk
test/integration/routes.it.test.js
test/test-helpers/mock-session.js
test/unit/controller/service-switch.controller.it.test.js

Simple utility to upgrade or redirect account specific URLs from the
current method to the proposed URL structure.
This will:
* redirect users who are following older links
* allow a seamless change for users actively using the admin tool during a
release
* log upgrades so that we can see how often this is happening
and when legacy code can be removed.

PP-7445 Update accounts URL utility
