alphagov/pay-selfservice

- app/views/provider_credentials/epdq.html
- app/views/provider_credentials/smartpay.html
- app/views/provider_credentials/worldpay.html
- test/ui/credentials_ui_tests.js
- test/ui/service_role_update_ui_tests.js
> PP-2437 - use table layout for creds page

- app/controllers/forgotten_password_controller.js
- app/controllers/login_controller.js
- app/views/forgotten_password/username_get.html
- test/fixtures/browser/forgotten_password_fixtures.js
- test/fixtures/user_fixtures.js
and added validation to forgotten password page
> PP-2006 - Standardised and clarified validation messages

- app/views/provider_credentials/sandbox.html
- test/ui/credentials_ui_tests.js
> PP-2347 - updated copy to be more clear and helpful

- app/views/transactions/index.html
- Datepicker got broken during upgrade to jquery 3.x, this updates the cdn references on the transactions pages to solve this
> PP-2531 Fix datepicker

- README.md
a correction to a small typo in the ADR link text in the readme file
visual inspection
> corrected typo re Architecture

- README.md
@mmcnicol has submitted a typo correction
To make things better
> PP-2552 accept open source typo correction

- app/middleware/get_request_context.js
- app/models/User.class.js
- app/routes.js
- app/services/clients/base_client.js
- test/unit/middleware/get_request_context_test.js
- Added `user.features` to user model
- Added `get_request_context` middleware to act as a temporary information store accessible using `correlationId` (stores `user.features` for the duration of the request)
- Added 'features' header to base_client using the `get_request_context` store
> PP-2540 Added feature flags to base client

- app/controllers/transactions/transaction_refund_controller.js
- app/models/charge.js
- test/integration/transaction_details_refunds_ft_tests.js
with @alexbishop1
Record which user did the refund
Tested locally by creating a refund and making sure the userId is captured in the DB (refund tbl)
> PP-2399 Add refunding user‘s external ID to refund request to connector

- app/assets/sass/gov-uk-overrides/_forms.scss
- app/assets/sass/modules/_transactions_filter.scss
- app/utils/display_converter.js
- app/views/includes/phase_banner.html
- app/views/layout.html
- app/views/services/team_member_invite.html
- app/views/services/team_member_permissions.html
Applying style and context updates to the user permissions pages
> PP-2309 update permissions page

- app/assets/sass/application.scss
- app/assets/sass/gov-uk-overrides/_movement.scss
- app/assets/sass/template/header.scss
- app/assets/sass/template/template.scss
- app/views/error_logged_in.html
- app/views/forgotten_password/new_password.html
- app/views/forgotten_password/password_requested.html
- app/views/forgotten_password/username_get.html
- app/views/includes/propositional_navigation_logged_out.html
- app/views/includes/side_navigation.html
- app/views/layout.html
- app/views/layout_logged_out.html
- app/views/login/login.html
- app/views/login/otp-login.html
- app/views/login/send_otp_again.html
- app/views/self_create_service/confirm.html
- app/views/self_create_service/register.html
- app/views/self_create_service/resend_otp.html
- app/views/self_create_service/set_name.html
- app/views/self_create_service/verify_otp.html
- app/views/services/add_service.html
- app/views/services/edit_service_name.html
- app/views/user_registration/re_verify_phone.html
- app/views/user_registration/register.html
- app/views/user_registration/verify_otp.html
There were loads of inconsistencies and inefficiencies with the way the grid was marked up and styled. This clears out some unnecessary declarations in favour of the default stuff.
Also added the propositional nav to the logged out states along with the beta badge to the header
> PP-2499 sign in and new account fixes

- app/assets/sass/template/header.scss
- app/views/layout.html
- app/views/layout_logged_out.html
- lib/template-config.js
Added the link to the footer and added the banner to the top
> PP-2434 add cookie links

- app/assets/sass/modules/_transaction_detail.scss
- app/models/TransactionEvent.class.js
- app/models/charge.js
- app/services/clients/adminusers_client.js
- app/services/clients/base_client.js
- app/services/user_service.js
- app/utils/transaction_view.js
- app/views/transaction_detail/_events.html
- lib/template-engine.js
- test/fixtures/pact_interaction_builder.js
- test/fixtures/user_fixtures.js
- test/integration/transaction_details_refunds_ft_tests.js
- test/ui/transaction_details_ui_tests.js
- test/unit/clients/adminusers_client/user/get_multiple_users_test.js
- test/unit/models/charge_test.js
- Added `submitted_by_friendly` which is the `submitted_by`'s email to events that have a `state_friendly` of `refund submitted`
- Added conditional template to show this and css to get nicer wrapping for long emails
- Moved js and css paths to constants in template-engine
- Added find multiple users api to adminusers client
- Added getting users to `findChargeWithEvents`
> PP-2575 show which user issued refund

- app/assets/sass/gov-uk-overrides/_forms.scss
- app/views/login/login.html
> PP-2653 - A few little fixes

- docker/build_and_test.Dockerfile
- docker/build_and_test.sh
- test/ui/transaction_details_ui_tests.js
- remove .only erroneously committed in tests
> PP-2575 remove .only from tests

- app/assets/sass/application.scss
- app/assets/sass/helpers/_buttons.scss
- app/assets/sass/helpers/_forms.scss
- app/assets/sass/modules/_dashboard.scss
- app/assets/sass/modules/_flex_grid.scss
- app/assets/sass/template/header.scss
- app/assets/sass/template/template.scss
- app/controllers/login_controller.js
- app/views/dashboard/_first-steps.html
- app/views/dashboard/index.html
- app/views/login/login.html
- app/views/services/_service_section.html
- app/views/services/index.html
- test/integration/login_controller_test.js
- test/ui/navigation_ui_tests.js
This is the beginnings of the new dashboard page. More panels will appear once we have finished work self creation of prototype payment page flow
> PP-2629 Added interim dashboard

- app/views/transaction_detail/_events.html
- test/ui/transaction_details_ui_tests.js
- updated submitted by markup and tests to help end-to-end writing
> PP-2575 updated `submitted by` markup

- app/assets/sass/helpers/_headings.scss
- app/assets/sass/modules/_flash.scss
- app/assets/sass/template/header.scss
- app/assets/sass/template/template.scss
- app/views/layout_logged_out.html
- app/views/login/login.html
The flash banner was placed in different places for layout and logged out layout
This caused style issues. I put it in the same place and then tweaked
spacing of elements it touches to make it more straight forward and
consistent when it is hidden or showing
> PP-2804 - Fixed inconsistencies in flash banner styles and placement

- README.md
- package.json
> PP-2604 manage secrets for ecs containers

- app/assets/sass/gov-uk-overrides/_forms.scss
- app/assets/sass/modules/_multi_select.scss
- app/client-side-scripts/multi-select.js
- app/controllers/transactions/transaction_list_controller.js
- Fixed autoclosing on safari
- Added select styling on firefox
- centered select and multi-select dropdown arrows vertically
> PP 2543 multi select fixes

- .dockerignore
- Dockerfile
- build-local.sh
- docker/build_and_test.sh
- Added `npm install --production` step to Dockerfile
- Removed `npm prune` step from build dockerfile
- added `node_modules` back into dockerignore
- Speeds up local builds
> Added NPM install step to Dockerfile

- app/assets/sass/modules/_total_results.scss
- app/browsered.js
- app/browsered/multi-select.js
- app/utils/filters.js
- app/views/includes/multi-select.html
- app/views/settings_read_only.html
- app/views/transactions/filter.html
- app/views/transactions/index.html
* Edited label to make it clearer it's a multi-select
* Moved to browsered as name is clearer
* Capitalise first letter of filter states, couldnt do with CSSas didnt work in FF
* removed merchant details as view-only users dont get to see that
* only constrain dropdownn height if there isnt enough room for it
* Updated aria and accessibility labels to make it easier for screen reader users how to use the multi-select
> PP-2543 - Multi select browser bug fixes and tweaks

- app/views/includes/head.html
- server.js
This is exactly the same way it works from pay-frontend, for continuity
> PP-2264 - adding ability to set Google Analytics tracking using process.env

- Dockerfile
- chamber.sha256sum
- docker-startup.sh
- update-chamber
Remove the vendored chamber binary and provide a single 'intelligent' entry point for the container, detecting whether or not to use chamber based on whether or not we're under ECS.
> PP-2604 Remove vendored chamber & create single entry point

- Dockerfile
- docker/build_and_test.Dockerfile
some minor security fixes, should also upgrade alpine base layer.
> PP-2851 upgrade to node 6.12.0

- Dockerfile
- docker/build_and_test.Dockerfile
some minor security fixes, should also upgrade alpine base layer.
> PP-2851 re-upgrade to node 6.12.0

- app/assets/sass/modules/_dashboard.scss
- app/assets/sass/modules/_flex_grid.scss
- app/utils/display_converter.js
- app/views/dashboard/_first-steps.html
I’ve added in the two new panels that link to the
incoming prototyping features. These panels only
show when on a test gateway and there is different
panel that shows when an account is live.
I've also improved and similified the flex-grid sass
> PP-2658 - Adding new prototyping panels to dashboard

- app/views/dashboard/_first-steps.html
Missed out links to the prototyping tools
> PP-2658 - added missing links

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/make_a_demo_payment/index_controller.js
- app/controllers/test_with_your_users/submit_controller.js
- app/views/dashboard/demo-payment/edit-amount.html
- app/views/dashboard/demo-service/create.html
- test/unit/browsered/field_validation_checks_test.js
- test/unit/controller/make_a_demo_payment_controller/index_controller_test.js
- test/unit/controller/test_with_your_users_controller/submit_controller_test.js
- Added Max Amount Validator and tests
- Added as inline client-side validator via html template
- Added server-side validator to demo and prototype controllers with amount inputs
> PP-2446 Added Max Amount Validator

- .editorconfig
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles.
> PP-1797 - Added an .editorconfig to keep things consistent

- Dockerfile
- docker-startup.sh
- package.json
- Removed sleep from prod dependencies as it was not used
- Removed build toolchain from prod docker images
> PP-3004 Removed Sleep

- docker-startup.sh
Restores `docker-startup.sh` which is needed by docker compose
> PP-3004 Restore docker-startup.sh

- Dockerfile
> PP-2967 Updating Docker packages

- app/views/dashboard/demo-payment/edit-amount.njk
- app/views/dashboard/demo-payment/edit-description.njk
- app/views/dashboard/demo-payment/index.njk
- app/views/dashboard/demo-payment/mock-card-details.njk
- app/views/dashboard/demo-service/confirm.njk
- app/views/dashboard/demo-service/create.njk
- app/views/dashboard/demo-service/index.njk
- app/views/dashboard/index.njk
- app/views/error.njk
- app/views/error_logged_in.njk
- app/views/forgotten_password/new_password.njk
- app/views/forgotten_password/password_requested.njk
- app/views/forgotten_password/username_get.njk
- app/views/login/login.njk
- app/views/login/noaccess.njk
- app/views/login/otp-login.njk
- app/views/token_generate.njk
- app/views/tokens.njk
- app/views/transactions/index.njk
Nunjucks uses snake_case, mustache used camelCase somehow `pageTitle` got missed
> PP-2993 - wrong var name for page titles

- app/controllers/register_service_controller.js
- app/routes.js
emails with leading/trailing whitespace were rejected, now we trim it so they're not
Also phone numbers with spaces in were rejected too and that seems a shame, no we strip them server side
> PP-2836 - Strip whitespace from email and phone numbers

- app/controllers/invite_user_controller.js
- app/controllers/test_with_your_users/links_controller.js
- app/models/form-fields/validators/required-field-left-blank.js
- app/utils/proxy.js
- test/unit/clients/adminusers_client/invite/complete_service_invite_test.js
- test/unit/clients/adminusers_client/invite/complete_user_invite_test.js
- test/unit/clients/adminusers_client/invite/generate_invite_otp_code_service_test.js
- test/unit/clients/adminusers_client/invite/generate_invite_otp_code_user_test.js
- test/unit/clients/adminusers_client/invite/invite_user_test.js
- test/unit/clients/adminusers_client/invite/resend_otp_code_test.js
- test/unit/clients/adminusers_client/invite/submit_service_registration_test.js
- test/unit/clients/adminusers_client/invite/verify_otp_code_test.js
- test/unit/clients/adminusers_client/invite/verify_service_otp_code_test.js
- test/unit/clients/adminusers_client/service/add_gateway_accounts_to_services_test.js
- test/unit/clients/adminusers_client/service/create_service_test.js
- test/unit/clients/adminusers_client/service/update_service_name_test.js
- test/unit/clients/adminusers_client/user/create_user_test.js
- test/unit/clients/adminusers_client/user/delete_user_test.js
- test/unit/clients/connector_client/connector_client_create_gateway_account_test.js
- test/unit/services/auth_service_test.js
- Removed calls to `console.log` that have been left in committed code
> PP-3033 Remove debug console.log calls left in code

- app/assets/sass/template/header.scss
- app/views/includes/phase_banner.njk
Switched phase tag for live from blue to grey as its confusing as the beta tag above is blue
> PP-2963 - Switched phase tag for live from blue to grey

- app/controllers/make_a_demo_payment/go_to_payment_controller.js
- app/controllers/test_with_your_users/submit_controller.js
- app/models/Product.class.js
- app/services/clients/products_client.js
- test/fixtures/product_fixtures.js
- test/unit/clients/product_client/product/create_test.js
- test/unit/controller/make_a_demo_payment_controller/go_to_payment_controller_test.js
- test/unit/controller/test_with_your_users_controller/submit_controller_test.js
- Added service names to requests to create a product
NOTE:
The api doesn't use this yet, `pay-products` will be updated to use this in due course
> PP-3035 service name in product creation requests

- Dockerfile
> PP-2967 Added a comment to Dockerfile

- app/views/dashboard/demo-service/index.njk
- Use currency filter for product list in lieu of erroneously deleted dynamic property on product class
> PP-3035 Fix product list

- app/views/services/_service_section.njk
Sonia noticed a visual regression that was accidentally introduced. This fixes it
> This somehow got forgotten in a change when the dashboard when live

- app/models/Payment.class.js
- app/services/clients/products_client.js
- test/fixtures/product_fixtures.js
- test/unit/clients/product_client/payment/create_test.js
- test/unit/clients/product_client/payment/get_by_payment_external_id_test.js
- test/unit/clients/product_client/payment/get_by_product_external_id_test.js
- test/unit/clients/product_client/product/update_service_name_by_gateway_account_id_test.js
- test/unit/clients/product_client/product/update_service_name_test.js
- added update service name to products client
- added synchronised code with products client in self-service
> PP-3048_add_update_service_name_to_products_client

- app/views/dashboard/demo-service/index.njk
Removing message about migration now the migration has happened
> PP-3157 - removed message about migration

- app/services/service_service.js
- test/unit/clients/product_client/product/update_service_name_by_gateway_account_id_test.js
Updated service service to also update the service name in pay-products
> PP-3048 - Added product service name update to edit service name in service_service.

- app/services/clients/connector_client.js
- app/services/transaction_service.js
- test/integration/transaction_download_ft_tests.js
- test/integration/transaction_list_ft_tests.js
- test/integration/transaction_search_ft_tests.js
- test/unit/services/transaction_service_test.js
Reverts alphagov/pay-selfservice#627
This broke e2e tests, reverting to keep master clean while I work on a fix
> Revert "PP-3193 Fix transaction download bug"

- app/views/dashboard/_activity.njk
- app/views/dashboard/_first-steps.njk
- app/views/includes/footer-categories.njk
Adding attributes to trigger track clicks on dashboard links so we can see what is being used (or not)
> PP-3129 - Adding more click events

- app/services/clients/products_client.js
- config/index.js
- test/fixtures/product_fixtures.js
- test/test.env
- test/unit/clients/product_client/payment/create_test.js
- test/unit/clients/product_client/payment/get_by_payment_external_id_test.js
- test/unit/clients/product_client/payment/get_by_product_external_id_test.js
- test/unit/clients/product_client/product/create_test.js
- test/unit/clients/product_client/product/disable_test.js
- test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
- test/unit/clients/product_client/product/get_by_product_external_id_test.js
- test/unit/clients/product_client/product/update_service_name_by_gateway_account_id_test.js
- remove PRODUCTS_API_TOKEN and its usage as it is no longer in use.
> PP-3204 remove PRODUCTS_API_TOKEN

- app/controllers/email_notifications_controller.js
- app/views/email_notifications/edit.njk
- Gov URLs are not necessarily from 'gov.uk' domain, so removed and refined copy text on edit custom paragraph.
- Add logging to keep records of users updating the custom paragraph.
> PP-3269 Change email notifications edit custom parapraph copy

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/credentials_controller.js
- app/views/includes/flash.njk
- app/views/layout.njk
- app/views/provider_credentials/smartpay.njk
- test/integration/credentials_ft_tests.js
- test/unit/browsered/field_validation_checks_test.js
The update notification credentials
- will now error gracefully if no username submitted
- will now error gracefully if no password submitted
- will now error gracefully if password is < 10 chars
> PP-3136 - validate on notification credentials update

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/make_a_demo_payment/index_controller.js
- app/controllers/test_with_your_users/submit_controller.js
- test/unit/browsered/field_validation_checks_test.js
- fix amount validation (error when amount is above £100.000)
- refactor method name from isBelowMaxAmount to isAboveMaxAmount to make more sense
- refactor error msg name to make more sense
- refactor test accordingly
> PP-3305 Fix amount validation for adhoc payments

- app/controllers/make_a_demo_payment/go_to_payment_controller.js
- app/controllers/test_with_your_users/disable_controller.js
- app/controllers/test_with_your_users/links_controller.js
- app/controllers/test_with_your_users/submit_controller.js
- add error logging in catch clause to identify what went wrong in make_a_demo_payment and test_with_your_users controllers.
> PP-3251 Add error logging to products controllers

- app/utils/registration_validations.js
- app/utils/service_name_validation.js
- Trim the received value before validating isEmpty
> PP-3295 Service name validation

- app/views/email_notifications/edit.njk
Make amendments to the text as per the jira ticket
Enhancement to the ticket, capitalising HTTPS and URL
solo
> PP-2295 Wrong spellings on 'Add a custom paragraph' to email page

- app/services/clients/connector_client.js
- app/utils/transaction_view.js
- app/views/transactions/index.njk
- test/integration/transaction_download_ft_tests.js
- test/integration/transaction_list_ft_tests.js
- test/ui/transaction_list_ui_tests.js
- test/ui/transaction_search_ui_tests.js
Limiting CSV download to 10,000 records. (made it based on ENV variable, but defaults to 10000 for now)
Also making 500 records downloads 
with @georgeracu
> PP-3355 Add limit to CSV download

- app/assets/sass/application.scss
- app/assets/sass/modules/_check-your-answers.scss
- app/assets/sass/modules/_create-payment-link.scss
- app/assets/sass/modules/_flash.scss
- app/controllers/payment-links/index-controller.js
- app/controllers/payment-links/index.js
- app/controllers/payment-links/information-controller.js
- app/controllers/payment-links/information-submit-controller.js
- app/controllers/payment-links/review-controller.js
- app/paths.js
- app/routes.js
- app/views/includes/flash.njk
- app/views/layout.njk
- app/views/payment-links/index.njk
- app/views/payment-links/information.njk
- app/views/payment-links/review.njk
- test/unit/controller/payment-links/information-controller.test.js
- test/unit/controller/payment-links/review-controller.test.js
Adding flow of creating a payment link, it stores it in the session.
> PP-3343 create payment link journey

- app/services/clients/connector_client.js
- app/utils/transaction_view.js
- test/integration/transaction_download_ft_tests.js
To verify if there is any relationship on the CPU spikes.
> PP-3355 Reverting default page sizing (to 100)

- npm-shrinkwrap.json
> BAU Add npm-shrinkwrap.json

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/register_service_controller.js
- app/utils/registration_validations.js
- app/views/self_create_service/set_name.njk
- test/unit/browsered/field_validation_checks_test.js
- test/unit/utils/registration_validations_test.js
-  Add service name validation in self creation of account.
> PP-3295 Add missing client side validation

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/register_service_controller.js
- app/utils/registration_validations.js
- app/views/self_create_service/set_name.njk
- test/unit/browsered/field_validation_checks_test.js
- test/unit/utils/registration_validations_test.js
- This reverts commit 854deb288a7d89d7cd5a5742a0e804193e01b111.
- _Accepttests_ doesn't like it since it is running phantomjs
> PP-3295 Revert Add missing client side validation

- app/services/auth_service.js
Better logging in auth_service:
- for failed deserialization
- for redirection to login
- for mismatched session version
> BAU add better logging in authservice

- app/browsered/multi-select.js
- Fixed setting id on multiselect elements
> PP-3382 Delete REFUNDS_IN_TX_LIST

- app/assets/sass/helpers/_admin_list.scss
- app/assets/sass/helpers/_headings.scss
- app/assets/sass/helpers/_text_treatment.scss
- app/assets/sass/modules/_flash.scss
- app/assets/sass/modules/_related_information.scss
- app/views/services/team_member_details.njk
- app/views/services/team_members.njk
- test/ui/team_member_details_ui_tests.js
A bunch of tweaks to layout and spacing to make things neater
> PP-3329 user management improvements

- app/views/services/team_member_invite.njk
Somehow the flash banner got removed this adds it back in
> PP-3329 - removed flash banner by accident

- app/views/includes/multi-select.njk
- Made ids unique per multi select container (currently there are 2 containers with same id)
- Added css classes on multi select labels for enhanced testing (per @juanjoqmelian advice)
> PP-3382 Make ids unique in the multi select

- app/views/payment-links/manage.njk
> PP-3345 Added CSS class for endtoend

- app/assets/sass/modules/_transaction_refund.scss
- app/browsered.js
- app/controllers/payment-links/get-amount-controller.js
- app/controllers/payment-links/index.js
- app/controllers/payment-links/post-amount-controller.js
- app/controllers/payment-links/post-information-controller.js
- app/paths.js
- app/routes.js
- app/views/payment-links/amount.njk
- app/views/payment-links/information.njk
- app/views/payment-links/review.njk
- test/unit/controller/payment-links/get-amount-controller.test.js
- test/unit/controller/payment-links/get-information-controller.test.js
- test/unit/controller/payment-links/post-amount-controller.test.js
- test/unit/controller/payment-links/post-information-controller.test.js
Before this PR user could only have a variable amount payment link. Now there is a new screen in the flow where a user can opt for a fixed amount, this amount is validated and passed through.
Also wrote unit tests for it.
> PP-3421 set fixed amount

- app/browsered/target-to-show.js
This has happened before and I had forgotten that we have to this.
> PP-3421 - this fixes a JS error that was breaking tests for e2e

- app/assets/sass/gov-uk-overrides/_forms.scss
- app/assets/sass/modules/_create-payment-link.scss
- app/browsered/field-validation-checks.js
- app/controllers/make_a_demo_payment/index_controller.js
- app/controllers/payment-links/post-amount-controller.js
- app/controllers/test_with_your_users/submit_controller.js
- app/views/payment-links/amount.njk
- app/views/payment-links/index.njk
- app/views/payment-links/information.njk
- app/views/payment-links/manage.njk
- app/views/payment-links/review.njk
Mark and Sonia made some updates to the Create a payment link flow this is the updates
> PP-3426 update content

- app/controllers/payment-links/post-review-controller.js
- test/unit/controller/payment-links/post-review-controller.test.js
Forgot to actually pass the amount over to products UI
> PP-3421 - added amount to the products payload

- app/utils/transaction_view.js
- test/integration/transaction_details_ft_tests.js
using the feature flag and displaying the new/old state depending on it.
> PP-3377 Fixed display state in transaction details page

- app/controllers/make_a_demo_payment/index_controller.js
- app/controllers/payment-links/post-amount-controller.js
- app/controllers/payment-links/post-review-controller.js
- app/controllers/test_with_your_users/submit_controller.js
- app/utils/currency_formatter.js
- test/unit/controller/payment-links/post-review-controller.test.js
- test/unit/utils/currency_formatter.test.js
Silvia pointed out in #693 that currency manipulation was hard to understand and could be made into a reusable function so I have.
> PP-3421 - making formatting currencies less confusing

- app/views/3d_secure/index.njk
- Added CSS ids for enhancing e2e tests
- Tests using these ids will follow in e2e
> PP-3449 Enable 3DS for EPDQ

- app/views/3d_secure/index.njk
- app/views/dashboard/_first-steps.njk
- app/views/dashboard/demo-payment/mock-card-details.njk
- app/views/dashboard/demo-service/index.njk
- app/views/includes/footer-categories.njk
- app/views/includes/propositional_navigation.njk
- app/views/includes/propositional_navigation_logged_out.njk
- app/views/provider_credentials/sandbox.njk
Update all references to new url
solo @belindac
> PP-3379 Change documentation link in header and footer

- app/views/dashboard/_activity.njk
Net income links to transactions filtered by payments and refunds
> PP-3320 - Added link from dashboard for Net income

- app/paths.js
- app/routes.js
To fix broken accept tests
https://github.com/alphagov/pay-accepttests/pull/204
> PP-3432 - temporarily reinstate old paths so we have both routes

- app/assets/sass/modules/_create-payment-link.scss
- app/views/payment-links/index.njk
- app/views/payment-links/information.njk
- hiding content about links until we know what the url will be
- fixing spacing in example list
> PP-3426 - content updates

- app/views/provider_credentials/sandbox.njk
Couldnt rebase https://github.com/alphagov/pay-selfservice/pull/713 so making another PR.
Thanks to @quis for spotting
> Updating link to match docs thanks @quis

- app/utils/response.js
At the moment in the error page in test environment we show: 
```
[object Object]
```
Something not meaningful at all, so trying to show the actual message with this fix.
> PP-3500 Show error message properly

- Jenkinsfile
- Use separate e2e jobs for card, dd and products 
- Dont run zap
> PP-3436 Update Jenkinsfile

- app/views/tokens.njk
Include ids on tabs in api keys page for testability reasons.
> PP-3548 Include ids on tabs in api keys page for testability reasons.

- Jenkinsfile
- app/views/3d_secure/index.njk
Remove unused parameters from deployEcs now they have been split out into separate steps
Amended documentation link to new url
solo @belindac
> PP-3381 and PP-3379 Remove unused params, update documentation urls

- app/middleware/get_gateway_account.js
- test/unit/middleware/get_gateway_account_test.js
- Enable 3DS for SmartPay
- Based on a feature flag (env variable) we decide to enable/disable 3DS for SmartPay
> PP-3525 Enable 3DS for SmartPay with feature flag

- app/views/services/team_member_details.njk
- app/views/services/team_members.njk
Add members id for testability
> PP-3557 Add members id for testability

- app/views/payment-links/review.njk
Adding a virtual pageview when link is created so we can count links created
> PP-3394 - virtual pageview on link creation

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/views/payment-links/information.njk
Right now NAXSI rejects a bunch of characters in titles, it displays a nasty error this introduces nice client side errors.
> PP-3446 - add more validations to payment link title

- app/services/clients/direct_debit_connector_client.js
We need to check if we are not passing `null` gateway account in case there is no service assigned
> PP-3521 Fix login when there is not services assigned

- app/utils/display_converter.js
- app/utils/navBuilder.js
- test/ui/navigation_ui_tests.js
Some settings aren’t relevant to Direct debit this hides them.
> PP-3644 - hide settings from DD that arent relevant

- Jenkinsfile
> [REVIEW-ONLY] Pp 3615 run pact tests on pr

- docker/build_and_test.sh
- See: https://explainshell.com/explain?cmd=set+-ueo+pipefail
> PP-3615 Make build and test script fail when any command fails

- app/views/dashboard/_activity.njk
- app/views/dashboard/_first-steps.njk
This makes payment links navigateable from the dashboard.
I also recently found out routes is avaiable to the view so I can
properly add links using a less fragile way :D
> PP-3658 - Added 'payment link' link to dashboard

- Jenkinsfile
> PP-3616: Always delete contract test workspace

- Jenkinsfile
> bau: Use updated method name

- Jenkinsfile
Tag consumer as 'test' on deploy after a smoke test run
> PP-3621 Tag the consumer pact as 'test' on deploy

- test/integration/transaction_details_ft_tests.js
- test/integration/transaction_list_ft_tests.js
- Removed unused features from tests. They came up at story review
> PP-3574 Remove new states feature flag

- Jenkinsfile
See https://github.com/alphagov/pay-jenkins-library/pull/69/commits/50ac339ea3f832db53d7c0003f793c75c9c1add1
@oswaldquek
> PP-3707: Tagging script has been renamed

- package.json
Upgrades node.js engine version to 8.11.1 in package.json
> PP-3703 Version bumped Node.js engine in package.json

- app/views/payment-links/manage.njk
> BAU - noticed that these should have labels for screen readers 

- Jenkinsfile
We are no longer using accept tests
solo @belindac
> PP-3775 Remove references to accept tests

- app/controllers/dashboard/dashboard-activity-controller.js
- app/controllers/dashboard/dashboard-activity-controller.test.js
Moves period/custom date logic out of controller logic, tidies up a few things and adds unit tests to support it's operation.
The existing in-line date logic was starting to confuse the legibility the main controller function export, so this has been migrated to it's own private function, tided up to use switch statements and I've shaved things down a touch to hopefully make it a little neater and easier to interpret.
I did consider migrating this to it's own code file but felt the code was small and custom enough in nature to be kept in the controller. Happy to change this if there are conflicting opinions.
The date range logic could have been tested in isolation outside of the main controller but exposing it as a module exports, but this would have broken consistency with other …
> PP-3764 Moved date logic out of main dashboard controller logic. Added unit tests to support its operation

- app/controllers/edit_merchant_details/get.js
- app/controllers/edit_merchant_details/post.js
- app/middleware/resolve_service.js
- app/views/merchant_details/edit_merchant_details.njk
- test/unit/controller/edit_merchant_details_controller/get_test.js
- test/unit/middleware/resolve_service_test.js
- Added specific info text for merchant details based on gateway account
type
- Removed hint text specific to Direct Debit
- Fixed tests
> PP-3604 Display merchant details info based on gateway account

- app/routes.js
- app/views/includes/propositional_navigation.njk
- app/views/merchant_details/edit_merchant_details.njk
- app/views/services/add_service.njk
- app/views/services/edit_service_name.njk
- app/views/services/index.njk
- app/views/services/team_members.njk
- test/integration/validate_invite_controller_ft_tests.js
- test/ui/service_switcher_ui_tests.js
In the nav we're going to call in Switch service, which is what Notify
call it too
On the page itself, we’re removing the title My services and using the
sub-headline as the headline.
> PP-3826 - Renaming all instances of My services

- app/views/error.njk
> BAU - wrap in column so doesnt break grid

- app/services/clients/adminusers_client.js
- app/services/user_service.js
- app/views/twoFactorAuth/configure.njk
- app/views/twoFactorAuth/index.njk
- test/unit/controller/two-factor-auth-controller/get_index_controller.test.js
In my defense you can’t test the SMS message sending locally
- Using POST for resending texts which means it _actually_ works
- It wasn’t passing `provisional: true` in the body which meant it was texting people the wrong code
- @alexbishop1 got all picky about the wording which is going to get reviewed later on anyway, but he’s right so I tried to make it better. But it’s still not really as good as it will be I imagine but y'know _deliver value often_ and all that
> PP-3761 - Alex spotted some pretty embarrassing bugs with 2FA 

- bin/publish-pacts.js
No harm in having them all published. We can control
which tests get run using naming conventions (e.g.
selfservice-to-be)
> PP-3813 Publish all pacts

- test/unit/clients/connector_client/connector_get_gateway_account_test.js
- test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js
Fix some typos in provider states and pact definitions.
> PP-3813 Ensure correct type on gateway account id in pact file

- app/assets/sass/application.scss
- app/assets/sass/modules/_feedback-banner.scss
- app/controllers/feedback/get-index-controller.js
- app/controllers/feedback/index.js
- app/controllers/feedback/post-index-controller.js
- app/paths.js
- app/routes.js
- app/utils/display_converter.js
- app/views/feedback/index.njk
- app/views/includes/feedback-banner.njk
- app/views/layout.njk
- app/views/layout_logged_out.njk
- config/zendesk.js
- package-lock.json
- package.json
- test/unit/controller/feedback/get-index-controller.test.js
- test/unit/controller/feedback/post-index-controller.test.js
This makes it easier for our users to feedback on their experiences with GOV.UK Pay
Feedback is submitted straight to Zendesk
- it is marked as a question to the GOV.UK Pay group within the GDS organisation
- it is assigned to @soniaturcotte (she may regret this)
- The users current service name, ID and gateway account are prepended to the message so we can better help them with their query
> PP-2684 add feedback form

- app/controllers/two-factor-auth-controller/post-configure-controller.js
- app/views/includes/propositional_navigation.njk
- app/views/services/team_member_profile.njk
- app/views/twoFactorAuth/configure.njk
- app/views/twoFactorAuth/index.njk
- Small copy updates from Mark
- Tidying up the user profile table
- Added My profile to the header for easy access
> PP-3924 - copy updates and My profile is now in Header Nav

- app/views/includes/propositional_navigation.njk
Eagle eye @soniaturcotte lookin’ over my shoulder. 
In my defence I got it right in the `title` attribute.
> BAU - dont use title case

- app/views/3d_secure/index.njk
- app/views/3d_secure/on_confirm.njk
- Using correct notifcation 
- Wrapped in column so it doesn’t bleed into nav
> PP-3734 - fixing styling issues

- app/controllers/feedback/post-index-controller.js
- app/views/layout.njk
Zendesk request was stuck inside the box this sends it throught the
proxy, will still work locally where we don't need the proxy
@jonheslop with A LOT of help from @tlwr
> PP-2684 zendesk integration proxy fix

- app/views/transaction_detail/index.njk
per GOV.UK style guide
with @soniaturcotte @belindac
> Remove capitalisation

- package.json
- test/cypress/integration/user/login_spec.js
- test/cypress/integration/user/transaction_details_spec.js
- test/fixtures/config/self_service_user.json
- test/fixtures/pact_base.js
- test/fixtures/user_fixtures.js
- test/unit/clients/adminusers_client/authenticate/authenticate_test.js
- test/unit/clients/adminusers_client/user/get_user_test.js
Adds contract test assertions, unit tests, fixtures and Cypress.io browser/application tests to test password success/failure interactions.
> PP-3984 Replace shouldDenyAccessToSelfServiceIfCredentialsAreIncorrect e2e test with browser/contract implementation

- app/controllers/create_service_controller.js
- app/services/clients/adminusers_client.js
- app/services/service_service.js
- test/fixtures/service_fixtures.js
- test/unit/clients/adminusers_client/service/update_service_name_test.js
If checkbox not included then set welsh name to blank, then pass the blank string onto adminusers (also fix some linting errors).
> PP-4096 - if checkbox not included then set welsh name to blank

- app/views/includes/propositional_navigation.njk
- app/views/merchant_details/edit_merchant_details.njk
- app/views/merchant_details/merchant_details.njk
- app/views/services/team_members.njk
- test/integration/validate_invite_controller_ft_tests.js
- test/ui/service_switcher_ui_tests.js
Renames 'Switch service' to 'My services' and updates associated back links and unit tests.
> PP-4150 rename switch service to my services and rename associated links

- app/assets/sass/application-new.scss
- app/assets/sass/components/service-switch.scss
- app/browsered/autocomplete.js
- app/controllers/my-services/get-index-controller.js
- app/views/services/_service_switch.njk
Tweaks to My service page to improve the accessible autocomplete and also style live services as they were pre migration
> PP-4193 my services fixes

- app/utils/transaction_view.js
- app/views/transaction_detail/_payment.njk
- test/integration/transaction_details_ft_tests.js
- test/ui/transaction_details_ui_tests.js
- If not present, we will display `**** **` as it was before
> PP-4142 Show first 6 digits of card number in transaction detail if present

- app/views/transaction_detail/_refund.njk
- test/cypress/integration/user/transaction_details_spec.js
Include corporate card surcharge fee in full amount for refunds
- Use `net_amount_display` property which includes corporate card surcharge fee.
- Change `net_amount` property with `net_amount_display` for consistency.
> PP-4131 Include corporate card surcharge fee in full amount for refunds

- app/assets/sass/application-new.scss
- app/assets/sass/components/currency-input.scss
- app/assets/sass/components/flash.scss
- app/controllers/make_a_demo_payment/edit_controller.js
- app/controllers/make_a_demo_payment/index_controller.js
- app/controllers/make_a_demo_payment/mock_card_details_controller.js
- app/views/dashboard/demo-payment/edit-amount.njk
- app/views/dashboard/demo-payment/edit-description.njk
- app/views/dashboard/demo-payment/index.njk
- app/views/dashboard/demo-payment/mock-card-details.njk
- test/unit/controller/make_a_demo_payment_controller/edit_controller_test.js
- test/unit/controller/make_a_demo_payment_controller/mock_card_details_controller_test.js
Also removed cases where paths were passed to the templates as they are
available globally.
> PP-4323 - Migrating demo payment pages to use GOV.UK Frontend

- app/controllers/test_with_your_users/create_controller.js
- app/controllers/test_with_your_users/index_controller.js
- app/controllers/test_with_your_users/submit_controller.js
- app/views/dashboard/demo-service/confirm.njk
- app/views/dashboard/demo-service/create.njk
- app/views/dashboard/demo-service/index.njk
- test/unit/controller/test_with_your_users_controller/create_controller_test.js
- test/unit/controller/test_with_your_users_controller/submit_controller_test.js
Thanks for the description, @jonheslop
> PP-4327 - transistion test with your users templates over to GOV.UK Frontend

- app/views/3d_secure/index.njk
- app/views/3d_secure/on_confirm.njk
- test/ui/toggle_3ds_ui_tests.js
- test/unit/controller/toggle_3ds_controller/toggle_3ds_controller_test.js
> PP-4332 - Migrating to GOV.UK Frontend

- app/views/email_notifications/collection_email_mode.njk
- app/views/email_notifications/confirmation_email_toggle.njk
- app/views/email_notifications/off_confirm.njk
- app/views/email_notifications/refund_email_toggle.njk
- test/cypress/integration/user/email_notifications_spec.js
migrating email settings templates to GOV.UK Frontend
> PP-4334 - migrating email settings templates to GOV.UK Frontend

- app/assets/sass/components/transaction-filter.scss
> PP-4336 - set font to New Transport 🙈

- app/assets/sass/components/colour.scss
- app/assets/sass/components/navigation.scss
- app/browsered/input-confirm.js
- app/controllers/payment-links/get-start-controller.js
- app/controllers/payment-links/get-web-address-controller.js
- app/controllers/payment-links/post-information-controller.js
- app/controllers/payment-links/post-web-address-controller.js
- app/views/includes/side_navigation.njk
- app/views/payment-links/_nav.njk
- app/views/payment-links/index.njk
- app/views/payment-links/information.njk
- app/views/payment-links/web-address.njk
- test/unit/controller/payment-links/get_information_controller.test.js
- test/unit/controller/payment-links/post_information_controller.test.js
The first three screens of payment links
> PP-4335 – migrate payment links to govuk frontend: Part 1 – A long road ahead

- app/assets/sass/components/transaction-filter.scss
- app/views/transactions/filter.njk
Used incorrect classname and also decided it’s safer to wrap the
fieldset than add grid class directly to it
> PP-4357 - fix layout bug in ie11

- app/assets/sass/application-new.scss
- app/assets/sass/components/check-your-answers.scss
- app/controllers/payment-links/post-amount-controller.js
- app/controllers/payment-links/post-reference-controller.js
- app/controllers/payment-links/post-review-controller.js
- app/views/payment-links/amount.njk
- app/views/payment-links/reference.njk
- app/views/payment-links/review.njk
- test/unit/controller/payment-links/get_amount_controller.test.js
- test/unit/controller/payment-links/get_reference_controller.test.js
- test/unit/controller/payment-links/post_amount_controller.test.js
- test/unit/controller/payment-links/post_review_controller.test.js
- migrate reference template to GOV.UK Frontend
- migrate amount template to GOV.UK Frontend
- migrate review template to GOV.UK Frontend
> PP-4335 — migrate payment links to GOV.UK Frontend: Part II - An amble through the valley

- app/assets/sass/application-new.scss
- app/assets/sass/components/borders.scss
- app/controllers/payment-links/get-edit-controller.js
- app/controllers/payment-links/get-edit-information-controller.js
- app/controllers/payment-links/get-manage-controller.js
- app/views/payment-links/edit-amount.njk
- app/views/payment-links/edit-information.njk
- app/views/payment-links/edit.njk
- app/views/payment-links/manage.njk
- test/unit/controller/payment-links/get-edit-controller.test.js
- test/unit/controller/payment-links/get-edit-information-controller.test.js
- test/unit/controller/payment-links/get_manage_controller.test.js
- Migrate manage links template to GOV.UK Frontend
- Migrate edit payment link templates to GOV.UK Frontend
> PP-4335 — migrate payment links to govuk frontend: Part III — The last battle

- app/views/404.njk
- app/views/error.njk
Missed the 404 and error page 🙄
> PP-4359 migrate misc templates to govuk frontend 2

- app/views/self_create_service/confirm.njk
- app/views/self_create_service/register.njk
- app/views/self_create_service/resend_otp.njk
- app/views/self_create_service/set_name.njk
- app/views/self_create_service/verify_otp.njk
- app/views/user_registration/re_verify_phone.njk
- app/views/user_registration/register.njk
- app/views/user_registration/verify_otp.njk
- test/ui/self_create_service_ui_tests.js
The last of the templates coverted to GOV.UK Frontend
> PP-4360 sign up flow to GOV.UK Frontend

- app/views/includes/head.njk
> BAU - we should have a meta description

- Gruntfile.js
- package.json
No more stop/starting anything for any reason ⚡️
> PP-4401 - livereload for clientside JS

- README.md
> BAU - explain about Nodemon and Livereload

- app/views/includes/head.njk
> BAU - we should have a meta description and it should use the correct syntax

- app/services/clients/adminusers_client.js
- test/fixtures/config/self_service_user.json
- test/fixtures/service_fixtures.js
- test/unit/clients/adminusers_client/service/update_collect_billing_address_test.js
- Added method to the adminusers client to send patch request to update
the collect_billing_address option
- Added pact test for patch request
> PP-4159 Add ability to update collect billing address for service

- README.md
The _Running locally with `pay local`_ section refers to the Pay CLI
> Add note to README.md that the Pay CLI is not publicly-available

- app/views/includes/phase_banner.njk
“Sandbox test” is weird so going to call it “Test account”
> PP-4351 - change label from sandbox to test

- app/views/transaction_detail/index.njk
We were including a JS file we have deleted and this caused JS to stall
> PP-4481 - Fixing partial refund

- app/assets/sass/components/cookie-message.scss
- app/views/credentials/worldpay.njk
- test/ui/credentials_ui_tests.js
Worldpay call this Merchant code, we had users get confused by the fact we mislabeled it.
> PP-4173 merchant id rename

- app/middleware/resolve_service.js
- test/integration/service_users_ft_test.js
- test/unit/middleware/resolve_service_test.js
- 6e30374 & 42c7028 - First did a bit of tidying up as the middleware/tests weren’t up to scratch with our Node.JS best practices
- c082763 - I found this function confusing so simplified it a bit, could have gone further but didnt (see commit message)
- 6b5dfae - The meat of the ticket this is what I was actually here to do
> PP-4472 - add more tests around resolving service

- app/views/billing-address/confirm-off.njk
- app/views/billing-address/index.njk
- test/ui/toggle_collect_billing_address_ui_test.js
- test/unit/controller/billing-address-controller/toggle-billing-address-controller.test.js
Decided this copy needed to be a little clearer about potential problems with turning off billing address
> PP-4527 - update copy

- app/assets/js/components/datetime-picker.js
- app/assets/js/components/link-follower.js
- app/browsered/multi-select.js
- app/controllers/payment-links/get-manage-controller.js
- app/controllers/payment-links/post-amount-controller.js
- server.js
A number of lint warning were recently flagged against the `selfservice`
repository. This PR removes these issues, specifically high priority
concerns with checking equality (running boolean logic checks against
JavaScript strings always resulting in `true`)
Closes https://github.com/alphagov/pay-selfservice/pull/1040
> PP-4564: Address priority repo lint issues

- app/views/request-to-go-live/index.njk
- test/cypress/integration/user/request_to_go_live_index_spec.js
- Modified the "Request to go live" page content and updated tests
with @cobainc0
> PP-4449 New design changes

- test/unit/middleware/get_gateway_account_test.js
Parameterise tests (related to field disableToggle3ds)
> PP-4570 Parameterise tests - disableToggle3ds flag

- app/controllers/request-to-go-live/organisation-name/get.controller.js
- app/controllers/request-to-go-live/organisation-name/post.controller.js
- app/utils/response.js
- app/views/request-to-go-live/organisation-name.njk
- test/cypress/integration/request-to-go-live/organisation_name_spec.js
- test/fixtures/config/self_service_user.json
This PR implements pre-population of the organisation name and validation.
See commits for more information.
with @cobainc0
> PP-4451 Request to go live: "Organisation Name" page - display and validation logic

- README.md
Add steps to run locally to the README as I found this unintuitive as a new starter
Following steps in README should be able to run app
> Add steps to run selfservice locally

- app/controllers/request-to-go-live/choose-how-to-process-payments/get.controller.js
- app/controllers/request-to-go-live/choose-how-to-process-payments/index.js
- app/controllers/request-to-go-live/choose-how-to-process-payments/post.controller.js
- app/routes.js
- app/utils/choose_how_to_process_payments_validation.js
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
- implement page
- implement error checking
- add cypress tests
> PP-4452 Add choose how to process payment page

- app/views/self_create_service/register.njk
- app/views/self_create_service/resend_otp.njk
- app/views/user_registration/re_verify_phone.njk
- app/views/user_registration/register.njk
- package-lock.json
- test/ui/self_create_service_ui_tests.js
Use `tel` type for phone input fields. This is so the user agent can know how to handle this field. This is as per design system https://design-system.service.gov.uk/patterns/telephone-numbers/
go to: http://localhost:9400/create-service/register
input type on phone field should be `tel`
e.g. on iOS special input type should be displayed
> use tel type for telephone fields

- app/controllers/request-to-go-live/choose-how-to-process-payments/post.controller.js
- app/services/clients/adminusers_client.js
- app/services/service_service.js
- app/utils/choose_how_to_process_payments_validation.js
- test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/service_fixtures.js
- test/fixtures/user_fixtures.js
- test/fixtures/user_service_fixture.js
- test/integration/service_users_ft_test.js
- test/unit/clients/adminusers_client/service/get_service_users_test.js
- test/unit/services/service_service_test.js
- implement the patch logic
- implement new way of Cypress testing
- added user_service_fixture to avoid circular dependency
- add/refactor relevant tests
> PP-4452 Implement patch current go live stage

- app/controllers/request-to-go-live/organisation-name/post.controller.js
- app/services/clients/adminusers_client.js
- app/services/service_service.js
- test/cypress/integration/request-to-go-live/organisation_name_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/request_to_go_live_utils.js
- add PATCH request to allow selfservice to update merchant name in adminusers
- updates cypress tests to incorporate new behaviour
- minor refactoring
solo: @cobainc0
> PP-4451 Implements logic for updating Organisation name

- test/cypress/plugins/stubs.js
- test/cypress/utils/request_to_go_live_utils.js
- test/fixtures/service_fixtures.js
- test/unit/clients/adminusers_client/service/update_request_to_go_live_stage_test.js
> PP-4453 Add patch request to go live stage pact test

- app/services/clients/adminusers_client.js
- app/services/service_service.js
- test/unit/clients/adminusers_client/service/stripe_agreement_post_ip_address_test.js
> PP-4453 Add post Stripe agreement ip address pact test

- app/services/clients/adminusers_client.js
- app/services/service_service.js
- test/unit/clients/adminusers_client/service/govuk_pay_agreement_post_email_address_test.js
- add pact test
- refactor stripe_agreement_post_ip_address_test to confirm with 2019 coding style
> PP-4453 Add post GovUk agreement pact test

- app/controllers/request-to-go-live/agreement/post.controller.js
- test/cypress/integration/request-to-go-live/agreement_spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/go_live_requests_fixture.js
- test/unit/clients/adminusers_client/service/govuk_pay_agreement_post_email_address_test.js
- test/unit/clients/adminusers_client/service/stripe_agreement_post_ip_address_test.js
- implement posting the agreeing user's external id to adminusers
- update nunjuck test
> PP-4453 Implement post govuk pay agreement

- app/controllers/request-to-go-live/agreement/post.controller.js
- test/cypress/integration/request-to-go-live/agreement_spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/go_live_requests_fixture.js
- test/unit/clients/adminusers_client/service/stripe_agreement_post_ip_address_test.js
- implement posting the agreeing user's ip address to adminusers
- update nunjuck test
> PP-4453 Implement post stripe agreement

- app/controllers/feedback/post-index-controller.js
- app/services/clients/zendesk_client.js
- Refactor existing feedback post controller to use zendesk_client
> PP-4453 Refactor existing feedback post controller

- app/controllers/register_service_controller.js
- app/utils/registration_validations.js
- app/views/self_create_service/register.njk
- app/views/self_create_service/resend_otp.njk
- app/views/user_registration/re_verify_phone.njk
- app/views/user_registration/register.njk
- package-lock.json
- package.json
- test/integration/register_user_controller_ft_tests.js
- test/integration/validate_invite_controller_ft_tests.js
- test/ui/register_user_ui_tests.js
- test/ui/self_create_service_ui_tests.js
- test/unit/utils/registration_validations_test.js
This PR adds support for any valid format for telephone numbers.
It uses `google-libphonenumber` package to validate the telephone numbers (same for pay-adminusers).
please see commits for more information
> PP-4759 Improve international phone number support

- app/controllers/request-to-go-live/index/get.controller.js
- app/views/policy/document-downloads/contract_for_non_crown_bodies.njk
- app/views/policy/document-downloads/memorandum_of_understanding_for_crown_bodies.njk
- app/views/request-to-go-live/agreement.njk
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- app/views/request-to-go-live/index.njk
- app/views/request-to-go-live/organisation-name.njk
- test/cypress/integration/request-to-go-live/agreement_spec.js
- test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
- test/cypress/integration/request-to-go-live/index_spec.js
- test/cypress/integration/request-to-go-live/organisation_name_spec.js
- If the user has completed all the necessary steps when they visit the request to go live task list, show some copy about what we will ask them to do next rather than the completed steps
- Miscellaneous copy changes for request to go live pages
> PP-4861 Request to go live copy/design changes

- app/views/stripe-setup/responsible-person/index.njk
Nunjucks template for the main nominate a responsible person form. Not hooked up to anything yet.
with: @alexbishop1
> PP-4463 Adds Template for Responsible person

- app/views/stripe-setup/responsible-person/check-your-answers.njk
Adds Template for Responsible - check your answers
with: @alexbishop1
> PP-4463 Adds Template for Responsible Person - check your answers page

- app/controllers/stripe-setup/responsible-person/get.controller.js
- app/controllers/stripe-setup/responsible-person/index.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/views/stripe-setup/responsible-person/index.njk
Adds controllers for responsible person page without validation or path & route logic
with: @alexbishop1
> PP-4463 Adds controller logic for Responsible person page

- app/views/stripe-setup/responsible-person/index.njk
> PP-4463 Update nominate a responsible person page copy

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/controllers/stripe-setup/responsible-person/responsible-person-validations.js
- app/controllers/stripe-setup/responsible-person/responsible-person-validations.test.js
- app/views/stripe-setup/responsible-person/index.njk
Except for date of birth validation, which is coming later.
Update max lengths to match what we think Stripe accepts.
with @cobainc0
> PP-4463 Server-side validation for responsible person page

- app/utils/transaction_view.js
- app/views/transaction_detail/_payment.njk
- test/cypress/integration/transactions/transaction_details_spec.js
- test/fixtures/transaction_fixtures.js
Add Wallet Type to single transaction page
Charge with Wallet Type should appear on single transaction page
> PP-4910: Add Wallet Type to single transaction page

- app/browsered/field-validation-checks.js
- app/controllers/stripe-setup/bank-details/bank-details-validations.test.js
- app/controllers/stripe-setup/bank-details/post.controller.js
- app/controllers/stripe-setup/bank-details/post.controller.test.js
- app/middleware/stripe-setup/check-bank-details-not-submitted.js
- app/middleware/stripe-setup/check-bank-details-not-submitted.test.js
- app/middleware/stripe-setup/get-stripe-account.js
- app/middleware/stripe-setup/get-stripe-account.test.js
- app/routes.js
- app/services/clients/stripe/stripeBankAccount.model.js
- app/services/clients/stripe/stripeBankAccount.model.test.js
- app/views/stripe-setup/bank-details/index.njk
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/stripe_account_setup_fixtures.js
- test/unit/browsered/field_validation_checks_test.js
This PR contains Stripe Connect bank details submission implementation and minor tweaks (disable autocomplete and error messages).
Please see commits for more information.
with @alan-gds
> PP-4462 Bank details submission

- app/controllers/stripe-setup/bank-details/post.controller.js
- app/middleware/stripe-setup/check-bank-details-not-submitted.js
- app/middleware/stripe-setup/check-bank-details-not-submitted.test.js
- app/views/stripe-setup/bank-details/index.njk
- test/cypress/integration/stripe-setup/bank_details_spec.js
This PR contains cosmetic UX/UI improvents.
Please see commits for more information.
> PP-4462 Cosmetic UX and other improvements

- app/controllers/stripe-setup/responsible-person/post.controller.js
We want to use the term “normalise” to refer to more substantial alterations to incoming form fields.
> PP-4463 Rename normaliseField(…) function to trimField(…)

- app/controllers/stripe-setup/responsible-person/post.controller.js
> PP-4463 Make Stripe responsible person error view work

- app/services/clients/stripe/stripeCompany.model.js
- app/services/clients/stripe/stripeCompany.model.test.js
- app/services/clients/stripe/stripe_client.js
- Add `updateCompany` to Stripe client and related `StripeCompany` model
> PP-4949 Stripe client: update company

- test/cypress/integration/dashboard/dashboard_go_live_link_spec.js
- test/cypress/integration/dashboard/dashboard_links_spec.js
- test/cypress/integration/dashboard/dashboard_spec.js
- test/cypress/integration/request-to-go-live/agreement_spec.js
- test/cypress/integration/request-to-go-live/choose_how_to_process_payments_spec.js
- test/cypress/integration/request-to-go-live/index_spec.js
- test/cypress/integration/request-to-go-live/organisation_address_spec.js
- test/cypress/integration/request-to-go-live/organisation_name_spec.js
- test/cypress/integration/settings/allow_apple_pay_spec.js
- test/cypress/integration/settings/allow_google_pay_spec.js
- test/cypress/integration/settings/email_notifications_spec.js
- test/cypress/integration/settings/merchant_details_spec.js
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/integration/stripe-setup/responsible_person_spec.js
- test/cypress/integration/transactions/transaction_details_spec.js
- test/cypress/integration/transactions/transaction_search_spec.js
- test/cypress/integration/user/login_spec.js
- test/cypress/plugins/index.js
- test/cypress/utils/request_to_go_live_utils.js
- Rename methods to be more descriptive
> PP-4976 Rename go live cypress utils methods

- test/integration/transaction_download_ft_tests.js
Fixes failing test `should download a csv file when the next_page is relative URI (not full connector URL)`
CI should pass
> PP-4910 Fix tests

- test/cypress/integration/request-to-go-live/organisation_address_spec.js
- test/cypress/integration/request-to-go-live/organisation_name_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/request_to_go_live_utils.js
Add test to check submission of the page when valid inputs are entered redirects to the "Choose how to process payments" page
> PP-4976 Add cypress test for organisation address submission

- app/browsered/field-validation-checks.js
- app/controllers/stripe-setup/bank-details/get.controller.js
- app/controllers/stripe-setup/responsible-person/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/check-your-answers/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/check-your-answers/index.js
- app/controllers/stripe-setup/vat-number-company-number/check-your-answers/post.controller.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/index.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/post.controller.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/vat-number-validations.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/vat-number-validations.test.js
- app/middleware/stripe-setup/check-vat-number-company-number-not-submitted.test.js
- app/paths.js
- app/routes.js
- app/views/stripe-setup/bank-details/index.njk
- app/views/stripe-setup/vat-number-company-number/company-number.njk
- app/views/stripe-setup/vat-number-company-number/vat-number.njk
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/integration/stripe-setup/responsible_person_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/index_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/support.js
- test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js
- test/cypress/plugins/index.js
- test/cypress/plugins/stubs.js
- test/cypress/support/commands.js
- test/fixtures/user_fixtures.js
This PR finishes `Index` and `VAT number` pages logic and tests (except the redirect logic in `VAT number` page which will be implemented later).
Also, it has some cosmetic changes.
Please see commits for more information.
> PP-4949 Index and VAT number pages logic and tests

- app/browsered/field-validation-checks.js
- app/controllers/stripe-setup/bank-details/bank-details-validations.test.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.test.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/post.controller.js
- app/controllers/stripe-setup/vat-number-company-number/vat-number/vat-number-validations.test.js
- app/views/stripe-setup/vat-number-company-number/company-number.njk
- test/unit/browsered/field_validation_checks_test.js
This PR has some field-validation-checks -> `isNotVatNumber` and `isPhoneNumber` improvements
and other small changes.
Please see commits for more information.
> PP-4949 field-validation-checks: isNotVatNumber and isPhoneNumber improvements

- app/browsered/field-validation-checks.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/company-number-validations.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/post.controller.js
- app/views/stripe-setup/vat-number-company-number/company-number.njk
- test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
- Implemented controller logic
- Added tests
- Other minor modifications
> PP-4949 Stripe setup: company number page implementation

- Jenkinsfile
- both connector and adminusers using Java 11.
> BAU - Set JAVA_HOME for pact provider tests

- app/browsered/field-validation-checks.js
- app/controllers/stripe-setup/vat-number-company-number/check-your-answers/get.controller.js
- app/controllers/stripe-setup/vat-number-company-number/check-your-answers/post.controller.js
- app/controllers/stripe-setup/vat-number-company-number/company-number/post.controller.js
- app/views/stripe-setup/vat-number-company-number/check-your-answers.njk
- test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
- Implement "VAT number / company number - check your answers" page with display logic
and change of the data behaviour
> PP-4949 Stripe setup: "VAT number / company number - check your answers" page display logic

- app/models/Product.class.js
- test/fixtures/product_fixtures.js
- test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
- test/unit/clients/product_client/product/get_by_product_external_id_test.js
- test/unit/clients/product_client/product/get_by_product_path_test.js
Resolve language in Product model.
Remove non-existent service name field from model.
Enable pact tests for products and get them working.
> PP-5017 Resolve language on product

- Jenkinsfile
> PP-5017 Enable products pact tests on CI

- app/controllers/payment-links/get-information-controller.js
- app/views/payment-links/information.njk
- test/cypress/integration/payment-links/create_payment_link_spec.js
- test/cypress/utils/common_stubs.js
- test/unit/controller/payment-links/get_information_controller.test.js
> PP-5012 Resolve welsh service name for create payment link

- app/views/payment-links/index.njk
- test/cypress/integration/payment-links/create_payment_link_spec.js
> PP-5012 Add link to create a welsh payment link

- app/controllers/payment-links/get-edit-amount-controller.js
- app/controllers/payment-links/get-edit-information-controller.js
- app/views/payment-links/edit-amount.njk
- app/views/payment-links/edit-information.njk
- test/cypress/integration/payment-links/edit_payment_link_spec.js
- test/cypress/integration/payment-links/manage_payment_links_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/products_stubs.js
Display Welsh instructions when editing a Welsh payment link on the the
edit information page.
Don't show the example image on the edit amount page
Remove some commented out code in edit-amount.njk
> PP-5012 Show Welsh text for edit payment link

- app/views/payment-links/index.njk
> PP-5012 Add correct styling to link

- package-lock.json
- package.json
> Bump @govuk-pay/pay-js-commons from 1.4.0 to 2.2.0

- app/assets/sass/components/button.scss
- app/views/api-keys/_key.njk
- app/views/api-keys/create.njk
- app/views/payment-links/_product.njk
- app/views/team-members/team_member_details.njk
- app/views/transaction_detail/_refund.njk
- app/views/transaction_detail/index.njk
- package-lock.json
- package.json
Updating GOV.UK Frontend and updating all buttons to new secondary buttons
> BAU - GOV.UK Frontend 2.11 - secondary buttons

- test/unit/clients/connector_client/connector_get_transaction_details_test.js
Add pact test for retrieving transaction details with metadata.
> PP-4889 add pact test for metadata

- app/controllers/transactions/transaction_list_controller.js
- app/utils/transaction_view.js
- app/views/transaction_detail/_details.njk
- app/views/transaction_detail/_refund.njk
- app/views/transactions/list.njk
- test/cypress/integration/transactions/transaction_details_spec.js
- test/cypress/integration/transactions/transaction_search_spec.js
- test/fixtures/transaction_fixtures.js
- test/integration/transaction_details_ft_tests.js
- test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js
* Update transaction list to show fee, net columns 
* Update transaction details to show fee, net columns 
* Add consumer contract test with transaction fee structure 
* Add Cypress validation for showing/ hiding columns appropriately
Note: PR is in draft state as no transactions will have fees associated until Stripe billing is live, the code is ready to review
> PP-4997 Stripe fee/ net columns for transaction views

- app/controllers/transactions/transaction_download_controller.js
- app/utils/json_to_csv.js
Supersedes https://github.com/alphagov/pay-selfservice/pull/1378/commits
> PP-4997 Fee and net columns for Stripe CSV export

- Jenkinsfile
After extensive consultation it has been decided this is for the best.
> PP-5191: Default run e2e tests to false on PR

- test/unit/clients/adminusers_client/service/update_service_test.js
Return promise in update_service_test which previously wasn't awaited
> PP-5199 Fix promise not awaited in test

- app/views/team-members/team_members.njk
- test/ui/team_member_list_ui_tests.js
> PP-5184 team member page design updates

- app/services/clients/direct_debit_connector_client.js
> PP-5234: Service name should not be set by a call to dd-connector

- app/controllers/dashboard/dashboard-activity-controller.js
- app/models/DirectDebitGatewayAccount.class.js
- app/views/dashboard/_link-to-gocardless.njk
- app/views/dashboard/index.njk
- test/cypress/integration/dashboard/dashboard_gocardless_spec.js
- test/fixtures/gateway_account_fixtures.js
Show 'Connect to GoCardless' page if Gateway Account is live, uses the direct debit payment method and is not connected to GoCardless yet.
At this point I haven't wrote any tests and the html/css styling isn't quite right.
> Pp 5266 scenario 2

- server.js
- b94c7be - httpsAgent is unused
- f0487d6 - remove path
- 070b75b - these paths dont exist anymore
> BAU tidy server js

- app/views/transactions/display_size.njk
This removes some of the GOV.UK Frontend styling that was making the button look bad
> PP-5330 - use custom button that looks like link

- app/assets/sass/components/navigation.scss
- app/views/layout.njk
Also better because we don’t need to mess with negative margins
> PP-5331 - Reduce padding on main container if we have a phase banner

- app/controllers/settings/get.settings.controller.js
- app/views/settings/index.njk
- test/cypress/integration/settings/3ds-spec.js
- test/cypress/integration/settings/allow_apple_pay_spec.js
- test/cypress/integration/settings/allow_google_pay_spec.js
- test/cypress/integration/settings/email_notifications_spec.js
Extended settings tests to start from the settings index page not their subpages.
> PP-5185 settings page extended tests

- app/routes.js
- app/views/merchant_details/edit_merchant_details.njk
- app/views/merchant_details/merchant_details.njk
- app/views/team-members/team_member_details.njk
- app/views/team-members/team_member_invite.njk
- app/views/team-members/team_member_permissions.njk
- app/views/team-members/team_member_profile.njk
- app/views/team-members/team_members.njk
Fixes cookie banner on profile page and the spacing between the header and content on all the pages with my services
> PP-5361 fix layout probs on profile page

- app/assets/sass/application.scss
- app/assets/sass/components/button.scss
- app/assets/sass/components/colour.scss
- app/assets/sass/components/floats.scss
- app/assets/sass/components/text-align.scss
- app/views/dashboard/demo-payment/index.njk
- app/views/email_notifications/index.njk
- app/views/payment-links/edit.njk
- app/views/payment-links/review.njk
- app/views/payment-links/web-address.njk
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- app/views/services/_service_switch.njk
- app/views/services/index.njk
- app/views/stripe-setup/bank-details/check-your-answers.njk
- app/views/stripe-setup/responsible-person/check-your-answers.njk
- app/views/team-members/team_member_permissions.njk
- app/views/team-members/team_members.njk
- app/views/transactions/display_size.njk
- app/views/twoFactorAuth/configure.njk
Based on the guidance here - https://design-system.service.gov.uk/get-started/extending-and-modifying-components/#use-a-unique-prefix-for-component-names
> PP-5369 - rename custom class prefixes

- app/assets/sass/components/navigation.scss
- app/utils/navBuilder.js
> PP-5373 - add payment links to top nav

- app/assets/sass/components/borders.scss
- app/views/includes/footer-categories.njk
Conor and I don’t like them so we’re removing them
> BAU - remove borders from headings in footer

- app/assets/sass/application.scss
- app/assets/sass/components/container.scss
Increasing page width from 960px to 1100px this gives us more space for things.
> PP-5382 - Increase max page width

- app/assets/sass/components/navigation.scss
- app/views/includes/feedback-banner.njk
Because it’s better to use the macro than custom code, no visual difference
> PP-5382 - didn’t realise there was a macro for this

- app/assets/sass/components/navigation.scss
- app/utils/navBuilder.js
- app/views/includes/phase_banner.njk
Making sure this line is there
> BAU - settings page should hightlighed when active page

- app/controllers/user/phone-number/get.controller.js
- app/controllers/user/phone-number/index.js
- app/controllers/user/phone-number/post.controller.js
- app/paths.js
- app/routes.js
- app/services/clients/adminusers_client.js
- app/services/user_service.js
- app/views/team-members/edit-phone-number.njk
- app/views/team-members/team_member_profile.njk
- test/cypress/integration/user/edit-phone-number-spec.js
5e39c5b - Add link to update phone number
172ac9b - Add edit phone number page
cd47913 - Add post controller to actually update phone number
f74c6ce - Add phone number validation
b184e9c - Add Cypress test for updating phone number
Linting on commit also cleaned up `user_service.js`
> PP-5384 allow user to update phone numbers

- app/views/includes/footer.njk
This used to happen but when we moved it recently something changed…
> BAU - hide feeback banner when logged out

- app/controllers/partnerapp/handle_gocardless_connect_get.js
- test/cypress/integration/partnerapp/handle_redirect_from_gocardless_spec.js
> PP-5334 Modify copy for GoCardless connect error

- app/views/oauth/gocardless_complete.njk
> PP-5437 GoCardless connect complete copy tweaks

- app/utils/states.js
- package-lock.json
- test/cypress/integration/transactions/transaction_search_spec.js
- test/integration/transaction_list_ft_tests.js
- test/unit/utils/filters_test.js
- test/unit/utils/states_test.js
This relates to https://payments-platform.atlassian.net/browse/PP-5447.
It seems my VSCode made a lot of formatting changes too.
> zd3761275: Map 'capturable' status

- app/views/includes/head.njk
Sending (and hence recording) emails breaks our agreement with Google and is a
breach of our obligations under GDPR.
> PP-5512: Strip out email search param for Google Analytics

- app/views/includes/head.njk
> PP-5512: Send pageview to Google Analytics

- app/views/includes/footer-categories.njk
Thanks @yahoopete for spotting this!
> BAU - Slack changed the link

- README.md
- app/services/clients/ledger_client.js
- test/test.env
Add ledger services client using a singleton pattern, the same client should be offered to all modules requiring it, only exposing methods to make requests to ledger.
* update test environment to include ledger URL
* update README with upcoming feature flag
> PP-5500 Ledger service client

- app/models/charge.js
- app/services/clients/ledger_client.js
- app/services/clients/utils/ledger_legacy_connector_parity.js
- test/unit/clients/ledger_client/legacy_connector_parity_util_test.js
* Transaction details page feature flag to point to ledger or connector
* Depends on (forked from) https://github.com/alphagov/pay-selfservice/pull/1582
* Depends on https://github.com/alphagov/pay-infra/pull/2282
> PP-5426 Transaction view uses ledger (feature flag)

- app/utils/transaction_view.js
* ledger refund summary parity to be addresed in
https://payments-platform.atlassian.net/browse/PP-5552
* allow page to be rendered until then
> BAU Fix ledger refund summary transaction view

- app/views/dashboard/demo-payment/index.njk
- app/views/merchant_details/merchant_details.njk
- app/views/team-members/team_member_details.njk
A while ago this class was renamed and somehow these classes we not updated
> PP-5529 - fix files using wrong align right class

- app/services/clients/ledger_client.js
- app/services/clients/utils/ledger_legacy_connector_parity.js
- app/services/transaction_service.js
- app/utils/get_query_string_for_params.js
- test/unit/clients/ledger_client/legacy_connector_parity_util_test.js
Transactions list uses Ledger.
* split transaction service search into ledger and connector search
* async ledger search method
* introduce feature flag for using ledger data
* parse and flatten card brand param into `card_brand` expected by
Ledger, enabled with optional flag
> PP-5425 Transactions list search uses ledger (feature flag)

- app/services/clients/ledger_client.js
- app/services/transaction_service.js
Depends on (forked from) https://github.com/alphagov/pay-selfservice/pull/1589
* export search all transactions from ledger behind feature flag
* page ledger results utility similar to Connector
> PP-5428 CSV transactions download uses ledger

- app/services/clients/ledger_client.js
- test/fixtures/ledger_transaction_fixtures.js
- test/unit/clients/ledger_client/ledger_get_transaction_details_test.js
- add ledger transaction fixtures
- refactor ledger client to to use optional transaction_type query
- add get transaction in created state details pact test
> PP-5537 add get single transaction pact test

- test/fixtures/ledger_transaction_fixtures.js
- test/unit/clients/ledger_client/ledger_search_transaction_test.js
Reverts alphagov/pay-selfservice#1613
> Revert "PP-5537 add get events and search ledger transactions pact tests"

- test/unit/clients/connector_client/connector_get_transactions_and_summary_test.js
- Removes the pact test that matches with a partial reference on search
> PP-5611 Remove Partial Reference Pact Test

- app/views/includes/head.njk
See https://docs.google.com/document/d/1Scq-axCUknouQhKkf5ppqcqljeWSo62njL4p9qGcIjo/edit# to help verify this PR is correct.
> bau: Send analytics to cross-gov Google Analytics

- app/services/auth_service.js
- app/views/login/otp-login.njk
- test/ui/login_ui_tests.js
And use same pattern as Design System - https://design-system.service.gov.uk/components/error-summary/
i.e. Error message is in error summary and on input
> PP-5634 - Improved error message for OTP login step

- app/views/includes/footer.njk
Must be deployed after alphagov/pay-product-page#162
> PP-5653 - add a link to statement in the footer

- package-lock.json
- package.json
- test/cypress/integration/payment-links/create_payment_link_spec.js
- test/cypress/integration/payment-links/edit_payment_link_spec.js
- test/cypress/integration/request-to-go-live/organisation_address_spec.js
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/integration/stripe-setup/responsible_person_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js
Reverts alphagov/pay-selfservice#1644
Breaks end-to-end
> Revert "Bump govuk-frontend from 3.0.0 to 3.2.0"

- .hadolint.yaml
> Add Hadolint configuration from pay-code-analysis-config

- app/services/clients/ledger_client.js
- app/services/clients/utils/ledger_legacy_connector_parity.js
- package-lock.json
- test/fixtures/ledger_transaction_fixtures.js
- test/unit/clients/ledger_client/ledger_get_transaction_summary_test.js
- test/unit/clients/ledger_client/legacy_connector_parity_util_test.js
- add method to ledger_client to retrieve transactions summary
- add connector parity transformer
- add contract test
- add tests
> PP-5427 add get transactions-summary to ledger_client

- app/services/clients/ledger_client.js
- app/services/clients/utils/ledger_legacy_connector_parity.js
- test/fixtures/ledger_transaction_fixtures.js
- test/unit/clients/ledger_client/ledger_get_transaction_summary_test.js
- add to date query param to transactionSummary ledger call
- update tests
- fix: add net_income to legacy connector parity transformer
> PP-5427 add to date to ledger transaction summary

- app/controllers/dashboard/dashboard-activity-controller.js
- app/services/clients/ledger_client.js
- app/services/clients/utils/ledger_legacy_connector_parity.js
- test/cypress/integration/dashboard/dashboard_links_spec.js
- test/cypress/integration/dashboard/dashboard_spec.js
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/integration/stripe-setup/responsible_person_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/index_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/support.js
- test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/common_stubs.js
- test/integration/get_gateway_account_ft_test.js
- test/integration/login_controller_test.js
- test/unit/controller/dashboard/dashboard-activity-controller.test.js
PP-5427 switch activity dashboard to ledger
- refactor dashboard-activity-controller to use ledger
- update relevant tests
- refactor cypress tests
- code clean up: remove 'custom' date range (it has been removed from the dashboard ui)
> PP-5427 switch activity dashboard to ledger

- app/utils/format-PSP-name.js
- app/utils/navBuilder.js
- app/views/your-psp/_epdq.njk
- app/views/your-psp/_smartpay.njk
- app/views/your-psp/_worldpay.njk
- app/views/your-psp/index.njk
- test/ui/navigation_ui_tests.js
- test/unit/utils/format-PSP-name.test.js
Add new copy and settings nav label and update associated tests
> PP-5558 - your PSP copy updates

- test/cypress/integration/dashboard/dashboard_spec.js
- test/cypress/integration/transactions/transaction_details_spec.js
> BAU fix cypress tests

- app/views/api-keys/_key.njk
> BAU - add paragraph class so that it’s styled correctly

- test/cypress/integration/transactions/transaction_list_pagination_spec.js
- test/cypress/integration/transactions/transaction_search_spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/ledger_transaction_fixtures.js
- test/integration/pagination_ft_tests.js
- move pagination ft tests to cypress
> PP-5767 switch pagination ft tests to use ledger

- test/unit/clients/ledger_client/ledger_get_transaction_details_test.js
- add tests ledger_get_transaction_details_test to pact tests corporate surcharge and metadata
> PP-5770 add pact test for transaction details

- test/unit/clients/ledger_client/ledger_search_transaction_test.js
- add pact test for multiple values search
> PP-5770 add some pact test for transaction search

- test/unit/clients/ledger_client/ledger_search_transaction_test.js
- add a pact tests that filters transaction by to date
> PP-5770 WIP add pact tests for filtering by to_date

- app/controllers/your-psp/get-controller.js
- app/controllers/your-psp/get-flex-controller.js
- app/controllers/your-psp/index.js
- app/controllers/your-psp/post-flex-controller.js
- app/paths.js
- app/routes.js
- app/services/clients/connector_client.js
- app/views/credentials/epdq.njk
- app/views/credentials/smartpay.njk
- app/views/toggle-3ds/index.njk
- app/views/your-psp/_epdq.njk
- app/views/your-psp/_smartpay.njk
- app/views/your-psp/_worldpay-flex.njk
- app/views/your-psp/_worldpay.njk
- app/views/your-psp/flex.njk
- app/views/your-psp/index.njk
- test/cypress/integration/settings/your-psp-spec.js
- test/cypress/plugins/stubs.js
- test/fixtures/gateway_account_fixtures.js
- Added Flex credentials to Your PSP page
- Added Cypress tests for whole lot
> PP-5790 ability to add flex credentials

- app/assets/sass/application.scss
- app/assets/sass/components/container.scss
- app/views/includes/header.njk
- package-lock.json
- package.json
Update to the new GOV.UK Frontend and following their introduction of a new feature tackle our custom width pages in a different manner https://github.com/alphagov/govuk-frontend/releases/tag/v3.4.0
> Bau govuk frontend 3.4 bump

- app/views/your-psp/flex.njk
- test/cypress/integration/settings/3ds-spec.js
> BAU - Replace all WorldPay instances with Worldpay

- app/controllers/your-psp/get-controller.js
- app/controllers/your-psp/get-flex-controller.js
- app/controllers/your-psp/post-flex-controller.js
- app/views/your-psp/_worldpay-flex.njk
- app/views/your-psp/flex.njk
- test/cypress/integration/settings/your-psp-spec.js
- test/cypress/plugins/stubs.js
- add option of removing credentials
- update/add information phrases
- add/update relevant cypress tests
> PP-5951 add option to remove 3DS Flex credentials

- test/cypress/integration/manage-team-members/edit_permissions_spec.js
- test/cypress/integration/manage-team-members/manage_team_members_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/user_stubs.js
- test/fixtures/invite_fixtures.js
- test/fixtures/service_fixtures.js
- test/fixtures/user_fixtures.js
Replaces the `PermissionsIT.adminUserCanEditServiceRoleOfAnotherMemberOfTheTeam` end to end test
> PP-5996 Add cypress test for changing user permissions

- test/cypress/integration/manage-team-members/edit_permissions_spec.js
- test/cypress/integration/my-services/add_new_service_spec.js
- test/cypress/integration/settings/merchant_details_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/common_stubs.js
- test/fixtures/gateway_account_fixtures.js
- test/fixtures/service_fixtures.js
- test/fixtures/user_fixtures.js
- test/unit/clients/adminusers_client/service/create_service_test.js
- test/unit/clients/adminusers_client/user/assign_servicerole_test.js
Add Cypress test which follows the flow for adding a new service.
Modify some fixtures to get this to work.
> PP-5996 Add Cypress test for adding a new service

- app/controllers/transactions/transaction_download_controller.js
* track duration of fetch and processing duration for CSVs
* log details at info level
> PP-6048 Performance logging for CSV downloads

- test/cypress/integration/payment-links/delete_payment_links_spec.js
- test/cypress/plugins/stubs.js
- test/cypress/utils/products_stubs.js
- test/fixtures/product_fixtures.js
- test/unit/clients/product_client/product/create_test.js
- test/unit/clients/product_client/product/get_by_gateway_account_id_test.js
- test/unit/clients/product_client/product/get_by_product_external_id_test.js
- test/unit/clients/product_client/product/get_by_product_path_test.js
- test/unit/controller/make_a_demo_payment_controller/go_to_payment_controller_test.js
- test/unit/controller/payment-links/post_information_controller.test.js
- test/unit/controller/payment-links/post_review_controller.test.js
- test/unit/controller/payment-links/post_web_address_controller.test.js
- test/unit/controller/test_with_your_users_controller/submit_controller_test.js
Description:
- Moves PrototypeProductPaymentIT.shouldDeleteATestProductPayment from selfservice endtoend as a cypress test
> PP-6008-Add-delete-payment-link-cypress-test

- .travis.yml
- app/controllers/test_with_your_users/index_controller.js
- package.json
- test/fixtures/user_service_fixture.js
- test/integration/proxy_fn_tests.js
- test/integration/router_test.js
- test/integration/transaction_download_ft_tests.js
- test/unit/controller/login_controller_test.js
- test/unit/controller/validate_invite_controller_test.js
- test/unit/middleware/csrf_test.js
- test/unit/services/auth_service_test.js
- test/unit/utils/util_correlation_header_test.js
- test/unit/utils/util_dates_tests.js
Adds a simple .travis.yml build configuration for running CI node build tasks. Includes cypress tests.
> Run builds on travis

- app/controllers/transactions/transaction_download_controller.js
- app/services/clients/stream_client.js
- app/services/transaction_service.js
- test/integration/transaction_download_ft_tests.js
- test/unit/clients/stream_client_test.js
* client wrapper around Node core `http` library to make request listening on
data and completion events.
* use stream client with data and complete events to request to Ledger
endpoint
Should pass all current unit/ integration/ cypress tests for the future CSV download strategy.
> PP-6069 CSV download future strategy stream proxy

- test/fixtures/ledger_transaction_fixtures.js
> PP-5956 Include moto flag in ledger pacts

- test/fixtures/gateway_account_fixtures.js
> PP-5956 Include allow_moto flag in connector pact tests

- env-map.yml
> PP-6196 Correct card-connector url in the env-map.yml

- app/models/Product.class.js
- test/fixtures/product_fixtures.js
- test/unit/clients/product_client/product/get_by_gateway_account_id_with_metadata_test.js
- a product with metadata exists pact test
> PP-6160 add get product with metadata pact test

- app/assets/sass/application.scss
- app/assets/sass/components/reporting-columns.scss
- app/views/payment-links/_product.njk
- test/cypress/integration/payment-links/manage_payment_links_spec.js
- For each Payment Link, display the associated metadata
with @iqbalgds
> PP-6160 Show associated metadata on Manage Payment links page

- app/controllers/payment-links/metadata/metadata-form.js
- app/controllers/payment-links/metadata/resource-controller.js
- app/views/payment-links/metadata/edit-metadata.njk
- test/fixtures/service_fixtures.js
- test/unit/controller/payment-links/metadata/paymentlink_metadata_form.test.js
- test/unit/controller/payment-links/metadata/paymentlink_metadata_resource.test.js
* validates for empty inputs
* parses error codes from products and specifically targets form elements 
* follows design system guidelines for forms, specific feedback provided on inputs as well as in an error summary https://design-system.service.gov.uk/components/error-summary/
> PP-6153 Payment link metadata add/edit page validation

- app/assets/sass/components/reporting-columns.scss
- Fix issue with margins with <dt> tag on IE11
> PP-6160 Fix styling for IE11 on  Payment Links >  Reporting Columns

- app/controllers/payment-links/get-edit-controller.js
- app/controllers/payment-links/index.js
- app/controllers/payment-links/metadata/resource-controller.js
- app/routes.js
- app/services/clients/products_client.js
- app/views/payment-links/metadata/edit-metadata.njk
- test/unit/controller/payment-links/metadata/paymentlink_metadata_resource.test.js
- Allows editing of existing Reporting Columns from the 'Edit Payment Link' page.
- Updated controller for Reporting Columns so that it can handle Editing & Updating Reporting columns.
> PP-6157 Edit reporting columns on payment links

- app/controllers/transactions/transaction_detail_controller.js
- app/controllers/transactions/transaction_detail_redirect_controller.js
- app/paths.js
- app/routes.js
- app/services/clients/ledger_client.js
- app/utils/valid_account_id.js
- test/fixtures/ledger_transaction_fixtures.js
- test/integration/transaction_redirect_details_ft_tests.js
- Implements the service switcher, allowing routes to provide a
serviceId through the serviceSwitcher middleware, which will then
redirect users to that service before loading the page
- Tests to ensure that functionality works as expected.
> PP-6268 Implement Service Switcher

- app/controllers/all-service-transactions/download-transactions.js
- app/controllers/all-service-transactions/get-controller.js
- app/controllers/all-service-transactions/index.js
- app/controllers/transactions/transaction_detail_controller.js
- app/controllers/transactions/transaction_detail_redirect_controller.js
- app/controllers/transactions/transaction_list_controller.js
- app/paths.js
- app/routes.js
- app/services/auth_service.js
- app/utils/display_converter.js
- app/utils/transaction_view.js
- app/views/all_service_transactions/index.njk
- app/views/services/index.njk
- app/views/transaction_detail/index.njk
- Adds all services transactions view, a url, hidden behind a feature
flag, that displays all the transactions across all services in a
downloadable filterable format for users to access.
> PP-6303 All Services Transactions View

- app/views/all_service_transactions/index.njk
- Rename the title of the "All Service Transactions" page following
suggestions from @quis.
> BAU Rename All Service Transactions

- app/views/api-keys/_keys.njk
- app/views/dashboard/demo-payment/edit-amount.njk
- app/views/email_notifications/confirm.njk
- app/views/email_notifications/confirmation_email_toggle.njk
- app/views/email_notifications/edit.njk
- app/views/forgotten_password/new_password.njk
- app/views/login/send_otp_again.njk
- app/views/self_create_service/register.njk
- app/views/self_create_service/resend_otp.njk
- app/views/self_create_service/set_name.njk
- app/views/self_create_service/verify_otp.njk
- app/views/user_registration/re_verify_phone.njk
- app/views/user_registration/register.njk
- app/views/user_registration/verify_otp.njk
- Added ID attributes to buttons to be used across tests. Using css class makes the tests break easily if more components with same class are added to pages
> PP-6285 Add IDs to buttons

- app/views/self_create_service/resend_otp.njk
- app/views/user_registration/re_verify_phone.njk
- Fixed typo in button IDs. Don't want the same typo endup in tests too
> PP-6285 Fix typo in button ID

- app/browsered/cookie-functions.js
- test/unit/browsered/cookie-banner.test.js
- test/unit/browsered/cookie-functions.test.js
- Added test for cookie functions and also explicitly testing the domain being set for cookies
> PP-6285 Add tests for cookie functions

- app/browsered/cookie-banner.js
- app/browsered/cookie-functions.js
- test/unit/browsered/cookie-banner.test.js
- Reads analytics cookie on page load and loads analytics if consented or ignore if not consented previously
- Added relevant tests
with @sandorarpa
> PP-6300 Cookie analytics on page load

- test/fixtures/payout_fixtures.js
- test/unit/clients/ledger_client/ledger_search_payout_test.js
- add a new search payouts contract test
> PP-6491 add ledger payout search pact test

- app/routes.js
- app/views/payment-links/edit.njk
Reporting columns are ready to be released to all users.
* Remove presentation layer checking for experimental features
* Remove restriction on controllers/ endpoints
Improvements to the feature will follow based on user research and
feedback.
> PP-6623 Remove the experimental features flag for reporting columns

- app/services/clients/ledger_client.js
- test/cypress/plugins/stubs.js
- test/integration/payouts/payouts_service_it_test.js
- test/unit/clients/ledger_client/ledger_search_payout_test.js
Only fetch payouts from ledger which have state "paidout" to display on the list payouts page.
> PP-6591 Filter payouts by paidout state

- app/paths.js
- test/cypress/integration/payouts/payouts_list_spec.js
change from '/payouts' to '/payments-to-your-bank-account'
> PP-6591 Change url for payouts page

- app/controllers/my-services/get-index-controller.js
- app/views/services/index.njk
- test/cypress/integration/my-services/payouts_link_spec.js
- test/cypress/utils/common_stubs.js
Display the link if the user has any live stripe accounts.
Refactor the my-services/get-index-controller.js to use async await and be easier to follow.
> PP-6591 Add link to list payouts on "My services" page

- app/controllers/all-service-transactions/download-transactions.js
- app/controllers/payouts/payout_list_controller.js
Add info logs that can be used to monitor feature usage: 
* payout page feature
* download transaction for a given payout feature
> PP-6591 Payouts log user activity

- app/controllers/dashboard/dashboard-activity-controller.js
- Removed Xray segment from controller as we are not using Xray
Co-authored-by : @iqbalgds
> PP-6633 Remove Xray segment from Dashboard controller

- app/views/dashboard/_stripe_account_setup_banner.njk
- test/unit/controller/dashboard/dashboard-activity-controller.test.js
- Fixes conditions to display outstanding activities for Stripe account setup
- Match panel message to latest Stripe onboarding design
> PP-6633 Fix account status panel message

- app/assets/sass/application.scss
- app/assets/sass/components/psp-go-live-panel.scss
- app/views/dashboard/_stripe_account_setup_banner.njk
- app/views/stripe-setup/go-live-complete.njk
- Dashboard Stripe Setup banner
- Update `add detail` to go to the `add details` flow
- Update spacing
- Go Live page - update copy and styling.
> PP-6638 Update styling for  Dashboard Stripe Panel & Go Live page.

- app/views/stripe-setup/responsible-person/index.njk
- New content for where data is stored
- Link to product page about what it means to be a responsible person
> PP-6624 Amend content on responsible person page

- app/views/stripe-setup/vat-number-company-number/vat-number.njk
- test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js
> PP-6634 Fix error summary wording

- app/views/request-to-go-live/index.njk
- test/cypress/integration/request-to-go-live/index_spec.js
- Update copy and styling to work with new Stripe onboarding flow
- Update both 'BYOC' & 'Stripe Request to go live' page
> PP-6651 Update `Request to go live` page.

- app/controllers/dashboard/dashboard-activity-controller.js
- app/middleware/get_gateway_account.js
- app/views/dashboard/_stripe_account_setup_banner.njk
- app/views/includes/phase_banner.njk
- server.js
- test/cypress/integration/settings/3ds-spec.js
- test/cypress/integration/stripe-setup/bank_details_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/check_your_answers_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/company_number_spec.js
- test/cypress/integration/stripe-setup/vat-number-company-number/vat_number_spec.js
- test/cypress/integration/transactions/transaction_details_spec.js
- test/cypress/integration/transactions/transaction_search_spec.js
- test/cypress/utils/common_stubs.js
- test/integration/add_psp_details_ft_tests.js
- test/integration/login_controller_test.js
- test/unit/controller/dashboard/dashboard-activity-controller.test.js
Add account setup details to the session account object IFF this is a
live Stripe account.
* use `govuk-tag` to be inline with the design system
* grey for test
* light blue for information required
* blue for live
> PP-6652 Account status tag "setup" status

- app/assets/sass/components/navigation.scss
- app/views/includes/phase_banner.njk
- Service name tag
- LIVE service - remove PSP from tag name
- Add 5px between tag and service name
> PP-6651 Update Service tag

- app/views/dashboard/_stripe_account_setup_banner.njk
- app/views/request-to-go-live/index.njk
- Stripe > Request to go live
- Add link to responsible person > product pages doc
- Add info about company number
- Wrap info about admin users in Warning text
- Dashboard > Stripe Onboarding panel
- Remove dashes from bullet points
> PP-6651 Stripe onboarding updates

- app/views/stripe-setup/vat-number-company-number/company-number.njk
- Remove custom styling to labels to radio buttons
> PP-6651 Company number radio buttons - remove bold

- app/views/dashboard/_live_account_requested_banner.njk
> PP-6672 Dashboard > Stripe Go Live banner > update styling

- app/utils/filters.js
- app/views/transactions/filter.njk
- test/cypress/integration/transactions/transaction_list_pagination_spec.js
- test/cypress/integration/transactions/transaction_search_spec.js
- test/cypress/plugins/stubs.js
> PP-6644 Remove default from date from transactions list filters

- app/views/request-to-go-live/agreement.njk
- app/views/request-to-go-live/index.njk
- test/cypress/integration/request-to-go-live/agreement_spec.js
Updates with suggestions made when content design review performed.
> PP-6719 Update request to go live content

- .vscode/launch.json
- README.md
- Update README.md
- Update info running in debug mode with a SSH tunnel.
- Include info to run Mocha tests in debug mode.
- Update launch.json
- Rename the `nodemon` debug config to `Self Service`.
> PP-6775 Update README.md & launch.json

- test/cypress/integration/dashboard/dashboard-gocardless.cy.test.js
- test/cypress/integration/dashboard/dashboard.cy.test.js
- test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
- test/cypress/integration/manage-team-members/manage-team-members.cy.test.js
- test/cypress/integration/payouts/payouts-list.cy.test.js
- test/cypress/integration/request-to-go-live/index.cy.test.js
- test/cypress/integration/settings/3ds.cy.test.js
- test/cypress/integration/settings/allow-apple-pay.cy.test.js
- test/cypress/integration/settings/allow-google-pay.cy.test.js
- test/cypress/integration/settings/email-notifications.cy.test.js
- test/cypress/integration/settings/merchant-details.cy.test.js
- test/cypress/integration/settings/payment-types.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/cypress/integration/transactions/transaction-details.cy.test.js
- test/cypress/integration/transactions/transaction-list-pagination.cy.test.js
- test/cypress/integration/transactions/transaction-search.cy.test.js
- test/cypress/integration/user/edit-phone-number.cy.test.js
- test/cypress/integration/user/login.cy.test.js
- test/cypress/utils/request-to-go-live-utils.js
- test/cypress/utils/user-stubs.js
- Uses `getUserSuccess` stub from users-stub for all cypress tests
> PP-6828 Use common getUserSuccess stub

- test/cypress/integration/dashboard/dashboard-go-live-link.cy.test.js
- test/cypress/integration/dashboard/dashboard-links.cy.test.js
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
- test/cypress/integration/my-services/add-new-service.cy.test.js
- test/cypress/integration/my-services/my-services-links.cy.test.js
- test/cypress/integration/my-services/update-service-name.cy.test.js
- test/cypress/integration/partnerapp/handle-redirect-from-gocardless.cy.test.js
- test/cypress/integration/partnerapp/handle-redirect-to-gocardless.cy.test.js
- test/cypress/integration/payment-links/create-payment-link.cy.test.js
- test/cypress/integration/payment-links/delete-payment-links.cy.test.js
- test/cypress/integration/payment-links/edit-payment-link.cy.test.js
- test/cypress/integration/payment-links/manage-payment-links.cy.test.js
- test/cypress/integration/stripe-setup/bank-details.cy.test.js
- test/cypress/integration/stripe-setup/company-number.cy.test.js
- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- test/cypress/utils/common-stubs.js
- test/cypress/utils/user-stubs.js
- Moves user stubs out of common-stubs.js
> PP-6828 Refactor User stubs

- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- merge appropriate validation test into one: long text for address line 2 and invalid birth date
> PP-6864 merge responsible person validation tests

- test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
- test/cypress/integration/manage-team-members/manage-team-members.cy.test.js
- test/cypress/integration/my-services/add-new-service.cy.test.js
- test/cypress/integration/my-services/update-service-name.cy.test.js
- test/cypress/integration/request-to-go-live/agreement.cy.test.js
- test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
- test/cypress/integration/request-to-go-live/organisation-name.cy.test.js
- test/cypress/integration/settings/3ds.cy.test.js
- test/cypress/integration/settings/payment-types.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/cypress/integration/transactions/transaction-search.cy.test.js
- test/cypress/utils/gateway-account-stubs.js
- test/cypress/utils/go-live-request-stubs.js
- test/cypress/utils/invite-stubs.js
- test/cypress/utils/request-to-go-live-utils.js
- test/cypress/utils/service-stubs.js
- test/cypress/utils/user-stubs.js
- Refactor service stubs and user stubs further
> PP-6828 Refactor service stubs

- test/cypress/integration/transactions/transaction-details.cy.test.js
- test/cypress/integration/transactions/transaction-list-pagination.cy.test.js
- test/cypress/integration/transactions/transaction-search.cy.test.js
- test/cypress/utils/transaction-stubs.js
- Added new transaction stub helper for transaction stubs 
- cypress tests uses stubs helper defined in transaction stub
> PP-6828 Add transaction stub helper

- app/views/request-to-go-live/choose-how-to-process-payments.njk
- app/views/request-to-go-live/index.njk
- test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
Use the latest content for the government banking go live options.
> PP-6834 Government banking go live content

- test/cypress/integration/dashboard/dashboard-links.cy.test.js
- test/cypress/integration/my-services/my-services-links.cy.test.js
- test/cypress/integration/partnerapp/handle-redirect-from-gocardless.cy.test.js
- test/cypress/integration/payment-links/edit-payment-link.cy.test.js
- test/cypress/integration/payment-links/manage-payment-links.cy.test.js
- test/cypress/integration/settings/3ds.cy.test.js
- test/cypress/integration/settings/allow-apple-pay.cy.test.js
- test/cypress/integration/settings/allow-google-pay.cy.test.js
- test/cypress/integration/settings/email-notifications.cy.test.js
- test/cypress/integration/settings/payment-types.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/cypress/integration/stripe-setup/bank-details.cy.test.js
- test/cypress/integration/stripe-setup/company-number.cy.test.js
- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- test/cypress/integration/user/edit-phone-number.cy.test.js
- test/cypress/stubs/gateway-account-stubs.js
- Extracts common stub setup to helper methods locally
> PP-6828 Simplify stubs setup

- app/assets/sass/components/flash.scss
- app/views/dashboard/_stripe-account-setup-banner.njk
- app/views/includes/flash.njk
Reverts alphagov/pay-selfservice#2140
> PP-6950 Revert "PP-6863 Fix flash message on dashboard"

- .secrets.baseline
Add gds-pre-commit config file: `.secrets.baseline`
Please see here for more info: https://github.com/alphagov/gds-pre-commit/blob/master/usage.md
> BAU Add gds-pre-commit config file: .secrets.baseline

- app/views/transactions/display-size.njk
- app/views/transactions/paginator.njk
- test/cypress/integration/transactions/transaction-list-pagination.cy.test.js
- Added missing lastDigitsCardNumber and cardHolderName fields to the forms submitted during navigation and when changing the results size.
> PP-6875 Fix pagination navigation filters

- app/controllers/payment-links/get-edit-amount.controller.js
- app/controllers/payment-links/get-edit-information.controller.js
- app/controllers/payment-links/get-edit-reference.controller.js
- app/controllers/payment-links/get-edit.controller.js
- app/controllers/payment-links/post-edit-amount.controller.js
- app/controllers/payment-links/post-edit-information.controller.js
- app/controllers/payment-links/post-edit-reference.controller.js
- app/controllers/payment-links/post-edit.controller.js
- app/controllers/user/phone-number/post.controller.js
- app/middleware/express-unhandled-error-handler.js
- app/middleware/payment-method-card.js
- app/models/Payment.class.js
- app/utils/metrics.js
- app/utils/roles.js
Some minor mistakes got through because the pre-commit hook to lint
code wasn't working. Run lint on the project and fix these.
> BAU Run linter

- app/controllers/two-factor-auth-controller/get-configure.controller.js
> PP-7002 Fix typo

- test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
> PP-6958 Update Cypress test for Moto Mask inputs - make the checks more specific

- app/utils/filters.js
- app/utils/transaction-view.js
- app/views/transactions/common-hidden-search-fields.njk
- app/views/transactions/display-size.njk
- app/views/transactions/paginator.njk
- Moves hidden search filters to common nunjucks file so pagination changes can be consistent
- Fixes pagination when transactions are filtered by single card brand
> PP-7018 Fix pagination filters

- app/views/self-create-service/register.njk
> PP-7111 DAC Audit - Remove autofocus on email field when registering a new account

- app/views/stripe-setup/vat-number/index.njk
> PP-7098 Add label to heading for Stripe Onboarding > VAT Numbe page > H1

- app/utils/nav-builder.js
- On Settings page, rename the Settings link in the side bar to make it unique.
> PP-7100 DAC Audit - Update duplicate IDs

- app/views/payment-links/amount.njk
- app/views/payment-links/information.njk
- app/views/payment-links/reference.njk
- app/views/payment-links/review.njk
- app/views/payment-links/web-address.njk
- app/views/request-to-go-live/agreement.njk
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- app/views/request-to-go-live/organisation-address.njk
- app/views/request-to-go-live/organisation-name.njk
- Add the H1 text to the page title.
> PP-7099 DAC Audit - Make Page titles unique for the `Request to go live` & `Create payment link` flow

- app/views/services/_service-section.njk
- test/ui/service-switcher.ui.test.js
> PP-7079 DAC Audit - Services page - Add hidden spans to make links clearer for screen readers

- app/assets/sass/application.scss
- app/assets/sass/components/demo-payment.scss
- app/assets/sass/components/my-profile.scss
- app/views/dashboard/demo-payment/index.njk
- app/views/team-members/team-member-profile.njk
- test/ui/team-member-details.ui.test.js
- test/unit/controller/make-a-demo-payment-controller/index.controller.ft.test.js
- Update table in demo payment
- Convert to a DL list
- Update table in `My Profile` page
- Convert into a DL list
- Make the DL list have CSS `display: table` - as this allows us to us the design system table styling.
- Update `change` links to include hidden spans - so they are more descriptive for screen readers
> PP-7095 DAC Audit - Make tables in `DL` list

- app/controllers/register-service.controller.js
- app/controllers/register-user.controller.js
- Move exports to bottom of file
- Use async/await in remaining places
Tip: Set github diff to ignore whitespace changes. Not that much actually changes, just indentation.
> PP-7228 Clean up registration controllers

- app/models/User.class.js
- test/unit/models/User.class.test.js
- add isInternalUser function to User object. This is to help when doing structured logging to filter out internal user from statistical dashboards
> PP-7306 add is internal user

- app/models/User.class.js
- test/unit/models/User.class.test.js
- add numberOfLiveServices to User object. This is needed for structured logging for statistical purposes
> PP-7306 add number of live services to user object

- app/controllers/all-service-transactions/download-transactions.controller.js
- app/controllers/all-service-transactions/get.controller.js
- app/controllers/payouts/payout-list.controller.js
- app/controllers/transactions/transaction-download.controller.js
- app/services/transaction.service.js
- Added logging when all service transactions page is accessed and also flags to indicate if downloads are for all live service transactions and internal user
> PP-7306 Add logging for all live service transactions

- app/views/services/_service-section-small.njk
- app/views/services/_service-section.njk
- app/views/services/_service-switch.njk
- Nunjucks updates
- Remove Direct Debit heading.
- Remove Direct Debit from service link names
> PP-7304 Remove Direct Debit from My Service page > Template updates.

- app/controllers/make-a-demo-payment/go-to-payment.controller.js
* favour async/ await
* name all methods
* clarify naming
> PP-6129 Refactor make a demo payment controller

- app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
- app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
Add controller to enable or disable Worldpay 3DS Flex. Not actually hooked up to a page yet.
> PP-7416 Add controller to enable/disable Worldpay 3DS Flex

- app/views/payment-links/manage.njk
- Update `manage payment links` Nunjucks file
- Update the `Reporting columns` content.
> PP-7299 Manage Payment Links > Update content about Reporting Columns

- app/views/your-psp/_worldpay-flex.njk
_Spun off from https://github.com/alphagov/pay-selfservice/pull/2379 by @stevenjmesser_
> PP-6982 Update 3DS Flex link and add warning

- app/views/includes/flash.njk
- app/views/services/index.njk
- Update Nunjucks template to set page width to 'two thirds'
- Update Flash.njk so that it only add the container when there is a flash message.
> PP-7305 My Services > Fix page width issue.

- app/services/service-registration.service.js
- Move exports to bottom of file
- Name anonymous functions
- Remove function comment blocks that don't add anything
- Use async/await
- Remove unnecessary Promise creation
- Inline single line functions that are used internally in one place
Hiding whitespace changes will help review
> PP-7458 Refactor service-registration.service.js

- app/views/api-keys/create.njk
- add extra content explaining to copy the full of the new format API key.
> PP-7512 add content to create api key page

- app/services/clients/public-auth.client.js
- Publicauth client: replaces usage of old base client (old-base.client.js) with new client (base.client.js) which provides better interface with sensible defaults
> PP-7585 Publicauth client: use new baseclient

- app/views/your-psp/_worldpay.njk
Recreate #2441, which was created on a fork
> Add govuk-link class to <a> element

- app/controllers/credentials.controller.js
- app/services/clients/connector.client.js
- Connector client : updated number of client methods to use new baseclient (base.client.js) which provides better interface.
- Also updated credentials controller to use async/await as it relies on old baseclient way of working (passing callback function to old baseclient)
> PP-7585 Connector client: use new baseclient

- app/controllers/all-service-transactions/get.controller.js
- app/controllers/credentials.controller.js
- app/controllers/payment-types/get-index.controller.js
- app/controllers/transactions/transaction-list.controller.js
- app/services/clients/connector.client.js
- test/integration/transaction-list.ft.test.js
- test/unit/clients/connector-client/connector-get-card-types.pact.test.js
- Connector client: Updated more methods to use new base client
> PP-7585 Connector client: switch more methods to use new baseclient

- test/cypress/integration/manage-team-members/edit-permissions.cy.test.js
- test/cypress/integration/manage-team-members/manage-team-members.cy.test.js
- test/cypress/plugins/stubs.js
- test/cypress/stubs/user-stubs.js
Move user stubs out of `stubs.js` and construct them directly in the
`user-stubs` helper file.
> PP-7588 Move user stubs

- app/controllers/payment-types/get-index.controller.js
- app/controllers/payment-types/post-index.controller.js
- test/integration/payment-types/payment-types.it.test.js
- Added missing tests for payment types (get/update) scenarios
> PP-7585 Add integration tests for payment types

- app/controllers/payment-links/get-delete.controller.js
- app/controllers/payment-links/get-disable.controller.js
- app/controllers/payment-links/get-manage.controller.js
- app/controllers/payment-links/post-edit.controller.js
- Replaces promise code to use asnyc/await syntax which makes the code easier to follow.
> PP-7595 Switch payment links controllers to use asnyc/await

- app/views/merchant-details/edit-merchant-details.njk
- Update `edit-merchant-details.njk`
- Change `name` to `organisation name` and make into a header label.
- Make phone number into a header label.
- General updates to clean up HTML.
> PP-6919 My Service > Organisation Details - clean up page

- app/controllers/api-keys/post-revoke.controller.js
- app/controllers/payment-links/get-manage.controller.js
- app/controllers/request-to-go-live/agreement/post.controller.js
- app/controllers/service-roles-update.controller.js
- app/controllers/test-with-your-users/submit.controller.js
- app/controllers/two-factor-auth-controller/post-index.controller.js
- Replaces promise code to use asnyc/await syntax which makes the code easier to follow.
> PP-7595 Switch more promises to use asnyc/await

- app/routes.js
- test/integration/payment-types/payment-types.it.test.js
- Add the CSRF middleware function 'validateAndRefreshCsrf' to the account router.
> PP-7583 Url Structure > Add CSRF middleware to account router

- .secrets.baseline
- app/paths.js
- app/routes.js
- app/utils/nav-builder.js
- app/views/email-notifications/collection-email-mode.njk
- app/views/email-notifications/confirm.njk
- app/views/email-notifications/confirmation-email-toggle.njk
- app/views/email-notifications/edit.njk
- app/views/email-notifications/index.njk
- app/views/email-notifications/off-confirm.njk
- app/views/email-notifications/refund-email-toggle.njk
- app/views/settings/index.njk
- test/cypress/integration/settings/email-notifications.cy.test.js
Change email notifications routes to use the new account URL structure.
> PP-7583 Move email notifications routes

- .secrets.baseline
- app/controllers/toggle-moto-mask-card-number/toggleMotoMaskCardNumber.post.controller.js
- app/controllers/toggle-moto-mask-security-code/maskSecurityCode.post.controller.js
- app/paths.js
- app/routes.js
- app/utils/nav-builder.js
- app/views/settings/index.njk
- test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
Move these routes to use the new account URL structure.
> PP-7583 Move mask card details settings routes

- .secrets.baseline
- app/controllers/email-notifications/email-notifications.controller.js
- app/paths.js
- app/routes.js
- app/utils/display-converter.js
- app/utils/nav-builder.js
- app/views/billing-address/index.njk
- app/views/digital-wallet/apple-pay.njk
- app/views/digital-wallet/google-pay.njk
- app/views/email-notifications/collection-email-mode.njk
- app/views/email-notifications/confirmation-email-toggle.njk
- app/views/email-notifications/refund-email-toggle.njk
- app/views/toggle-3ds/index.njk
- app/views/toggle-moto-mask-card-number/index.njk
- app/views/toggle-moto-mask-security-code/index.njk
- test/cypress/integration/settings/3ds.cy.test.js
- test/cypress/integration/settings/allow-apple-pay.cy.test.js
- test/cypress/integration/settings/allow-google-pay.cy.test.js
- test/cypress/integration/settings/email-notifications.cy.test.js
- test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/test-helpers/html-assertions.js
- test/ui/toggle-collect-billing-address.ui.test.js
Update the settings route to use the new account URL structure.
> PP-7583 Move settings route

- .secrets.baseline
- app/controllers/email-notifications/email-notifications.controller.js
- app/paths.js
- app/routes.js
- app/utils/display-converter.js
- app/utils/nav-builder.js
- app/views/billing-address/index.njk
- app/views/digital-wallet/apple-pay.njk
- app/views/digital-wallet/google-pay.njk
- app/views/email-notifications/collection-email-mode.njk
- app/views/email-notifications/confirmation-email-toggle.njk
- app/views/email-notifications/refund-email-toggle.njk
- app/views/toggle-3ds/index.njk
- app/views/toggle-moto-mask-card-number/index.njk
- app/views/toggle-moto-mask-security-code/index.njk
- test/cypress/integration/settings/3ds.cy.test.js
- test/cypress/integration/settings/allow-apple-pay.cy.test.js
- test/cypress/integration/settings/allow-google-pay.cy.test.js
- test/cypress/integration/settings/email-notifications.cy.test.js
- test/cypress/integration/settings/mask-moto-card-number-and-security-code.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/test-helpers/html-assertions.js
- test/ui/toggle-collect-billing-address.ui.test.js
This reverts commit 260de53f34327c71c300a685ea0f5119bbbf1cca.
Want to temporarily revert so we can make another change first to allow safe deployment of the URL upgrade.
> Revert "PP-7583 Move settings route"

- app/routes.js
Group routes by the level they are at, and do some general tidying.
Remove unnecessary middleware:
`getAccount` and `permission` from all services transactions routes
- these should not be called as this route is accessed when the user is not within a service.
`getAccount` from feedback route
- we use `resolveService` on this route to send the service id in the feedback, but don't need `getAccount`.
> PP-7683 Tidy up routes file

- .secrets.baseline
- app/controllers/credentials.controller.js
- app/controllers/your-psp/post-flex.controller.js
- app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.js
- app/controllers/your-psp/post-toggle-worldpay-3ds-flex.controller.test.js
- app/paths.js
- app/routes.js
- app/utils/nav-builder.js
- app/views/credentials/worldpay.njk
- app/views/your-psp/_worldpay-flex.njk
- app/views/your-psp/flex.njk
- test/cypress/integration/settings/your-psp.cy.test.js
- test/integration/credentials.ft.test.js
Update your psp routes to use the new account URL structure.
> PP-7583 Move your psp routes

- .secrets.baseline
- app/controllers/credentials.controller.js
- app/paths.js
- app/routes.js
- app/utils/nav-builder.js
- app/views/credentials/epdq.njk
- app/views/credentials/smartpay.njk
- app/views/credentials/worldpay.njk
- app/views/your-psp/_epdq.njk
- app/views/your-psp/_smartpay.njk
- app/views/your-psp/_worldpay.njk
- test/cypress/integration/settings/your-psp.cy.test.js
- test/integration/credentials.ft.test.js
- test/ui/credentials.ui.test.js
This reverts commit c913abe1fdf25c926f7a5a2b3406e6038b93d4f0.
Broke end-to-end tests 😢
> Revert "PP-7583 Update credentials routes"

- app/views/services/index.njk
> PP-7532 Make add new service a button

- app/views/dashboard/_stripe-account-setup-banner.njk
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
- Change 'Stripe have ...' to 'Stripe has ...'
> BAU Update Stripe onboarding typos

- app/controllers/dashboard/index.js
- app/controllers/dashboard/redirect-to-dashboard.controller.js
- app/controllers/root/index.controller.js
- app/routes.js
- test/integration/login.controller.test.js
- test/unit/controller/root/index.controller.test.js
- Added new root (for path `/`) controller which redirects users to account dashboard when `ENABLE_MY_SERVICES_AS_DEFAULT_VIEW` flag is not enabled and to My service page when the flag is enabled
> PP-7531 Add root controller

- app/controllers/my-services/get-index.controller.js
Check if the current date is after the date specified by the `MY_SERVICES_DEFAULT_NOTIFICATION_END_DATE` environment variable, which is expected to be a unix timestamp. If it is, do not display the notification.
If the environment variable is not set, show the notification if the other conditions are met.
Skipping adding tests for this as we expect the banner to be very short lived.
> PP-7701 Don't show notification after specified date

- app/assets/js/components/notification-banner.js
- Update `click` handler, so it only closes the banner
when you click the `Hide button`
> PP-7701 Fix bug - My Services > Notification banner

- app/assets/js/components/notification-banner.js
- Update the analytics call when the `hide message` button is called
- Update to use `ga` rather then the older `_gaq`
> PP-7701 My Services Default page > Notificatons banner - fix analytics bug

- app/assets/js/components/notification-banner.js
- app/views/services/index.njk
- test/cypress/integration/my-services/my-services-notification-banner.cy.test.js
- Update the button text on the `My Services > Notification banner` to 'hide this message'
> PP-7701 My Services Notification banner - fix button text

- test/fixtures/user.fixtures.js
- add the new permission to the existing pact test
> PP-7765 add psp test account stage update permission to pact test

- test/fixtures/user.fixtures.js
> PP-7765 correct underscore to hyphen in permission's name

- app/controllers/request-psp-test-account/get.controller.js
- app/controllers/request-psp-test-account/index.js
- app/paths.js
- app/routes.js
- app/utils/display-converter.js
- app/views/request-psp-test-account/index.njk
- test/cypress/integration/request-psp-test-account/index.cy.test.js
- test/fixtures/user.fixtures.js
- Added new controller (GET) to request Stripe test account and relevant tests
with @iqbalgds
> PP-7740 Add request Stripe test account page

- app/controllers/request-psp-test-account/index.js
- app/controllers/request-psp-test-account/post.controller.js
- app/paths.js
- app/routes.js
- app/services/clients/adminusers.client.js
- app/views/request-psp-test-account/index.njk
- test/cypress/integration/request-psp-test-account/index.cy.test.js
- test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.test.js
- test/cypress/stubs/service-stubs.js
- test/cypress/stubs/user-stubs.js
- test/fixtures/service.fixtures.js
- Added controller (POST) to submit request for Stripe test account and relevant test.
> PP-7756 Submit request for Stripe test account

- test/unit/clients/adminusers-client/service/update-psp-test-account-stage.pact.test.js
- Added pact test for PATCH request (field current_psp_test_account_stage)
> PP-7756 Add pact test for psp test account stage

- app/views/dashboard/_links.njk
- app/views/request-psp-test-account/index.njk
- test/cypress/integration/request-psp-test-account/index.cy.test.js
- test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.test.js
- Update content (current) for Stripe test account pages.
> PP-7766 Update content for Stripe test account pages

- app/views/404.njk
- app/views/dashboard/_links.njk
- app/views/error.njk
- app/views/request-psp-test-account/index.njk
- app/views/services/index.njk
- app/views/transactions/list.njk
- test/cypress/integration/errors/errors.cy.test.js
- test/cypress/integration/my-services/my-services-links.cy.test.js
- test/cypress/integration/payment-links/manage-payment-links.cy.test.js
- test/cypress/integration/request-psp-test-account/index.cy.test.js
- test/cypress/integration/request-psp-test-account/submit-request-for-psp-test-account.cy.test.js
- test/cypress/integration/request-to-go-live/agreement.cy.test.js
- test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.test.js
- test/cypress/integration/request-to-go-live/index.cy.test.js
- test/cypress/integration/request-to-go-live/organisation-address.cy.test.js
- test/cypress/integration/request-to-go-live/organisation-name.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/cypress/integration/stripe-setup/bank-details.cy.test.js
- test/cypress/integration/stripe-setup/company-number.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- test/integration/error-handler.ft.test.js
- test/ui/transaction-search.ui.test.js
- Updated content for Stripe test account pages and error pages
> PP-7766 Content changes for Stripe test account and error pages

- app/controllers/request-psp-test-account/post.controller.js
- app/views/payouts/list.njk
- app/views/request-psp-test-account/index.njk
- Updated payout page content (to latest) for test transactions
- Also fixes setting service created date when Stripe test account request is submitted.
> PP-7766 Update payout page content

- app/views/api-keys/create.njk
- app/views/api-keys/index.njk
- Add new content to API keys index page.
- Add `API security` text to `create API flow`
> PP-7484 API Keys - Add API security text.

- app/controllers/payment-links/metadata/metadata-form.js
- package-lock.json
- package.json
- Update pay-js-commons to 3.0.5
- Update metadata-form.js to use new constants from pay-js-commons
> BAU Bump pay-js-commons and update metadata-form.js

- app/views/payouts/list.njk
The default behaviour is described in this content but the customised
production platform has a hidden flag to expedite this. Update content
to match what users will experience.
> PP-7835 Update payout description text for test Stripe accounts

- app/controllers/all-service-transactions/download-transactions.controller.js
- app/controllers/transactions/transaction-download.controller.js
- app/services/transaction.service.js
- Added is_live field to CSV download logs which indicates if the download is for live account(s) or test accounts.
> PP-7835 Add is_live field to CSV download log

- app/controllers/credentials.controller.js
- app/controllers/credentials.controller.test.js
- app/controllers/dashboard/dashboard-activity.controller.js
- test/cypress/integration/all-service-transactions/all-service-transactions.cy.test.js
- test/cypress/integration/payment-links/create-payment-link.cy.test.js
- test/cypress/integration/request-psp-test-account/index.cy.test.js
- test/cypress/stubs/products-stubs.js
- test/cypress/stubs/transaction-stubs.js
- test/fixtures/ledger-transaction.fixtures.js
- test/integration/service-users.ft.test.js
- test/ui/invite-user.ui.test.js
- test/ui/service-role-update.ui.test.js
- test/ui/team-member-list.ui.test.js
- test/unit/clients/products-client/product/get-by-gateway-account-id-and-type-with-metadata.pact.test.js
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
As we did for the other gateway credentials, trim Smartpay notification
credentials before sending them to connector.
> PP-4339 Trim notification credentials

- app/controllers/transactions/transaction-list.controller.js
- app/views/transactions/filter.njk
- Update controller - to pass down 'isExperimentalFeaturesEnabled' to view.
- Add 'Advance filters' toggle.
- Only show this if the service has 'isExperimentalFeaturesEnabled' = true.
- The toggle contains the metadata inbox filter.
> PP-7859 Metadata Transactions filter - add UI elements

- app/views/includes/header.njk
- add "features" link to top navigation bar
> PP-7725 add "Features" to top navigation bar

- test/integration/login.controller.test.js
- test/test.env
- Update the test.env - make the flag true.
- Update the single failing test.
> PP-7702 Update tests when 'ENABLE_MY_SERVICES_AS_DEFAULT_VIEW=true'

- app/views/includes/footer-categories.njk
> PP-7923 Remove performance platform link

- app/views/api-keys/index.njk
- app/views/api-keys/revoked-keys.njk
> PP-7893 Reword links on API key pages

- app/middleware/permission.js
> PP-7735 Remove redundant comment

- app/controllers/register-service.controller.js
- test/integration/self-registration/self-registration-service-naming.ft.test.js
Reference ticket for requirements.
> ...keep the experience for brand new sign ups to Pay to go back to the account dashboard in favour of the my services list (login behaviour)
> PP-7966 Redirect to dashboard on user registration

- app/views/includes/footer-categories.njk
Add link to product page for performance data.
> PP-7931 Add link to performance page

- app/assets/csv/sample_reporting_payout.csv
- app/views/payouts/list.njk
Description:
- Fixes broken CSV link
- Modifies .csv to have readable data
- Minor spelling correction
> PP-8003 - Fix sample reporting csv broken link

- app/views/request-psp-test-account/index.njk
We say on the page before that we can do it in 1 working day, so update that on the test account requested page too.
> PP-8003 Update test account requested content

- package-lock.json
- Fixes production dependencies for security vulnerabilities
> PP-7905 npm audit fix - production dependencies only

- .github/workflows/run-tests.yml
- add new action to run unit tests by github actions
> PP-8048 add action to run unit tests

- .github/workflows/run-tests.yml
- Updated setup-node action to latest version actions/setup-node@v2
- and updated action to use current node version 12.22.1 used for docker image
> PP-8083 Bump setup-node action from v1 to v2

- .github/workflows/run-tests.yml
- Actions : Added govuk_modules to cached folders list
- Corrected actions/setup-node version
> PP-8083 Add govuk_modules to actions cache

- app/controllers/credentials/credentials-form.js
- app/controllers/credentials/credentials-form.test.js
- test/fixtures/worldpay-credentials.fixtures.js
- test/unit/clients/connector-client/connector-post-worldpay-check-credentials.pact.test.js
- add consumer pact for credentials checking
- adjust key alias to work with merchant id HTML ID restrictions in end
to end tests
> PP-8131 Pact tests for Worldpay credentials validation

- app/errors.js
- app/utils/credentials.js
- app/utils/credentials.test.js
- test/fixtures/gateway-account.fixtures.js
- adds fixtures for `provider_switch_enabled` and
`gateway_account_credentials` account properties
- add simplest case utility to make use of the new credentials
> PP-8213 Add gateway account credentials fixtures and util (bump-ci)

- test/cypress/integration/settings/switch-psp.cy.test.js
Add Cypress tests to check the task list is displayed properly with correct tags etc. and to test the journey for completing the first step.
> PP-8216 Add Cypress tests for task list

- test/fixtures/gateway-account.fixtures.js
- test/unit/clients/connector-client/connector-patch-gateway-account-credential-state.pact.test.js
- test/unit/clients/connector-client/connector-patch-gateway-account-merchant-id.pact.test.js
- add a pact test to patch Google Pay gateway merchant id
- add a pact test to patch gateway credential state
> PP-8277 add patch gateway merchant id and patch state pact test

- test/fixtures/gateway-account.fixtures.js
- test/unit/clients/connector-client/connector-post-switch-payment-provider.pact.test.js
- add new pact test for switching payment provider (psp)
> PP-8277 add post switch payment provider pact test

- test/fixtures/charge.fixtures.js
- test/unit/clients/connector-client/connector-post-create-charge.pact.test.js
- add new pact test for creating a charge
> PP-8277 add post create charge pact test

- app/utils/validation/server-side-form-validations.js
- change code to create a new master sha release
> BAU create a dummy new master release

- test/fixtures/charge.fixtures.js
- test/unit/clients/connector-client/connector-get-charge.pact.test.js
- add new pact test, get charge from connector
> PP-8277 add get single charge pact test

- app/controllers/my-services/get-index.controller.js
- app/models/GatewayAccount.class.js
- app/models/User.class.js
- app/utils/display-converter.js
- app/views/dashboard/_switching-psp-banner.njk
- app/views/includes/phase-banner.njk
- app/views/services/_service-switch.njk
- test/cypress/integration/settings/switch-psp.cy.test.js
- test/unit/models/User.class.test.js
- Updated dashboard banner & labels to latest content
- Banner and switch PSP labels are only available to admin users of service
> PP-8214 Switch PSP - update dashboard banner and labels

- app/controllers/your-psp/get.controller.js
- app/utils/credentials.js
- app/utils/credentials.test.js
- app/views/your-psp/index.njk
- package-lock.json
- package.json
- test/cypress/integration/settings/switch-psp.cy.test.js
Add inset text on the "Your PSP" page to indicate:
- When switch is in progress
- On the "Old PSP" page after switch, when the provider switched
- On the "Your PSP" page after switch, when the current provider became active
Display dates in the format "7 July 2021".
> PP-8219 Add psp switch status inset text

- app/controllers/switch-psp/verify-psp-integration.controller.js
- app/services/clients/connector.client.js
- test/fixtures/gateway-account.fixtures.js
- test/unit/clients/connector-client/connector-patch-gateway-account-credential-state.pact.test.js
- Patches `last_updated_by_user_external_id` when patching credentials state (to VERIFIED_WITH_LIVE_PAYMENT)
> PP-8298 Patch user_external_id when patching credentials state

- app/services/clients/connector.client.js
> PP-8273 Remove unused client method

- app/controllers/switch-psp/switch-psp.controller.js
- app/utils/nav-builder.js
- app/views/switch-psp/switch-psp.njk
- app/views/switch-psp/verify-psp-integration-payment.njk
- test/cypress/integration/settings/switch-psp.cy.test.js
- Update content to finalised version
- Move "Switch PSP" item in settings nav below "Your PSP"
> PP-8272 Update PSP switch content

- test/cypress/integration/settings/switch-psp.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- test/fixtures/gateway-account.fixtures.js
Depends on https://github.com/alphagov/pay-selfservice/pull/2842
Add Cypress coverage on happy path, ensure pages show appropriately for go live and switching context.
> PP-8218 Cypress coverage for switch to Stripe task list

- app/views/your-psp/_smartpay.njk
This tech docs page is being removed, so remove link to it.
> PP-8371 Remove link to documentation for Smartpay

- test/unit/clients/connector-client/connector-get-gateway-account-by-external-id.pact.test.js
- remove top level credentials from selfservice pact tests
> PP-8138 remove top level credentials from selfservice pact tests

- .github/workflows/run-tests.yml
> PP-8224 Pin github action versions

- .github/dependabot.yml
> PP-8224 Add github actions to dependabot file

- .github/dependabot.yml
- package-lock.json
- package.json
- Bumps stripe module to latest version 
- Change log https://github.com/stripe/stripe-node/compare/v8.167.0...v8.174.0
> PP-8555 Bump stripe version from 8.167.0 to 8.174.0

- package-lock.json
- package.json
Reverts alphagov/pay-selfservice#2934
> Revert "Bump @sentry/node from 6.12.0 to 6.13.2"

- app/controllers/your-psp/kyc-tasks.service.js
- app/controllers/your-psp/kyc-tasks.service.test.js
- Added a new service to calculate the status of the tasks required for additional kyc data.
> PP-8801 Add KYC tasks service

- app/controllers/your-psp/get.controller.js
- app/paths.js
- app/views/your-psp/_stripe.njk
- app/views/your-psp/index.njk
- test/cypress/integration/dashboard/dashboard-kyc-add-details.cy.test.js
- test/cypress/integration/settings/your-psp.cy.test.js
- test/unit/controller/settings/your-psp.ft.test.js
- Add new tasks list to Your PSP - Stripe page
Won't list tasks
> PP-8801 Add tasks for Stripe KYC

- test/fixtures/stripe-account-setup.fixtures.js
- test/unit/clients/connector-client/connector-set-stripe-account-setup-flag.pact.test.js
- Added a pact test for stripe director task
> PP-8804 Add pact test for director task

- app/services/clients/stripe/StripePerson.class.js
- app/services/clients/stripe/StripePerson.class.test.js
Add phone and email as optional fields to the Stripe responsible person schema so we send them to Stripe if we have collected them
> PP-8831 Add new fields to responsible person schema

- app/controllers/stripe-setup/director/get.controller.js
- app/controllers/stripe-setup/director/get.controller.test.js
- app/controllers/stripe-setup/director/index.js
- app/models/StripeAccountSetup.class.js
- app/paths.js
- app/routes.js
- app/utils/credentials.js
- app/utils/credentials.test.js
- app/utils/nav-builder.js
- app/views/stripe-setup/director/index.njk
- app/views/your-psp/_stripe.njk
- test/cypress/integration/stripe-setup/director.cy.test.js
- test/cypress/stubs/stripe-account-setup-stub.js
- test/fixtures/stripe-account-setup.fixtures.js
- test/fixtures/user.fixtures.js
- Added new controller (GET) for director page
- Unit and cypress test for new page
- Updated routes, paths and navigation for director page
> PP-8804 Stripe setup: Add controller for director

- app/controllers/stripe-setup/director/index.js
- app/controllers/stripe-setup/director/post.controller.js
- app/controllers/stripe-setup/director/post.controller.test.js
- app/routes.js
- app/services/clients/stripe/StripeCompany.class.js
- app/services/clients/stripe/StripeCompany.class.test.js
- app/views/stripe-setup/director/index.njk
- Updated director controller for POST
- POST is context aware (i.e., new services onboarding, kyc, switch PSP)
- Will raise separate PR for cypress tests
> PP-8804 Stripe setup - Update director controller for POST

- app/controllers/stripe-setup/director/post.controller.js
- test/cypress/integration/stripe-setup/director.cy.test.js
- test/cypress/stubs/stripe-psp-stubs.js
- test/fixtures/stripe-psp.fixtures.js
- Added cypress tests for Stripe director page
> PP-8804 Add cypress tests (for POST method) for Stripe director page

- app/controllers/stripe-setup/bank-details/post.controller.js
- app/controllers/stripe-setup/bank-details/post.controller.test.js
- app/controllers/stripe-setup/company-number/post.controller.js
- app/controllers/stripe-setup/company-number/post.controller.test.js
- app/controllers/stripe-setup/director/post.controller.js
- app/controllers/stripe-setup/director/post.controller.test.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/controllers/stripe-setup/responsible-person/post.controller.test.js
- app/controllers/stripe-setup/vat-number/post.controller.js
- app/controllers/stripe-setup/vat-number/post.controller.test.js
- Updated all stripe setup controllers (POST method) to use utility methods to get Stripe connect account ID and some validation.
> PP-8804 Stripe setup: Use utility methods

- app/controllers/request-to-go-live/organisation-address/get.controller.js
- app/controllers/request-to-go-live/organisation-address/post.controller.js
- app/controllers/request-to-go-live/organisation-address/post.controller.test.js
- app/controllers/stripe-setup/responsible-person/get.controller.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/models/ServiceUpdateRequest.class.js
- app/views/request-to-go-live/organisation-address.njk
- test/cypress/integration/request-to-go-live/organisation-address.cy.test.js
- test/fixtures/service.fixtures.js
- test/test.env
If the COLLECT_ADDITIONAL_KYC_DATA is enabled, collect the URL on the
organisation address page of the request to go live flow.
> PP-8830 Collect URL on organisation details page

- app/views/stripe-setup/director/index.njk
- test/cypress/integration/stripe-setup/director.cy.test.js
- Updated director page content to the latest
Refer to PP-8902 for latest content
> PP-8804 Update director page content

- app/controllers/stripe-setup/add-psp-account-details/get.controller.js
- app/controllers/stripe-setup/add-psp-account-details/get.controller.test.js
- Include director task after responsible person info
- Only applicable if COLLECT_ADDITIONAL_KYC_DATA env variable is true
> PP-8833 include director task in Stripe setup

- test/unit/clients/adminusers-client/service/update-service.pact.test.js
Update the PATCH service update patch request to include updating the
merchant_details URL.
> PP-8830 Update pact test to include URL

- app/controllers/kyc/index.js
- app/controllers/kyc/organisation-url.controller.js
- app/routes.js
- app/views/kyc/organisation-url.njk
- Add new route for Org URL page
- Add new Nunjucks file
- Update content
> PP-8802 - Add KYC Organisation URL feature

- app/controllers/dashboard/dashboard-activity.controller.js
- app/views/dashboard/_stripe-account-setup-banner.njk
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- add director task to banner
- only display additional task if COLLECT_ADDITIONAL_KYC_DATA is true
> PP-8833 add director task to Stripe onboarding banner

- app/views/stripe-setup/director/index.njk
- Fix styling for Work email address label on director page
> PP-8866 Fix director page styling

- app/assets/sass/components/request-to-go-live.scss
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/views/dashboard/_additional_kyc_info_banner.njk
- app/views/dashboard/_live-account-requested-banner.njk
- app/views/dashboard/_stripe-account-setup-banner.njk
- app/views/kyc/organisation-url.njk
- app/views/request-to-go-live/agreement.njk
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- app/views/request-to-go-live/index.njk
- app/views/request-to-go-live/organisation-address.njk
- app/views/request-to-go-live/organisation-name.njk
- app/views/stripe-setup/bank-details/index.njk
- app/views/stripe-setup/company-number/index.njk
- app/views/stripe-setup/go-live-complete.njk
- app/views/stripe-setup/responsible-person/index.njk
- app/views/stripe-setup/vat-number/index.njk
- app/views/your-psp/_stripe.njk
- test/cypress/integration/dashboard/dashboard-kyc-add-details.cy.test.js
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
- test/cypress/integration/request-to-go-live/agreement.cy.test.js
- test/cypress/integration/request-to-go-live/index.cy.test.js
- test/cypress/integration/request-to-go-live/organisation-name.cy.test.js
- test/cypress/integration/stripe-setup/bank-details.cy.test.js
- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- test/ui/responsible-persion.ui.test.js
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
- update pages with content finalised in [KYC signed-off content](https://docs.google.com/document/d/1-_ohNR4DjT26alRaIAdu2cR5Rqq9TEbhGYJEkoFlQkA)
- update Cypress tests
> PP-8902 add final content for KYC implementation

- app/views/dashboard/_stripe-account-setup-banner.njk
- app/views/stripe-setup/director/index.njk
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
- Remove redundant director task from the banner
- Change ordering of error message on director page
> PP-8866 Minor KYC content fixes

- app/views/request-to-go-live/index.njk
- app/views/stripe-setup/company-number/index.njk
- app/views/stripe-setup/vat-number/index.njk
- These changes are some things that we missed in the first round and/or later additions.
> PP-8902 some correcting changes

- app/views/dashboard/_live-account-requested-banner.njk
- app/views/dashboard/_stripe-account-setup-banner.njk
- app/views/stripe-setup/company-number/index.njk
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.test.js
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
- update banners with new design system banners
**Stripe account:**
**Live account requested:**
> PP-8902 ensure design system banners are used

- app/views/dashboard/_stripe-account-setup-banner.njk
- test/unit/controller/dashboard/dashboard-activity.controller.ft.test.js
- fix rendering of Stripe restricted account banner
> PP-8902 fix restricted account banner

- app/views/kyc/organisation-url.njk
- app/views/stripe-setup/company-number/index.njk
- app/views/stripe-setup/responsible-person/index.njk
- app/views/stripe-setup/responsible-person/kyc-additional-information.njk
- app/views/stripe-setup/vat-number/index.njk
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
- test/cypress/integration/stripe-setup/company-number.cy.test.js
- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
Small fixes to:
- change the title of the responsible person page to match the signed
off content
- remove the addition h1 on the VAT number and company number pages
- fix the case of a submit button
> PP-8902 Small content fixes

- app/views/your-psp/_stripe.njk
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
- update Stripe task list content
> PP-8902 update content of task list

- app/controllers/request-to-go-live/agreement/get.controller.js
- app/controllers/request-to-go-live/agreement/post.controller.js
- app/controllers/request-to-go-live/organisation-address/post.controller.js
- app/controllers/stripe-setup/director/post.controller.js
- app/controllers/stripe-setup/responsible-person/get.controller.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/views/request-to-go-live/agreement.njk
- test/cypress/integration/request-to-go-live/agreement.cy.test.js
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
Use the error summary component and display an inline error message.
> PP-8928 Improve error message on agreement page

- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
- test/cypress/stubs/stripe-psp-stubs.js
- Update the `Your PSP - Stripe > KYC` Cypress test to include tests to test
the Org URL page.
> PP-8802 Org URL page - add Cypress test.

- app/models/GatewayAccount.class.js
- app/views/includes/phase-banner.njk
- app/views/services/_service-switch.njk
- test/cypress/integration/my-services/my-services-links.cy.test.js
- test/cypress/stubs/gateway-account-stubs.js
- test/fixtures/gateway-account.fixtures.js
- Add LIVE INFORMATION NEEDED tag for services that require additional KYC data
Services page:
Breadcrumbs:
> PP-8926 add information needed tag

- app/controllers/switch-psp/switch-psp.controller.js
- app/controllers/switch-psp/switch-tasks.service.js
- app/controllers/switch-psp/switch-tasks.service.test.js
- app/paths.js
- app/routes.js
- app/views/kyc/organisation-url.njk
- app/views/switch-psp/switch-psp.njk
- test/cypress/integration/settings/switch-psp.cy.test.js
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
- test/cypress/integration/switch-psp/organisation-url.cy.test.js
- Added organisation URL task to switch PSP tasks
- Moved organisation url validation cypress test (from kyc specific tests as there are short lived) to organisation-url cypress test
> PP-8835 Switch PSP - Add organisation URL task

- app/controllers/stripe-setup/responsible-person/post-additional-details.controller.js
- app/controllers/stripe-setup/responsible-person/post-additional-details.controller.test.js
When adding the functionality to enable the new Stripe account capabilities and setting the flag that KYC was complete for the gateway account, the page where the user adds just the email and telephone to the responsible person was missed.
When this page is submitted, check whether the KYC task list is now complete, and if so call the function to do complete the KYC process and show a success banner notifying the user that KYC is complete.
> PP-8861 Complete KYC if responsible person is last task

- app/controllers/stripe-setup/government-entity-document/get.controller.js
- app/controllers/stripe-setup/government-entity-document/get.controller.test.js
- app/controllers/stripe-setup/government-entity-document/index.js
- app/models/StripeAccountSetup.class.js
- app/paths.js
- app/routes.js
- app/views/stripe-setup/government-entity-document/index.njk
- test/cypress/integration/stripe-setup/government-entity-document.cy.test.js
- test/cypress/stubs/stripe-account-setup-stub.js
- test/fixtures/stripe-account-setup.fixtures.js
- test/fixtures/user.fixtures.js
- test/unit/clients/connector-client/connector-set-stripe-account-setup-flag.pact.test.js
- Added get controller for new Stripe onboarding task (Proof of Government Entity document)
- Also added a pact test for equivalent stripe setup task in connector
> PP-8962 Add get controller for government entity document task

- app/services/clients/stripe/StripeAccount.class.js
- app/services/clients/stripe/StripeAccount.class.test.js
- app/services/clients/stripe/stripe.client.js
- package-lock.json
- package.json
- Installed `multer` package which is a expressjs middleware for handling multipart/form-data (to upload file for Stripe task - Proof of Government entity document).
- Added stripe client method to create file for government entity verification on Stripe
- Updated StripeAccount class for the payload required to attach verification document to stripe account.
> PP-8962 Install multer dependency and add Stripe client methods for file upload

- app/controllers/stripe-setup/add-psp-account-details/get.controller.js
- app/controllers/stripe-setup/add-psp-account-details/get.controller.test.js
- app/views/dashboard/_stripe-account-setup-banner.njk
- app/views/request-to-go-live/index.njk
- test/integration/add-psp-details.ft.test.js
- Added proof of government entity document task to stripe onboarding flow
> PP-8961 Add government entity document task to Stripe onboarding flow

- app/controllers/switch-psp/switch-tasks.service.js
- app/controllers/switch-psp/switch-tasks.service.test.js
- app/controllers/your-psp/kyc-tasks.service.js
- app/controllers/your-psp/kyc-tasks.service.test.js
- app/views/switch-psp/switch-psp.njk
- app/views/your-psp/_stripe.njk
- test/cypress/integration/settings/switch-psp.cy.test.js
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.test.js
- test/cypress/stubs/stripe-psp-stubs.js
- test/fixtures/stripe-psp.fixtures.js
- Added government entity document task to switch PSP and KYC tasks
> PP-8961 Add government entity document task to switch PSP and KYC tasks

- app/controllers/kyc/organisation-url/post.controller.js
- app/controllers/kyc/organisation-url/post.controller.test.js
- app/controllers/stripe-setup/director/post.controller.js
- app/controllers/stripe-setup/director/post.controller.test.js
- app/controllers/stripe-setup/government-entity-document/post.controller.js
- app/controllers/stripe-setup/government-entity-document/post.controller.test.js
- app/controllers/stripe-setup/responsible-person/post-additional-details.controller.js
- app/controllers/stripe-setup/responsible-person/post-additional-details.controller.test.js
- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/controllers/stripe-setup/responsible-person/post.controller.test.js
- app/controllers/user/phone-number/post.controller.js
- app/utils/validation/field-validation-checks.js
- app/utils/validation/server-side-form-validations.js
- app/views/stripe-setup/responsible-person/kyc-additional-information.njk
- Handles known errors from stripe for onboarding tasks and displays relevant error messages to users
- Handles errors for the following
- URL
- phone number
- date of birth
- file
> PP-9059 Handle known stripe errors

- app/controllers/webhooks/webhooks.controller.js
- app/controllers/webhooks/webhooks.service.js
- app/controllers/webhooks/webhooks.service.test.js
- app/services/clients/webhooks.client.js
- app/views/webhooks/_paginator.njk
- app/views/webhooks/detail.njk
- test/cypress/integration/webhooks/webhooks.cy.test.js
- test/cypress/stubs/webhooks-stubs.js
- test/fixtures/webhooks.fixtures.js
Lines webhook detail/ message list up with https://github.com/alphagov/pay-webhooks/pull/43
Match backend design changes in the webhook service. Match fixtures and
process to the new schema specified in
https://github.com/alphagov/pay-webhooks/pull/43.
Delivery attempts and message details to follow in separate change.
> PP-8501 Update webhook detail page to match backend

- app/controllers/webhooks/webhooks.controller.js
- app/controllers/webhooks/webhooks.service.js
- app/paths.js
- app/routes.js
- app/services/clients/webhooks.client.js
- app/views/webhooks/detail.njk
- app/views/webhooks/message.njk
- test/cypress/integration/webhooks/webhooks.cy.test.js
- test/cypress/stubs/webhooks-stubs.js
- test/fixtures/webhooks.fixtures.js
Depends on https://github.com/alphagov/pay-selfservice/pull/3170
An individual message, showing the history of delivery attempts
All messages for a given webhook
> PP-8501 Webhook event detail page

- app/views/webhooks/detail.njk
- app/views/webhooks/edit.njk
- app/views/webhooks/list.njk
- app/views/webhooks/signing_secret.njk
- app/views/webhooks/toggle_active.njk
- test/cypress/integration/webhooks/webhooks.cy.test.js
Depends on https://github.com/alphagov/pay-selfservice/pull/3171
> PP-9034: Webhooks content first pass

- app/utils/validation/server-side-form-validations.js
- app/utils/validation/server-side-form-validations.test.js
- test/cypress/integration/stripe-setup/director.cy.test.js
- test/cypress/integration/stripe-setup/responsible-person.cy.test.js
- Update error messages for go live flow or stripe onboarding pages as suggested by `PP-8914`
> PP-9177 update error messages part 2

- app/controllers/policy/supported-policy-documents.js
- app/views/policy/document/v2/contract-for-non-crown-bodies.njk
- app/views/policy/document/v2/memorandum-of-understanding-for-crown-bodies.njk
- app/views/policy/document/v2/policy-no-html.njk
- app/views/policy/document/v2/stripe-connected-account-agreement.njk
- Updated date on new contract pages to 21-Feb
> PP-9080 Update date for new contracts

- app/views/policy/document/v2/contract-for-non-crown-bodies.njk
- app/views/policy/document/v2/memorandum-of-understanding-for-crown-bodies.njk
- app/views/policy/document/v2/stripe-connected-account-agreement.njk
- Updated no.of pages and new contracts size to the latest
> PP-9080 Update new contracts size and page numbers

- app/assets/js/components/notification-banner.js
- app/controllers/my-services/get-index.controller.js
- app/controllers/my-services/index.js
- app/controllers/my-services/remove-notification.controller.js
- app/paths.js
- app/routes.js
- app/views/services/index.njk
- test/cypress/integration/my-services/my-services-notification-banner.cy.test.js
- Added new notification banner for new contracts from 21-Feb-22.
- Banner to appear for all admin users until 21-Feb
> PP-9244 Add my services notification banner for new contracts

- docker/build_and_test.Dockerfile
- glibc needed to build Docker image
> PP-9187 re-adding glibc

- app/views/includes/footer-categories.njk
- Update contract links in the footer to the new 2022 versions.
> PP-9264 Footer links - update to new contracts

- package-lock.json
- package.json
Override `minimist` to `1.2.5` to prevent security warnings
> PP-9148 override minimist to 1.2.5

- package-lock.json
- package.json
Reverts alphagov/pay-selfservice#3266
> Revert "Bump stripe from 8.207.0 to 8.209.0"

- dev.yml
This was added for PaaS in https://github.com/alphagov/pay-selfservice/pull/1815 so can be safely deleted
build should still pass
> BAU: Remove unused PaaS files

- app/controllers/agreements/agreements.service.js
- app/controllers/agreements/agreements.service.test.js
- app/services/clients/ledger.client.js
- test/fixtures/agreement.fixtures.js
Add ledger client utility methods for accessing agreements according to
shared endpoint spec.
Use standard pagination util and cover this formatting in an agreements
service.
> PP-9541 Agreements rest client utility and fixtures

- app/controllers/stripe-setup/check-org-details/get.controller.js
- app/controllers/stripe-setup/check-org-details/get.controller.test.js
- app/controllers/stripe-setup/check-org-details/index.js
- app/paths.js
- app/routes.js
- app/views/stripe-setup/check-org-details/index.njk
- Add path, route, controller for the new `Check org details` page.
> PP-9004 Check org details page

- app/controllers/stripe-setup/check-org-details/index.js
- app/controllers/stripe-setup/check-org-details/post.controller.js
- app/controllers/stripe-setup/check-org-details/post.controller.test.js
- app/routes.js
- app/views/stripe-setup/check-org-details/index.njk
- Show an error message if the `Check org details` form is submitted without
selecting a radio button.
- Update Nunjuks controller.
- Add new Post controller
- Add unit tests.
> PP-9004 Check org details page - add validation

- app/views/payment-links/_product.njk
- Updated nunjucks template in the products page to render the layout of the  payment links properly.
- Made minor changes to the indentations to make it more readable.
>  PP-9794 minor changes to fix broken payment link

- test/fixtures/ledger-transaction.fixtures.js
- test/unit/clients/ledger-client/ledger-search-transaction.pact.test.js
- Added pact test for dispute transaction search
> PP-9673 Add pact test for dispute transactions search

- app/services/clients/ledger.client.js
- test/cypress/integration/transactions/transaction-details.cy.test.js
- test/cypress/stubs/transaction-stubs.js
- test/unit/clients/ledger-client/ledger-get-dispute-transactions.pact.test.js
- Added pact test for `Get dispute transactions from ledger`
> PP-9662 Add pact test

- app/views/transaction-detail/index.njk
Transaction detail -> Transaction details
> PP-9662 Rename transaction detail page

- README.md
Fix a broken link in README.md
> BAU: fix a broken link in README.md

- app/controllers/payment-links/get-manage.controller.js
- app/views/payment-links/_pre-filled-payment-moto-content.njk
- app/views/payment-links/index.njk
- app/views/payment-links/manage.njk
- Added link to create a pre-filled payment link to content
- Added link for email support and MOTO payment link to content.
> PP-8939 adding pre-filled payment links to content

- app/views/services/index.njk
- test/cypress/integration/my-services/my-services-links.cy.test.js
- change text of report links and make them bold.
- update tests
> PP-9946 make report links more visible

- app/controllers/switch-psp/switch-tasks.service.js
- app/controllers/switch-psp/switch-tasks.service.test.js
- app/views/switch-psp/switch-psp.njk
- test/cypress/integration/settings/switch-psp.cy.test.js
- Update switch tasks service - add new `CONFIRM_ORGANISATION_DETAILS` task
- Update view
- Add test
- Update Cypress test
> PP-9984 Switch to Stripe - update task list

- test/cypress/integration/settings/switch-psp.cy.test.js
- test/cypress/integration/stripe-setup/update-org-details.cy.test.js
- test/cypress/stubs/stripe-account-setup-stub.js
- Update `switch-psp` cypress test
- Add test to check the task `check org details`
- Update `org details` page test
- Add test for successful submission - check that Stripe is called
> PP-9984 Switch PSP > Check org details - update Cypress tests

- app/services/clients/stripe/StripeCompany.class.js
- app/services/clients/stripe/StripeCompany.class.test.js
- Constructs StripeCompany object with `executives_provided` flag
> Fix: Stripe SRO page error

- app/views/your-psp/_worldpay-flex.njk
- Removed link to 3ds-secure-2 product which is out of date and about to be removed
> PP-9648 Remove link to 3d-secure-2 page

- app/controllers/your-psp/get.controller.js
- app/controllers/your-psp/get.controller.test.js
- app/views/your-psp/_stripe.njk
Added environment variable for task List flag
Added unit test to show when the flag is set to true or false
> PP-10209 your PSP enable task list flag

- app/controllers/request-to-go-live/organisation-address/post.controller.js
- app/controllers/request-to-go-live/organisation-address/post.controller.test.js
- app/controllers/request-to-go-live/organisation-name/post.controller.js
- app/controllers/request-to-go-live/organisation-name/post.controller.test.js
- Limits organisation name to 100 characters as PSP (stripe) allows only up to 100 characters.
> PP-10100 Limit organisation name to 100 characters

- .secrets.baseline
- app/services/clients/adminusers.client.js
- test/fixtures/invite.fixtures.js
- test/unit/clients/adminusers-client/invite/update-invite-password.pact.test.js
Add a method to the adminusers client to update the password for an invite. Add a corresponding pact test.
> PP-10055 Add client method to update invite password

- .secrets.baseline
- app/controllers/dashboard/dashboard-activity.controller.js
- app/views/dashboard/_worldpay_account_not_configured_banner.njk
- app/views/dashboard/index.njk
- test/cypress/integration/dashboard/dashboard-worldpay-setup-banner.cy.test.js
- Added banner to the dashboard for Worldpay accounts (for which account setup is incomplete).
- Links to Your-PSP settings page
- Preview
> PP-10199 Add banner for Worldpay accounts

- app/controllers/request-to-go-live/choose-takes-payments-over-phone/post.controller.js
- app/controllers/request-to-go-live/choose-takes-payments-over-phone/post.controller.test.js
- app/models/ServiceUpdateRequest.class.js
- Added post controller for the new page (Choose takes payments over the phone) to be added to the request to go live flow
> PP-10199 Add post controller

- app/controllers/your-psp/post-flex.controller.js
- app/controllers/your-psp/post-flex.controller.test.js
- app/services/clients/adminusers.client.js
- test/fixtures/invite.fixtures.js
- test/pact/adminusers-client/invite/send-otp.pact.test.js
- test/pact/adminusers-client/invite/update-invite-phone-number.pact.test.js
* `updateInvitePhoneNumber`
* `sendOtp`
> PP-10280: Add two new methods on `adminusers.client`

- app/controllers/your-psp/get.controller.js
- app/controllers/your-psp/your-psp-tasks.service.js
- app/controllers/your-psp/your-psp-tasks.service.test.js
- Added service tasks for new Stripe onboarding tasklist
- Added unit test for the service tasks
- Updated your Psp controller to include the new tasklist
> PP-10210 Yourpsp Stripe display task list

- app/services/clients/adminusers.client.js
- test/pact/adminusers-client/invite/reprovision-otp.pact.test.js
> PP-10367: Add reprovision-otp endpoint on adminusers.client

- .secrets.baseline
- app/controllers/registration/registration.controller.js
- app/paths.js
- app/routes.js
- app/routes.test.js
- app/views/registration/email.njk
- app/views/registration/get-security-codes.njk
Added a new page to enter an email address for starting registration.  This is not yet hooked up.
> PP-10402: New page: enter email

- .secrets.baseline
- app/controllers/registration/registration.controller.js
- app/controllers/registration/registration.controller.test.js
- app/routes.js
- app/routes.test.js
- app/views/registration/check-email.njk
- test/cypress/integration/registration/start-self-signup-registration.cy.test.js
- test/cypress/stubs/invite-stubs.js
Displays a page telling the user to check their email to find the invite email.
> PP-10402: New page: check email

- app/views/two-factor-auth/_authenticator-app-instructions.njk
> PP-10052 Content fix

- app/views/login/login.njk
- test/cypress/integration/user/login.cy.test.js
Link to new start page of registration journey.
> PP-10061: Link to new start page of registration journey

- .secrets.baseline
- app/controllers/invite-user.controller.js
- app/controllers/registration/registration.controller.js
- app/middleware/invite-cookie-is-present.js
- app/models/User.class.js
- app/utils/email-tools.js
- app/utils/email-tools.test.js
- app/utils/validation/field-validation-checks.js
Log a line when a user completes a registration. Include in the log line the second factor method chosen and whether the user was an internal GDS user or not.
Include the `internal_user` field for all lines logged for the registration pages, determining this from the email address used for the registration.
> BAU Log when a user completes registration

- app/views/registration/email.njk
- app/views/registration/get-security-codes.njk
- app/views/registration/password.njk
- app/views/registration/phone-number.njk
- app/views/registration/sms-code.njk
These are needed for the end-to-end tests.
> PP-10286: Add ids to some continue buttons

- app/controllers/privacy/privacy.controller.js
- app/controllers/privacy/privacy.controller.test.js
- app/paths.js
- app/routes.js
- app/routes.test.js
- app/views/privacy/privacy.njk
- test/cypress/integration/privacy/privacy.cy.test.js
- Setup the route and page for the privacy page
- No need for a feature flag as this page is not linked anywhere
- Content will be updated in a future URL.
> PP-10242 Setup new Privacy page

- app/views/privacy/privacy.njk
- Add content to the page.
- Sub navigation will be added in another PR.
> PP-10242 Privacy page - add content.

- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js
- Updated your PSP task list test to check each task is hyperlinked with the correct url and the state  of each task is updated
> PP-10349 Hyperlink stripe onboarding tasks

- app/controllers/agreements/agreements.controller.js
- app/controllers/agreements/agreements.controller.test.js
Ledger returns a 404 when the search agreements API endpoint is called with a page number that does not exist. Handle this by showing a not found error page to the user with status code 404.
> PP-10485 Show page not found when ledger returns 404

- app/views/includes/footer.njk
- app/views/privacy/privacy.njk
- Add link to the privacy page in the footer.
- Privacy page - fix minor styling issues.
> PP-10242 Privacy page - add link to the footer

- app/controllers/stripe-setup/vat-number/post.controller.js
- app/controllers/stripe-setup/vat-number/post.controller.test.js
- app/controllers/switch-psp/switch-tasks.service.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- Updated VAT's post controller so when ENABLE_STRIPE_ONBOARDING_TASK_LIST is set to true it redirects to task-list page
- Updated VAT's cypress test
> PP-10352 redirect user when VAT complete

- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js
- test/cypress/integration/stripe-setup/vat-number.cy.test.js
- Updated Cypress test to check page is redirected to task-list page valid VAT number is submitted
> PP-10352 redirect user when VAT complete cypress test

- app/controllers/stripe-setup/company-number/post.controller.js
- app/controllers/stripe-setup/company-number/post.controller.test.js
-  Updated Company number's post controller so when ENABLE_STRIPE_ONBOARDING_TASK_LIST flag is set to true it redirects to task-list page
> PP-10356 redirect user when company registration complete

- app/controllers/stripe-setup/bank-details/post.controller.js
- app/controllers/stripe-setup/bank-details/post.controller.test.js
- app/controllers/stripe-setup/company-number/post.controller.js
- app/controllers/stripe-setup/company-number/post.controller.test.js
- app/controllers/stripe-setup/vat-number/post.controller.js
- app/controllers/stripe-setup/vat-number/post.controller.test.js
- Updated the redirect for the post VAT, Bank details controllers to use req.params.credentialId
> PP-10356 fixing how we request credentialId 

- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js
- test/cypress/stubs/stripe-psp-stubs.js
- Updated Cypress test to check service director page is redirected to task-list page when valid service director information are provided.
>  PP-10353 return user when service director task complete cypress test

- app/controllers/stripe-setup/responsible-person/post.controller.js
- app/controllers/stripe-setup/responsible-person/post.controller.test.js
- Updated responsible person's post controller to redirect when ENABLE_STRIPE_ONBOARDING_TASK_LIST flag is true and details are added
- Added unit test accordingly
>   PP-10354 return user when responsible person complete

- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.test.js
-  Updated Cypress test to check page is redirected to task-list page when a valid responsible person information is submitted
> PP-10354 return user when responsible person complete cypress test

- app/services/auth.service.js
- remove setting gateway account id on cookie when redirecting after login
> PP-10413 remove setting gateway account id on cookie

- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
- Updated cypress test to redirect to task-list when organisation details are correct
> PP-10350 redirect user when address name complete cypress test

- .github/workflows/post-merge.yml
- .github/workflows/run-tests.yml
Located and replaced all usages of set-output commands in run-tests.yml and post-merge.yml workflows.
> PP-10675:replaced all usages of set-output in run-tests.yml and post-merge.yml workflows.

- app/controllers/stripe-setup/bank-details/get.controller.js
- app/controllers/stripe-setup/check-org-details/get.controller.js
- app/controllers/stripe-setup/company-number/get.controller.js
- app/controllers/stripe-setup/director/get.controller.js
- app/controllers/stripe-setup/government-entity-document/get.controller.js
- app/controllers/stripe-setup/responsible-person/get.controller.js
- app/controllers/stripe-setup/vat-number/get.controller.js
- app/utils/credentials.js
- app/utils/credentials.test.js
- app/views/stripe-setup/bank-details/index.njk
- app/views/stripe-setup/check-org-details/index.njk
- app/views/stripe-setup/company-number/index.njk
- app/views/stripe-setup/director/index.njk
- app/views/stripe-setup/government-entity-document/index.njk
- app/views/stripe-setup/responsible-person/index.njk
- app/views/stripe-setup/vat-number/index.njk
-  Added function to look for ENABLE_STRIPE_ONBOARDING_TASK_LIST and yourPsp route
- Added necessary unit tets
-  Updated controller logic for all seven tasks to have a back-link to task-list when EnableStribeOnboardingTaskList flag is true
- Updated nunjucks logic to render back-link when flag is 'true'
> PP-10342 Add back-link to redirect user from each task to the task list

- app/controllers/your-psp/your-psp-tasks.service.js
- app/controllers/your-psp/your-psp-tasks.service.test.js
- Added function that calculates number of steps completed in the onboarding journey
- Added necessary tests for the function
>  PP-10343 Add progress indicator for Task-list

- app/controllers/your-psp/get.controller.js
- app/views/your-psp/_stripe.njk
- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
- Added logic in nunjucks file to show progress indicator when ENABLE_STRIPE_ONBOARDING_TASK_LIST is true
- Updated cypress test to check progress of tasks
>  PP-10343 Add progress indicator for tasklist cypress tests

- app/views/your-psp/_stripe.njk
- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
- Updated heading styling according to the task list design pattern
> PP-10343 stripe progress indicator: fix heading styling

- app/views/your-psp/index.njk
- test/cypress/integration/settings/your-psp-stripe-kyc.cy.js
- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
- test/cypress/integration/stripe-setup/director.cy.js
- Updated heading for Stripe onboarding tasks
- Updated necessary cypress tests
> PP-10347 Add page heading to task list

- app/views/your-psp/_stripe.njk
- test/cypress/integration/settings/your-psp-stripe-tasklist.cy.js
- For stripe onboarding tasks, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled:
- Display warning text when tasks are not complete
> PP-10346 display warning sign when tasks are not complete

- app/controllers/dashboard/dashboard-activity.controller.js
- app/controllers/dashboard/dashboard-activity.controller.test.js
- app/controllers/your-psp/get.controller.test.js
- For stripe onboarding tasks, when ENABLE_STRIPE_ONBOARDING_TASK_LIST is enabled, show Show banner when onboarding is incomplete:
- Updated dashboard activity controller and added ENABLE_STRIPE_ONBOARDING_TASK_LIST
- Updated the necessary unit test
> PP-10358 show banner when tasks not complete on dashboard

- app/views/dashboard/_stripe-account-setup-banner_tasklist.njk
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.js
- For the dashboard, fix minor content bug to the Stripe restricted banner
> PP-10358 fixing content for Stripe restricted banner

- app/views/dashboard/_stripe-account-setup-banner_tasklist.njk
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.js
- For the dashboard, update minor content for the Stripe banner
>  PP-10358 fixing content for the new Stripe dashboard

- app/controllers/stripe-setup/director/post.controller.js
- app/controllers/stripe-setup/director/post.controller.test.js
- Updated post controller for director to check for ENABLE_STRIPE_ONBOARDING_TASK_LIST and pass variable to the error page
- Added unit tests
> PP-10840 fix side nav disappearing when error for director task

- app/controllers/request-to-go-live/organisation-address/post.controller.js
- app/controllers/request-to-go-live/organisation-address/post.controller.test.js
- Pass the flag down that check if the Stripe tasklist is enabled and if on a `your-psp` route to the the error page.
- This flag is used to show the side nav.
> PP-10840 Stripe task list - fix side nav error when updating org address

- test/cypress/integration/payment-links/amount-hint.cy.js
- test/cypress/integration/payment-links/create-payment-link.cy.js
Remove some of the .within(() => {}) blocks from the tests as they made it difficult to read once the tests were combined.
Hiding whitespace changes from the diff will help with reviewing
> PP-19862 Combine Cypress tests for creating payment links

- test/pact/connector-client/connector-get-gateway-account-by-external-id.pact.test.js
- remove Smartpay related code. Smartpay is no longer supported and it's unnecessary waste of time to refactor its classes every time we do a change to other PPS.
> PP-10865 remove smartpay part 1

- test/cypress/integration/request-to-go-live/agreement.cy.js
> PP-10862 Make go live agreement Cypress tests standalone

- app/controllers/request-to-go-live/choose-how-to-process-payments/post.controller.js
- app/views/request-to-go-live/choose-how-to-process-payments.njk
- test/cypress/integration/request-to-go-live/choose-how-to-process-payments.cy.js
- Removed BYOC payments providers from the request to go live flow options
- and content changes for hint text for the remaining payment providers
> PP-10261 Remove BYOC providers from request to go live flow

- app/views/agreements/macro/status.njk
- test/cypress/integration/agreements/agreements.cy.js
- update agreement status with new `inactive` tag
> PP-10949 add new agreement status

- app/services/clients/connector.client.js
- test/fixtures/cancel-agreement.fixtures.js
- test/pact/connector-client/connector-post-cancel-agreement.pact.test.js
- test/test-helpers/pact/pact-interaction-builder.js
- Add new `cancel agreement` function and PACT test.
> PP-10601 Update connector client - add `cancel agreement` function

- app/controllers/agreements/agreements.service.js
- app/controllers/agreements/agreements.service.test.js
- Add new function to call the connector client to cancel an agreement.
> PP-10601 Cancel agreement - update agreement service

- app/paths.js
- app/routes.js
- app/views/agreements/detail.njk
- Add route for the cancel agreement functionality.
- Add `cancel agreement` functionality to the view.
- Add cancel notification when a agreement has been cancelled successfully.
> PP-10601 Cancel agreement - update agreement detail view

- package-lock.json
- package.json
> ZD-5357596: Bump pay-js-commons to 3.9.0

- app/views/agreements/detail.njk
- test/cypress/integration/agreements/agreement.cy.js
- test/fixtures/agreement.fixtures.js
- Display Date cancelled and Cancelled by fields if available when agreement is cancelled
> PP-10520 display cancelled date and cancelled by user email

- test/pact/connector-client/connector-post-cancel-agreement.pact.test.js
- refactor cancel agreement pact test to use the new state from connector
with @james-peacock-gds
> PP-10598 refactor agreement pact test

- test/fixtures/agreement.fixtures.js
- test/pact/ledger-client/ledger-get-one-agreement.pact.test.js
- add a new pact test for getting an agreement with payment instrument from Ledger
with @james-peacock-gds
> PP-11121 add get one agreement pact test

- test/fixtures/agreement.fixtures.js
- test/pact/ledger-client/ledger-get-one-agreement.pact.test.js
- add a pact test when the agreement does not exist
> PP-11121 add agreement not found pact test

- package-lock.json
- package.json
- test/test-helpers/test-env.js
One less dev dependency to deal with, and a simpler setup. 
This has already been done for Products UI https://github.com/alphagov/pay-products-ui/pull/2072
> BAU: Replace envfile with dotenv

- .secrets.baseline
- test/cypress/integration/settings/your-psp.cy.js
- test/fixtures/gateway-account.fixtures.js
- Add Cypress tests for the `Your PSP > Woldpay recurring` credentials page.
> PP-11251 Your PSP > Worldpay creds - add Cypress tests for recurring accounts

- app/views/your-psp/_worldpay-flex.njk
- Updating the 3DS flex content on the `Your PSP > Worldpay test account`.
- Make it more relevant for test Worldpay accounts.
- Content has been reviewed by content designer.
> PP-11251 Your PSP > Worldpay - update 3DS content for test Wolrdpay accounts

- test/pact/adminusers-client/authenticate/authenticate.pact.test.js
- test/pact/adminusers-client/forgotten-password/create-forgotten-password.pact.test.js
- test/pact/adminusers-client/user/authenticate.pact.test.js
In a previous commit we disabled some pact tests due to adminusers being refactored.
- refactor tests for adminusers changes
- re-enable tests
> PP-11283 re-enable pact tests

- .secrets.baseline
- app/controllers/dashboard/dashboard-activity.controller.test.js
- app/controllers/service-users.controller.js
- app/models/User.class.js
- app/services/auth.service.test.js
- app/views/includes/header.njk
- app/views/team-members/team-member-details.njk
- app/views/team-members/team-members.njk
- test/cypress/stubs/user-stubs.js
- test/fixtures/invite.fixtures.js
- test/fixtures/user.fixtures.js
- test/integration/service-users.ft.test.js
- test/pact/adminusers-client/user/authenticate.pact.test.js
- test/ui/team-member-details.ui.test.js
- test/ui/team-member-list.ui.test.js
We no longer have username as such stored in adminusers and we are not going to include it in any responses that contain user info.
- remove username from User.class
- refactor code accordingly
- refactor views accordingly
- refactor tests accordingly
> PP-11327 remove username from User class

- .github/workflows/post-merge.yml
Updating pact broker to new url
> PP-11292: update pact broker url

- app/controllers/digital-wallet/get-google-pay.controller.js
- app/controllers/digital-wallet/post-google-pay.controller.js
- app/controllers/digital-wallet/post-google-pay.controller.test.js
- app/utils/credentials.js
- app/views/digital-wallet/google-pay.njk
- test/cypress/integration/settings/allow-google-pay.cy.js
- test/fixtures/user.fixtures.js
- test/pact/adminusers-client/authenticate/authenticate.pact.test.js
- test/pact/adminusers-client/user/authenticate.pact.test.js
Use the design system components for displaying errors on the Google pay settings page.
Add unit tests and improve Cypress tests.
> PP-11318 Improve google pay settings page

- package-lock.json
- package.json
update pay-js-commons to latest
> BAU update pay-js-commons to latest

- app/views/404.njk
> BAU 404 template formatting error

- package-lock.json
- package.json
> BAU bump pay-js-commons

- bin/publish-pacts.js
- package-lock.json
- package.json
- test/pact/publicauth-client/get-tokens.pact.test.js
- test/test-helpers/pact/pact-proxy.js
- Upgrade PactJS library to the latest
- Removes pact-node library in favour of pact-core library
> PP-12028 Upgrade pact library

- .github/workflows/codeql.yml
I had copied and pasted the `main` branch from pay-webhooks 🤦
> BAU: Fix CodeQL workflow branch

- app/services/clients/public-auth.client.js
- Change ‘public-auth.client’ methods to use ‘axios-base-client’ library.
- Refactor call parameters initialisation.
- Use ‘async/await’ syntax.
> PP-11681 Replace ‘base-client’ with ‘axios-base-client’ in 'public-auth.client'

- test/pact/connector-client/connector-post-request-stripe-test-account.pact.test.js
Reverts alphagov/pay-selfservice#4251
> Revert "PP-12413: Temporarily disable request stripe test account pact test"

- app/views/policy/document/pci-dss-attestation-of-compliance.njk
Authored by @alanmaddrell
This is applying the changes from https://github.com/alphagov/pay-selfservice/pull/4248# but within the alphagov org so the pact tests can run
> PP-1300: Update attestation of compliance.

- app/views/services/select-org-type.njk
- test/cypress/integration/my-services/add-new-service.cy.js
- comments from the design review of PP-13091
> PP-13091 design comments

- app/utils/nav-builder.js
- test/cypress/integration/settings/api-keys.cy.js
- test/cypress/stubs/token-stubs.js
- test/fixtures/token.fixtures.js
- test/ui/navigation.ui.test.js
- Do not show API Keys link in Settings for a disabled gateway account
> PP-13121-Hide API Keys link

- app/views/api-keys/create.njk
Self-evident
With @alanmaddrell
> PP-13146 update created api key warning next

- app/utils/cookie.js
- wrong variable casing used. Fix casing.
> PP-13011 fix SameSite session cookie

- app/utils/cookie.js
- wrong variable casing used. Fix casing.
> PP-13011 fix registration cookie SameSite

- .secrets.baseline
- app/controllers/dashboard/dashboard-activity.controller.js
- app/controllers/dashboard/dashboard-activity.controller.test.js
- app/views/dashboard/_links.njk
- test/cypress/integration/dashboard/dashboard-disabled-account-banner.cy.js
- test/cypress/integration/dashboard/dashboard-go-live-link.cy.js
- test/cypress/integration/dashboard/dashboard-links.cy.js
- test/cypress/integration/dashboard/dashboard-statistics.cy.js
- test/cypress/integration/dashboard/dashboard-stripe-add-details.cy.js
- test/cypress/integration/dashboard/dashboard-worldpay-setup-banner.cy.js
- test/cypress/integration/demo-payment/demo-payment.cy.js
- test/cypress/integration/demo-payment/mock-cards-stripe.cy.js
- test/cypress/integration/demo-payment/mock-cards.cy.js
- test/cypress/integration/settings/switch-psp.cy.js
- test/cypress/utils/request-to-go-live-utils.js
- test/fixtures/gateway-account.fixtures.js
- test/integration/dashboard/dashboard-activity.controller.ft.test.js
> PP-13030: Do not show request live account link for a Worldpay test service

- app/views/privacy/privacy.njk
> BAU Add user survey to privacy notice & fix typo

- app/routes.js
- app/simplified-account-routes.js
- app/simplifiedAccountRoutes.js
The obvious benefit is to make managing routes easier.
> PP-13135: Modularise simplified account routes

- README.md
- package-lock.json
- package.json
- test/cypress/plugins/index.js
Also included a tiny `run-amock` version bump.
> PP-13235: Removed all references to Mountebank

- package-lock.json
- package.json
- Update `express` to `v4.21.1`
> PP-13282 Update express to 4.21.1

- app/controllers/simplified-account/settings/email-notifications/email-notifications.controller.js
- app/controllers/simplified-account/settings/email-notifications/email-notifications.controller.test.js
- app/paths.js
- app/services/clients/connector.client.js
- app/services/email.service.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/email-notifications/collect-email-page.njk
- app/views/simplified-account/settings/email-notifications/index.njk
- test/cypress/integration/simplified-account/service-settings/email-notifications.cy.js
- test/cypress/integration/simplified-account/service-settings/service-name.cy.js
> PP-13135: Edit email collection settings

- app/controllers/simplified-account/settings/stripe-details/company-number/company-number.controller.js
- app/controllers/simplified-account/settings/stripe-details/director/director.controller.js
- app/controllers/simplified-account/settings/stripe-details/government-entity-document/government-entity-document.controller.js
- app/controllers/simplified-account/settings/stripe-details/organisation-details/organisation-details.controller.js
- app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.js
- app/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
- app/controllers/simplified-account/settings/stripe-details/vat-number/vat-number.controller.js
- app/middleware/simplified-account/enforce-payment-provider-type.middleware.js
- app/middleware/simplified-account/enforce-payment-provider-type.middleware.test.js
- app/middleware/simplified-account/index.js
- app/models/payment-providers.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/stripe-details/company-number/index.njk
- app/views/simplified-account/settings/stripe-details/director/index.njk
- app/views/simplified-account/settings/stripe-details/government-entity-document/index.njk
- app/views/simplified-account/settings/stripe-details/organisation-details/index.njk
- app/views/simplified-account/settings/stripe-details/responsible-person/index.njk
- app/views/simplified-account/settings/stripe-details/vat-number/index.njk
- test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary-test-helpers.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary.cy.js
- stripe details task summary view cypress test
- new middleware: enforcePaymentProviderType
- restrict an express route to only be accessible to the configured payment provider
> PP-12444 cypress test for stripe details summary view

- app/controllers/simplified-account/settings/email-notifications/email-notifications.controller.js
- app/controllers/simplified-account/settings/email-notifications/email-notifications.controller.test.js
- app/controllers/simplified-account/settings/email-notifications/refund-emails.controller.js
- app/controllers/simplified-account/settings/email-notifications/refund-emails.controller.test.js
- app/controllers/simplified-account/settings/index.js
- app/paths.js
- app/services/clients/connector.client.js
- app/services/email.service.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/email-notifications/index.njk
- app/views/simplified-account/settings/email-notifications/refund-email-toggle.njk
- test/cypress/integration/simplified-account/service-settings/email-notifications.cy.js
Cypress test will be in a future PR.
> PP-13135: Functionality to toggle the sending of refund emails

- app/views/simplified-account/settings/team-members/index.njk
- test/cypress/integration/simplified-account/service-settings/team-members.cy.js
- Alter Simplified Settings / Team Members page to show '(me)' next to the logged-in user instead of '(you)', and to show 'View my profile' instead of 'View'. (as per [Figma ](https://www.figma.com/design/2xrNzEL8AjblsiPoS3cAY9/GOV.UK-Pay-design-work))
**Screenshot as of 11-11-2024 (admin user is logged in)**
-----------
> PP-13137 Update to match design

- app/controllers/simplified-account/settings/stripe-details/bank-account/bank-account.controller.js
- app/controllers/simplified-account/settings/stripe-details/bank-account/bank-account.controller.test.js
- app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-check-answers.controller.js
- app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-contact-details.controller.js
- app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-home-address.controller.js
- app/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.js
- app/controllers/simplified-account/settings/stripe-details/stripe-details.controller.js
- app/errors.js
- app/middleware/error-handler.js
- app/middleware/simplified-account/check-task-completion.js
- app/paths.js
- app/services/stripe-details.service.js
- app/simplified-account-routes.js
- app/utils/custom-nunjucks-filters/govuk-date.js
- app/utils/simplified-account/settings/stripe-details/tasks.js
- app/utils/simplified-account/settings/stripe-details/tasks.test.js
- app/utils/simplified-account/validation/responsible-person.schema.js
- app/views/simplified-account/settings/stripe-details/responsible-person/check-your-answers.njk
- app/views/simplified-account/settings/stripe-details/responsible-person/contact-details.njk
- app/views/simplified-account/settings/stripe-details/responsible-person/home-address.njk
- app/views/simplified-account/settings/stripe-details/responsible-person/index.njk
- package-lock.json
- package.json
- server.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary.cy.js
- controllers, views and validation functions for new multi-part responsible person form
- users now see a check your answers page before submitting the responsible person details
- new checkTaskCompletion middleware and accompanying error class to prevent users from visiting task pages they have already completed
- new nunjucks custom filter to display dates in standard format summary tables etc
> PP-12444 simplified account settings responsible person stripe task

- app/controllers/simplified-account/settings/index.js
- app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.js
- app/controllers/simplified-account/settings/organisation-details/organisation-details.controller.js
- app/paths.js
- app/simplified-account-routes.js
- app/utils/simplified-account/settings/service-settings.js
- app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
- app/views/simplified-account/settings/organisation-details/index.njk
- Basic scaffold for organisation details settings with controllers and routing. 
- Basic Organisation Details index page with Summary List
> PP-13255 Add routing and controllers for Organisation Details settings

- app/controllers/simplified-account/settings/email-notifications/email-notifications.controller.js
- app/controllers/simplified-account/settings/email-notifications/templates/custom-paragraph.controller.js
- app/controllers/simplified-account/settings/email-notifications/templates/custom-paragraph.controller.test.js
- app/controllers/simplified-account/settings/email-notifications/templates/templates.controller.js
- app/paths.js
- app/services/clients/connector.client.js
- app/services/email.service.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/email-notifications/custom-paragraph.njk
- app/views/simplified-account/settings/email-notifications/templates.njk
- test/cypress/integration/simplified-account/service-settings/email-notifications/email-notifications.cy.js
PR for the "Add a custom paragraph" functionality. Also made some permissions fixes in the routes file.
Add a custom paragraph screen:
Confirmation banner:
Validation:
> PP-13135: Add a custom paragraph

- app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
- Add organisation details form
- This is currently just the form layout, full functionality will follow in later PRs
> PP-13255 Add organisation details form skeleton

- app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.js
- app/controllers/simplified-account/settings/team-members/team-members.controller.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/team-members/change-permission.njk
- set up controller and template for 'change permission'
- will implement the functionality in a subsequent PR
Screenshot (role headings will be made bolder in a subsequent PR)
> PP-13297 set up controller and template

- app/controllers/simplified-account/settings/organisation-details/edit-organisation-details.controller.js
- app/controllers/simplified-account/settings/organisation-details/organisation-details-validation.js
- app/utils/simplified-account/validation/organisation-details.schema.js
- app/utils/simplified-account/validation/organisation-details.schema.test.js
- app/utils/simplified-account/validation/responsible-person.schema.js
- app/utils/validation/postcode-validation.js
- app/utils/validation/server-side-form-validations.js
- app/views/simplified-account/settings/organisation-details/edit-organisation-details.njk
- Add form validation for organisation details using `express-validator`
> PP-13255 Add input validation for organisation details form

- app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.js
- app/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.test.js
- app/views/simplified-account/settings/team-members/change-permission.njk
- add the functionality to update a user's role based on the selection made by the admin user in the change permission form.
- add unit tests for the post controller
To do in subsequent PRs:
> PP-13297 Add post controller and unit tests

- test/cypress/integration/simplified-account/service-settings/team-members/change-permission.cy.js
- Cypress test for change permissions.
> PP-13297 Cypress test

- app/controllers/simplified-account/settings/team-members/invite/invite.controller.js
- app/controllers/simplified-account/settings/team-members/invite/invite.controller.test.js
- app/controllers/simplified-account/settings/team-members/team-members.controller.js
- app/controllers/simplified-account/settings/team-members/team-members.controller.test.js
- app/paths.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/team-members/invite.njk
Implement the invite team member get controller to present the form as per the design.
To do in subsequent PRs:
- implement post controller
Screenshot of form for a service with agent-initiated moto enabled:
> PP-13296 invite team member

- app/views/simplified-account/settings/team-members/invite.njk
- test/cypress/integration/simplified-account/service-settings/team-members/invite.cy.js
- test/cypress/stubs/invite-stubs.js
- Cypress test for inviting a user to a service
> PP-13296 invite user cypress tests

- app/controllers/simplified-account/settings/card-types/card-types.controller.js
- app/controllers/simplified-account/settings/index.js
- app/simplified-account-routes.js
- app/views/simplified-account/settings/card-types/index.njk
- basic setup for get controller for card types simplified settings page
- implementation will be done in subsequent PRs
> PP-13312 set up route, controller and template

- test/cypress/integration/simplified-account/service-settings/stripe-details/bank-details.cy.js
- test/cypress/stubs/stripe-account-setup-stub.js
> PP-12444 cypress test bank details stripe onboarding task

- app/assets/sass/components/multi-select.scss
- app/browsered/multi-select.js
- app/views/includes/multi-select.njk
- refactored the multi-select progressive enhancement to improve usability
https://github.com/user-attachments/assets/7df8f05f-60f3-44e6-9f3f-7b7f32733333
> PP-13398 make the multi-select dropdown enhancement easier to use

- app/services/stripe-details.service.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/bank-details.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/company-number.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/confirm-org-details.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/director.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/task-summary.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/vat-number.cy.js
- test/cypress/stubs/stripe-account-setup-stub.js
- cypress test for the `confirm org details` stripe setup task
> PP-12444 cypress test confirm org details stripe setup task

- app/controllers/simplified-account/settings/team-members/team-members.controller.test.js
- Refactor team members controller test to use the ControllerTestBuilder.
> BAU Refactor team-members controller test

- app/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
- app/models/WorldpayTasks.class.js
- app/views/simplified-account/settings/worldpay-details/credentials.njk
- app/views/simplified-account/settings/worldpay-details/index.njk
- Show completed task card when credentials are set
- Autofill form with existing credentials merchant code and username when editing credentials
> PP-13313 Show card for completed tasks when credentials are set

- app/simplified-account-routes.js
- Return 404 when attempting to access Worldpay details settings for non-Worldpay account
> PP-13313 Allow only Worldpay accounts to view Worldpay Details settings

- app/models/WorldpayTasks.class.js
- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
- Cypress tests for Worldpay details landing page
> PP-13313 Worldpay details landing page Cypress tests

- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
- test/cypress/stubs/api-keys-stubs.js
Cypress test for https://github.com/alphagov/pay-selfservice/pull/4397
> PP-12395: Cypress test for creating an api key

- app/controllers/simplified-account/settings/api-keys/api-keys.controller.js
- app/controllers/simplified-account/settings/api-keys/revoke/revoke.controller.js
- app/controllers/simplified-account/settings/api-keys/revoke/revoke.controller.test.js
- app/views/simplified-account/settings/api-keys/index.njk
- app/views/simplified-account/settings/api-keys/revoke.njk
Validation if nothing is selected:
Notification on successful revocation of key:
> PP-12395: Validation and success notification when revoking API key

- src/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.test.js
- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
- test/cypress/stubs/gateway-account-stubs.js
- Cypress tests for Worldpay credentials form in Worldpay details settings
> PP-13313 Add Cypress tests for Worldpay credentials form

- package-lock.json
- package.json
- src/controllers/simplified-account/settings/api-keys/revoked-keys/revoked-keys.controller.js
- src/simplified-account-routes.js
- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
- test/cypress/stubs/api-keys-stubs.js
Cypress test for https://github.com/alphagov/pay-selfservice/pull/4410
> PP-12395: Cypress test for the Show revoked API keys page

- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
- Cypress tests for showing the "All tasks completed" success banner in Worldpay details settings
> PP-13313 Cypress tests for Worldpay details success banner

- src/routes.js
- src/views/simplified-account/settings/api-keys/index.njk
- src/views/simplified-account/settings/api-keys/revoked-keys.njk
- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
> PP-12395: Show 'Not used yet' if key has not been used

- README.md
- test/cypress/integration/simplified-account/service-settings/card-types/card-types.cy.js
- test/cypress/stubs/gateway-account-stubs.js
- test/fixtures/card.fixtures.js
- add cypress test for simplified accounts card types setting
> PP-13312 cypress test card types setting

- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.test.js
- src/simplified-account-routes.js
- src/views/simplified-account/settings/worldpay-details/flex-credentials.njk
- Add post handler for submitting 3ds flex credentials
- add input validation using `express-validator`
- add tests for flex credentials controller
> PP-12440 Add validation for Worldpay details flex credentials setting

- src/controllers/simplified-account/settings/worldpay-details/credentials/worldpay-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.test.js
- src/models/WorldpayTasks.class.js
- src/models/gateway-account-credential/Worldpay3dsFlexCredential.class.js
- src/models/gateway-account/GatewayAccountUpdateRequest.class.js
- src/services/clients/connector.client.js
- src/services/email.service.js
- src/services/worldpay-details.service.js
- src/views/simplified-account/settings/worldpay-details/credentials.njk
- test/cypress/integration/simplified-account/service-settings/email-notifications/email-notifications.cy.js
- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
POST functionality for Worldpay details 3DS flex credentials task
* Implement checking credentials with Worldpay via connector, updating credentials in Connector,
* and updating gateway account integration version in Connector
* Implement single Connector client patch gateway account method, with common PatchRequest object
> PP-12440 Implement POST functionality for 3DS flex credentials

- src/controllers/payment-links/post-amount.controller.js
- src/controllers/payment-links/post-edit-amount.controller.js
- src/controllers/payment-links/validations/amount-validations.js
- src/views/payment-links/amount.njk
- Use `express-validator` to validate amount in payment links
- apply validation to edit payment link amount
- Applies minimum Stripe payment amount validation to edit payment link controllers
> PP-13511 Use express-validator for payment link amount validation

- src/controllers/simplified-account/settings/index.js
- src/controllers/simplified-account/settings/switch-psp/index.js
- src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/switch-to-worldpay.controller.js
- src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/switch-to-worldpay.controller.test.js
- src/paths.js
- src/simplified-account-routes.js
- src/utils/simplified-account/settings/SettingsBuilder.class.js
- src/utils/simplified-account/settings/service-settings.js
- src/views/simplified-account/settings/switch-psp/switch-to-worldpay/index.njk
- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
- test/cypress/integration/simplified-account/service-settings/switch-psp/switch-to-worldpay/switch-to-worldpay.cy.js
- path and route
- basic controller with unit test
- index view
- cypress E2E test for admin and non-admin users
> PP-12427 switch to worldpay simplified setting scaffold

- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.js
- src/models/WorldpayTasks.class.js
- src/views/simplified-account/settings/worldpay-details/index.njk
- remove `completedCard` property from `WorldpayTask` class
> PP-12440 Refactor completed task cards in Worldpay Details

- test/cypress/integration/simplified-account/service-settings/webhooks/webhooks.cy.js
- Cypress test for the main simplified settings webhook page
- Tests for the create webhook page will be done in a subsequent PR
> Pp 13136 Webhook settings Cypress tests

- src/views/simplified-account/settings/worldpay-details/index.njk
- test/cypress/integration/simplified-account/service-settings/worldpay-details/one-off-customer-initiated.cy.js
- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
- Cypress tests for displaying 3DS Flex credentials task on index page
- tests for form flow will follow in later PR
> PP-12440 Cypress tests for 3DS Flex credentials task

- test/cypress/integration/simplified-account/service-settings/webhooks/create-webhook.cy.js
- test/cypress/integration/simplified-account/service-settings/webhooks/webhooks.cy.js
- Cypress test for the create webhook page
> PP-13136 Cypress test for create webhook

- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/flex-credentials/worldpay-flex-credentials.controller.test.js
- src/views/simplified-account/settings/worldpay-details/includes/_flex-credentials-input.njk
- test/cypress/integration/simplified-account/service-settings/worldpay-details/flex-credentials.cy.js
- test/cypress/plugins/index.js
- test/cypress/stubs/gateway-account-stubs.js
- Cypress tests for 3DS Flex credentials form
- show success banner when 3DS flex credentials task is last to be completed
- redirect user if they try to access 3DS flex credentials task out of order
> PP-12440 Cypress tests for 3DS Flex credentials form

- src/views/simplified-account/settings/webhooks/index.njk
> PP-13136 apply no-visited-state to webhook actions

- src/controllers/simplified-account/settings/card-payments/apple-pay.controller.js
- src/controllers/simplified-account/settings/card-payments/apple-pay.controller.test.js
- src/controllers/simplified-account/settings/card-payments/collect-billing-address.controller.test.js
- src/controllers/simplified-account/settings/card-payments/default-billing-address-country.controller.test.js
- src/controllers/simplified-account/settings/card-payments/google-pay.controller.test.js
- src/controllers/simplified-account/settings/card-payments/index.controller.js
- src/controllers/simplified-account/settings/card-payments/index.controller.test.js
- src/views/simplified-account/settings/card-payments/index.njk
Add unit tests for the card-payments controllers.
> PP-12416: Add controller unit test for card-payments

- src/views/simplified-account/settings/webhooks/detail.njk
- test/cypress/integration/simplified-account/service-settings/webhooks/webhook-detail.cy.js
- Cypress test for the webhook details page
NB the page for this test is not yet complete as design for the 'events' section is being reworked. This test will be updated later to reflect those changes. Similarly, the test will be updated when the functionality for the update and deactivate buttons has been implemented.
> PP-13521 Webhook details cypress test

- test/cypress/integration/simplified-account/service-settings/worldpay-details/recurring-credentials.cy.js
Cypress tests for https://github.com/alphagov/pay-selfservice/pull/4457
> PP-13261: Cypress tests for CIT credentials

- src/controllers/simplified-account/settings/worldpay-details/recurring-merchant-initiated-credentials/recurring-merchant-initiated-credentials.controller.js
- src/controllers/simplified-account/settings/worldpay-details/recurring-merchant-initiated-credentials/recurring-merchant-initiated-credentials.controller.test.js
- src/controllers/simplified-account/settings/worldpay-details/worldpay-details.controller.js
- src/models/gateway-account-credential/GatewayAccountCredentialUpdateRequest.class.js
- src/services/worldpay-details.service.js
- src/simplified-account-routes.js
- src/views/simplified-account/settings/worldpay-details/recurring-merchant-initiated-credentials.njk
- test/cypress/integration/simplified-account/service-settings/worldpay-details/recurring-credentials.cy.js
Will cover in a future PR:
* Showing the "Service connected to Worldpay" banner where the CIT or MIT is the last cred that's been provided.
> PP-13261: Merchant initiated tx creds functionality

- test/cypress/integration/simplified-account/service-settings/worldpay-details/worldpay-details.cy.js
Cypress test for https://github.com/alphagov/pay-selfservice/pull/4469
> PP-13261: Worldpay index page cypress test for an RCP service

- src/models/GatewayAccount.class.js
- src/models/GatewayAccount.class.test.js
- src/utils/simplified-account/settings/service-settings.js
- add utility method to GatewayAccount class to easily determine if a gateway is switching to the queried provider
> BAU simplified gateway psp switch check

- src/controllers/simplified-account/settings/switch-psp/switch-to-worldpay/add-flex-credentials.controller.test.js
- test/cypress/integration/simplified-account/service-settings/switch-psp/switch-to-worldpay/add-3ds-flex-credential.cy.js
- test/cypress/integration/simplified-account/service-settings/switch-psp/switch-to-worldpay/switch-to-worldpay.cy.js
- test/cypress/stubs/gateway-account-stubs.js
Cypress tests for https://github.com/alphagov/pay-selfservice/pull/4478
> PP-13353: Cypress tests for adding 3DS Flex credentials

- src/client-side/autocomplete.js
- src/views/simplified-account/services/my-services/_service-section.njk
- `My Services` was recently refactored, this PR fixes an issue where the service filter was not working correctly with the new code
> PP-13525 update service filter to work with refactored view

- src/controllers/simplified-account/settings/webhooks/create/create.controller.test.js
- src/controllers/simplified-account/settings/webhooks/update/update-webhook.controller.test.js
- src/services/clients/webhooks.client.js
- src/utils/simplified-account/validation/webhook.schema.js
- test/test-helpers/simplified-account/controllers/ControllerTestBuilder.class.js
- controller tests for update webhook settings
- add validation to create/update webhook to enforce only valid webhook subscriptions
> PP-13522 Update webhook controller tests

- src/controllers/simplified-account/settings/webhooks/toggle/toggle-webhook-status.controller.js
- src/controllers/simplified-account/settings/webhooks/toggle/toggle-webhook-status.controller.test.js
- src/controllers/simplified-account/settings/webhooks/update/update-webhook.controller.test.js
- test/test-helpers/simplified-account/controllers/ControllerTestBuilder.class.js
- tests for controller added in #4490
> PP-13522 Add tests for toggle webhook status controller

- src/controllers/simplified-account/settings/webhooks/update/update-webhook.controller.js
- src/controllers/simplified-account/settings/webhooks/update/update-webhook.controller.test.js
- src/services/webhooks.service.js
- test/cypress/integration/simplified-account/service-settings/webhooks/update-webhook.cy.js
- test/cypress/stubs/webhooks-stubs.js
- cypress tests for updating webhook
- return 404 when webhook not found
> PP-13522 Cypress tests for update webhook flow

- src/views/simplified-account/settings/webhooks/toggle-status.njk
- test/cypress/integration/simplified-account/service-settings/webhooks/toggle-webhook-status.cy.js
- fix the link in error message shown on toggle webhook status form to correctly link to the radio input
> PP-13522 Fix toggle webhook status error to link to first radio button

- src/controllers/simplified-account/settings/card-payments/apple-pay.controller.js
- src/controllers/simplified-account/settings/card-payments/card-payments.controller.js
- src/controllers/simplified-account/settings/card-payments/card-payments.controller.test.js
- src/controllers/simplified-account/settings/card-payments/collect-billing-address.controller.js
- src/controllers/simplified-account/settings/card-payments/constants.js
- src/controllers/simplified-account/settings/card-payments/default-billing-address-country.controller.js
- src/controllers/simplified-account/settings/card-payments/google-pay.controller.js
- src/controllers/simplified-account/settings/card-payments/google-pay.controller.test.js
- src/controllers/simplified-account/settings/card-payments/moto-security/hide-card-number.controller.js
- src/controllers/simplified-account/settings/card-payments/moto-security/hide-card-security-code.controller.js
- src/models/gateway-account-credential/Credential.class.js
- src/models/gateway-account-credential/GatewayAccountCredentialUpdateRequest.class.js
- src/services/clients/connector.client.js
- src/services/worldpay-details.service.js
- src/utils/credentials.js
- src/utils/simplified-account/validation/google-pay.schema.js
- src/utils/simplified-account/validation/on-off-toggle.js
- src/utils/types/settings/settings-request.js
- src/views/simplified-account/settings/card-payments/google-pay.njk
- src/views/simplified-account/settings/card-payments/index.njk
- test/cypress/integration/simplified-account/service-settings/card-payments/util.js
- add additional validation chain for on/off toggles with inline fields
- update google pay controller
- check for payment provider type, if worldpay also validate google pay merchant id when toggling setting
- middleware validating that worldpay accounts have active credentials when attempting to modify google pay setting
- update card payments controller
- pass `googlePayEditable` bool to the view context
- update card payments index view
- show change link conditional on account in correct state for google pay
- update card payments google pay view
- add inline `googlePayMerchantId` field to the radio toggle when account is worldpay
- add `SettingsRequest` jsdoc typedef
- update worldpay details service
- add function for patching google pay merchant id to worldpay account credential
- …
> PP-13354 enable setting google pay for worldpay accounts

- src/views/transaction-detail/_details.njk
Fix the row id for (copy-paste error) for corporate exemption
with @abdirizakidris
> PP-13747 fix id

- src/views/simplified-account/settings/team-members/remove-user.njk
- test/cypress/integration/simplified-account/service-settings/team-members/remove-team-member.cy.js
- correct id of radio buttons so that validation error message link points to the first radio button.
https://github.com/user-attachments/assets/0eca9434-9bb0-4eb6-b8ce-b0dda6ee9025
> PP-13630 Correct validation error link for remove user

- src/controllers/simplified-account/settings/team-members/invite/invite.controller.test.js
Refactor invite controller test to use ControllerTestBuilder
> PP-13356 Use ControllerTestBuilder

- src/controllers/simplified-account/settings/team-members/change-permission/change-permission.controller.test.js
Refactor change permissions controller test to use the ControllerTestBuilder
> PP-13356 Use ControllerTestBuilder in Change Permissions test

- src/views/includes/phase-banner.njk
- add ids to service nav elements for selenium targeting
> BAU admintool e2e test failure

- src/controllers/simplified-account/settings/email-notifications/email-collection-mode/email-collection-mode.controller.js
- src/controllers/simplified-account/settings/email-notifications/email-collection-mode/email-collection-mode.controller.test.js
- src/controllers/simplified-account/settings/email-notifications/email-notifications.controller.js
- src/controllers/simplified-account/settings/email-notifications/email-notifications.controller.test.js
- src/models/GatewayAccount.class.js
- src/simplified-account-routes.js
Extract this out into its own folder, controller and test as per the standard pattern.
> PP-13356: Extract out email collection mode functionality

- src/controllers/simplified-account/settings/stripe-details/company-number/company-number.controller.js
- src/controllers/simplified-account/settings/stripe-details/company-number/company-number.controller.test.js
- src/controllers/simplified-account/settings/stripe-details/vat-number/vat-number.controller.js
- src/controllers/simplified-account/settings/stripe-details/vat-number/vat-number.controller.test.js
- src/views/simplified-account/settings/stripe-details/company-number/index.njk
- src/views/simplified-account/settings/stripe-details/vat-number/index.njk
- test/cypress/integration/simplified-account/service-settings/stripe-details/company-number.cy.js
- test/cypress/integration/simplified-account/service-settings/stripe-details/vat-number.cy.js
- update vat and company number stripe onboarding tasks to no longer set a default radio state
https://github.com/user-attachments/assets/2ed14d77-35b7-4735-8d05-4ec4cf79b54b
https://github.com/user-attachments/assets/749a03e4-9cb1-470f-9d9d-41ffd659d171
> PP-13609 disable default radio selection stripe details

- src/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.test.js
- src/controllers/simplified-account/settings/api-keys/create/create-api-key.controller.test.js
- src/controllers/simplified-account/settings/api-keys/validations.js
- src/views/simplified-account/settings/api-keys/api-key-name.njk
- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
- update error message summary to be suitably descriptive
- add error message to the corresponding field
> PP-13762 Correct api key name error message

- src/views/simplified-account/settings/stripe-details/index.njk
- Update content to meet accessibility requirements, make clear which details are being referred to.
> PP-13795 update content on Stripe details page

- src/views/simplified-account/settings/card-payments/index.njk
- To ensure correct ordering of heading levels, update 'MOTO security' heading to h2
> PP-13779 correct MOTO security heading

- src/controllers/simplified-account/settings/email-notifications/email-notifications.controller.js
- src/controllers/simplified-account/settings/email-notifications/email-notifications.controller.test.js
- src/middleware/simplified-account/settings/default-view-decider.middleware.js
- src/middleware/simplified-account/settings/default-view-decider.middleware.test.js
- src/models/GatewayAccount.class.js
- src/simplified-account-routes.js
Update the controller to bring it in line with use of the ControllerTestBuilder pattern.
Avoid using GatewayAccount's rawResponse field.
> PP-13356: Email notifications controller code improvements

- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-contact-details.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-home-address.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.test.js
- src/utils/simplified-account/validation/responsible-person.schema.js
- src/views/simplified-account/settings/stripe-details/responsible-person/home-address.njk
- test/cypress/integration/simplified-account/service-settings/stripe-details/responsible-person.cy.js
- update validation error messages for Responsible Person name fields
- correct ordering of error messages on Responsible Person name and dob page
- ensure Address Line 1 validation error message is linked to the field
- move list of required validations out of the controllers to improve controller readability
https://github.com/user-attachments/assets/aa7ae528-84d5-4dc4-b0d5-b6d2f35cbf95
> PP-13763 Correct validation error display for Stripe Responsible Person

- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-contact-details.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person-home-address.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.js
- src/controllers/simplified-account/settings/stripe-details/responsible-person/responsible-person.controller.test.js
- src/utils/simplified-account/validation/responsible-person.schema.js
- src/views/simplified-account/settings/stripe-details/responsible-person/home-address.njk
- test/cypress/integration/simplified-account/service-settings/stripe-details/responsible-person.cy.js
Reverts alphagov/pay-selfservice#4536
> Revert "PP-13763 Correct validation error display for Stripe Responsible Person"

- src/controllers/simplified-account/settings/webhooks/event/event.controller.test.js
- src/views/simplified-account/settings/webhooks/detail.njk
- src/views/simplified-account/settings/webhooks/event.njk
- test/cypress/integration/simplified-account/service-settings/webhooks/webhook-detail.cy.js
- test/cypress/integration/simplified-account/service-settings/webhooks/webhook-event.cy.js
- test/fixtures/webhooks.fixtures.js
Add Cypress and unit tests for Webhook Event details.
Also corrected page header title for the event detail.
> PP-13521: Webhook events details tests

- src/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.js
- src/controllers/simplified-account/settings/api-keys/change-name/change-name.controller.test.js
- src/views/simplified-account/settings/api-keys/api-key-name.njk
- test/cypress/integration/simplified-account/service-settings/api-keys/api-keys.cy.js
Reverts alphagov/pay-selfservice#4544
> Revert "PP-13624 Prepopulate api key name field"

- src/views/simplified-account/settings/organisation-details/_edit-organisation-details-name.njk
> BAU — Add missing quotation marks

- src/utils/nav-builder.js
- update simplified account settings link to replace existing settings link for degatewayed users
> PP-13555 Update simplified account settings link to replace existing settings link

- src/views/includes/degateway-banner.njk
Self-evident
_Screenshots if view has been modified:_
> PP-13894 update degateway banner text

- .secrets.baseline
- test/pact/connector-client/connector-get-charge.pact.test.js
PP-13386
This PR should pass when https://github.com/alphagov/pay-connector/pull/5767 is merged.
> PP-13386: Pact test for get charge by service external id

- package-lock.json
- package.json
New version of pay-js-commons, just bumping self-service so it doesn't get left behind
N/A
N/A
> ZD-6099831: Bump pay-js-commons

- package-lock.json
- package.json
> PP-14024 Bump pay-js-metrics to v1.0.14

- README.md
> PP-13977 Update README with latest Node version

- src/controllers/request-to-go-live/organisation-address/get.controller.js
- src/controllers/request-to-go-live/organisation-address/get.controller.test.js
- src/controllers/request-to-go-live/organisation-address/post.controller.js
- src/controllers/request-to-go-live/organisation-address/post.controller.test.js
- src/views/request-to-go-live/organisation-address.njk
PP-13526
- cleanup the Request to Go Live flow
- remove Stripe Onboarding and Credential Switching journeys since these have been re-implemented in simplified settings
- N/A - all views should stay the same
> PP-13526 Cleanup Request to Go Live flow

- .secrets.baseline
- test/cypress/integration/user/login.cy.js
- test/cypress/stubs/gateway-account-stubs.js
> PP-14012 Add Cypress test for redirect on successful login

- package-lock.json
- src/assets/sass/components/pagination.scss
- src/controllers/simplified-account/services/agreements/agreements.controller.test.ts
- src/controllers/simplified-account/services/agreements/agreements.controller.ts
- src/controllers/simplified-account/services/index.ts
- src/models/agreements/Agreement.class.ts
- src/models/agreements/PaymentInstrument.class.ts
- src/models/agreements/agreement-status.ts
- src/models/agreements/dto/Agreement.dto.ts
- src/models/agreements/dto/AgreementSearch.dto.ts
- src/models/agreements/dto/PaymentInstrument.dto.ts
- src/paths.js
- src/server.js
- src/services/agreements.service.ts
- src/services/clients/pay/LedgerClient.class.ts
- src/simplified-account-routes.js
- src/utils/simplified-account/navigation/service-navigation.ts
- src/views/simplified-account/services/agreements/detail.njk
- src/views/simplified-account/services/agreements/index.njk
- src/views/simplified-account/services/agreements/macro/payment-instrument.njk
- src/views/simplified-account/services/agreements/macro/status.njk
- test/cypress/integration/simplified-account/agreements/agreements.cy.ts
- test/cypress/integration/simplified-account/common/assertions.ts
- test/cypress/integration/simplified-account/payment-links/index.cy.ts
PP-14122
- migrate the agreements search journey to the service model and rewrite the controller in typescript
- update the view to use design system pagination
- tidy up the search page markup
- use the new service layout
- update the service navigation to include agreements
> [!IMPORTANT]
> Complete this checklist when adding/modifying nunjucks templates
<details>
<summary>checklist</summary>
</details>
> [!NOTE]
> Include mobile and desktop variants, **highlight**(`#ff0000`) changes to existing views to help reviewers
> PP-14122 agreements search service model

- src/views/simplified-account/settings/card-payments/collect-billing-address.njk
- src/views/simplified-account/settings/card-payments/index.njk
- test/cypress/integration/simplified-account/service-settings/card-payments/index.cy.js
- test/cypress/integration/simplified-account/service-settings/card-payments/updates.cy.js
- test/cypress/integration/simplified-account/service-settings/service-name/service-name.cy.js
Update headers and body texts for `Billing address page`
> PP-13921 update billing address page

- src/controllers/simplified-account/services/payment-links/create/constants.ts
- src/controllers/simplified-account/services/payment-links/create/index.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-information.controller.test.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-information.controller.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-reference.controller.test.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-reference.controller.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.test.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.ts
- src/paths.js
- src/simplified-account-routes.js
- src/views/simplified-account/services/payment-links/create/review.njk
[PP-**14352**](https://payments-platform.atlassian.net/browse/PP-14352)
With this change, we are re-implementing a Review page for the new Payment
Link Creation journey.
- Run the branch locally
- create a user and service with `pay local user`
- start the new payment link creation journey
- enter data in the information page
- enter data in the reference page
- Continue 
- check that you are in the review page as in the designs (see screenshot below)
- Click to change the name, URL, or details
- check that you are directed back to the information page
- check that when clicking Continue, you come back straight to the review page
- Click to change the reference
- check that you are directed back to the reference page
- check that when clicking Continue, you come back straight to the …
> PP-14352 - Introduce Payment Link creation Review page (step 4)  - Part 1: Display only

- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.test.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.ts
- src/models/products/CreateProductRequest.class.ts
- src/models/products/dto/CreateProductRequest.dto.ts
- src/services/tokens.service.ts
[PP-**14352**](https://payments-platform.atlassian.net/browse/PP-14352)
With this change, we are completing the payment link creation journey.
With the previous PR[1], we have implemented a new review page for
the service admin to check the values entered in the payment link creation
journey and to change any details if needed.
With this commit, we are implementing the post method triggered by the 
`Create payment link` button and also a success message to be displayed 
in the payment links index page.
Further information in JIra[2].
[1]
https://github.com/alphagov/pay-selfservice/pull/4697
[2]
https://payments-platform.atlassian.net/browse/PP-14352
- Run the branch locally
- create a user and service with `pay local user`
- start the new payment link creation journey
- enter data in the …
> PP-14352 Implement payment link creation from the new review page

- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.test.ts
- src/controllers/simplified-account/services/payment-links/create/payment-link-review.controller.ts
- src/models/products/CreateProductRequest.class.ts
- src/models/products/dto/CreateProductRequest.dto.ts
PP-14545
- fix bug with reference data not being saved on payment link creation
> PP-14545 Save reference data on payment link creation
